use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('ABOUT', 'ABOUT_ROOT_MENU');

DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('ABOUT', 'ABOUT_ROOT_MENU');

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('ABOUT', 'ABOUT_ROOT_MENU');

DELETE FROM RES WHERE RESOURCE_ID IN('ABOUT','ABOUT_ROOT_MENU');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES('ABOUT', 'MENU_ITEM', 'ABOUT', 'About OpenIAM', '/webconsole/about.html', 3, 'Y');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, IS_PUBLIC) VALUES('ABOUT_ROOT_MENU', 'MENU_ITEM', 'ABOUT_ROOT_MENU', 'About OpenIAM', 'Y');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ABOUT_PUB', 'ABOUT', 'MENU_IS_PUBLIC', 'true');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ABOUT_DESC', 'ABOUT', 'MENU_DISPLAY_NAME', 'About OpenIAM');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ABOUT_ROOT_MENU_PUB', 'ABOUT_ROOT_MENU', 'MENU_IS_PUBLIC', 'true');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ABOUT_ROOT_MENU_DESC', 'ABOUT_ROOT_MENU', 'MENU_DISPLAY_NAME', 'About OpenIAM');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ADMIN', 'ABOUT');