use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('CHALLENGE_RESPONSE_QUESTION', 'CHALLENGE_RESPONSE_QUESTION_ROOT',  'CHALLENGE_RESPONSE_QUESTION_NEW');

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('CHALLENGE_RESPONSE_QUESTION', 'CHALLENGE_RESPONSE_QUESTION_ROOT',  'CHALLENGE_RESPONSE_QUESTION_NEW');

DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN (
'CHALLENGE_RESPONSE_QUESTION', 'CHALLENGE_RESPONSE_QUESTION_ROOT',  'CHALLENGE_RESPONSE_QUESTION_NEW');

DELETE FROM RES WHERE RESOURCE_ID IN('CHALLENGE_RESPONSE_QUESTION', 'CHALLENGE_RESPONSE_QUESTION_ROOT',  'CHALLENGE_RESPONSE_QUESTION_NEW');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL, DISPLAY_ORDER, IS_PUBLIC, IS_SSL) VALUES('CHALLENGE_RESPONSE_QUESTION', 'MENU_ITEM', 'CHALLENGE_RESPONSE_QUESTION', 'Challenge Response Question', '/webconsole/challengeResponseQuestion.html', 3, 'Y', 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('CHALLENGE_RESPONSE_QUESTION_PUB', 'CHALLENGE_RESPONSE_QUESTION', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('CHALLENGE_RESPONSE_QUESTION_DESC', 'CHALLENGE_RESPONSE_QUESTION', 'MENU_DISPLAY_NAME', 'Challenge Response Question');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ADMIN', 'CHALLENGE_RESPONSE_QUESTION');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('CHALLENGE_RESPONSE_QUESTION_ROOT', 'MENU_ITEM', 'CHALLENGE_RESPONSE_QUESTION_ROOT', 'Challenge Response Question Root Menu');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('CHALLENGE_RESP_QUESTION_ROOT_PUB', 'CHALLENGE_RESPONSE_QUESTION_ROOT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('CHALLENGE_RESP_QUEST_ROOT_DESC', 'CHALLENGE_RESPONSE_QUESTION_ROOT', 'MENU_DISPLAY_NAME', 'Challenge Response Question Root Menu');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('CHALLENGE_RESPONSE_QUESTION_NEW', 'MENU_ITEM', 'CHALLENGE_RESPONSE_QUESTION_NEW', 'New Question', '/webconsole/editChallengeResponseQuestion.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('CHALLENGE_RESP_QUESTION_NEW_PUB', 'CHALLENGE_RESPONSE_QUESTION_NEW', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('CHALLENGE_RESP_QUESTION_NEW_DSC', 'CHALLENGE_RESPONSE_QUESTION_NEW', 'MENU_DISPLAY_NAME', 'Create New Question');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('CHALLENGE_RESPONSE_QUESTION_ROOT', 'CHALLENGE_RESPONSE_QUESTION_NEW');










