USE openiam;

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_CHANGE_RULE' WHERE DEF_PARAM_ID='111';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_CHANGE_RULE' WHERE DEF_PARAM_ID='129';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_CHANGE_RULE' WHERE DEF_PARAM_ID='133';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_CHANGE_RULE' WHERE DEF_PARAM_ID='134';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_CHANGE_RULE' WHERE DEF_PARAM_ID='141';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_CHANGE_RULE' WHERE DEF_PARAM_ID='142';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_CHANGE_RULE' WHERE DEF_PARAM_ID='139';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='FORGET_PSWD' WHERE DEF_PARAM_ID='130';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='FORGET_PSWD' WHERE DEF_PARAM_ID='131';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='FORGET_PSWD' WHERE DEF_PARAM_ID='132';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='FORGET_PSWD' WHERE DEF_PARAM_ID='171';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_COMPOSITION' WHERE DEF_PARAM_ID='135';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_COMPOSITION' WHERE DEF_PARAM_ID='136';

UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_COMPOSITION' WHERE DEF_PARAM_ID='120';

DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID IN ('180','181');

INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID,POLICY_DEF_ID,NAME,DESCRIPTION,OPERATION,VALUE1,VALUE2,REPEATS,PARAM_GROUP,HANDLER_LANGUAGE,POLICY_PARAM_HANDLER) VALUES ('180','100','MIN_WORDS_PASSPHRASE','Minimum number of words in the phrase',NULL,'',NULL,NULL,'PSWD_COMPOSITION',NULL,'org.openiam.idm.srvc.pswd.rule.PassphraseMinWordsRule');
INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID,POLICY_DEF_ID,NAME,DESCRIPTION,OPERATION,VALUE1,VALUE2,REPEATS,PARAM_GROUP,HANDLER_LANGUAGE,POLICY_PARAM_HANDLER) VALUES ('181','100','REPEAT_SAME_WORD_PASSPHRASE','Repetition of the same word in the phrase',NULL,NULL,NULL,NULL,'PSWD_COMPOSITION',NULL,'org.openiam.idm.srvc.pswd.rule.PassphraseRepeatWordRule');

DELETE FROM POLICY_ATTRIBUTE WHERE DEF_PARAM_ID IN ('123','124','125','126','128','120','135','136');

DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID='123';

DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID='124';

DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID='125';

DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID='126';

DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID='128';

DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID='120';

DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID='135';

DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID='136';