USE openiam;

UPDATE RES SET URL='/webconsole-idm/provisioning/syncloglist.html' WHERE RESOURCE_ID='SYNCLOG';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('SYNCLOG_MENU_ITEM', 'MENU_ITEM', 'SYNCLOG_MENU_ITEM', 'LOG Viewer', '/webconsole-idm/provisioning/syncloglist.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SYNCLOG_PUB', 'SYNCLOG_MENU_ITEM', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SYNCLOG_DESC', 'SYNCLOG_MENU_ITEM', 'MENU_DISPLAY_NAME', 'Synchronization Transaction Log Viewer');