use openiam;

DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'MNGSYSRULES_DESC';
DELETE FROM res_to_res_membership WHERE RESOURCE_ID = 'MNGSYS_EDIT_MENU_ROOT' AND MEMBER_RESOURCE_ID = 'MNGSYSRULES';
DELETE FROM RES WHERE RESOURCE_ID = 'MNGSYSRULES';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, IS_PUBLIC, IS_SSL) VALUES ('MNGSYSRULES', 'MENU_ITEM', 'Managed system roles', 'MNGSYSRULES', 3, '/webconsole-idm/provisioning/mngsystemrules.html','Y','N');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('MNGSYS_EDIT_MENU_ROOT', 'MNGSYSRULES');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('MNGSYSRULES_DESC', 'MNGSYSRULES', 'MENU_DISPLAY_NAME', 'Manages system rules');
