use openiam;

UPDATE RES SET URL='/selfservice/users.html' WHERE RESOURCE_ID='CREATEREQ';
UPDATE RES SET URL='/selfservice/myTasks.html' WHERE RESOURCE_ID='REQINBOX';
UPDATE RES SET URL='/selfservice/newUser.html' WHERE RESOURCE_ID='NEWUSER';

DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN('CREATEREQ');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES('CREATEREQ', '1');

DELIMITER $$

DROP PROCEDURE IF EXISTS showBetaMenus$$


CREATE PROCEDURE showBetaMenus()
	BEGIN
		IF ((SELECT count(*) FROM RESOURCE_PROP WHERE RESOURCE_ID='REQINBOX' AND NAME='IS_VISIBLE') >= 1) THEN
			UPDATE RESOURCE_PROP SET PROP_VALUE='true' WHERE  RESOURCE_ID='REQINBOX' AND NAME='IS_VISIBLE';
		ELSE
			INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('REQINBOX_VISIBLE', 'REQINBOX', 'IS_VISIBLE', 'true');
		END IF;
		
		IF ((SELECT count(*) FROM RESOURCE_PROP WHERE RESOURCE_ID='NEWUSER' AND NAME='IS_VISIBLE') >= 1) THEN
			UPDATE RESOURCE_PROP SET PROP_VALUE='true' WHERE  RESOURCE_ID='NEWUSER' AND NAME='IS_VISIBLE';
		ELSE
			INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('NEWUSER_VISIBLE', 'NEWUSER', 'IS_VISIBLE', 'true');
		END IF;
		
		IF ((SELECT count(*) FROM RESOURCE_PROP WHERE RESOURCE_ID='CREATEREQ' AND NAME='IS_VISIBLE') >= 1) THEN
			UPDATE RESOURCE_PROP SET PROP_VALUE='true' WHERE  RESOURCE_ID='CREATEREQ' AND NAME='IS_VISIBLE';
		ELSE
			INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('CREATEREQ_VISIBLE', 'CREATEREQ', 'IS_VISIBLE', 'true');
		END IF;
	END$$
	
DELIMITER ;

call showBetaMenus();

DROP PROCEDURE showBetaMenus;

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('SELFSERV_USER_EDIT_ROOT', 'SELFSERV_USER_EDIT', 'SELFSERV_USER_MEMSHP');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('SELFSERV_USER_EDIT_ROOT', 'SELFSERV_USER_EDIT', 'SELFSERV_USER_MEMSHP');
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('SELFSERV_USER_EDIT_ROOT', 'SELFSERV_USER_EDIT', 'SELFSERV_USER_MEMSHP');
DELETE FROM RES WHERE RESOURCE_ID IN('SELFSERV_USER_EDIT_ROOT', 'SELFSERV_USER_EDIT', 'SELFSERV_USER_MEMSHP');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('SELFSERV_USER_EDIT_ROOT', 'MENU_ITEM', 'SELFSERV_USER_EDIT_ROOT', 'SelfService Edit User Root');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_USR_EDIT_RT_PUB', 'SELFSERV_USER_EDIT_ROOT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_USR_EDIT_RT_DESC', 'SELFSERV_USER_EDIT_ROOT', 'MENU_DISPLAY_NAME', 'SelfService Edit User Root');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('SELFSERV_USER_EDIT', 'MENU_ITEM', 'SELFSERV_USER_EDIT', 'Edit User','/selfservice/editUser.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERV_USER_EDIT_PUB', 'SELFSERV_USER_EDIT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERV_USER_EDIT_DESC', 'SELFSERV_USER_EDIT', 'MENU_DISPLAY_NAME', 'Edit User');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('SELFSERV_USER_MEMSHP', 'MENU_ITEM', 'SELFSERV_USER_MEMSHP', 'User Entitlements','/selfservice/userEntitlements.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERV_USER_MEMSHP_PUB', 'SELFSERV_USER_MEMSHP', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERV_USER_MEMSHP_DES', 'SELFSERV_USER_MEMSHP', 'MENU_DISPLAY_NAME', 'User Entitlements');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERV_USER_EDIT_ROOT', 'SELFSERV_USER_EDIT');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERV_USER_EDIT_ROOT', 'SELFSERV_USER_MEMSHP');
