use openiam;


DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RES WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='PROFILE_PIC';


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, DISPLAY_ORDER, IS_PUBLIC, URL) 
	VALUES('PROFILE_PIC', 'MENU_ITEM', 'PROFILE_PIC', 'Edit Your Profile Picture', 10, 'Y', '/selfservice/editProfilePic.html');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('PROFILE_PIC_PUB', 'PROFILE_PIC', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('PROFILE_PIC_DESC', 'PROFILE_PIC', 'MENU_DISPLAY_NAME', 'Edit Your Profile Picture');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFCENTER', 'PROFILE_PIC');

DELETE FROM RESOURCE_ROLE WHERE ROLE_ID='9' and RESOURCE_ID='PROFILE_PIC';
INSERT INTO RESOURCE_ROLE (ROLE_ID, RESOURCE_ID) VALUES('9', 'PROFILE_PIC');

DELETE FROM LANGUAGE_MAPPING WHERE ID IN ('EN_PROFILE_PIC_DESC', 'DE_PROFILE_PIC_DESC',
  'ES_PROFILE_PIC_DESC', 'RU_PROFILE_PIC_DESC', 'JP_PROFILE_PIC_DESC');

INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES
  ('EN_PROFILE_PIC_DESC', '1', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture'),
  ('DE_PROFILE_PIC_DESC', '2', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture'),
  ('ES_PROFILE_PIC_DESC', '4', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture'),
  ('RU_PROFILE_PIC_DESC', '8', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture'),
  ('JP_PROFILE_PIC_DESC', '9', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture');

-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Edit Your Profile Picture' WHERE ID = 'EN_PROFILE_PIC_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Edit Your Profile Picture' WHERE ID = 'DE_PROFILE_PIC_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Edit Your Profile Picture' WHERE ID = 'ES_PROFILE_PIC_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Edit Your Profile Picture' WHERE ID = 'RU_PROFILE_PIC_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Edit Your Profile Picture' WHERE ID = 'JP_PROFILE_PIC_DESC';