use openiam;

UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED' WHERE ID='DEMetadataTypeEntity76';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED' WHERE ID='ESMetadataTypeEntity76';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED' WHERE ID='JPMetadataTypeEntity72';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED', TEXT_VALUE='TERMINATED' WHERE ID='MetadataTypeEntity72';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED', TEXT_VALUE='Удален' WHERE ID='RUMetadataTypeEntity78';
UPDATE METADATA_TYPE SET TYPE_ID='TERMINATED', DESCRIPTION='TERMINATED'  WHERE TYPE_ID='TERMINATE';

