use openiam;
UPDATE POLICY_ATTRIBUTE pa 
JOIN POLICY_DEF_PARAM pd ON pa.DEF_PARAM_ID = pd.DEF_PARAM_ID SET pa.REQUIRED='N'
WHERE pa.POLICY_ID= "4000" AND (
  ((pd.OPERATION = "RANGE" AND (pa.VALUE1 IS NULL OR pa.VALUE1 = "") AND (pa.VALUE2 IS NULL OR pa.VALUE2 = ""))
   OR (pd.OPERATION = "String" AND (pa.VALUE1 IS NULL OR pa.VALUE1 = "") )
   OR (pd.OPERATION = "select" AND (pa.VALUE1 IS NULL OR pa.VALUE1 = "") )
  ));
