use openiam;

ALTER TABLE LOCATION ALTER COLUMN ADDRESS1 NVARCHAR(400) NULL;
ALTER TABLE LOCATION ALTER COLUMN ADDRESS2 NVARCHAR(400) NULL;
ALTER TABLE LOCATION ALTER COLUMN ADDRESS3 NVARCHAR(400) NULL;

ALTER TABLE ADDRESS ALTER COLUMN ADDRESS1 NVARCHAR(400) NULL;
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS2 NVARCHAR(400) NULL;
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS3 NVARCHAR(400) NULL;
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS4 NVARCHAR(400) NULL;
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS5 NVARCHAR(400) NULL;
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS6 NVARCHAR(400) NULL;
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS7 NVARCHAR(400) NULL;


