use openiam;

ALTER TABLE GRP ADD GRP_CLASSIFICATION NVARCHAR(32) NULL;
ALTER TABLE GRP ADD AD_GRP_TYPE NVARCHAR(32) NULL;
ALTER TABLE GRP ADD AD_GRP_SCOPE NVARCHAR(32) NULL;
ALTER TABLE GRP ADD GRP_RISK NVARCHAR(32) NULL;
ALTER TABLE GRP ADD MAX_USER_NUMBER INT NULL;
ALTER TABLE GRP ADD MEMBERSHIP_DURATION_SECONDS bigint NULL;

ALTER TABLE GRP	ADD CONSTRAINT GRP_CLASS_FK FOREIGN KEY (GRP_CLASSIFICATION) REFERENCES METADATA_TYPE (TYPE_ID);
ALTER TABLE GRP	ADD CONSTRAINT GRP_AD_TYPE_FK FOREIGN KEY (AD_GRP_TYPE) REFERENCES METADATA_TYPE (TYPE_ID);
ALTER TABLE GRP	ADD CONSTRAINT GRP_AD_SCOPE_FK FOREIGN KEY (AD_GRP_SCOPE) REFERENCES METADATA_TYPE (TYPE_ID);
ALTER TABLE GRP	ADD CONSTRAINT GRP_RISK_FK FOREIGN KEY (GRP_RISK) REFERENCES METADATA_TYPE (TYPE_ID);

CREATE TABLE GROUP_ORGANIZATION (
  GRP_ID NVARCHAR(32) NULL,
  COMPANY_ID NVARCHAR(32) NULL,
  CONSTRAINT FK_GRP FOREIGN KEY (GRP_ID)REFERENCES GRP (GRP_ID),
  CONSTRAINT FK_ORG FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID));

ALTER TABLE GRP DROP GRP_COMPANY_FK;
ALTER TABLE GRP DROP COLUMN COMPANY_ID;
