use openiam;

IF EXISTS (SELECT * FROM information_schema.columns WHERE TABLE_CATALOG='openiam' AND table_name = 'CONTENT_PROVIDER' AND column_name = 'LOGIN_URL') 
BEGIN
	ALTER TABLE CONTENT_PROVIDER DROP COLUMN LOGIN_URL;
END;

IF EXISTS (SELECT * FROM information_schema.columns WHERE TABLE_CATALOG='openiam' AND table_name = 'CONTENT_PROVIDER' AND column_name = 'POSTBACK_URL_PARAM_NAME') 
BEGIN
	ALTER TABLE CONTENT_PROVIDER DROP COLUMN POSTBACK_URL_PARAM_NAME;
END;

ALTER TABLE CONTENT_PROVIDER ADD LOGIN_URL NVARCHAR(300) NULL;
ALTER TABLE CONTENT_PROVIDER ADD POSTBACK_URL_PARAM_NAME NVARCHAR(50) NULL;

GO
UPDATE CONTENT_PROVIDER SET LOGIN_URL='/idp/login.html';
UPDATE CONTENT_PROVIDER SET POSTBACK_URL_PARAM_NAME='postbackURL';

ALTER TABLE CONTENT_PROVIDER ALTER COLUMN LOGIN_URL NVARCHAR(300) NOT NULL;
ALTER TABLE CONTENT_PROVIDER ALTER COLUMN POSTBACK_URL_PARAM_NAME NVARCHAR(50) NOT NULL;

