use openiam;

DELETE FROM COMPANY_ATTRIBUTE WHERE COMPANY_ID IS NULL;

ALTER TABLE COMPANY_ATTRIBUTE DROP FOREIGN KEY FK_COMPANY_ATTRIBUTE_COMPANY;

ALTER TABLE COMPANY_ATTRIBUTE MODIFY COMPANY_ID VARCHAR(32) NOT NULL;

ALTER TABLE COMPANY_ATTRIBUTE ADD CONSTRAINT FK_COMPANY_ATTRIBUTE_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(COMPANY_ID);

