CREATE TABLE COURSE (
       COURSE_ID            varchar(32) NOT NULL,
       NAME                 varchar(60) NULL,
       COURSE_NUMBER        varchar(30) NULL,
       DISTRICT_ID          varchar(32) NULL,
       SIS_COURSE_NUMBER    VARCHAR(30) NULL,
       IS_PUBLIC            INTEGER  NULL,
       STATUS               VARCHAR(20) NULL DEFAULT 'ACTIVE', /* ACTIVE, INACTIVE */
       PRIMARY KEY (COURSE_ID)
) ENGINE=InnoDB;


CREATE TABLE COURSE_ATTRIBUTE (
       COURSE_ATTR_ID       varchar(32) NOT NULL,
       NAME                 varchar(60) NULL,
       VALUE                varchar(255) NULL,
       COURSE_ID            varchar(32) NULL,
       PRIMARY KEY (COURSE_ATTR_ID),
       CONSTRAINT REF_COURSE_COURSE_ATTR FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
) ENGINE=InnoDB;


CREATE TABLE TERM (
       TERM_ID            varchar(32) NOT NULL,
       NAME               varchar(60) NULL,
       SCHOOL_YEAR        varchar(30) NULL,
       PERIOD_DESCRIPTION VARCHAR(255) NULL,   /* DESCRIBE WHAT PART OF YEAR  */
       PRIMARY KEY (TERM_ID)
) ENGINE=InnoDB;



CREATE TABLE COURSE_TERM (
       COURSE_TERM_ID     VARCHAR(32) NOT NULL,
       TERM_ID            varchar(32) NOT NULL,
       COURSE_ID          varchar(32) NOT NULL,
       SECTION_ID         INTEGER NOT NULL,
       STATUS             VARCHAR(20) NULL ,
       PRIMARY KEY (COURSE_TERM_ID),
       CONSTRAINT REF_COURSE_TERM_TERM FOREIGN KEY (TERM_ID) REFERENCES TERM(TERM_ID),
       CONSTRAINT REF_COURSE_TERM_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
) ENGINE=InnoDB;


CREATE TABLE COURSE_TERM_USER (
  COURSE_TERM_USER_ID     VARCHAR(32) NOT NULL,
  COURSE_TERM_ID          VARCHAR(32) NOT NULL,
  USER_ID                 VARCHAR(32) NOT NULL,
  USER_TYPE               VARCHAR(30) NULL DEFAULT 'STUDENT',
  START_DATE              DATETIME,
  END_DATE                DATETIME,
  PRIMARY KEY (COURSE_TERM_USER_ID)
) ENGINE=InnoDB;


