
drop table COURSE_TERM_USER;
drop table COURSE_TERM;
DROP TABLE TERM;
DROP TABLE COURSE_PROGRAM;
DROP TABLE COURSE_ATTRIBUTE;
DROP TABLE COURSE;
DROP TABLE PROGRAM;

CREATE TABLE PROGRAM (
  PROGRAM_ID      VARCHAR(32) NOT NULL,
  NAME    VARCHAR(60) NOT NULL,
  STATUS  VARCHAR(20) NULL DEFAULT 'ACTIVE', /* ACTIVE, INACTIVE */
  PRIMARY KEY (PROGRAM_ID)
)ENGINE=InnoDB;

CREATE TABLE COURSE (
       COURSE_ID            VARCHAR(32) NOT NULL,
       NAME                 varchar(60) NULL,
       COURSE_NUMBER        varchar(30) NULL,
       DISTRICT_ID          varchar(32) NULL,
       IS_PUBLIC            INTEGER  NULL,
       STATUS               VARCHAR(20) NULL DEFAULT 'ACTIVE', /* ACTIVE, INACTIVE */
       COURSE_FOLDER        VARCHAR(255),
       PRIMARY KEY (COURSE_ID)
) ENGINE=InnoDB;


CREATE TABLE COURSE_ATTRIBUTE (
       COURSE_ATTRIBUTE_ID                   varchar(32) NOT NULL,
       NAME                 varchar(60) NULL,
       VALUE                varchar(255) NULL,
       COURSE_ID            varchar(32) NULL,
       PRIMARY KEY (COURSE_ATTRIBUTE_ID),
       CONSTRAINT REF_COURSE_COURSE_ATTR FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
) ENGINE=InnoDB;

CREATE TABLE COURSE_PROGRAM(
     COURSE_PROGRAM_ID    varchar(32) NOT NULL,
     COURSE_ID            VARCHAR(32) NOT NULL,
     PROGRAM_ID           VARCHAR(32) NOT NULL,
     PRIMARY KEY (COURSE_PROGRAM_ID),
      CONSTRAINT REF_COURSEPRG_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
      CONSTRAINT REF_COURSEPRG_PROGRAM FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
)


CREATE TABLE TERM (
       ID            varchar(32) NOT NULL,
       NAME               varchar(60) NULL,
       SCHOOL_YEAR        varchar(30) NULL,
       PERIOD_DESCRIPTION VARCHAR(255) NULL,   /* DESCRIBE WHAT PART OF YEAR  */
       PRIMARY KEY (TERM_ID)
) ENGINE=InnoDB;



CREATE TABLE COURSE_TERM (
       ID                 VARCHAR(32) NOT NULL,
       TERM_ID            varchar(32) NOT NULL,
       COURSE_ID          varchar(32) NOT NULL,
       SECTION_NBR        INTEGER NOT NULL,
       STATUS             VARCHAR(20) NULL ,
       PRIMARY KEY (COURSE_TERM_ID),
       CONSTRAINT REF_COURSE_TERM_TERM FOREIGN KEY (TERM_ID) REFERENCES TERM(TERM_ID),
       CONSTRAINT REF_COURSE_TERM_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
) ENGINE=InnoDB;


CREATE TABLE COURSE_TERM_USER (
  COURSE_TERM_USER_ID     VARCHAR(32) NOT NULL,
  COURSE_TERM_ID          VARCHAR(32) NOT NULL,
  USER_ID                 VARCHAR(32) NOT NULL,
  USER_TYPE               VARCHAR(30) NULL DEFAULT 'STUDENT',
  START_DATE              DATETIME,
  END_DATE                DATETIME,
  PRIMARY KEY (COURSE_TERM_USER_ID)
) ENGINE=InnoDB;




insert into MENU (menu_id, menu_group, menu_name,menu_desc,url,LANGUAGE_CD, DISPLAY_ORDER) values('COURSE_MANAGEMENT','SELFCENTER','Course Management','Course Management','{SELFSERVICE}courseManagement.selfserve', 'en',8);


INSERT INTO ROLE (ROLE_ID,SERVICE_ID,ROLE_NAME) VALUES ('STUDENT','USR_SEC_DOMAIN','STUDENT');
INSERT INTO ROLE (ROLE_ID,SERVICE_ID,ROLE_NAME) VALUES ('FACULTY','USR_SEC_DOMAIN','FACULTY');



INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('SELF_USERSUMMARY','FACULTY','USR_SEC_DOMAIN');
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('SELF_USERIDENTITY','FACULTY','USR_SEC_DOMAIN');
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('SELF_USERGROUP','FACULTY','USR_SEC_DOMAIN');
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('SELF_USERROLE','FACULTY','USR_SEC_DOMAIN');
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('SELF_USERPSWDRESET','FACULTY','USR_SEC_DOMAIN');
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('SELF_QUERYUSER','FACULTY','USR_SEC_DOMAIN');

INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('SELFSERVICE','FACULTY','USR_SEC_DOMAIN');
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('ACCESSCENTER','FACULTY','USR_SEC_DOMAIN');
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('SELFCENTER','FACULTY','USR_SEC_DOMAIN');
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('CHNGPSWD','FACULTY','USR_SEC_DOMAIN');
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('IDQUEST','FACULTY','USR_SEC_DOMAIN');
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('PROFILE','FACULTY','USR_SEC_DOMAIN');

INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID, SERVICE_ID) VALUES('COURSE_MANAGEMENT','FACULTY','USR_SEC_DOMAIN');

insert into USERS (user_id,first_name, last_name, STATUS, COMPANY_ID ) values('4000','faculty','','ACTIVE','100');
insert into USERS (user_id,first_name, last_name, STATUS, COMPANY_ID ) values('4001','student','','ACTIVE','100');
insert into LOGIN(SERVICE_ID, LOGIN, MANAGED_SYS_ID, USER_ID, PASSWORD,RESET_PWD, IS_LOCKED, AUTH_FAIL_COUNT) VALUES('USR_SEC_DOMAIN','faculty','0','4000','b83a81d1b3f5f209a70ec02c3d7f7fc5',0,0,0);
insert into LOGIN(SERVICE_ID, LOGIN, MANAGED_SYS_ID, USER_ID, PASSWORD,RESET_PWD, IS_LOCKED, AUTH_FAIL_COUNT) VALUES('USR_SEC_DOMAIN','student','0','4001','b83a81d1b3f5f209a70ec02c3d7f7fc5',0,0,0);

INSERT INTO USER_ROLE (USER_ROLE_ID, SERVICE_ID, ROLE_ID, USER_ID, STATUS) VALUES('102','USR_SEC_DOMAIN','FACULTY','4000','ACTIVE');
INSERT INTO USER_ROLE (USER_ROLE_ID, SERVICE_ID, ROLE_ID, USER_ID, STATUS) VALUES('103','USR_SEC_DOMAIN','STUDENT','4001','ACTIVE');