use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS POLICY_SCHEMA_CHANGE$$

CREATE PROCEDURE POLICY_SCHEMA_CHANGE()
	BEGIN
		IF EXISTS (SELECT * FROM information_schema.columns WHERE TABLE_SCHEMA = 'openiam' AND TABLE_NAME='POLICY_ATTRIBUTE' AND COLUMN_NAME = 'REQUIRED') THEN
			ALTER TABLE POLICY_ATTRIBUTE DROP COLUMN REQUIRED;
 		END IF;
	END$$
DELIMITER ;

call POLICY_SCHEMA_CHANGE();
DROP PROCEDURE POLICY_SCHEMA_CHANGE;

ALTER TABLE POLICY_ATTRIBUTE ADD COLUMN REQUIRED CHAR(1) DEFAULT 'Y';
UPDATE POLICY_ATTRIBUTE SET REQUIRED='Y';
ALTER TABLE POLICY_ATTRIBUTE MODIFY REQUIRED CHAR(1) NOT NULL DEFAULT 'Y';
