USE openiam;

CREATE  TABLE DEF_RECON_ATTR_MAP (
  DEF_ATTR_MAP_ID VARCHAR(32) NOT NULL ,
  DEF_ATTR_MAP_NAME VARCHAR(100) NOT NULL ,
  PRIMARY KEY (DEF_ATTR_MAP_ID));

CREATE  TABLE RECON_RES_ATTR_MAP (
  RECON_RES_ATTR_MAP_ID INT NOT NULL AUTO_INCREMENT,
  ATTR_POLICY_ID VARCHAR(32) NULL ,
  DEF_RECON_ATTR_MAP_ID VARCHAR(32) NULL ,
  ATTR_MAP_ID VARCHAR(32) NOT NULL ,
  PRIMARY KEY (RECON_RES_ATTR_MAP_ID));

INSERT INTO RECON_RES_ATTR_MAP (ATTR_MAP_ID, ATTR_POLICY_ID) SELECT t1.ATTRIBUTE_MAP_ID, t1.ATTRIBUTE_POLICY_ID FROM ATTRIBUTE_MAP AS t1;
INSERT INTO DEF_RECON_ATTR_MAP (DEF_ATTR_MAP_ID, DEF_ATTR_MAP_NAME) VALUES ('Login.login','Principal'),('User.title','Functional Title');

UPDATE ATTRIBUTE_MAP am,RECON_RES_ATTR_MAP rram SET am.ATTRIBUTE_POLICY_ID=rram.RECON_RES_ATTR_MAP_ID
WHERE am.ATTRIBUTE_MAP_ID=rram.ATTR_MAP_ID;

ALTER TABLE RECON_RES_ATTR_MAP CHANGE COLUMN RECON_RES_ATTR_MAP_ID RECON_RES_ATTR_MAP_ID VARCHAR(32) NOT NULL;
ALTER TABLE RECON_RES_ATTR_MAP DROP COLUMN ATTR_MAP_ID ;



