use openiam;

CREATE  TABLE MANAGED_SYS_RULE (
  MANAGED_SYS_RULE_ID VARCHAR(32) NOT NULL ,
  MANAGED_SYS_ID VARCHAR(32) NOT NULL ,
  MANAGED_SYS_RULE_NAME VARCHAR(45) NULL ,
  MANAGED_SYS_RULE_VALUE VARCHAR(45) NULL ,
  PRIMARY KEY (MANAGED_SYS_RULE_ID));
