use openiam;

ALTER TABLE URI_PATTERN_META_VALUE ADD GROOVY_SCRIPT VARCHAR(200) NULL;

ALTER TABLE CONTENT_PROVIDER ADD MANAGED_SYS_ID VARCHAR(32) NULL;

UPDATE CONTENT_PROVIDER SET MANAGED_SYS_ID='0';

ALTER TABLE CONTENT_PROVIDER MODIFY COLUMN MANAGED_SYS_ID VARCHAR(32) NOT NULL;

ALTER TABLE CONTENT_PROVIDER ADD CONSTRAINT FK_CP_MANAGED_SYS FOREIGN KEY(MANAGED_SYS_ID) REFERENCES MANAGED_SYS(MANAGED_SYS_ID);