use openiam;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='SYNCH_CONFIG' AND column_name='PRE_SYNC_SCRIPT') 
	ALTER TABLE SYNCH_CONFIG ADD PRE_SYNC_SCRIPT NVARCHAR(80) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='SYNCH_CONFIG' AND column_name='POST_SYNC_SCRIPT') 
	ALTER TABLE SYNCH_CONFIG ADD POST_SYNC_SCRIPT NVARCHAR(80) NULL;
