use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS CHANGE_SUPERVISOR_TABLE$$
CREATE PROCEDURE CHANGE_SUPERVISOR_TABLE()
	BEGIN
		IF EXISTS (SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='openiam' and table_name = 'ORG_STRUCTURE' AND column_name  = 'ORG_STRUCTURE_ID') THEN
	 		ALTER TABLE ORG_STRUCTURE 
				DROP PRIMARY KEY, 
				DROP COLUMN COMMENTS, 
				DROP COLUMN STATUS, 
				DROP COLUMN END_DATE, 
				DROP COLUMN START_DATE, 
				DROP COLUMN SUPERVISOR_TYPE, 
				DROP COLUMN ORG_STRUCTURE_ID, 
				CHANGE COLUMN IS_PRIMARY_SUPER IS_PRIMARY_SUPER VARCHAR(1) NOT NULL DEFAULT 'N', 
				ADD PRIMARY KEY (SUPERVISOR_ID, STAFF_ID) ;


			UPDATE ORG_STRUCTURE 
			SET IS_PRIMARY_SUPER='Y'
			WHERE IS_PRIMARY_SUPER='1';

			UPDATE ORG_STRUCTURE 
			SET IS_PRIMARY_SUPER='N'
			WHERE IS_PRIMARY_SUPER='0';

		END IF;
	
	END$$
DELIMITER ;

call CHANGE_SUPERVISOR_TABLE();
DROP PROCEDURE CHANGE_SUPERVISOR_TABLE;








