use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS REMOVE_UNUSED_COLUMNS$$

CREATE PROCEDURE REMOVE_UNUSED_COLUMNS()
	BEGIN
		IF EXISTS (SELECT * FROM information_schema.columns WHERE table_schema='openiam' AND table_name = 'CONTENT_PROVIDER' AND column_name = 'MIN_AUTH_LEVEL') THEN
			ALTER TABLE CONTENT_PROVIDER DROP FOREIGN KEY CP_AUTH_LEVEL_FK;
			ALTER TABLE CONTENT_PROVIDER DROP COLUMN MIN_AUTH_LEVEL;
 		END IF;
 		
 		IF EXISTS (SELECT * FROM information_schema.columns WHERE table_schema='openiam' AND table_name = 'URI_PATTERN' AND column_name = 'MIN_AUTH_LEVEL') THEN
 			ALTER TABLE URI_PATTERN DROP FOREIGN KEY URI_PATTERN_AUTH_LEVEL_FK;
			ALTER TABLE URI_PATTERN DROP COLUMN MIN_AUTH_LEVEL;
 		END IF;
	END$$
DELIMITER ;

call REMOVE_UNUSED_COLUMNS();
DROP PROCEDURE REMOVE_UNUSED_COLUMNS;