use openiam;

ALTER TABLE RESOURCE_TYPE ADD COLUMN URL VARCHAR(512) NULL DEFAULT NULL;
ALTER TABLE RESOURCE_TYPE DROP COLUMN METADATA_TYPE_ID;
ALTER TABLE RESOURCE_TYPE MODIFY COLUMN RESOURCE_TYPE_ID varchar(32) NOT NULL;

