use openiam;

ALTER TABLE RES DROP FOREIGN KEY FK_RESOURCE_RESOURCE_TYPE;
ALTER TABLE RES CHANGE COLUMN RESOURCE_TYPE_ID RESOURCE_TYPE_ID VARCHAR(32) NOT NULL, 
  ADD CONSTRAINT FK_RESOURCE_RESOURCE_TYPE FOREIGN KEY (RESOURCE_TYPE_ID ) REFERENCES RESOURCE_TYPE (RESOURCE_TYPE_ID);

