use openiam;

DROP PROCEDURE IF EXISTS ADD_NEW_COLUMN;

DELIMITER $$
CREATE PROCEDURE ADD_NEW_COLUMN()
	BEGIN
		IF NOT EXISTS (SELECT * FROM information_schema.columns WHERE table_schema='openiam' AND table_name = 'REPORT_INFO' AND column_name = 'BUILT_IN') THEN
			ALTER TABLE REPORT_INFO ADD COLUMN BUILT_IN CHAR(1) DEFAULT 'N' NOT NULL;
 		END IF;
	END$$
DELIMITER ;

call ADD_NEW_COLUMN();
DROP PROCEDURE ADD_NEW_COLUMN;
