use openiam;
-- CREATE IDENTITY TABLE 

CREATE TABLE IDENTITY (
    IDENTITY_ID VARCHAR(32) NOT NULL,
    MANAGED_SYS_ID VARCHAR(32) NOT NULL,
    IDENTITY VARCHAR(320) NOT NULL,
    REFERRED_OBJECT_ID VARCHAR(32) NOT NULL,
    IDENTITY_TYPE VARCHAR(20) NULL, -- GROUP, ROLE, TYPE ...
    CREATE_DATE DATETIME NULL,
    CREATED_BY VARCHAR(32) NULL,
    STATUS varchar(20) NULL
);