use openiam;

ALTER TABLE OPENIAM_LOG ADD KEY CREATED_DATETIME (CREATED_DATETIME), ADD KEY LOG_ACTION (LOG_ACTION);
ALTER TABLE OPENIAM_LOG_ATTRIBUTE ADD KEY FK_LOG_ATTRIBUTE_LOG (OPENIAM_LOG_ID);
ALTER TABLE OPENIAM_LOG_TARGET ADD KEY FK_LOG_TARGET_LOG (OPENIAM_LOG_ID);
ALTER TABLE OPENIAM_LOG_LOG_MEMBERSHIP ADD KEY OPENIAM_LOG_ID (OPENIAM_LOG_ID), ADD KEY OPENIAM_MEMBER_LOG_ID (OPENIAM_MEMBER_LOG_ID);
