use openiam;

CREATE TABLE REPORT_PARAMETER_METATYPE (
	PARAM_METATYPE_ID VARCHAR(32) NOT NULL COLLATE utf8_bin,
	PARAM_METATYPE_NAME VARCHAR(45) NOT NULL,
	IS_MULTIPLE CHAR(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (PARAM_METATYPE_ID)) 
ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE REPORT_CRITERIA_PARAMETER ADD COLUMN PARAM_META_TYPE_ID VARCHAR(32) NULL DEFAULT NULL COLLATE utf8_bin,
	ADD COLUMN IS_MULTIPLE CHAR(1) NOT NULL DEFAULT 'N',
	ADD COLUMN IS_REQUIRED CHAR(1) NOT NULL DEFAULT 'N',
	ADD COLUMN CAPTION VARCHAR(100) NOT NULL;

ALTER TABLE REPORT_CRITERIA_PARAMETER ADD CONSTRAINT RCP_PARAM_META_TYPE_FK 
	FOREIGN KEY (PARAM_META_TYPE_ID) REFERENCES REPORT_PARAMETER_METATYPE (PARAM_METATYPE_ID);
