USE openiam;
ALTER TABLE AUTH_ATTRIBUTE MODIFY COLUMN DEFAULT_VALUE VARCHAR(4096);
ALTER TABLE AUTH_LEVEL_ATTRIBUTE MODIFY COLUMN VALUE_AS_STRING VARCHAR(4096);
ALTER TABLE AUTH_PROVIDER_ATTRIBUTE MODIFY COLUMN VALUE VARCHAR(4096);
ALTER TABLE URI_PATTERN_META_VALUE MODIFY COLUMN STATIC_VALUE VARCHAR(4096);
ALTER TABLE LOGIN_ATTRIBUTE MODIFY COLUMN NAME VARCHAR(100), MODIFY COLUMN VALUE VARCHAR(4096);
ALTER TABLE METADATA_ELEMENT MODIFY COLUMN ATTRIBUTE_NAME VARCHAR(100), MODIFY COLUMN STATIC_DEFAULT_VALUE VARCHAR(4096);
ALTER TABLE POLICY_ATTRIBUTE MODIFY COLUMN NAME VARCHAR(100), MODIFY COLUMN VALUE1 VARCHAR(4096), MODIFY COLUMN VALUE2 VARCHAR(4096);
ALTER TABLE REQUEST_ATTRIBUTE MODIFY COLUMN NAME VARCHAR(100), MODIFY COLUMN VALUE VARCHAR(4096);
ALTER TABLE GRP_ATTRIBUTES MODIFY COLUMN NAME VARCHAR(100), MODIFY COLUMN VALUE VARCHAR(4096);
ALTER TABLE COMPANY_ATTRIBUTE MODIFY COLUMN VALUE VARCHAR(4096);
ALTER TABLE ROLE_ATTRIBUTE MODIFY COLUMN NAME VARCHAR(100), MODIFY COLUMN VALUE VARCHAR(4096);
ALTER TABLE USER_ATTRIBUTES MODIFY COLUMN NAME VARCHAR(100), MODIFY COLUMN VALUE VARCHAR(4096);

