USE openiam;

ALTER TABLE LOGIN_ATTRIBUTE
	ADD CONSTRAINT FK_LOGIN_METADATA_ELEMENT
	FOREIGN KEY (METADATA_ID)
	REFERENCES METADATA_ELEMENT(METADATA_ID);

ALTER TABLE RESOURCE_PROP
	ADD CONSTRAINT FK_RES_PROP_METADATA_ELEMENT
	FOREIGN KEY (METADATA_ID)
	REFERENCES METADATA_ELEMENT(METADATA_ID);

ALTER TABLE ROLE_ATTRIBUTE
	ADD CONSTRAINT FK_ROLE_ATTR_METADATA_ELEMENT
	FOREIGN KEY (METADATA_ID)
	REFERENCES METADATA_ELEMENT(METADATA_ID);

