use openiam;

UPDATE GRP SET COMPANY_ID=NULL WHERE COMPANY_ID NOT IN(SELECT COMPANY_ID FROM COMPANY);

ALTER TABLE GRP ADD CONSTRAINT GRP_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);