use openiam;

ALTER TABLE RESOURCE_PROP CHANGE PROP_VALUE VALUE VARCHAR(4096);

ALTER TABLE RESOURCE_PROP CHANGE NAME NAME VARCHAR(100);

ALTER TABLE RESOURCE_PROP ADD COLUMN IS_MULTIVALUED char(1) NOT NULL DEFAULT 'N';