use openiam;

ALTER TABLE RESOURCE_PROP CHANGE METADATA_ID METADATA_ID VARCHAR(32);

ALTER TABLE ROLE_ATTRIBUTE CHANGE METADATA_ID METADATA_ID VARCHAR(32);

ALTER TABLE GRP_ATTRIBUTES CHANGE METADATA_ID METADATA_ID VARCHAR(32);