use openiam;

ALTER TABLE EMAIL_ADDRESS DROP FOREIGN KEY EMAIL_ADDRESS_TYPE_FK ;
ALTER TABLE EMAIL_ADDRESS CHANGE COLUMN TYPE_ID TYPE_ID VARCHAR(32) NULL DEFAULT NULL;
ALTER TABLE EMAIL_ADDRESS ADD CONSTRAINT EMAIL_ADDRESS_TYPE_FK FOREIGN KEY (TYPE_ID) REFERENCES METADATA_TYPE (TYPE_ID);


ALTER TABLE ADDRESS DROP FOREIGN KEY ADDRESS_TYPE_FK ;
ALTER TABLE ADDRESS CHANGE COLUMN TYPE_ID TYPE_ID VARCHAR(32) NULL  DEFAULT NULL; 
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_TYPE_FK FOREIGN KEY (TYPE_ID) REFERENCES METADATA_TYPE (TYPE_ID);


ALTER TABLE PHONE DROP FOREIGN KEY PHONE_TYPE_FK ;
ALTER TABLE PHONE CHANGE COLUMN TYPE_ID TYPE_ID VARCHAR(32) NULL  DEFAULT NULL; 
ALTER TABLE PHONE ADD CONSTRAINT PHONE_TYPE_FK FOREIGN KEY (TYPE_ID) REFERENCES METADATA_TYPE (TYPE_ID);

