use openiam;

ALTER TABLE RESOURCE_PROP CHANGE _VALUE ATTR_VALUE VARCHAR(4096);
ALTER TABLE GRP_ATTRIBUTES CHANGE _VALUE ATTR_VALUE VARCHAR(4096);
ALTER TABLE ROLE_ATTRIBUTE CHANGE _VALUE ATTR_VALUE VARCHAR(4096);
ALTER TABLE COMPANY_ATTRIBUTE CHANGE _VALUE ATTR_VALUE VARCHAR(4096);
