use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS REMOVE_UI_THEME_FK$$

CREATE PROCEDURE REMOVE_UI_THEME_FK()
	BEGIN
		IF EXISTS (SELECT * FROM information_schema.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'openiam' AND TABLE_NAME='CONTENT_PROVIDER' AND CONSTRAINT_NAME = 'CP_UI_THEME') THEN
			ALTER TABLE CONTENT_PROVIDER DROP FOREIGN KEY CP_UI_THEME;
 		END IF;
		
		IF EXISTS (SELECT * FROM information_schema.columns WHERE table_schema='openiam' AND table_name = 'CONTENT_PROVIDER' AND column_name = 'UI_THEME_ID') THEN
			ALTER TABLE CONTENT_PROVIDER DROP COLUMN UI_THEME_ID;
 		END IF;
 		
 		IF EXISTS (SELECT * FROM information_schema.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'openiam' AND TABLE_NAME='URI_PATTERN' AND CONSTRAINT_NAME = 'URI_PATTERN_UI_THEME') THEN
			ALTER TABLE URI_PATTERN DROP FOREIGN KEY URI_PATTERN_UI_THEME;
 		END IF;
 		
 		IF EXISTS (SELECT * FROM information_schema.columns WHERE table_schema='openiam' AND table_name = 'URI_PATTERN' AND column_name = 'UI_THEME_ID') THEN
 			ALTER TABLE URI_PATTERN DROP COLUMN UI_THEME_ID;
 		END IF;
	END$$
DELIMITER ;

call REMOVE_UI_THEME_FK();
DROP PROCEDURE REMOVE_UI_THEME_FK;

DROP TABLE IF EXISTS UI_THEME;

CREATE TABLE UI_THEME(
	UI_THEME_ID VARCHAR(32) NOT NULL,
	UI_THEME_NAME VARCHAR(100) NOT NULL,
	URL VARCHAR(300) NOT NULL,
	PRIMARY KEY(UI_THEME_ID)
) ENGINE=InnoDB;/* DEFAULT CHARSET=utf8 COLLATE utf8_bin;

ALTER TABLE URI_PATTERN CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;
ALTER TABLE CONTENT_PROVIDER CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;
*/

ALTER TABLE UI_THEME ADD CONSTRAINT UI_THEME_NAME_UNIUE UNIQUE(UI_THEME_NAME);

ALTER TABLE CONTENT_PROVIDER ADD COLUMN UI_THEME_ID VARCHAR(32) NULL;
ALTER TABLE URI_PATTERN ADD COLUMN UI_THEME_ID VARCHAR(32) NULL;

ALTER TABLE CONTENT_PROVIDER ADD CONSTRAINT CP_UI_THEME FOREIGN KEY (UI_THEME_ID) REFERENCES UI_THEME(UI_THEME_ID);
ALTER TABLE URI_PATTERN ADD CONSTRAINT URI_PATTERN_UI_THEME FOREIGN KEY (UI_THEME_ID) REFERENCES UI_THEME(UI_THEME_ID);
