use openiam;

DELETE FROM RECON_RES_ATTR_MAP WHERE RECON_RES_ATTR_MAP_ID IN ('80','81');
DELETE FROM ATTRIBUTE_MAP WHERE ATTRIBUTE_MAP_ID IN ('700','701');
DELETE FROM POLICY WHERE POLICY_ID IN ('5200','5201');



INSERT INTO POLICY (POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,RULE_SRC_URL,RULE_TEXT)
VALUES ('5200','104','city','City',1,CURRENT_TIMESTAMP(),'3000','provision/city.groovy','');
INSERT INTO POLICY (POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,RULE_SRC_URL,RULE_TEXT)
VALUES ('5201','104','supervisor','Supervisor',1,CURRENT_TIMESTAMP(),'3000','provision/supervisor.groovy','');

INSERT INTO RECON_RES_ATTR_MAP (RECON_RES_ATTR_MAP_ID,ATTR_POLICY_ID) VALUES (80,5200);
INSERT INTO RECON_RES_ATTR_MAP (RECON_RES_ATTR_MAP_ID,ATTR_POLICY_ID) VALUES (81,5201);

INSERT INTO ATTRIBUTE_MAP (ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
VALUES (700,101,101,'USER','l',NULL,NULL,80,NULL,'ACTIVE',NULL,NULL,NULL,'STRING',NULL,NULL);

INSERT INTO ATTRIBUTE_MAP (ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
VALUES (701,101,101,'USER','manager',NULL,NULL,81,NULL,'ACTIVE',NULL,NULL,NULL,'MANAGER',NULL,NULL);