USE openiam;

DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'RES_TYPE_DESC';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID='RES_TYPE_ITEM';
DELETE FROM RES WHERE RESOURCE_ID='RES_TYPE_ITEM';

DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'RES_TYPE_NEW_DESC';
DELETE FROM res_to_res_membership WHERE RESOURCE_ID='RES_TYPE_MENU_ROOT';
DELETE FROM RES WHERE RESOURCE_ID='RES_TYPE_MENU_ROOT';
DELETE FROM RES WHERE RESOURCE_ID='RES_TYPE_NEW';

INSERT INTO RES (RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,IS_PUBLIC,URL) VALUES ('RES_TYPE_ITEM','MENU_ITEM','Resource Type','RES_TYPE_ITEM',1,'Y','/webconsole/resourceTypes.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID,RESOURCE_ID,NAME,PROP_VALUE) VALUES ('RES_TYPE_DESC','RES_TYPE_ITEM','MENU_DISPLAY_NAME','Resource Type');
INSERT INTO res_to_res_membership (RESOURCE_ID,MEMBER_RESOURCE_ID) VALUES ('ACC_CONTROL','RES_TYPE_ITEM');

INSERT INTO RES (RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,IS_PUBLIC) VALUES ('RES_TYPE_MENU_ROOT','MENU_ITEM','resource type root menu','RES_TYPE_MENU_ROOT',1,'Y'); 
INSERT INTO RES (RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,IS_PUBLIC,URL) VALUES ('RES_TYPE_NEW','MENU_ITEM','metadata type edit','RES_TYPE_EDIT',1,'Y','/webconsole/editResourceType.html'); 
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID,RESOURCE_ID,NAME,PROP_VALUE) VALUES ('RES_TYPE_NEW_DESC','RES_TYPE_NEW','MENU_DISPLAY_NAME','New Resource Type');
INSERT INTO res_to_res_membership (RESOURCE_ID,MEMBER_RESOURCE_ID) VALUES ('RES_TYPE_MENU_ROOT','RES_TYPE_NEW');
