use openiam;

DELETE FROM AUTH_LEVEL_ATTRIBUTE WHERE AUTH_LEVEL_GROUPING_ID IN('CERT_AUTH', 'KERB_AUTH');

DELETE FROM URI_AUTH_LEVEL_GRP_XREF WHERE AUTH_LEVEL_GROUPING_ID IN('CERT_AUTH', 'KERB_AUTH');
DELETE FROM CP_AUTH_LEVEL_GRP_XREF WHERE AUTH_LEVEL_GROUPING_ID IN('CERT_AUTH', 'KERB_AUTH');
DELETE FROM AUTH_LEVEL_GROUPING WHERE AUTH_LEVEL_GROUPING_ID IN('CERT_AUTH', 'KERB_AUTH');

DELETE FROM AUTH_LEVEL WHERE AUTH_LEVEL_ID IN('KERB_AUTH', 'CERT_AUTH');

INSERT INTO AUTH_LEVEL (AUTH_LEVEL_ID, AUTH_LEVEL_NAME, REQUIRES_AUTHENTICATION) VALUES('KERB_AUTH', 'Kerberos Authentication', 'Y');

INSERT INTO AUTH_LEVEL_GROUPING (AUTH_LEVEL_GROUPING_ID, AUTH_LEVEL_ID, NAME) VALUES('KERB_AUTH', 'KERB_AUTH', 'Kerberos Authentication');