use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS hideManualReconciliation$$

CREATE PROCEDURE hideManualReconciliation()
	BEGIN
		IF ((SELECT count(*) FROM RESOURCE_PROP WHERE RESOURCE_ID='MANUALRECON' AND NAME='IS_VISIBLE') >= 1) THEN
			UPDATE RESOURCE_PROP SET PROP_VALUE='false' WHERE  RESOURCE_ID='MANUALRECON' AND NAME='IS_VISIBLE';
		ELSE
			INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('MANUALRECON_VISIBLE', 'MANUALRECON', 'IS_VISIBLE', 'false');
		END IF;
	END$$
DELIMITER ;

call hideManualReconciliation();

DROP PROCEDURE hideManualReconciliation;