use openiam;


DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('SELFSERVICE_EXT', 'SELFSRV_EXAMPLE');
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('SELFSERVICE_EXT', 'SELFSRV_EXAMPLE');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('SELFSERVICE_EXT', 'SELFSRV_EXAMPLE');
DELETE FROM RES  WHERE RESOURCE_ID IN('SELFSERVICE_EXT', 'SELFSRV_EXAMPLE');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('SELFSERVICE_EXT', 'MENU_ITEM', 'SELFSERVICE_EXT', 'SelfService Extension Root');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERVICE_EXT_PB', 'SELFSERVICE_EXT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERVICE_EXT_DN', 'SELFSERVICE_EXT', 'MENU_DISPLAY_NAME', 'SelfService Extension Root');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, IS_PUBLIC, URL) VALUES ('SELFSRV_EXAMPLE', 'MENU_ITEM', 'SELFSRV_EXAMPLE', 'Example', 'Y', '/selfservice-ext/example.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSRV_EXAMPLE_DN', 'SELFSRV_EXAMPLE', 'MENU_DISPLAY_NAME', 'Example');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSRV_EXAMPLE_PB', 'SELFSRV_EXAMPLE', 'MENU_IS_PUBLIC', 'false');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('SELFSERVICE_EXT', 'SELFSRV_EXAMPLE');