use openiam;

DELETE FROM ATTRIBUTE_MAP WHERE MANAGED_SYS_ID='150';
DELETE FROM MNG_SYS_OBJECT_MATCH WHERE MANAGED_SYS_ID = '150';
DELETE FROM MANAGED_SYS WHERE MANAGED_SYS_ID = '150';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID = '151';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID = '150';
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID = '151';
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID = '150';
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID = '151';
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID = '150';
DELETE FROM RESOURCE_PRIVILEGE WHERE RESOURCE_ID = '151';
DELETE FROM RESOURCE_PRIVILEGE WHERE RESOURCE_ID = '150';
DELETE FROM RESOURCE_POLICY WHERE RESOURCE_ID = '151';
DELETE FROM RESOURCE_POLICY WHERE RESOURCE_ID = '150';

DELETE FROM RES WHERE RESOURCE_ID = '150';
DELETE FROM RES WHERE RESOURCE_ID = '151';


DELETE FROM PROVISION_CONNECTOR WHERE CONNECTOR_ID = '100';

DELETE FROM RECON_RES_ATTR_MAP WHERE RECON_RES_ATTR_MAP_ID='77';
DELETE FROM RECON_RES_ATTR_MAP WHERE RECON_RES_ATTR_MAP_ID='76';
DELETE FROM RECON_RES_ATTR_MAP WHERE RECON_RES_ATTR_MAP_ID='75';
DELETE FROM POLICY WHERE POLICY_ID = '5000';
DELETE FROM POLICY WHERE POLICY_ID = '5001';
DELETE FROM POLICY WHERE POLICY_ID = '5002';

insert into POLICY (POLICY_ID, POLICY_DEF_ID, NAME, DESCRIPTION, STATUS, CREATE_DATE, CREATED_BY, RULE_TEXT, RULE_SRC_URL) VALUES ('5000','104', 'ps-role', 'role', 1,CURRENT_TIMESTAMP(), '3000', '','provision/ps/role.groovy');
insert into POLICY (POLICY_ID, POLICY_DEF_ID, NAME, DESCRIPTION, STATUS, CREATE_DATE, CREATED_BY, RULE_TEXT, RULE_SRC_URL) VALUES ('5001','104', 'ps-displayName', 'displayName', 1,CURRENT_TIMESTAMP(), '3000', '','provision/ps/displayName.groovy');
insert into POLICY (POLICY_ID, POLICY_DEF_ID, NAME, DESCRIPTION, STATUS, CREATE_DATE, CREATED_BY, RULE_TEXT, RULE_SRC_URL) VALUES ('5002','104', 'ps-employeeId', 'employeeId', 1,CURRENT_TIMESTAMP(), '3000', '','provision/ps/employeeId.groovy');

#4562,5001,5000,4502,5002,4509


INSERT INTO RECON_RES_ATTR_MAP (RECON_RES_ATTR_MAP_ID,ATTR_POLICY_ID) VALUES (75,5000);
INSERT INTO RECON_RES_ATTR_MAP (RECON_RES_ATTR_MAP_ID,ATTR_POLICY_ID) VALUES (76,5001);
INSERT INTO RECON_RES_ATTR_MAP (RECON_RES_ATTR_MAP_ID,ATTR_POLICY_ID) VALUES (77,5002);


#ADMINRESOURCE
INSERT INTO RES (RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,URL,MIN_AUTH_LEVEL,IS_PUBLIC,ADMIN_RESOURCE_ID,RISK) VALUES ('151','ADMIN_RESOURCE',NULL,'RES_ADMIN_PEOPLE_SOFT',NULL,NULL,NULL,'Y',NULL,NULL);

#RESOURCE_
INSERT INTO RES (RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,URL,MIN_AUTH_LEVEL,IS_PUBLIC,ADMIN_RESOURCE_ID,RISK) VALUES ('150','MANAGED_SYS',NULL,'PEOPLE_SOFT_M_SYS',NULL,NULL,NULL,'N',151,NULL);

#CONNECTOR
INSERT INTO PROVISION_CONNECTOR (CONNECTOR_ID,NAME,CLIENT_COMM_PROTOCOL, SERVICE_URL,SERVICE_NAMESPACE,SERVICE_PORT,CONNECTOR_INTERFACE) VALUES ('100','PEOPLESOFT DB CONNECTOR','CLEAR','localhost:9080/openiam-esb/idmsrvc/PeoplesoftDbConnector','http://www.openiam.org/service/connector','NA','LOCAL');

#MSYS
INSERT INTO MANAGED_SYS (MANAGED_SYS_ID,NAME,DESCRIPTION,STATUS,CONNECTOR_ID,HOST_URL,APPL_URL,PORT,COMM_PROTOCOL,USER_ID,PSWD,START_DATE,END_DATE,RESOURCE_ID,PRIMARY_REPOSITORY,SECONDARY_REPOSITORY_ID,ALWAYS_UPDATE_SECONDARY,RES_DEPENDENCY,ADD_HNDLR,MODIFY_HNDLR,DELETE_HNDLR,SETPASS_HNDLR,SUSPEND_HNDLR,SEARCH_HNDLR,LOOKUP_HNDLR,TEST_CONNECTION_HNDLR,RECONCILE_RESOURCE_HNDLR,HNDLR_5,DRIVER_URL,CONNECTION_STRING,ATTRIBUTE_NAMES_LOOKUP,ATTRIBUTE_NAMES_HNDLR) VALUES ('150','PEOPLESOFT DB CONNECTOR','PEOPLESOFT DB CONNECTOR','ACTIVE','100',NULL,NULL,NULL,'CLEAR','root',NULL,NULL,NULL,150,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'oracle.jdbc.driver.OracleDriver','jdbc:oracle:thin:@localhost:1521:mkyong',NULL,NULL);

INSERT INTO ATTRIBUTE_MAP (ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID) VALUES (624,150,150,'PRINCIPAL','principal',NULL,NULL,65,NULL,'ACTIVE',NULL,NULL,NULL,'STRING',NULL,NULL);

INSERT INTO ATTRIBUTE_MAP
(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID) VALUES (625,150,150,'USER','displayName',NULL,NULL,76,NULL,'ACTIVE',NULL,NULL,NULL,'STRING',NULL,NULL);

INSERT INTO ATTRIBUTE_MAP
(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID) VALUES (626,150,150,'USER','role',NULL,NULL,75,NULL,'ACTIVE',NULL,NULL,NULL,'STRING',NULL,NULL);

INSERT INTO ATTRIBUTE_MAP
(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID) VALUES (627,150,150,'USER','email',NULL,NULL,2,NULL,'ACTIVE',NULL,NULL,NULL,'STRING',NULL,NULL);

INSERT INTO ATTRIBUTE_MAP
(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID) VALUES (628,150,150,'USER','employeeId',NULL,NULL,77,NULL,'ACTIVE',NULL,NULL,NULL,'STRING',NULL,NULL);

INSERT INTO ATTRIBUTE_MAP
(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID) VALUES (629,150,150,'USER','password',NULL,NULL,58,NULL,'ACTIVE',NULL,NULL,NULL,'DATE',NULL,NULL);
