use openiam;

UPDATE METADATA_TYPE SET IS_SENSITIVE='Y' WHERE TYPE_ID IN(SELECT STATUS_CD FROM STATUS WHERE STATUS_CD NOT IN('CONTRACTOR'));
UPDATE METADATA_TYPE SET IS_SENSITIVE='Y' WHERE TYPE_ID IN('CONTRACTOR TYPE');