use openiam;

DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE IN('ResourceEntity');


DELIMITER $$

DROP PROCEDURE IF EXISTS migrateMenus$$

CREATE PROCEDURE migrateMenus()
	BEGIN
		DECLARE done INT DEFAULT FALSE;
		DECLARE _id VARCHAR(32);
		DECLARE _resourceId VARCHAR(32);
		DECLARE _value VARCHAR(40);
		DECLARE cur1 CURSOR FOR (
			SELECT RESOURCE_PROP_ID, RESOURCE_ID, PROP_VALUE FROM RESOURCE_PROP 
				WHERE RESOURCE_ID IN(
					SELECT RESOURCE_ID FROM RES WHERE RESOURCE_TYPE_ID IN('MENU_ITEM')
				) AND NAME='MENU_DISPLAY_NAME'
		);
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
		OPEN cur1;
			
		REPEAT 
			FETCH cur1 INTO _id, _resourceId, _value;
			IF (_id IS NOT NULL) THEN
				IF (_resourceId IS NOT NULL) THEN
					IF (_value IS NOT NULL) THEN
						IF ((SELECT count(*) FROM LANGUAGE_MAPPING WHERE ID=_id)= 0) THEN
							INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES(_id, '1', 'ResourceEntity', _resourceId, _value);
						END IF;
					END IF;
				END IF;
			END IF;
		UNTIL done END REPEAT;
		CLOSE cur1;
	END$$
DELIMITER ;

call migrateMenus();

DROP PROCEDURE migrateMenus;