use openiam;

UPDATE REPORT_CRITERIA_PARAMETER SET IS_MULTIPLE = 'N' WHERE REPORT_INFO_ID IN (SELECT REPORT_INFO_ID FROM REPORT_INFO WHERE BUILT_IN = 'Y');
UPDATE REPORT_CRITERIA_PARAMETER SET IS_MULTIPLE = 'Y' WHERE RCP_ID IN (1011,1014);

DELETE FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID='1024';
INSERT INTO REPORT_CRITERIA_PARAMETER (REPORT_INFO_ID, RCP_ID, PARAM_NAME, CAPTION, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, IS_MULTIPLE) VALUES ('102','1024','USER_ID','User',null,'1','USER','N');
