use openiam;

DELETE FROM RESOURCE_GROUP  WHERE RESOURCE_ID IN('DIRECTORY');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('DIRECTORY');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN('DIRECTORY');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN('DIRECTORY');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('DIRECTORY');
DELETE FROM res_to_res_membership  WHERE MEMBER_RESOURCE_ID IN('DIRECTORY');
DELETE FROM RES WHERE RESOURCE_ID IN('DIRECTORY');

UPDATE RES SET IS_PUBLIC='N' WHERE RESOURCE_ID IN ('IDMAN', 'ACC_CONTROL', 'PROVISIONING', 'SECURITY_POLICY', 'REPORT', 'WEB_REPORT', 'ADMIN', 'ACCESSCENTER', 'REQUEST_APPROVAL', 'SELFSERVICE_REPORT', 'DIR_LOOKUP_PAGE');

UPDATE RES SET IS_PUBLIC='Y' WHERE RESOURCE_ID IN ('IDM', 'SELFSERVICE', 'SELFSERVICE_MYINFO', 'SELFSERVICE_MYAPPS', 'SELFCENTER', 'CHNGPSWD', 'IDQUEST', 'PROFILE');