use openiam;
DELETE FROM res_to_res_membership where MEMBER_RESOURCE_ID="META_ADMIN";
DELETE FROM res_to_res_membership where MEMBER_RESOURCE_ID="META_SEARCH";
DELETE FROM res_to_res_membership where RESOURCE_ID="META_SUBMENU_ROOT";

DELETE FROM RES where RESOURCE_ID="META_TYPE_EDIT_RETURN";
DELETE FROM res_to_res_membership where MEMBER_RESOURCE_ID="META_TYPE_EDIT_RETURN";
DELETE FROM LANGUAGE_MAPPING where ID="META_TYPE_EDIT_RETURN_DESC";

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, IS_PUBLIC) VALUES  ('META_TYPE_EDIT_RETURN','MENU_ITEM','metadata type edit','metadata type edit', 1, '/webconsole/metaDataTypeEdit.html', 'Y');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID, CREATE_DATE, UPDATE_DATE) VALUES ('META_SUBMENU_ROOT','META_TYPE_EDIT_RETURN',CURDATE(),CURDATE());
INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES('META_TYPE_EDIT_RETURN_DESC', '1', 'ResourceEntity.displayNameMap', 'META_TYPE_EDIT_RETURN', 'Return to Metadata type');

