use openiam;

delete from RESOURCE_GROUP where RESOURCE_ID='UPLOAD_CUST_PSWD_POLICY';
delete from RESOURCE_ROLE where RESOURCE_ID='UPLOAD_CUST_PSWD_POLICY';
delete from RESOURCE_USER where RESOURCE_ID='UPLOAD_CUST_PSWD_POLICY';
delete from RESOURCE_PROP where RESOURCE_ID='UPLOAD_CUST_PSWD_POLICY';
delete from res_to_res_membership where MEMBER_RESOURCE_ID='UPLOAD_CUST_PSWD_POLICY' or RESOURCE_ID='UPLOAD_CUST_PSWD_POLICY';
delete from RES where RESOURCE_ID='UPLOAD_CUST_PSWD_POLICY';

