use openiam;

insert into POLICY_ATTRIBUTE(POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, REQUIRED) VALUES('PWD_EQ_PWD', '138', '4000', 'PWD_EQ_PWD', 'Y'); 

insert into POLICY_ATTRIBUTE(POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, REQUIRED) VALUES('PWD_PASSWORD', '183', '4000', 'PWD_PASSWORD', 'Y'); 

insert into POLICY_ATTRIBUTE(POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, REQUIRED) VALUES('RESET_BY_USER', '139', '4000', 'RESET_BY_USER', 'Y'); 
