use openiam;

delete from LANGUAGE_LOCALE where LANGUAGE_ID='8';
delete from LANGUAGE_MAPPING where LANGUAGE_ID='8';
delete from LANGUAGE_MAPPING where LANGUAGE_ID in ('1','4','2') AND REFERENCE_ID='8' AND REFERENCE_TYPE like 'Language%';
delete from LANGUAGE where ID='8';


insert into LANGUAGE(ID, LANGUAGE,  IS_USED, LANGUAGE_CODE, IS_DEFAULT)
values ('8', 'Russian', 'Y', 'ru', 'N');

insert into LANGUAGE_LOCALE(ID, LANGUAGE_ID,  LOCALE)
values ('10', '8', 'ru_RU');

Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate326','8','326','MetadataElementEntity.languageMap','registeredAddress');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate327','8','327','MetadataElementEntity.languageMap','destinationIndicator');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate328','8','328','MetadataElementEntity.languageMap','preferredDeliveryMethod');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate329','8','329','MetadataElementEntity.languageMap','presentationAddress');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate330','8','330','MetadataElementEntity.languageMap','supportedApplicationContext');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate331','8','331','MetadataElementEntity.languageMap','member');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate332','8','332','MetadataElementEntity.languageMap','owner');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate333','8','333','MetadataElementEntity.languageMap','roleOccupant');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate334','8','334','MetadataElementEntity.languageMap','seeAlso');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate335','8','335','MetadataElementEntity.languageMap','userPassword');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate336','8','336','MetadataElementEntity.languageMap','userCertificate');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate337','8','337','MetadataElementEntity.languageMap','cACertificate');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate338','8','338','MetadataElementEntity.languageMap','authorityRevocationList');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate339','8','339','MetadataElementEntity.languageMap','certificateRevocationList');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate340','8','340','MetadataElementEntity.languageMap','crossCertificatePair');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate341','8','341','MetadataElementEntity.languageMap','givenName');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate342','8','342','MetadataElementEntity.languageMap','initials');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate343','8','343','MetadataElementEntity.languageMap','generationQualifier');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate344','8','344','MetadataElementEntity.languageMap','x500UniqueIdentifier');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate346','8','346','MetadataElementEntity.languageMap','uniqueMember');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate347','8','347','MetadataElementEntity.languageMap','houseIdentifier');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate348','8','348','MetadataElementEntity.languageMap','uid');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate349','8','349','MetadataElementEntity.languageMap','mail');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate350','8','350','MetadataElementEntity.languageMap','ref');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate351','8','351','MetadataElementEntity.languageMap','referral');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate352','8','352','MetadataElementEntity.languageMap','krbName');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate401','8','401','MetadataElementEntity.languageMap','SUBMIT_USER_TO_CONNECTOR');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate402','8','402','MetadataElementEntity.languageMap','INCLUDE_IN_PASSWORD_SYNC');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate405','8','405','MetadataElementEntity.languageMap','INCLUDE_IN_SYNC');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate406','8','406','MetadataElementEntity.languageMap','TABLE_NAME');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate407','8','407','MetadataElementEntity.languageMap','GROUP_MEMBERSHIP_ENABLED');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate408','8','408','MetadataElementEntity.languageMap','ON_DELETE');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate409','8','409','MetadataElementEntity.languageMap','PRE_PROCESS');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate410','8','410','MetadataElementEntity.languageMap','POST_PROCESS');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate411','8','411','MetadataElementEntity.languageMap','HOST_URL');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate412','8','412','MetadataElementEntity.languageMap','BASE_DN');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate413','8','413','MetadataElementEntity.languageMap','HOST_LOGIN ID');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate415','8','415','MetadataElementEntity.languageMap','COMMUNICATION_PROTOCOL');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate416','8','416','MetadataElementEntity.languageMap','OBJECT_CLASS');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate418','8','418','MetadataElementEntity.languageMap','SEARCH_ATTRIBUTE');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate419','8','419','MetadataElementEntity.languageMap','MANAGED_SYS_ID');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate420','8','420','MetadataElementEntity.languageMap','DN_ATTRIBUTE');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate421','8','421','MetadataElementEntity.languageMap','PASSWORD');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate430','8','430','MetadataElementEntity.languageMap','END_POINT');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate440','8','440','MetadataElementEntity.languageMap','OPERATION_NAME');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate450','8','450','MetadataElementEntity.languageMap','URL');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUDEPARTMENT','8','DEPARTMENT','OrganizationTypeEntity.displayNameMap','Подразделение');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUDIVISION','8','DIVISION','OrganizationTypeEntity.displayNameMap','Филиал');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORGANIZATION','8','ORGANIZATION','OrganizationTypeEntity.displayNameMap','Организация');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSUBSIDIARY','8','SUBSIDIARY','OrganizationTypeEntity.displayNameMap','Дочерняя компания');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSYS_ACTION','8','SYS_ACTION','ResourceTypeEntity.displayNameMap','Системное событие');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUI_TEMPLATE','8','UI_TEMPLATE','ResourceTypeEntity.displayNameMap','UI-шаблон');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUURL_PATTERN','8','URL_PATTERN','ResourceTypeEntity.displayNameMap','Образец URL');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAUTH_PROVIDER','8','AUTH_PROVIDER','ResourceTypeEntity.displayNameMap','Провайдер аутентификации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAUTH_REPO','8','AUTH_REPO','ResourceTypeEntity.displayNameMap','Репозиторий аутентификации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUI_WIDGET','8','UI_WIDGET','ResourceTypeEntity.displayNameMap','UI-виджет');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUADMIN_RESOURCE','8','ADMIN_RESOURCE','ResourceTypeEntity.displayNameMap','Ресурс администратора');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCONTENT_PROVIDER','8','CONTENT_PROVIDER','ResourceTypeEntity.displayNameMap','Контент-провайдер');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMANAGED_SYS','8','MANAGED_SYS','ResourceTypeEntity.displayNameMap','Управляемые системы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMENU_ITEM','8','MENU_ITEM','ResourceTypeEntity.displayNameMap','Меню');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU200','8','200','IdentityQuestionEntity.displayNameMap','Назовите последние четыре цифры Вашего номера социального страхования.');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU201','8','201','IdentityQuestionEntity.displayNameMap','Назовите девичью фамилию Вашей матери.');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU202','8','202','IdentityQuestionEntity.displayNameMap','Где Вы ходили в школу?');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU203','8','203','IdentityQuestionEntity.displayNameMap','Как зовут Вашего домашнего питомца?');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU204','8','204','IdentityQuestionEntity.displayNameMap','Какое Ваше любимое блюдо?');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU205','8','205','IdentityQuestionEntity.displayNameMap','Какой Ваш любимый цвет?');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU206','8','206','IdentityQuestionEntity.displayNameMap','В каком городе Вы родились?');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU207','8','207','IdentityQuestionEntity.displayNameMap','Какой вид спорта вам нравится?');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU209','8','209','IdentityQuestionEntity.displayNameMap','Назовите последние четыре цифры номера Вашего водительского удостоверения.');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU210','8','210','IdentityQuestionEntity.displayNameMap','Назовите Вашу любимую школу?');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU211','8','211','IdentityQuestionEntity.displayNameMap','Назовите имя Вашего первого питомца.');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU212','8','212','IdentityQuestionEntity.displayNameMap','Назовите Ваш любимый фильм, игру или песню.');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU213','8','213','IdentityQuestionEntity.displayNameMap','Как называется Ваша любимая книга?');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU214','8','214','IdentityQuestionEntity.displayNameMap','Назовите имя Вашего первого парня / девушки.');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU215','8','215','IdentityQuestionEntity.displayNameMap','Назовите имя Вашего любимого школьного учителя.');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU216','8','216','IdentityQuestionEntity.displayNameMap','Назовите год выпуска и модель Вашего первого автомобиля (Год-Модель).');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU217','8','217','IdentityQuestionEntity.displayNameMap','Где вы встретили Вашу «вторую половинку»?');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RU218','8','218','IdentityQuestionEntity.displayNameMap','Кто был Вашим первым питомцем и как его звали (Вид питомца-Имя)?');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RULANGUAGE_ADMIN1','8','LANGUAGE_ADMIN','ResourceEntity.displayNameMap','Языки');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RULANGUAGE_EDIT1','8','LANGUAGE_EDIT','ResourceEntity.displayNameMap','Новый язык');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RULANGUAGE_SEARCH1','8','LANGUAGE_SEARCH','ResourceEntity.displayNameMap','Языки');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUBULK_OPS_DESC','8','BULK_OPS','ResourceEntity.displayNameMap','Групповые задачи с пользователями');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity56','8','SECURITY MANAGER','MetadataTypeEntity.displayNameMap','Администратор безопасности');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity61','8','ATTR','MetadataTypeEntity.displayNameMap','Атрибут');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity66','8','OFF-LINE','MetadataTypeEntity.displayNameMap','Офлайн');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity70','8','DELETED','MetadataTypeEntity.displayNameMap','УДАЛЕНО');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity75','8','PENDING_START_DATE','MetadataTypeEntity.displayNameMap','Ожидаемая дата начала');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity81','8','LOCKED_ADMIN','MetadataTypeEntity.displayNameMap','Заблокировано администратором');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity86','8','SYS ACCOUNT','MetadataTypeEntity.displayNameMap','Системная учетная запись');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMETA_ADMIN_DESC','8','META_ADMIN','ResourceEntity.displayNameMap','Элементы метаданных');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMETA_TYPE_ADMIN_DESC','8','META_TYPE_ADMIN','ResourceEntity.displayNameMap','Типы метаданных');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMETA_TYPE_EDIT_DESC','8','META_TYPE_EDIT','ResourceEntity.displayNameMap','Новый тип метаданных');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMETA_EDIT_DESC','8','META_EDIT','ResourceEntity.displayNameMap','Новый элемент метаданных');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMETA_SEARCH_DESC','8','META_SEARCH','ResourceEntity.displayNameMap','Поиск метаданных');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RURES_TYPE_DESC','8','RES_TYPE_ITEM','ResourceEntity.displayNameMap','Тип ресурса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RURES_TYPE_NEW_DESC','8','RES_TYPE_NEW','ResourceEntity.displayNameMap','Новый тип ресурса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAUTH_LVL_GRP_NEW_ROOT_DN','8','AUTH_LVL_GRP_NEW_ROOT','ResourceEntity.displayNameMap','Группировка по уровню аутентификации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAUTH_LVL_GRP_EDIT_ROOT_DN','8','AUTH_LVL_GRP_EDIT_ROOT','ResourceEntity.displayNameMap','Редактирование группировки по уровню аутентификации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUBACK_TO_AUTH_LVL_GRP_SRH_DN','8','BACK_TO_AUTH_LVL_GRP_SRH','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAUTH_LVL_GRP_ATTR_DN','8','AUTH_LVL_GRP_ATTR','ResourceEntity.displayNameMap','Атрибуты группировки по уровню аутентификации - корневой элемент');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUBACK_TO_AUTH_LVL_DN','8','BACK_TO_AUTH_LVL','ResourceEntity.displayNameMap','Вернуться к группам');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAUTH_LEVEL_GRP_DN','8','AUTH_LEVEL_GRP','ResourceEntity.displayNameMap','Группы аутентификации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERVICE_EXT_DN','8','SELFSERVICE_EXT','ResourceEntity.displayNameMap','Расширения SelfService - Корневой элемент');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_EXAMPLE_DN','8','SELFSRV_EXAMPLE','ResourceEntity.displayNameMap','Пример');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUGROUP_ROOT_MENU_DESC','8','GROUP_ROOT_MENU','ResourceEntity.displayNameMap','Группы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUGROUP_SEARCH_DESC','8','GROUP_SEARCH','ResourceEntity.displayNameMap','Поиск групп');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUIDM_MENU_DISPLAY','8','IDM','ResourceEntity.displayNameMap','Идентификатор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUIDQUEST_MENU_DISPLAY','8','IDQUEST','ResourceEntity.displayNameMap','Ответ на запрос');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RULOCATION_MENU_DISPLAY','8','LOCATION','ResourceEntity.displayNameMap','Расположение');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMANAGEREQ_MENU_DISPLAY','8','MANAGEREQ','ResourceEntity.displayNameMap','История запросов');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMETADATA_MENU_DISPLAY','8','METADATA','ResourceEntity.displayNameMap','Метаданные');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMNGSYS_DESC','8','MNGSYS_MENU_ITEM','ResourceEntity.displayNameMap','Управляемые системы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMNGSYS_DSC','8','MNGSYS_NEW','ResourceEntity.displayNameMap','Создать управляемую систему');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMNGSYS_MENU_DISPLAY','8','MNGSYS','ResourceEntity.displayNameMap','Управляемая система');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEWUSER-NOAPPRV_MENU_DISPLAY','8','NEWUSER-NOAPPRV','ResourceEntity.displayNameMap','Создать пользователя без подтверждения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEWUSER_MENU_DISPLAY','8','NEWUSER','ResourceEntity.displayNameMap','Новый пользователь');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_GROUP_DESC','8','NEW_GROUP','ResourceEntity.displayNameMap','Создать новую группу');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_ORG_DESC','8','NEW_ORG','ResourceEntity.displayNameMap','Создать новую организацию');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_ROLE_DESC','8','NEW_ROLE','ResourceEntity.displayNameMap','Создать новую роль');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_USER_DESC','8','NEW_USER','ResourceEntity.displayNameMap','Создать нового пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORGANIZATION_EDIT_ID_DESC','8','ORGANIZATION_EDIT_ID','ResourceEntity.displayNameMap','Меню редактирования организаций');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORGANIZATION_ROOT_ID_DESC','8','ORGANIZATION_ROOT_ID','ResourceEntity.displayNameMap','Организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORG_MEMBERSHIP_DESC','8','ORG_MEMBERSHIP','ResourceEntity.displayNameMap','Подразделения организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORG_MENU_DISPLAY','8','ORG','ResourceEntity.displayNameMap','Организация');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORG_SEARCH_DESC','8','ORG_SEARCH','ResourceEntity.displayNameMap','Поиск организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPAGE_TMPLT_EDIT_DESC','8','PAGE_TEMPLATE_EDIT','ResourceEntity.displayNameMap','Меню редактирования шаблона страницы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPAGE_TMPLT_EDIT_NEW_DESC','8','PAGE_TEMPLATE_EDIT_NEW','ResourceEntity.displayNameMap','Редактировать шаблон');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPAGE_TMPLT_EDIT_SEARCH_DESC','8','PAGE_TEMPLATE_EDIT_SEARCH','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPAGE_TMPLT_NEW_DSC','8','PAGE_TEMPLATE_NEW','ResourceEntity.displayNameMap','Создать новый шаблон');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPAGE_TMPLT_ROOT_DESC','8','PAGE_TEMPLATE_ROOT','ResourceEntity.displayNameMap','Шаблоны страниц');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPAGE_TMPLT_SEARCH_DESC','8','PAGE_TEMPLATE_SEARCH','ResourceEntity.displayNameMap','Поиск шаблонов страниц');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPROFILE_MENU_DISPLAY','8','PROFILE','ResourceEntity.displayNameMap','Редактировать ваш профиль');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPROVCONNECT_DESC','8','PROVCONNECT_MENU_ITEM','ResourceEntity.displayNameMap','Инициализация коннекторов');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPROVCONNECT_MENU_DISPLAY','8','PROVCONNECT','ResourceEntity.displayNameMap','Коннекторы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPROVISIONING_MENU_DISPLAY','8','PROVISIONING','ResourceEntity.displayNameMap','Инициализация');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPROV_CONNECTOR_DSC','8','PROV_CONNECTOR_NEW','ResourceEntity.displayNameMap','Создать новый коннектор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUREPORT_MENU_DISPLAY','8','REPORT','ResourceEntity.displayNameMap','Управление отчетами');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUREQINBOX_MENU_DISPLAY','8','REQINBOX','ResourceEntity.displayNameMap','Входящие');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RURESOURCE_EDIT_PAGE_ROOT_DIS','8','RESOURCE_EDIT_PAGE_ROOT','ResourceEntity.displayNameMap','Редактирование ресурса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RURESPOLICYMAP_MENU_DISPLAY','8','RESPOLICYMAP','ResourceEntity.displayNameMap','Карта политик');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RURESRECONCILE_MENU_DISPLAY','8','RESRECONCILE','ResourceEntity.displayNameMap','Реконсиляция');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RURESSUMMARY_MENU_DISPLAY','8','RESSUMMARY','ResourceEntity.displayNameMap','Детализация ресурсов');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RURES_ENT_SUB_DIS','8','RES_ENT_SUB','ResourceEntity.displayNameMap','Разрешения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUROLE_EDIT_MENU_DESC','8','ROLE_EDIT_MENU','ResourceEntity.displayNameMap','Редактирование роли - главное меню');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUROLE_ENTITLEMENTS_DESC','8','ROLE_ENTITLEMENTS','ResourceEntity.displayNameMap','Разрешения ролей');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUROLE_MENUS_DESC','8','ROLE_MENUS','ResourceEntity.displayNameMap','Меню');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUROLE_ROOT_MENU_DESC','8','ROLE_ROOT_MENU','ResourceEntity.displayNameMap','Роли');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUROLE_SEARCH_DESC','8','ROLE_SEARCH','ResourceEntity.displayNameMap','Поиск роли');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSECURITY_GROUP_MENU_DISPLAY','8','SECURITY_GROUP','ResourceEntity.displayNameMap','Группа');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSECURITY_POLICY_MENU_DISPLAY','8','SECURITY_POLICY','ResourceEntity.displayNameMap','Политика');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSECURITY_RES_MENU_DISPLAY','8','SECURITY_RES','ResourceEntity.displayNameMap','Ресурс');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSECURITY_ROLE_MENU_DISPLAY','8','SECURITY_ROLE','ResourceEntity.displayNameMap','Роль');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFCENTER_MENU_DISPLAY','8','SELFCENTER','ResourceEntity.displayNameMap','Центр самообслуживания');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERVICE_MENU_DISPLAY','8','SELFSERVICE','ResourceEntity.displayNameMap','САМООБСЛУЖИВАНИЕ');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERVICE_MYAPPS_DESC','8','SELFSERVICE_MYAPPS','ResourceEntity.displayNameMap','Мои приложения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERVICE_MYINFO_DESC','8','SELFSERVICE_MYINFO','ResourceEntity.displayNameMap','Моя информация');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELF_QUERYUSER_MENU_DISPLAY','8','SELF_QUERYUSER','ResourceEntity.displayNameMap','Управление пользователем');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSYNCUSER_MENU_DISPLAY','8','SYNCUSER','ResourceEntity.displayNameMap','Синхронизация');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUTEMPLATE_SEARCH_CHILD_DESC','8','TEMPLATE_SEARCH_CHILD','ResourceEntity.displayNameMap','Страница шаблонов');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUURI_META_BACK_DESC','8','URI_META_BACK','ResourceEntity.displayNameMap','Вернуться к шаблонам');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUURI_META_EDIT_DESC','8','URI_META_EDIT','ResourceEntity.displayNameMap','URI Meta меню');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUURI_PTRN_EDIT_DESC','8','URI_PATTERN_EDIT','ResourceEntity.displayNameMap','Меню редактирования URI-шаблонов');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUURI_PTRN_EDIT_NEW_PATTERN_DES','8','URI_PATTERN_EDIT_NEW_PATTERN','ResourceEntity.displayNameMap','Создать URI-шаблон');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUURI_PTRN_EDIT_PATTERN_DESC','8','URI_PATTERN_EDIT_PATTERN','ResourceEntity.displayNameMap','Редактировать URI-шаблон');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_ATTRIBUTES_DESC','8','USER_ATTRIBUTES','ResourceEntity.displayNameMap','Атрибуты пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_BULK_MENU_DISPLAY','8','USER_BULK','ResourceEntity.displayNameMap','Операции над группой пользователей');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_DELEGATION_DESC','8','USER_DELEGATION','ResourceEntity.displayNameMap','Фильтр полномочий пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_EDIT_CONTACT_INFO_DESC','8','USER_EDIT_CONTACT_INFO','ResourceEntity.displayNameMap','Контактная информация');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RULanguageEntity4','8','4','LanguageEntity.displayNameMap','Испанский');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUEDIT_ORG_TYPE_DESC','8','EDIT_ORG_TYPE','ResourceEntity.displayNameMap','Редактирование типа организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUBATCH_TASK_ROOT_DESC','8','BATCH_TASK_ROOT','ResourceEntity.displayNameMap','Групповые задачи');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUEDIT_BATCH_TASK_DESC','8','EDIT_BATCH_TASK','ResourceEntity.displayNameMap','Редактирование групповых задач');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity1','8','ADGroup','MetadataTypeEntity.displayNameMap','AD-тип пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity2','8','ADUser','MetadataTypeEntity.displayNameMap','AD-тип пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity3','8','AD_Connector','MetadataTypeEntity.displayNameMap','AD-коннектор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity4','8','AD_GROUP_TYPE','MetadataTypeEntity.displayNameMap','AD-тип группы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity5','8','AUTHENTICATION_PROVIDER','MetadataTypeEntity.displayNameMap','Аутентификация провайдера');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity6','8','AUTH_REPO','MetadataTypeEntity.displayNameMap','Аутентификация репозитория');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity7','8','CHECKBOX','MetadataTypeEntity.displayNameMap','Флажок');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity8','8','CONTENT_PROVIDER','MetadataTypeEntity.displayNameMap','Контент-провайдер');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity9','8','Contractor','MetadataTypeEntity.displayNameMap','Тип контрактника');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity10','8','DATE','MetadataTypeEntity.displayNameMap','Поле типа «дата»');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity11','8','DEFAULT_GROUP','MetadataTypeEntity.displayNameMap','Тип группы по умолчанию');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity12','8','departmentType','MetadataTypeEntity.displayNameMap','Подразделение');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity13','8','DIRECTORY','MetadataTypeEntity.displayNameMap','Каталог');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity14','8','divisionType','MetadataTypeEntity.displayNameMap','Филиал');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity15','8','FILE','MetadataTypeEntity.displayNameMap','Файл');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity16','8','GOOGLE_Connector','MetadataTypeEntity.displayNameMap','Google Apps-коннектор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity17','8','InetOrgPerson','MetadataTypeEntity.displayNameMap','Тип пользователя InetOrgPerson');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity18','8','LdapOrgPerson','MetadataTypeEntity.displayNameMap','Тип пользователя LdapOrgPerson');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity19','8','LDAP_Connector','MetadataTypeEntity.displayNameMap','LDAP-коннектор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity20','8','LDAP_GROUP_TYPE','MetadataTypeEntity.displayNameMap','Тип группы LDAP');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity21','8','LINUX_Connector','MetadataTypeEntity.displayNameMap','Linux-коннектор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity22','8','MANAGED_SYS','MetadataTypeEntity.displayNameMap','Управляемая система');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity23','8','MENU_ITEM','MetadataTypeEntity.displayNameMap','Тип элемента меню');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity24','8','MULTI_SELECT','MetadataTypeEntity.displayNameMap','Список мультивыбора');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity25','8','NO-PROVISION-APP','MetadataTypeEntity.displayNameMap','Приложения, не используемые для провижн');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity26','8','OrgOpenIAM','MetadataTypeEntity.displayNameMap','OpenIAM');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity27','8','PASSWORD','MetadataTypeEntity.displayNameMap','Поле для ввода пароля');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity28','8','RADIO','MetadataTypeEntity.displayNameMap','Переключатель');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity29','8','RDBMS_Connector','MetadataTypeEntity.displayNameMap','RDBMS-коннектор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity30','8','SCRIPT_Connector','MetadataTypeEntity.displayNameMap','Script-коннектор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity31','8','SELECT','MetadataTypeEntity.displayNameMap','Поле со списком');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity32','8','SOAP_Connector','MetadataTypeEntity.displayNameMap','SOAP-коннектор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity33','8','SystemAccount','MetadataTypeEntity.displayNameMap','Тип системного аккаунта');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity34','8','SYS_ACTION','MetadataTypeEntity.displayNameMap','Системные события');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity35','8','TEXT','MetadataTypeEntity.displayNameMap','Текстовое поле');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity36','8','TEXTAREA','MetadataTypeEntity.displayNameMap','Многострочное поле ввода');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity37','8','UI_TEMPLATE','MetadataTypeEntity.displayNameMap','UI-шаблон');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity38','8','UI_WIDGET','MetadataTypeEntity.displayNameMap','UI-виджет');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity39','8','URL','MetadataTypeEntity.displayNameMap','URL');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity40','8','URL_PATTERN','MetadataTypeEntity.displayNameMap','Пример URL');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity41','8','WEBSERVICE','MetadataTypeEntity.displayNameMap','Веб-сервис');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity42','8','WEBSERVICE_OP','MetadataTypeEntity.displayNameMap','Операция веб-сервиса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity43','8','WORK_EMAIL','MetadataTypeEntity.displayNameMap','Рабочий email');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity44','8','PRIMARY_EMAIL','MetadataTypeEntity.displayNameMap','Основной email');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity45','8','HOME_EMAIL','MetadataTypeEntity.displayNameMap','Домашний email');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity46','8','OFFICE_PHONE','MetadataTypeEntity.displayNameMap','Рабочий телефон');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity47','8','CELL_PHONE','MetadataTypeEntity.displayNameMap','Сотовый телефон');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity48','8','HOME_PHONE','MetadataTypeEntity.displayNameMap','Домашний телефон');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity49','8','OFFICE_ADDRESS','MetadataTypeEntity.displayNameMap','Рабочий адрес');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity50','8','HOME_ADDRESS','MetadataTypeEntity.displayNameMap','Домашний адрес');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity51','8','ADMIN_RESOURCE','MetadataTypeEntity.displayNameMap','Ресурс администратора');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity52','8','KERBEROS_SERVICE_NAME','MetadataTypeEntity.displayNameMap','Имя сервиса Kerberos');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity53','8','KERBEROS_KEYTAB_FILE','MetadataTypeEntity.displayNameMap','Файл Kerberos Keytab');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity54','8','MANAGER','MetadataTypeEntity.displayNameMap','Менеджер');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity55','8','SALES REP','MetadataTypeEntity.displayNameMap','Торговый представитель');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity57','8','SERVICE REP','MetadataTypeEntity.displayNameMap','Представитель сервисной службы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity58','8','ACCNT','MetadataTypeEntity.displayNameMap','Аккаунт');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity59','8','ADMGP','MetadataTypeEntity.displayNameMap','Группа администратора');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity60','8','ADMIN','MetadataTypeEntity.displayNameMap','Администратор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity62','8','BL','MetadataTypeEntity.displayNameMap','Заблокировать');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity63','8','DL','MetadataTypeEntity.displayNameMap','Удалить');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity64','8','RJ','MetadataTypeEntity.displayNameMap','Отклонить');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity65','8','UB','MetadataTypeEntity.displayNameMap','Разблокировать');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity67','8','READY','MetadataTypeEntity.displayNameMap','Готовый к работе');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity68','8','ACTIVE','MetadataTypeEntity.displayNameMap','Активный');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity69','8','APPROVAL_DECLINED','MetadataTypeEntity.displayNameMap','Утверждение отклонено');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity71','8','INACTIVE','MetadataTypeEntity.displayNameMap','Неактивный');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity72','8','LEAVE','MetadataTypeEntity.displayNameMap','Отпуск');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity73','8','PENDING_APPROVAL','MetadataTypeEntity.displayNameMap','В ожидании утверждения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity74','8','PENDING_INITIAL_LOGIN','MetadataTypeEntity.displayNameMap','В ожидании первого входа');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity76','8','PENDING_USER_VALIDATION','MetadataTypeEntity.displayNameMap','В ожидании аттестации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity77','8','RETIRED','MetadataTypeEntity.displayNameMap','На пенсии');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity78','8','TERMINATE','MetadataTypeEntity.displayNameMap','Прервать');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity79','8','DISABLED','MetadataTypeEntity.displayNameMap','Выключенный');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity80','8','LOCKED','MetadataTypeEntity.displayNameMap','Заблокированный');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity82','8','AFFILIATE','MetadataTypeEntity.displayNameMap','Филиал');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity83','8','CONTRACTOR TYPE','MetadataTypeEntity.displayNameMap','Контрактор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity84','8','PERM FULL TIME','MetadataTypeEntity.displayNameMap','Постоянная полная занятость');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity85','8','PERM PART TIME','MetadataTypeEntity.displayNameMap','Постоянная частичная занятость');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity87','8','VENDOR','MetadataTypeEntity.displayNameMap','Поставщик');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RULanguageEntity1','8','1','LanguageEntity.displayNameMap','Английский');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RULanguageEntity7','8','8','LanguageEntity.displayNameMap','Русский');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCNT_PROV_NEW_EDIT_PUB_DESC','8','CONTENT_PROV_NEW_EDIT','ResourceEntity.displayNameMap','Создать нового провайдера');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAM_PROV_AM_ATTR_DESC','8','AM_PROV_AM_ATTR','ResourceEntity.displayNameMap','Атрибуты запроса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAM_PROV_EDIT_CURRENT_DESC','8','AM_PROV_EDIT_CURRENT','ResourceEntity.displayNameMap','Редактировать провайдера');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAM_PROV_EDIT_DESC','8','AM_PROV_EDIT','ResourceEntity.displayNameMap','Меню редактирования провайдера аутентификации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAM_PROV_NEW_DSC','8','AM_PROV_NEW','ResourceEntity.displayNameMap','Создать нового провайдера');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAM_PROV_NEW_EDIT_PUB_DESC','8','AM_PROV_NEW_EDIT','ResourceEntity.displayNameMap','Создать нового провайдера');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAM_PROV_ROOT_DESC','8','AM_PROV_ROOT','ResourceEntity.displayNameMap','Провайтеры аутентификации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAM_PROV_SEARCH_CHILD_PUB_DESC','8','AM_PROV_SEARCH_CHILD','ResourceEntity.displayNameMap','Поставщики проверки подлинности');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAM_PROV_SEARCH_DESC','8','AM_PROV_SEARCH','ResourceEntity.displayNameMap','Поиск провайдера');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAUDITREPORT_MENU_DISPLAY','8','AUDITREPORT','ResourceEntity.displayNameMap','Отчеты проверки');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAUDIT_RPT_MENU_DISPLAY','8','AUDIT_RPT','ResourceEntity.displayNameMap','Отчет проверки');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUBACK_TO_CP_DESC','8','BACK_TO_CP','ResourceEntity.displayNameMap','Вернуться к контент-провайдеру');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUBATCH_PROC_MENU_DISPLAY','8','BATCH_PROC','ResourceEntity.displayNameMap','Групповые процессы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCHALLENGE_MENU_DISPLAY','8','CHALLENGE','ResourceEntity.displayNameMap','Вопросы для напоминания пароля');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCHNGPSWD_MENU_DISPLAY','8','CHNGPSWD','ResourceEntity.displayNameMap','Изменить пароль');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCNT_PROV_EDIT_CURRENT_DESC','8','CONTENT_PROV_EDIT_CURRENT','ResourceEntity.displayNameMap','Редактировать провайдера');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCNT_PROV_EDIT_DESC','8','CONTENT_PROV_EDIT','ResourceEntity.displayNameMap','Меню редактирования контент-провайдера');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCNT_PROV_EDIT_SEARCH_DESC','8','CONTENT_PROV_EDIT_SEARCH','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCNT_PROV_NEW_DSC','8','CONTENT_PROV_NEW','ResourceEntity.displayNameMap','Создать нового провайдера');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCNT_PROV_ROOT_DESC','8','CONTENT_PROV_ROOT','ResourceEntity.displayNameMap','Контент-провайдеры');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCNT_PROV_SEARCH_CHILD_PUB_DE','8','CONTENT_PROV_SEARCH_CHILD','ResourceEntity.displayNameMap','Контент-провайдеры');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCNT_PROV_SEARCH_DESC','8','CONTENT_PROV_SEARCH','ResourceEntity.displayNameMap','Поиск контент-провайдеров');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCREATEREQ_MENU_DISPLAY','8','CREATEREQ','ResourceEntity.displayNameMap','Создать запрос');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCR_RES_DISP_NAME','8','CREATE_RESOURCE_MENU','ResourceEntity.displayNameMap','Создать новый ресурс');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCUST_FIELD_EDIT_DESC','8','CUSTOM_FIELD_EDIT','ResourceEntity.displayNameMap','Меню редактирования настраиваемых полей');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCUST_FIELD_EDIT_NEW_DESC','8','CUSTOM_FIELD_EDIT_NEW','ResourceEntity.displayNameMap','Создать новое настраиваемое поле');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCUST_FIELD_EDIT_SEARCH_DESC','8','CUSTOM_FIELD_EDIT_SEARCH','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCUST_FIELD_NEW_DSC','8','CUSTOM_FIELD_NEW','ResourceEntity.displayNameMap','Создать новое настраиваемое поле');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCUST_FIELD_ROOT_DESC','8','CUSTOM_FIELD_ROOT','ResourceEntity.displayNameMap','Настраиваемые поля');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCUST_FIELD_SEARCH_CHILD_DESC','8','CUSTOM_FIELD_SEARCH_CHILD','ResourceEntity.displayNameMap','Настраиваемые поля');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCUST_FIELD_SEARCH_DESC','8','CUSTOM_FIELD_SEARCH','ResourceEntity.displayNameMap','Поиск настраиваемых полей');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUDELG_FILTER_MENU_DISPLAY','8','DELG_FILTER','ResourceEntity.displayNameMap','Фильтр делегирования');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUDIRECTORY_MENU_DISPLAY','8','DIRECTORY','ResourceEntity.displayNameMap','Поиск в справочнике');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUEDIT_GROUP_DESC','8','EDIT_GROUP','ResourceEntity.displayNameMap','Редактирование группы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUEDIT_ORG_DESC','8','EDIT_ORG','ResourceEntity.displayNameMap','Редактирование организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUEDIT_RESOURCE_DIS','8','EDIT_RESOURCE','ResourceEntity.displayNameMap','Редактирование ресурса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUEDIT_ROLE_DESC','8','EDIT_ROLE','ResourceEntity.displayNameMap','Редактирование роли');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUGROUP_EDIT_MENU_DESC','8','GROUP_EDIT_MENU','ResourceEntity.displayNameMap','Главное меню редактирования группы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUGROUP_ENTITLEMENTS_DESC','8','GROUP_ENTITLEMENTS','ResourceEntity.displayNameMap','Разрешения групп');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUGROUP_MENUS_DESC','8','GROUP_MENUS','ResourceEntity.displayNameMap','Меню');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSS_ACCESS_REVIEW_DESC','8','SELFSERV_ACCESS_REVIEW','ResourceEntity.displayNameMap','Проверка доступа');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUREQUEST_APPROVAL_DESC','8','REQUEST_APPROVAL','ResourceEntity.displayNameMap','Подтверждение запроса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERVICE_GROUPS_DN','8','SELFSERVICE_GROUPS','ResourceEntity.displayNameMap','Группы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERVICE_ROLES_DN','8','SELFSERVICE_ROLES','ResourceEntity.displayNameMap','Роли');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERVICE_RESOURCES_DN','8','SELFSERVICE_RESOURCES','ResourceEntity.displayNameMap','Ресурсы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSS_ORG_BACK_SEARCH_DN','8','SS_ORG_BACK_SEARCH','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_GRP_SRCH_ROOT_DESC','8','SELFSRV_GRP_SRCH_ROOT','ResourceEntity.displayNameMap','Группы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERV_GRP_NEW_DN','8','SELFSERV_GRP_NEW','ResourceEntity.displayNameMap','Создать новую группу');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_GRP_EDIT_ROOT_DESC','8','SELFSRV_GRP_EDIT_ROOT','ResourceEntity.displayNameMap','Редактирование группы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERV_GRP_EDIT_DN','8','SELFSERV_GRP_EDIT','ResourceEntity.displayNameMap','Редактировать группу');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERV_GRP_BACK_SRCH_DN','8','SELFSERV_GRP_BACK_SRCH','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_ROLE_SRCH_ROOT_DN','8','SELFSRV_ROLE_SRCH_ROOT','ResourceEntity.displayNameMap','Роли');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERV_ROLE_NEW_DN','8','SELFSERV_ROLE_NEW','ResourceEntity.displayNameMap','Создать новую роль');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_ROLE_EDIT_ROOT_DESC','8','SELFSRV_ROLE_EDIT_ROOT','ResourceEntity.displayNameMap','Редактирование роли');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_ROLE_EDIT_DN','8','SELFSRV_ROLE_EDIT','ResourceEntity.displayNameMap','Редактировать роль');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_ROLE_BACK_SRCH_DN','8','SELFSRV_ROLE_BACK_SRCH','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_RES_SRCH_ROOT_DN','8','SELFSRV_RES_SRCH_ROOT','ResourceEntity.displayNameMap','Ресурсы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_RES_NEW_DN','8','SELFSRV_RES_NEW','ResourceEntity.displayNameMap','Создать новый ресурс');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_RES_EDIT_ROOT_DESC','8','SELFSRV_RES_EDIT_ROOT','ResourceEntity.displayNameMap','Редактирование ресурса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_RES_EDIT_DN','8','SELFSRV_RES_EDIT','ResourceEntity.displayNameMap','Редактировать ресурс');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSRV_RES_BACK_SRCH_DN','8','SELFSRV_RES_BACK_SRCH','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMENUS_SEARCH_DC','8','MENUS_SEARCH','ResourceEntity.displayNameMap','Меню');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUI_THEME_ROOT_DN','8','UI_THEME_ROOT','ResourceEntity.displayNameMap','Основная тема пользовательского интерфейса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUI_THEME_ROOT_SRCH_DN','8','UI_THEME_ROOT_SRCH','ResourceEntity.displayNameMap','Поиск тем пользовательского интерфейса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_UI_THEME_DN','8','NEW_UI_THEME','ResourceEntity.displayNameMap','Новая тема пользовательского интерфейса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUI_THEME_EDIT_DN','8','UI_THEME_EDIT','ResourceEntity.displayNameMap','Редактировать тему пользовательского интерфейса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUI_THEME_EDIT_MODIFY_DN','8','UI_THEME_EDIT_MODIFY','ResourceEntity.displayNameMap','Редактировать тему пользовательского интерфейса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUI_THEMES_DN','8','UI_THEMES','ResourceEntity.displayNameMap','Темы пользовательского интерфейса');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSS_GRP_ENT_DN','8','SS_GRP_ENT','ResourceEntity.displayNameMap','Разрешения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSS_ROLE_ENT_DN','8','SS_ROLE_ENT','ResourceEntity.displayNameMap','Разрешения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERV_USER_EDIT_DESC','8','SELFSERV_USER_EDIT','ResourceEntity.displayNameMap','Редактировать пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERV_USER_MEMSHP_DES','8','SELFSERV_USER_MEMSHP','ResourceEntity.displayNameMap','Разрешения пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCHLLNG_RESP_QUESTION_DESC','8','CHALLENGE_RESPONSE_QUESTION','ResourceEntity.displayNameMap','Вопрос для восстановления пароля');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCHLLNG_RESP_QUEST_ROOT_DESC','8','CHALLENGE_RESPONSE_QUESTION_ROOT','ResourceEntity.displayNameMap','Вопросы для восстановления пароля');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCHLLNG_RESP_QUESTION_NEW_DSC','8','CHALLENGE_RESPONSE_QUESTION_NEW','ResourceEntity.displayNameMap','Создать новый вопрос');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSYNCUSER_EDIT_DESC','8','SYNCUSER_EDIT','ResourceEntity.displayNameMap','Редактировать синхронизацию');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSYNCUSER_POLICYMAP_DESC','8','SYNCUSER_POLICYMAP','ResourceEntity.displayNameMap','Карта политик');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUWEB_REPORT_ROOT_DESC','8','WEB_REPORT_ROOT','ResourceEntity.displayNameMap','Отчеты');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUWEB_REPORT_NEW_DSC','8','WEB_REPORT_NEW','ResourceEntity.displayNameMap','Создать новый отчет');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUCONF_POLICY_PAGE_DIS','8','CONF_POLICY_PAGE','ResourceEntity.displayNameMap','Настройка IT-политики');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORG_TYPE_SUBMENU_ROOT_DESC','8','ORG_TYPE_SUBMENU_ROOT','ResourceEntity.displayNameMap','Типы организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORG_TYPE_SUBMENU_EDIT_DESC','8','ORG_TYPE_SUBMENU_EDIT','ResourceEntity.displayNameMap','Редактирование типа организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORG_TYPE_SEARCH_DESC','8','ORG_TYPE_SEARCH','ResourceEntity.displayNameMap','Поиск типов организаций');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_ORG_TYPE_DESC','8','NEW_ORG_TYPE','ResourceEntity.displayNameMap','Новый тип организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUEDIT_ORG_MEMBERSHIP_DESC','8','EDIT_ORG_MEMBERSHIP','ResourceEntity.displayNameMap','Состав организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORG_TYPE_EDIT_SEARCH_DESC','8','ORG_TYPE_EDIT_SEARCH','ResourceEntity.displayNameMap','Поиск типов организаций');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUEDIT_ORG_TYPE_IDMAN_DESC','8','EDIT_ORG_TYPE_IDMAN','ResourceEntity.displayNameMap','Типы организаций');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSUP_SUB_PAGE_DIS','8','SUP_SUB_PAGE','ResourceEntity.displayNameMap','Начальники и подчиненные');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSEARCH_BATCH_NEW_DESC','8','SEARCH_BATCH_NEW','ResourceEntity.displayNameMap','Поиск групповых задач');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_BATCH_TASK_DESC','8','NEW_BATCH_TASK','ResourceEntity.displayNameMap','Новая групповая задача');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUBATCH_TASK_EDIT_DESC','8','BATCH_TASK_EDIT','ResourceEntity.displayNameMap','Редактирование групповой задачи');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSEARCH_BATCH_EDIT_DESC','8','SEARCH_BATCH_EDIT','ResourceEntity.displayNameMap','Поиск групповых задач');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUADMIN_BATCH_TASKS_DESC','8','ADMIN_BATCH_TASKS','ResourceEntity.displayNameMap','Групповые задачи');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUDIR_LOOKUP_PAGE_DIS','8','DIR_LOOKUP_PAGE','ResourceEntity.displayNameMap','Поиск в справочнике');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMANUALRECON_DESC','8','MANUALRECON','ResourceEntity.displayNameMap','Reconciliation вручную');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSUBSCRIBE_MENU_DESC','8','SUBSCRIBE','ResourceEntity.displayNameMap','Подписка');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUVIEW_MENU_DESC','8','VIEW','ResourceEntity.displayNameMap','Просмотр');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELF_SUB_REPORT_NEW_DSC','8','SELF_SUB_REPORT_NEW','ResourceEntity.displayNameMap','Подписаться на отчет');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELF_VIEW_REPORT_ROOT_DESC','8','SELF_VIEW_REPORT_ROOT','ResourceEntity.displayNameMap','Просмотр отчета');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELF_VIEW_REPORT_NEW_DSC','8','SELF_VIEW_REPORT_NEW','ResourceEntity.displayNameMap','Создать новый вид отчета');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERVE_SUP_SUB_DESC','8','SELFSERVE_SUP_SUB','ResourceEntity.displayNameMap','Начальники и подчиненные');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSER_USER_LOGIN_DESC','8','SELFSER_USER_LOGIN','ResourceEntity.displayNameMap','Личности');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUACCESSCENTER_MENU_DISPLAY','8','ACCESSCENTER','ResourceEntity.displayNameMap','Управление доступом');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUWEB_REPORT_DESC','8','WEB_REPORT','ResourceEntity.displayNameMap','Отчет');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSERVICE_REPORT_DESC','8','SELFSERVICE_REPORT','ResourceEntity.displayNameMap','Отчет');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSS_ACC_MNGMNT_ORG_DESC','8','SELFSRVS_ACCESS_MNGMNT_ORG','ResourceEntity.displayNameMap','Организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSS_ACC_MNGMNT_ORG_NEW_DESC','8','SELF_SUB_ORGS_NEW','ResourceEntity.displayNameMap','Новая организация');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSS_ACC_MG_ORG_SEARCH_DESC','8','SELF_SUB_ORGS_SEARCH','ResourceEntity.displayNameMap','Поиск организации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSYNCLOG_ADMIN_DESC','8','SYNCLOG','ResourceEntity.displayNameMap','Просмотр логов');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUACC_CONTROL_MENU_DISPLAY','8','ACC_CONTROL','ResourceEntity.displayNameMap','Контроль доступа');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate101','8','101','MetadataElementEntity.languageMap','Display Name');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate104','8','104','MetadataElementEntity.languageMap','Preferred Language');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate105','8','105','MetadataElementEntity.languageMap','VehicleLicense');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate106','8','106','MetadataElementEntity.languageMap','Given Name');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate107','8','107','MetadataElementEntity.languageMap','LabeledURI');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate108','8','108','MetadataElementEntity.languageMap','Initials');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate110','8','110','MetadataElementEntity.languageMap','BusinessCategory');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate131','8','131','MetadataElementEntity.languageMap','Display Name');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate134','8','134','MetadataElementEntity.languageMap','Preferred Language');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate135','8','135','MetadataElementEntity.languageMap','VehicleLicense');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate136','8','136','MetadataElementEntity.languageMap','Given Name');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate137','8','137','MetadataElementEntity.languageMap','LabeledURI');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate138','8','138','MetadataElementEntity.languageMap','Initials');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate140','8','140','MetadataElementEntity.languageMap','Display Name');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate150','8','150','MetadataElementEntity.languageMap','Display Name');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate160','8','160','MetadataElementEntity.languageMap','Display Name');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate260','8','260','MetadataElementEntity.languageMap','BusinessCategory');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate261','8','261','MetadataElementEntity.languageMap','StartDate');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate262','8','262','MetadataElementEntity.languageMap','EndDate');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate300','8','300','MetadataElementEntity.languageMap','name');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate301','8','301','MetadataElementEntity.languageMap','distinguishedName');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate302','8','302','MetadataElementEntity.languageMap','objectclass');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate303','8','303','MetadataElementEntity.languageMap','aliasedObjectName');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate304','8','304','MetadataElementEntity.languageMap','cn');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate305','8','305','MetadataElementEntity.languageMap','sn');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate306','8','306','MetadataElementEntity.languageMap','serialNumber');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate307','8','307','MetadataElementEntity.languageMap','c');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate308','8','308','MetadataElementEntity.languageMap','l');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate309','8','309','MetadataElementEntity.languageMap','st');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate310','8','310','MetadataElementEntity.languageMap','street');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate311','8','311','MetadataElementEntity.languageMap','o');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate312','8','312','MetadataElementEntity.languageMap','ou');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate313','8','313','MetadataElementEntity.languageMap','title');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate314','8','314','MetadataElementEntity.languageMap','description');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate315','8','315','MetadataElementEntity.languageMap','businessCategory');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate316','8','316','MetadataElementEntity.languageMap','postalAddress');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate317','8','317','MetadataElementEntity.languageMap','postalCode');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate318','8','318','MetadataElementEntity.languageMap','postOfficeBox');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate319','8','319','MetadataElementEntity.languageMap','physicalDeliveryOfficeName');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate320','8','320','MetadataElementEntity.languageMap','telephoneNumber');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate321','8','321','MetadataElementEntity.languageMap','telexNumber');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate322','8','322','MetadataElementEntity.languageMap','teletexTerminalIdentifier');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate323','8','323','MetadataElementEntity.languageMap','facsimileTelephoneNumber');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate324','8','324','MetadataElementEntity.languageMap','x121Address');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUElementMigrate325','8','325','MetadataElementEntity.languageMap','internationaliSDNNumber');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_EDIT_INFO_DESC','8','USER_EDIT_INFO','ResourceEntity.displayNameMap','Информация о пользователе');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_EDIT_MENU_DESC','8','USER_EDIT_MENU','ResourceEntity.displayNameMap','Редактирование пользователя - корневое меню');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_ENTITLEMENTS_DESC','8','USER_ENTITLEMENTS','ResourceEntity.displayNameMap','Разрешения пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_IDENTITY_DESC','8','USER_IDENTITY','ResourceEntity.displayNameMap','Пользовательские идентичности');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_MENUS_DESC','8','USER_MENUS','ResourceEntity.displayNameMap','Меню');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_MENU_DESC','8','USER','ResourceEntity.displayNameMap','Пользователь');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_ROOT_MENU_DESC','8','USER_ROOT_MENU','ResourceEntity.displayNameMap','Пользователи');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_SEARCH_DESC','8','USER_SEARCH','ResourceEntity.displayNameMap','Поиск пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSYNCUSER_DESC','8','SYNCUSER_MENU_ITEM','ResourceEntity.displayNameMap','Синхронизация');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSYNCUSER_NEW_DESC','8','SYNCUSER_NEW','ResourceEntity.displayNameMap','Создать синхронизацию');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMNGSYS_EDIT_DESC','8','MNGSYS_EDIT','ResourceEntity.displayNameMap','Редактировать управляемые системы');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPOLICY_ROOT_MENU_DESC','8','PASSWORD_POLICY_ROOT_MENU','ResourceEntity.displayNameMap','Политики паролей');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_PASSWORD_POLICY_DESC','8','NEW_PASSWORD_POLICY','ResourceEntity.displayNameMap','Создать новую политику паролей');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAUTH_POLICY_MENU_DESC','8','AUTHENTICATION_POLICY','ResourceEntity.displayNameMap','Политика аутентификации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAUTH_POLICY_ROOT_MENU_DESC','8','AUTHENTICATION_POLICY_ROOT_MENU','ResourceEntity.displayNameMap','Политики аутентификации');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUASSOC_POLICY_DESC','8','ASSOC_POLICY','ResourceEntity.displayNameMap','Ассоциирование политики');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPASSWORD_POLICY_EDIT_DESC','8','PASSWORD_POLICY_EDIT','ResourceEntity.displayNameMap','Ассоциирование политики - корневое меню');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUPLOAD_CUST_PSWD_POLICY_DESC','8','UPLOAD_CUST_PSWD_POLICY','ResourceEntity.displayNameMap','Загрузить политику паролей');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUATTRIBUTE_POLICY_DESC','8','ATTRIBUTE_POLICY','ResourceEntity.displayNameMap','Атрибутивная политика');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPOLICY_ATTR_ROOT_DESC','8','POLICY_ATTR_ROOT','ResourceEntity.displayNameMap','Атрибутивные политики');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_POLICY_ATTR_DESC','8','NEW_POLICY_ATTR','ResourceEntity.displayNameMap','Новая атрибутивная политика');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUEDIT_POL_ATTR_SRCH_BCK_DESC','8','EDIT_POLICY_ATTR_SRCH_BCK','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RURES_APROVER_ASSOC_DN','8','RES_APROVER_ASSOC','ResourceEntity.displayNameMap','Цепочки для утверждения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUGRP_APROVER_ASSOC_DN','8','GRP_APROVER_ASSOC','ResourceEntity.displayNameMap','Цепочки для утверждения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUROLE_APROVER_ASSOC_DN','8','ROLE_APROVER_ASSOC','ResourceEntity.displayNameMap','Цепочки для утверждения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSYNCLOG_DESC','8','SYNCLOG_MENU_ITEM','ResourceEntity.displayNameMap','Просмотрщик логов синхронизационных транзакций');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMNGSYSRULES_DESC','8','MNGSYSRULES','ResourceEntity.displayNameMap','Правила управляемых систем');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELF_SUB_REPORT_ROOT_DESC','8','SELF_SUB_REPORT_ROOT','ResourceEntity.displayNameMap','Подписаться на отчет');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSELFSER_USER_NEW_LOGIN_DESC','8','SELFSER_USER_NEW_LOGIN','ResourceEntity.displayNameMap','Создать новый идентификатор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSS_ACC_MNGMNT_ORG_EDIT_DESC','8','SELF_SUB_ORGS_EDIT','ResourceEntity.displayNameMap','Редактировать организацию');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUADMIN_MENU_DISPLAY','8','ADMIN','ResourceEntity.displayNameMap','Администрирование');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUAM_PROV_EDIT_SEARCH_DESC','8','AM_PROV_EDIT_SEARCH','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUORG_APROVER_ASSOC_DN','8','ORG_APROVER_ASSOC','ResourceEntity.displayNameMap','Цепочки для утверждения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUI_THEME_BACK_SRCH_DN','8','UI_THEME_BACK_SRCH','ResourceEntity.displayNameMap','Вернуться к поиску');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSS_RES_ENT_DN','8','SS_RES_ENT','ResourceEntity.displayNameMap','Разрешения');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMETA_TYPE_SEARCH_DESC','8','META_TYPE_SEARCH','ResourceEntity.displayNameMap','Поиск типов метаданных');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_AUTH_LVL_GRP_DN','8','NEW_AUTH_LVL_GRP','ResourceEntity.displayNameMap','Создать новую группировку');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUIMPERSIONATION_MENU_DESC','8','IMPERSIONATION_MENU','ResourceEntity.displayNameMap','Персонация');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUIDMAN_MENU_DISPLAY','8','IDMAN','ResourceEntity.displayNameMap','Пользователь-администратор');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUURI_PATTERN_EDTPROVSEARCHDESC','8','URI_PATTERN_EDT_PROV_SEARCH','ResourceEntity.displayNameMap','Поиск контент-провайдера');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_HISTORY_DESC','8','USER_HISTORY','ResourceEntity.displayNameMap','История пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUUSER_RESET_PASSWORD_DESC','8','USER_RESET_PASSWORD','ResourceEntity.displayNameMap','Сброс пароля');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPOLICY_MENU_DESC','8','PASSWORD_POLICY','ResourceEntity.displayNameMap','Политика паролей');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUNEW_AUTH_POLICY_DESC','8','NEW_AUTHENTICATION_POLICY','ResourceEntity.displayNameMap','Создать новую политику установления подлинности');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUPOLICY_ATTR_EDIT_ROOT_DESC','8','POLICY_ATTR_EDIT_ROOT','ResourceEntity.displayNameMap','Редактирование атрибутивной политики');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSS_USR_EDIT_RT_DESC','8','SELFSERV_USER_EDIT_ROOT','ResourceEntity.displayNameMap','Редактирование пользователя');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMNG_SYS_VIEWER_DESC','8','MNG_SYS_VIEWER','ResourceEntity.displayNameMap','Просмотр управляемых систем');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUDEFAULT_USER_TYPE','8','DEFAULT_USER','MetadataTypeEntity.displayNameMap','Пользователь по умолчанию');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUINTERNAL_USER_TYPE','8','INTERNAL_USER','MetadataTypeEntity.displayNameMap','Внутренний пользователь');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMETA_TYPE_EDIT_RETURN_DESC','8','META_TYPE_EDIT_RETURN','ResourceEntity.displayNameMap','Вернуться к типам метаданных');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RULanguageEntity2','8','2','LanguageEntity.displayNameMap','Немецкий');

INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('LanguageEntity8','1','8','LanguageEntity.displayNameMap','Russian');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESLanguageEntity8','4','8','LanguageEntity.displayNameMap','Ruso');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('DELanguageEntity8','2','8','LanguageEntity.displayNameMap','Russisch');




