use openiam;

DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('UI_THEME_ROOT', 'UI_THEME_ROOT_SRCH', 'NEW_UI_THEME', 'UI_THEME_EDIT', 'UI_THEME_BACK_SRCH', 'UI_THEME_EDIT_MODIFY', 'UI_THEMES');
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('UI_THEME_ROOT', 'UI_THEME_ROOT_SRCH', 'NEW_UI_THEME', 'UI_THEME_EDIT', 'UI_THEME_BACK_SRCH', 'UI_THEME_EDIT_MODIFY', 'UI_THEMES');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('UI_THEME_ROOT', 'UI_THEME_ROOT_SRCH', 'NEW_UI_THEME', 'UI_THEME_EDIT', 'UI_THEME_BACK_SRCH', 'UI_THEME_EDIT_MODIFY', 'UI_THEMES');
DELETE FROM RES WHERE RESOURCE_ID IN('UI_THEME_ROOT', 'UI_THEME_ROOT_SRCH', 'NEW_UI_THEME', 'UI_THEME_EDIT', 'UI_THEME_BACK_SRCH', 'UI_THEME_EDIT_MODIFY', 'UI_THEMES');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('UI_THEME_ROOT', 'MENU_ITEM', 'UI_THEME_ROOT', 'UI Theme Root');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEME_ROOT_PB', 'UI_THEME_ROOT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEME_ROOT_DN', 'UI_THEME_ROOT', 'MENU_DISPLAY_NAME', 'UI Theme Root');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES ('UI_THEME_ROOT_SRCH', 'MENU_ITEM', 'UI_THEME_ROOT_SRCH', 'Search UI Themes', '/webconsole/uiThemes.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEME_ROOT_SRCH_DN', 'UI_THEME_ROOT_SRCH', 'MENU_DISPLAY_NAME', 'Search UI Themes');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEME_ROOT_SRCH_PB', 'UI_THEME_ROOT_SRCH', 'MENU_IS_PUBLIC', 'true');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES ('NEW_UI_THEME', 'MENU_ITEM', 'NEW_UI_THEME', 'New UI Theme', '/webconsole/newUITheme.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('NEW_UI_THEME_DN', 'NEW_UI_THEME', 'MENU_DISPLAY_NAME', 'New UI Theme');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('NEW_UI_THEME_PB', 'NEW_UI_THEME', 'MENU_IS_PUBLIC', 'true');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('UI_THEME_ROOT', 'UI_THEME_ROOT_SRCH');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('UI_THEME_ROOT', 'NEW_UI_THEME');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('UI_THEME_EDIT', 'MENU_ITEM', 'UI_THEME_EDIT', 'UI Theme Edit');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEME_EDIT_PB', 'UI_THEME_EDIT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEME_EDIT_DN', 'UI_THEME_EDIT', 'MENU_DISPLAY_NAME', 'UI Theme Edit');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES ('UI_THEME_BACK_SRCH', 'MENU_ITEM', 'UI_THEME_BACK_SRCH', 'Back to Search', '/webconsole/uiThemes.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEME_BACK_SRCH_DN', 'UI_THEME_BACK_SRCH', 'MENU_DISPLAY_NAME', 'Back to Search');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEME_BACK_SRCH_PB', 'UI_THEME_BACK_SRCH', 'MENU_IS_PUBLIC', 'true');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES ('UI_THEME_EDIT_MODIFY', 'MENU_ITEM', 'UI_THEME_EDIT_MODIFY', 'Edit UI Theme', '/webconsole/editUITheme.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEME_EDIT_MODIFY_DN', 'UI_THEME_EDIT_MODIFY', 'MENU_DISPLAY_NAME', 'Edit UI Theme');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEME_EDIT_MODIFY_PB', 'UI_THEME_EDIT_MODIFY', 'MENU_IS_PUBLIC', 'true');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('UI_THEME_EDIT', 'UI_THEME_BACK_SRCH');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('UI_THEME_EDIT', 'UI_THEME_EDIT_MODIFY');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES ('UI_THEMES', 'MENU_ITEM', 'UI_THEMES', 'UI Themes', '/webconsole/uiThemes.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEMES_DN', 'UI_THEMES', 'MENU_DISPLAY_NAME', 'UI Themes');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('UI_THEMES_PB', 'UI_THEMES', 'MENU_IS_PUBLIC', 'true');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('ADMIN', 'UI_THEMES');