use openiam;

UPDATE ATTRIBUTE_MAP SET ATTRIBUTE_NAME = 'objectClass'
 WHERE ATTRIBUTE_NAME = 'objectclass'
   AND MANAGED_SYS_ID IN (SELECT MANAGED_SYS_ID FROM MANAGED_SYS WHERE CONNECTOR_ID = 51 OR CONNECTOR_ID IN 
       (SELECT CONNECTOR_ID FROM PROVISION_CONNECTOR WHERE SERVICE_PORT = 'LDAPConnectorServicePort')
   );