use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('SS_GRP_ENT', 'SS_ROLE_ENT', 'SS_RES_ENT');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('SS_GRP_ENT', 'SS_ROLE_ENT', 'SS_RES_ENT');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('SS_GRP_ENT', 'SS_ROLE_ENT', 'SS_RES_ENT');
DELETE FROM RES WHERE RESOURCE_ID IN('SS_GRP_ENT', 'SS_ROLE_ENT', 'SS_RES_ENT');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES ('SS_GRP_ENT', 'MENU_ITEM', 'SS_GRP_ENT', 'New UI Theme', '/selfservice/groupEntitlements.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_GRP_ENT_DN', 'SS_GRP_ENT', 'MENU_DISPLAY_NAME', 'Entitlements');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_GRP_ENT_PB', 'SS_GRP_ENT', 'MENU_IS_PUBLIC', 'true');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('SELFSRV_GRP_EDIT_ROOT', 'SS_GRP_ENT');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES ('SS_ROLE_ENT', 'MENU_ITEM', 'SS_ROLE_ENT', 'New UI Theme', '/selfservice/roleEntitlements.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ROLE_ENT_DN', 'SS_ROLE_ENT', 'MENU_DISPLAY_NAME', 'Entitlements');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ROLE_ENT_PB', 'SS_ROLE_ENT', 'MENU_IS_PUBLIC', 'true');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('SELFSRV_ROLE_EDIT_ROOT', 'SS_ROLE_ENT');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES ('SS_RES_ENT', 'MENU_ITEM', 'SS_RES_ENT', 'New UI Theme', '/selfservice/resourceEntitlements.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_RES_ENT_DN', 'SS_RES_ENT', 'MENU_DISPLAY_NAME', 'Entitlements');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_RES_ENT_PB', 'SS_RES_ENT', 'MENU_IS_PUBLIC', 'true');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('SELFSRV_RES_EDIT_ROOT', 'SS_RES_ENT');