use openiam;

DELETE FROM ATTRIBUTE_MAP WHERE ATTRIBUTE_MAP_ID = '610';
DELETE FROM ATTRIBUTE_MAP WHERE ATTRIBUTE_MAP_ID = '611';
DELETE FROM RECON_RES_ATTR_MAP WHERE RECON_RES_ATTR_MAP_ID = '63';
DELETE FROM RECON_RES_ATTR_MAP WHERE RECON_RES_ATTR_MAP_ID = '64';

DELETE FROM POLICY WHERE POLICY_ID = '4659';


INSERT INTO POLICY (POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,RULE_SRC_URL,RULE_TEXT) VALUES ('4659','104','googleGroups','GoogleApps groups Policy',1,CURRENT_TIMESTAMP(),'3000','provision/googleGroups.groovy','');

INSERT INTO RECON_RES_ATTR_MAP (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID) VALUES (64,4659);
INSERT INTO ATTRIBUTE_MAP (ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID, STATUS, DATA_TYPE) VALUES ('611','103','103','USER','groups','64','ACTIVE','STRING');


INSERT INTO RECON_RES_ATTR_MAP (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID) VALUES (63,4540);
INSERT INTO ATTRIBUTE_MAP (ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID, STATUS, DATA_TYPE) VALUES ('610','103','103','USER','userEmail','63','ACTIVE','STRING');

UPDATE ATTRIBUTE_MAP SET ATTRIBUTE_NAME= 'login', ATTRIBUTE_POLICY_ID='26' WHERE ATTRIBUTE_MAP_ID = '400';
UPDATE ATTRIBUTE_MAP SET DATA_TYPE= 'STRING' WHERE MANAGED_SYS_ID = '103';
