--***************************************RELEASE.3.3***************************************/
--***************************************fix for ATTRIBUTE_MAP***************************************/
UPDATE ATTRIBUTE_MAP SET DATA_TYPE='STRING' WHERE DATA_TYPE IS NULL;
UPDATE ATTRIBUTE_MAP SET DATA_TYPE='STRING' WHERE DATA_TYPE='String';

--***************************************dml/1.localization_for_menu.sql***************************************/
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='CHANGE_PASS_MANAGED_SYS';

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC','1','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Change Password Extended');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC10','10','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','更改密碼擴展');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC2','2','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Passwort ändern Erweiterte');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC4','4','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Cambiar contraseña Extended');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC8','8','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Расширенная смена пароля');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC9','9','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','パスワードの変更は、拡張');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC11','11','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Alterar senha Extensão');

--***************************************dml/2.managed_sys_drop_ATTRIBUTE_NAMES_LOOKUP.sql ***************************************/
alter table MANAGED_SYS drop column ATTRIBUTE_NAMES_LOOKUP;

--***************************************dml/3.alter_sync_config_connection_url_length.sql***************************************/
ALTER TABLE SYNCH_CONFIG ALTER COLUMN CONNECTION_URL TYPE VARCHAR(500);
ALTER TABLE SYNCH_CONFIG ALTER COLUMN CONNECTION_URL SET DEFAULT NULL;

--***************************************ddl/1.Location_ddl.sql***************************************/
DELETE FROM LOCATION;
ALTER TABLE LOCATION ALTER COLUMN ACTIVE TYPE CHAR(1);
ALTER TABLE LOCATION ALTER COLUMN ACTIVE SET DEFAULT 'Y';
ALTER TABLE LOCATION ALTER COLUMN NAME TYPE VARCHAR(100);
ALTER TABLE LOCATION ALTER COLUMN COUNTRY TYPE VARCHAR(100);
ALTER TABLE LOCATION ALTER COLUMN CITY TYPE VARCHAR(100);
ALTER TABLE LOCATION ALTER COLUMN STATE TYPE VARCHAR(100);
ALTER TABLE LOCATION ALTER COLUMN POSTAL_CD TYPE VARCHAR(100);
ALTER TABLE LOCATION ALTER COLUMN BLDG_NUM TYPE VARCHAR(100);
ALTER TABLE ADDRESS ADD COLUMN COPY_FROM_LOCATION_ID VARCHAR(32);

commit;
--***************************************dml/4.Location.sql***************************************/
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'ORG_LOCATION';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'ORG_LOCATION';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'ORG_LOCATION_PUB';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'ORG_LOCATION_DESC';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID = 'ORG_LOCATION';
DELETE FROM RES WHERE RESOURCE_ID = 'ORG_LOCATION';
DELETE FROM LOCATION;

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL, DISPLAY_ORDER) VALUES('ORG_LOCATION', 'MENU_ITEM', 'ORG_LOCATION', 'Organization Location','/webconsole/organizationLocation.html',3);
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORG_LOCATION_PUB', 'ORG_LOCATION', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORG_LOCATION_DESC', 'ORG_LOCATION', 'MENU_DISPLAY_NAME', 'Organization Location');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ORGANIZATION_EDIT_ID', 'ORG_LOCATION');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORG_LOCATION', '9');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESORG_LOCATION','1','ORG_LOCATION','ResourceEntity.displayNameMap','Organization Location');

commit;
--***************************************ddl/2.addr_location_extend_addr.sql***************************************/
ALTER TABLE LOCATION ALTER COLUMN ADDRESS1 TYPE VARCHAR(400);
ALTER TABLE LOCATION ALTER COLUMN ADDRESS2 TYPE VARCHAR(400);
ALTER TABLE LOCATION ALTER COLUMN ADDRESS3 TYPE VARCHAR(400);

ALTER TABLE ADDRESS ALTER COLUMN ADDRESS1 TYPE VARCHAR(400);
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS2 TYPE VARCHAR(400);
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS3 TYPE VARCHAR(400);
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS4 TYPE VARCHAR(400);
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS5 TYPE VARCHAR(400);
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS6 TYPE VARCHAR(400);
ALTER TABLE ADDRESS ALTER COLUMN ADDRESS7 TYPE VARCHAR(400);

commit;
--***************************************ddl/3.alter_group_table.sql***************************************/
ALTER TABLE GRP ADD COLUMN GRP_CLASSIFICATION VARCHAR(32) NULL;
ALTER TABLE GRP ADD COLUMN AD_GRP_TYPE VARCHAR(32) NULL;
ALTER TABLE GRP ADD COLUMN AD_GRP_SCOPE VARCHAR(32) NULL;
ALTER TABLE GRP ADD COLUMN GRP_RISK VARCHAR(32) NULL;
ALTER TABLE GRP ADD COLUMN MAX_USER_NUMBER INT NULL;
ALTER TABLE GRP ADD COLUMN MEMBERSHIP_DURATION_SECONDS NUMERIC(20) NULL;

ALTER TABLE GRP	ADD CONSTRAINT GRP_CLASS_FK FOREIGN KEY (GRP_CLASSIFICATION) REFERENCES METADATA_TYPE (TYPE_ID);
ALTER TABLE GRP	ADD CONSTRAINT GRP_AD_TYPE_FK FOREIGN KEY (AD_GRP_TYPE) REFERENCES METADATA_TYPE (TYPE_ID);
ALTER TABLE GRP	ADD CONSTRAINT GRP_AD_SCOPE_FK FOREIGN KEY (AD_GRP_SCOPE) REFERENCES METADATA_TYPE (TYPE_ID);
ALTER TABLE GRP	ADD CONSTRAINT GRP_RISK_FK FOREIGN KEY (GRP_RISK) REFERENCES METADATA_TYPE (TYPE_ID);

CREATE TABLE GROUP_ORGANIZATION (
  GRP_ID VARCHAR(32) NULL,
  COMPANY_ID VARCHAR(32) NULL,
  CONSTRAINT FK_GRP FOREIGN KEY (GRP_ID)REFERENCES GRP (GRP_ID),
  CONSTRAINT FK_ORG FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID));
  
ALTER TABLE GRP DROP CONSTRAINT GRP_COMPANY_FK;
ALTER TABLE GRP DROP COLUMN COMPANY_ID;

commit;
--***************************************dml/5.add_group_types.sql***************************************/
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('m', 'Admin Group', 'Y', 'Y', 'GROUP_CLASSIFICATION', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('a', 'Application Group', 'Y', 'Y', 'GROUP_CLASSIFICATION', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('g', 'Other Group', 'Y', 'Y', 'GROUP_CLASSIFICATION', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('SECURITY_GROUP', 'Security Group', 'Y', 'Y', 'AD_GROUP_TYPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('DISTRIBUTION_GROUP', 'Distribution Group', 'Y', 'Y', 'AD_GROUP_TYPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('Universal', 'Universal', 'Y', 'Y', 'AD_GROUP_SCOPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('Global', 'Global', 'Y', 'Y', 'AD_GROUP_SCOPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('Domain_Local', 'Domain Local', 'Y', 'Y', 'AD_GROUP_SCOPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('HIGH_RISK', 'High Risk', 'N', 'N', 'RISK', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('LOW_RISK', 'Low Risk', 'N', 'N', 'RISK', 'N', 'N');

INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('AD_GROUP', 'AD GROUP', 'Y', 'N', 'GROUP_TYPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('GENERAL_GROUP', 'General Group', 'Y', 'N', 'GROUP_TYPE', 'N', 'N');


insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENApplicationGroup','1','a','MetadataTypeEntity.displayNameMap','Application Group');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENOtherGroup','1','g','MetadataTypeEntity.displayNameMap','Other Group');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENAdminGroup','1','m','MetadataTypeEntity.displayNameMap','Admin Group');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENDISTRIBUTION_GROUP','1','DISTRIBUTION_GROUP','MetadataTypeEntity.displayNameMap','Distribution Group');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENSECURITY_GROUP','1','SECURITY_GROUP','MetadataTypeEntity.displayNameMap','Security Group');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENDomain_Local','1','Domain_Local','MetadataTypeEntity.displayNameMap','Domain Local');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENGlobal','1','Global','MetadataTypeEntity.displayNameMap','Global');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENUniversal','1','Universal','MetadataTypeEntity.displayNameMap','Universal');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENHIGH_RISK','1','HIGH_RISK','MetadataTypeEntity.displayNameMap','High');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENLOW_RISK','1','LOW_RISK','MetadataTypeEntity.displayNameMap','Low');

insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENAD_GROUP','1','AD_GROUP','MetadataTypeEntity.displayNameMap','AD Group Type');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENGENERAL_GROUP','1','GENERAL_GROUP','MetadataTypeEntity.displayNameMap','General Group Type');

commit;
--***************************************dml/6.challenge_questions_menus.sql***************************************/
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM RES WHERE RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('WEBCONSOLE_CHALLENGE_QUEST', 'MENU_ITEM', 'Challenge Response', 'WEBCONSOLE_CHALLENGE_QUEST', 'WEBCONSOLE_CHALLENGE_QUEST', '/webconsole/challengeQuestRes.html', 20, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('WEBCONSOLE_CHALLENGE_QUEST_PUB', 'WEBCONSOLE_CHALLENGE_QUEST', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('WEBCONSOLE_CHALLENGE_QUEST_DESC', 'WEBCONSOLE_CHALLENGE_QUEST', 'MENU_DISPLAY_NAME', 'Challenge Response');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('WEBCONSOLE_CHALLENGE_QUEST_VIS', 'WEBCONSOLE_CHALLENGE_QUEST', 'IS_VISIBLE', 'false');


INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('USER_EDIT_MENU', 'WEBCONSOLE_CHALLENGE_QUEST');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_WEBCONSOLE_CHALLENGE_QUEST','1','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES  ('DE_WEBCONSOLE_CHALLENGE_QUEST','2','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES  ('ES_WEBCONSOLE_CHALLENGE_QUEST','4','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES  ('RU_WEBCONSOLE_CHALLENGE_QUEST','8','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES  ('JP_WEBCONSOLE_CHALLENGE_QUEST','9','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES  ('ZH_WEBCONSOLE_CHALLENGE_QUEST','10','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES  ('PT_WEBCONSOLE_CHALLENGE_QUEST','11','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response');

commit;
--***************************************dml/7.bulk_operation_for_group_menu.sql***************************************/
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SS_GRP_BULK_OP';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'SS_GRP_BULK_OP';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'SS_GRP_BULK_OP_PUB';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'SS_GRP_BULK_OP_DESC';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID = 'SS_GRP_BULK_OP';
DELETE FROM RES WHERE RESOURCE_ID = 'SS_GRP_BULK_OP';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL, DISPLAY_ORDER) VALUES('SS_GRP_BULK_OP', 'MENU_ITEM', 'GRP_BULK_OP', 'Bulk Operations','/selfservice/groupsBulkOperations.html',4);
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_GRP_BULK_OP_PUB', 'SS_GRP_BULK_OP', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_GRP_BULK_OP_DESC', 'SS_GRP_BULK_OP', 'MENU_DISPLAY_NAME', 'Bulk Operations');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSRV_GRP_SRCH_ROOT', 'SS_GRP_BULK_OP');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('SS_GRP_BULK_OP', '9');

INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ENSS_GRP_BULK_OP','1','SS_GRP_BULK_OP','ResourceEntity.displayNameMap','Bulk Operations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUSS_GRP_BULK_OP','8','SS_GRP_BULK_OP','ResourceEntity.displayNameMap','Пакетная обработка');

commit;
--***************************************dml/8.add_btns_on_entitlements.sql***************************************/

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('ENT_USR_ROLE_BTN_ROOT', 'ROLES_ADD_BTN', 'ROLES_EDT_BTN', 'ROLES_DEL_BTN', 'ROLES_INFO_BTN', 'ROLES_PROV_BTN', 'ROLES_DEPROV_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('ENT_USR_ROLE_BTN_ROOT', 'ROLES_ADD_BTN', 'ROLES_EDT_BTN', 'ROLES_DEL_BTN', 'ROLES_INFO_BTN', 'ROLES_PROV_BTN', 'ROLES_DEPROV_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('ENT_USR_ROLE_BTN_ROOT', 'ROLES_ADD_BTN', 'ROLES_EDT_BTN', 'ROLES_DEL_BTN', 'ROLES_INFO_BTN', 'ROLES_PROV_BTN', 'ROLES_DEPROV_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('ENT_USR_ROLE_BTN_ROOT', 'ROLES_ADD_BTN', 'ROLES_EDT_BTN', 'ROLES_DEL_BTN', 'ROLES_INFO_BTN', 'ROLES_PROV_BTN', 'ROLES_DEPROV_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('ENT_USR_ROLE_BTN_ROOT', 'ROLES_ADD_BTN', 'ROLES_EDT_BTN', 'ROLES_DEL_BTN', 'ROLES_INFO_BTN', 'ROLES_PROV_BTN', 'ROLES_DEPROV_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('ENT_USR_ROLE_BTN_ROOT', 'ROLES_ADD_BTN', 'ROLES_EDT_BTN', 'ROLES_DEL_BTN', 'ROLES_INFO_BTN', 'ROLES_PROV_BTN', 'ROLES_DEPROV_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('ENT_USR_ROLE_BTN_ROOT', 'ROLES_ADD_BTN', 'ROLES_EDT_BTN', 'ROLES_DEL_BTN', 'ROLES_INFO_BTN', 'ROLES_PROV_BTN', 'ROLES_DEPROV_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('ENT_USR_ROLE_BTN_ROOT', 'ROLES_ADD_BTN', 'ROLES_EDT_BTN', 'ROLES_DEL_BTN', 'ROLES_INFO_BTN', 'ROLES_PROV_BTN', 'ROLES_DEPROV_BTN');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ENT_USR_ROLE_BTN_ROOT', 'MENU_ITEM', 'Root menu for UserRole Membership', 'ENT_USR_ROLE_BTN_ROOT', 'ENT_USR_ROLE_BTN_ROOT', null, 20, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_ROLE_BTN_ROOT_PUB', 'ENT_USR_ROLE_BTN_ROOT', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_ROLE_BTN_ROOT_DESC', 'ENT_USR_ROLE_BTN_ROOT', 'MENU_DISPLAY_NAME', 'Root menu for UserRole Membership');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ROLES_ADD_BTN', 'MENU_ITEM', 'Add User To Role', 'ROLES_ADD_BTN', 'ROLES_ADD_BTN', '/webconsole/addUserToRole.html', 21, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_ADD_BTN_PUB', 'ROLES_ADD_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_ADD_BTN_DESC', 'ROLES_ADD_BTN', 'MENU_DISPLAY_NAME', 'Add User To Role');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ROLES_EDT_BTN', 'MENU_ITEM', 'Edit Role', 'ROLES_EDT_BTN', 'ROLES_EDT_BTN', null, 22, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_EDT_BTN_PUB', 'ROLES_EDT_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_EDT_BTN_DESC', 'ROLES_EDT_BTN', 'MENU_DISPLAY_NAME', 'Edit Role');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ROLES_DEL_BTN', 'MENU_ITEM', 'Delete User from Role', 'ROLES_DEL_BTN', 'ROLES_DEL_BTN', '/webconsole/removeUserFromRole.html', 23, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_DEL_BTN_PUB', 'ROLES_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_DEL_BTN_DESC', 'ROLES_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete User from Role');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ROLES_INFO_BTN', 'MENU_ITEM', 'Role Info', 'ROLES_INFO_BTN', 'ROLES_INFO_BTN', null, 24, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_INFO_BTN_PUB', 'ROLES_INFO_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_INFO_BTN_DESC', 'ROLES_INFO_BTN', 'MENU_DISPLAY_NAME', 'Role Info');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ROLES_PROV_BTN', 'MENU_ITEM', 'Provision User by Role', 'ROLES_PROV_BTN', 'ROLES_PROV_BTN', '/webconsole/provisionUserByRole.html', 25, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_PROV_BTN_PUB', 'ROLES_PROV_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_PROV_BTN_DESC', 'ROLES_PROV_BTN', 'MENU_DISPLAY_NAME', 'Provision User by Role');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ROLES_DEPROV_BTN', 'MENU_ITEM', 'DeProvision User by Role', 'ROLES_DEPROV_BTN', 'ROLES_DEPROV_BTN', '/webconsole/deprovisionUserByRole.html', 26, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_DEPROV_BTN_PUB', 'ROLES_DEPROV_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ROLES_DEPROV_BTN_DESC', 'ROLES_DEPROV_BTN', 'MENU_DISPLAY_NAME', 'DeProvision User by Role');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ROLE_BTN_ROOT', 'ROLES_ADD_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ROLE_BTN_ROOT', 'ROLES_EDT_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ROLE_BTN_ROOT', 'ROLES_DEL_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ROLE_BTN_ROOT', 'ROLES_INFO_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ROLE_BTN_ROOT', 'ROLES_PROV_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ROLE_BTN_ROOT', 'ROLES_DEPROV_BTN');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ENT_USR_ROLE_BTN_ROOT', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ROLES_ADD_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ROLES_EDT_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ROLES_DEL_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ROLES_INFO_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ROLES_PROV_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ROLES_DEPROV_BTN', '9');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ENT_USR_ROLE_BTN_ROOT','1','ENT_USR_ROLE_BTN_ROOT','ResourceEntity.displayNameMap','User Role Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ENT_USR_ROLE_BTN_ROOT','2','ENT_USR_ROLE_BTN_ROOT','ResourceEntity.displayNameMap','User Role Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ENT_USR_ROLE_BTN_ROOT','4','ENT_USR_ROLE_BTN_ROOT','ResourceEntity.displayNameMap','User Role Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ENT_USR_ROLE_BTN_ROOT','8','ENT_USR_ROLE_BTN_ROOT','ResourceEntity.displayNameMap','User Role Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ENT_USR_ROLE_BTN_ROOT','9','ENT_USR_ROLE_BTN_ROOT','ResourceEntity.displayNameMap','User Role Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ENT_USR_ROLE_BTN_ROOT','10','ENT_USR_ROLE_BTN_ROOT','ResourceEntity.displayNameMap','User Role Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ENT_USR_ROLE_BTN_ROOT','11','ENT_USR_ROLE_BTN_ROOT','ResourceEntity.displayNameMap','User Role Membership Buttons');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ROLES_ADD_BTN','1','ROLES_ADD_BTN','ResourceEntity.displayNameMap','Add Role to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ROLES_ADD_BTN','2','ROLES_ADD_BTN','ResourceEntity.displayNameMap','Add Role to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ROLES_ADD_BTN','4','ROLES_ADD_BTN','ResourceEntity.displayNameMap','Add Role to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ROLES_ADD_BTN','8','ROLES_ADD_BTN','ResourceEntity.displayNameMap','Add Role to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ROLES_ADD_BTN','9','ROLES_ADD_BTN','ResourceEntity.displayNameMap','Add Role to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ROLES_ADD_BTN','10','ROLES_ADD_BTN','ResourceEntity.displayNameMap','Add Role to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ROLES_ADD_BTN','11','ROLES_ADD_BTN','ResourceEntity.displayNameMap','Add Role to User');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ROLES_EDT_BTN','1','ROLES_EDT_BTN','ResourceEntity.displayNameMap','Edit Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ROLES_EDT_BTN','2','ROLES_EDT_BTN','ResourceEntity.displayNameMap','Edit Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ROLES_EDT_BTN','4','ROLES_EDT_BTN','ResourceEntity.displayNameMap','Edit Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ROLES_EDT_BTN','8','ROLES_EDT_BTN','ResourceEntity.displayNameMap','Edit Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ROLES_EDT_BTN','9','ROLES_EDT_BTN','ResourceEntity.displayNameMap','Edit Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ROLES_EDT_BTN','10','ROLES_EDT_BTN','ResourceEntity.displayNameMap','Edit Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ROLES_EDT_BTN','11','ROLES_EDT_BTN','ResourceEntity.displayNameMap','Edit Role');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ROLES_DEL_BTN','1','ROLES_DEL_BTN','ResourceEntity.displayNameMap','Remove Role from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ROLES_DEL_BTN','2','ROLES_DEL_BTN','ResourceEntity.displayNameMap','Remove Role from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ROLES_DEL_BTN','4','ROLES_DEL_BTN','ResourceEntity.displayNameMap','Remove Role from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ROLES_DEL_BTN','8','ROLES_DEL_BTN','ResourceEntity.displayNameMap','Remove Role from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ROLES_DEL_BTN','9','ROLES_DEL_BTN','ResourceEntity.displayNameMap','Remove Role from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ROLES_DEL_BTN','10','ROLES_DEL_BTN','ResourceEntity.displayNameMap','Remove Role from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ROLES_DEL_BTN','11','ROLES_DEL_BTN','ResourceEntity.displayNameMap','Remove Role from User');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ROLES_INFO_BTN','1','ROLES_INFO_BTN','ResourceEntity.displayNameMap','Role Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ROLES_INFO_BTN','2','ROLES_INFO_BTN','ResourceEntity.displayNameMap','Role Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ROLES_INFO_BTN','4','ROLES_INFO_BTN','ResourceEntity.displayNameMap','Role Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ROLES_INFO_BTN','8','ROLES_INFO_BTN','ResourceEntity.displayNameMap','Role Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ROLES_INFO_BTN','9','ROLES_INFO_BTN','ResourceEntity.displayNameMap','Role Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ROLES_INFO_BTN','10','ROLES_INFO_BTN','ResourceEntity.displayNameMap','Role Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ROLES_INFO_BTN','11','ROLES_INFO_BTN','ResourceEntity.displayNameMap','Role Info');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ROLES_PROV_BTN','1','ROLES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ROLES_PROV_BTN','2','ROLES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ROLES_PROV_BTN','4','ROLES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ROLES_PROV_BTN','8','ROLES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ROLES_PROV_BTN','9','ROLES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ROLES_PROV_BTN','10','ROLES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ROLES_PROV_BTN','11','ROLES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Role');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ROLES_DEPROV_BTN','1','ROLES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ROLES_DEPROV_BTN','2','ROLES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ROLES_DEPROV_BTN','4','ROLES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ROLES_DEPROV_BTN','8','ROLES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ROLES_DEPROV_BTN','9','ROLES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ROLES_DEPROV_BTN','10','ROLES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ROLES_DEPROV_BTN','11','ROLES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Role');

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('ENT_USR_GRP_BTN_ROOT', 'GROUPS_ADD_BTN', 'GROUPS_EDT_BTN', 'GROUPS_DEL_BTN', 'GROUPS_INFO_BTN', 'GROUPS_PROV_BTN', 'GROUPS_DEPROV_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('ENT_USR_GRP_BTN_ROOT', 'GROUPS_ADD_BTN', 'GROUPS_EDT_BTN', 'GROUPS_DEL_BTN', 'GROUPS_INFO_BTN', 'GROUPS_PROV_BTN', 'GROUPS_DEPROV_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('ENT_USR_GRP_BTN_ROOT', 'GROUPS_ADD_BTN', 'GROUPS_EDT_BTN', 'GROUPS_DEL_BTN', 'GROUPS_INFO_BTN', 'GROUPS_PROV_BTN', 'GROUPS_DEPROV_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('ENT_USR_GRP_BTN_ROOT', 'GROUPS_ADD_BTN', 'GROUPS_EDT_BTN', 'GROUPS_DEL_BTN', 'GROUPS_INFO_BTN', 'GROUPS_PROV_BTN', 'GROUPS_DEPROV_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('ENT_USR_GRP_BTN_ROOT', 'GROUPS_ADD_BTN', 'GROUPS_EDT_BTN', 'GROUPS_DEL_BTN', 'GROUPS_INFO_BTN', 'GROUPS_PROV_BTN', 'GROUPS_DEPROV_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('ENT_USR_GRP_BTN_ROOT', 'GROUPS_ADD_BTN', 'GROUPS_EDT_BTN', 'GROUPS_DEL_BTN', 'GROUPS_INFO_BTN', 'GROUPS_PROV_BTN', 'GROUPS_DEPROV_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('ENT_USR_GRP_BTN_ROOT', 'GROUPS_ADD_BTN', 'GROUPS_EDT_BTN', 'GROUPS_DEL_BTN', 'GROUPS_INFO_BTN', 'GROUPS_PROV_BTN', 'GROUPS_DEPROV_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('ENT_USR_GRP_BTN_ROOT', 'GROUPS_ADD_BTN', 'GROUPS_EDT_BTN', 'GROUPS_DEL_BTN', 'GROUPS_INFO_BTN', 'GROUPS_PROV_BTN', 'GROUPS_DEPROV_BTN');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ENT_USR_GRP_BTN_ROOT', 'MENU_ITEM', 'Root menu for UserGroup Membership', 'ENT_USR_GRP_BTN_ROOT', 'ENT_USR_GRP_BTN_ROOT', null, 30, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_GRP_BTN_ROOT_PUB', 'ENT_USR_GRP_BTN_ROOT', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_GRP_BTN_ROOT_DESC', 'ENT_USR_GRP_BTN_ROOT', 'MENU_DISPLAY_NAME', 'Root menu for UserGroup Membership');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('GROUPS_ADD_BTN', 'MENU_ITEM', 'Add User To Group', 'GROUPS_ADD_BTN', 'GROUPS_ADD_BTN', '/webconsole/addUserToGroup.html', 31, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_ADD_BTN_PUB', 'GROUPS_ADD_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_ADD_BTN_DESC', 'GROUPS_ADD_BTN', 'MENU_DISPLAY_NAME', 'Add User To Group');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('GROUPS_EDT_BTN', 'MENU_ITEM', 'Edit Group', 'GROUPS_EDT_BTN', 'GROUPS_EDT_BTN', null, 32, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_EDT_BTN_PUB', 'GROUPS_EDT_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_EDT_BTN_DESC', 'GROUPS_EDT_BTN', 'MENU_DISPLAY_NAME', 'Edit Group');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('GROUPS_DEL_BTN', 'MENU_ITEM', 'Delete User from Group', 'GROUPS_DEL_BTN', 'GROUPS_DEL_BTN', '/webconsole/removeUserFromGroup.html', 33, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_DEL_BTN_PUB', 'GROUPS_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_DEL_BTN_DESC', 'GROUPS_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete User from Group');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('GROUPS_INFO_BTN', 'MENU_ITEM', 'Group Info', 'GROUPS_INFO_BTN', 'GROUPS_INFO_BTN', null, 34, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_INFO_BTN_PUB', 'GROUPS_INFO_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_INFO_BTN_DESC', 'GROUPS_INFO_BTN', 'MENU_DISPLAY_NAME', 'Group Info');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('GROUPS_PROV_BTN', 'MENU_ITEM', 'Provision User by Group', 'GROUPS_PROV_BTN', 'GROUPS_PROV_BTN', '/webconsole/provisionUserByGroup.html', 35, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_PROV_BTN_PUB', 'GROUPS_PROV_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_PROV_BTN_DESC', 'GROUPS_PROV_BTN', 'MENU_DISPLAY_NAME', 'Provision User by Group');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('GROUPS_DEPROV_BTN', 'MENU_ITEM', 'DeProvision User by Group', 'GROUPS_DEPROV_BTN', 'GROUPS_DEPROV_BTN', '/webconsole/deprovisionUserByGroup.html', 36, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_DEPROV_BTN_PUB', 'GROUPS_DEPROV_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('GROUPS_DEPROV_BTN_DESC', 'GROUPS_DEPROV_BTN', 'MENU_DISPLAY_NAME', 'DeProvision User by Group');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_GRP_BTN_ROOT', 'GROUPS_ADD_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_GRP_BTN_ROOT', 'GROUPS_EDT_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_GRP_BTN_ROOT', 'GROUPS_DEL_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_GRP_BTN_ROOT', 'GROUPS_INFO_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_GRP_BTN_ROOT', 'GROUPS_PROV_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_GRP_BTN_ROOT', 'GROUPS_DEPROV_BTN');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ENT_USR_GRP_BTN_ROOT', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('GROUPS_ADD_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('GROUPS_EDT_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('GROUPS_DEL_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('GROUPS_INFO_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('GROUPS_PROV_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('GROUPS_DEPROV_BTN', '9');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ENT_USR_GRP_BTN_ROOT','1','ENT_USR_GRP_BTN_ROOT','ResourceEntity.displayNameMap','User Group Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ENT_USR_GRP_BTN_ROOT','2','ENT_USR_GRP_BTN_ROOT','ResourceEntity.displayNameMap','User Group Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ENT_USR_GRP_BTN_ROOT','4','ENT_USR_GRP_BTN_ROOT','ResourceEntity.displayNameMap','User Group Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ENT_USR_GRP_BTN_ROOT','8','ENT_USR_GRP_BTN_ROOT','ResourceEntity.displayNameMap','User Group Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ENT_USR_GRP_BTN_ROOT','9','ENT_USR_GRP_BTN_ROOT','ResourceEntity.displayNameMap','User Group Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ENT_USR_GRP_BTN_ROOT','10','ENT_USR_GRP_BTN_ROOT','ResourceEntity.displayNameMap','User Group Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ENT_USR_GRP_BTN_ROOT','11','ENT_USR_GRP_BTN_ROOT','ResourceEntity.displayNameMap','User Group Membership Buttons');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_GROUPS_ADD_BTN','1','GROUPS_ADD_BTN','ResourceEntity.displayNameMap','Add Group to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_GROUPS_ADD_BTN','2','GROUPS_ADD_BTN','ResourceEntity.displayNameMap','Add Group to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_GROUPS_ADD_BTN','4','GROUPS_ADD_BTN','ResourceEntity.displayNameMap','Add Group to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_GROUPS_ADD_BTN','8','GROUPS_ADD_BTN','ResourceEntity.displayNameMap','Add Group to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_GROUPS_ADD_BTN','9','GROUPS_ADD_BTN','ResourceEntity.displayNameMap','Add Group to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_GROUPS_ADD_BTN','10','GROUPS_ADD_BTN','ResourceEntity.displayNameMap','Add Group to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_GROUPS_ADD_BTN','11','GROUPS_ADD_BTN','ResourceEntity.displayNameMap','Add Group to User');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_GROUPS_EDT_BTN','1','GROUPS_EDT_BTN','ResourceEntity.displayNameMap','Edit Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_GROUPS_EDT_BTN','2','GROUPS_EDT_BTN','ResourceEntity.displayNameMap','Edit Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_GROUPS_EDT_BTN','4','GROUPS_EDT_BTN','ResourceEntity.displayNameMap','Edit Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_GROUPS_EDT_BTN','8','GROUPS_EDT_BTN','ResourceEntity.displayNameMap','Edit Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_GROUPS_EDT_BTN','9','GROUPS_EDT_BTN','ResourceEntity.displayNameMap','Edit Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_GROUPS_EDT_BTN','10','GROUPS_EDT_BTN','ResourceEntity.displayNameMap','Edit Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_GROUPS_EDT_BTN','11','GROUPS_EDT_BTN','ResourceEntity.displayNameMap','Edit Group');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_GROUPS_DEL_BTN','1','GROUPS_DEL_BTN','ResourceEntity.displayNameMap','Remove Group from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_GROUPS_DEL_BTN','2','GROUPS_DEL_BTN','ResourceEntity.displayNameMap','Remove Group from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_GROUPS_DEL_BTN','4','GROUPS_DEL_BTN','ResourceEntity.displayNameMap','Remove Group from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_GROUPS_DEL_BTN','8','GROUPS_DEL_BTN','ResourceEntity.displayNameMap','Remove Group from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_GROUPS_DEL_BTN','9','GROUPS_DEL_BTN','ResourceEntity.displayNameMap','Remove Group from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_GROUPS_DEL_BTN','10','GROUPS_DEL_BTN','ResourceEntity.displayNameMap','Remove Group from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_GROUPS_DEL_BTN','11','GROUPS_DEL_BTN','ResourceEntity.displayNameMap','Remove Group from User');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_GROUPS_INFO_BTN','1','GROUPS_INFO_BTN','ResourceEntity.displayNameMap','Group Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_GROUPS_INFO_BTN','2','GROUPS_INFO_BTN','ResourceEntity.displayNameMap','Group Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_GROUPS_INFO_BTN','4','GROUPS_INFO_BTN','ResourceEntity.displayNameMap','Group Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_GROUPS_INFO_BTN','8','GROUPS_INFO_BTN','ResourceEntity.displayNameMap','Group Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_GROUPS_INFO_BTN','9','GROUPS_INFO_BTN','ResourceEntity.displayNameMap','Group Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_GROUPS_INFO_BTN','10','GROUPS_INFO_BTN','ResourceEntity.displayNameMap','Group Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_GROUPS_INFO_BTN','11','GROUPS_INFO_BTN','ResourceEntity.displayNameMap','Group Info');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_GROUPS_PROV_BTN','1','GROUPS_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_GROUPS_PROV_BTN','2','GROUPS_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_GROUPS_PROV_BTN','4','GROUPS_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_GROUPS_PROV_BTN','8','GROUPS_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_GROUPS_PROV_BTN','9','GROUPS_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_GROUPS_PROV_BTN','10','GROUPS_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_GROUPS_PROV_BTN','11','GROUPS_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Group');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_GROUPS_DEPROV_BTN','1','GROUPS_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_GROUPS_DEPROV_BTN','2','GROUPS_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_GROUPS_DEPROV_BTN','4','GROUPS_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_GROUPS_DEPROV_BTN','8','GROUPS_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_GROUPS_DEPROV_BTN','9','GROUPS_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_GROUPS_DEPROV_BTN','10','GROUPS_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_GROUPS_DEPROV_BTN','11','GROUPS_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Group');


DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('ENT_USR_RES_BTN_ROOT', 'RESOURCES_ADD_BTN', 'RESOURCES_EDT_BTN', 'RESOURCES_DEL_BTN', 'RESOURCES_INFO_BTN', 'RESOURCES_PROV_BTN', 'RESOURCES_DEPROV_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('ENT_USR_RES_BTN_ROOT', 'RESOURCES_ADD_BTN', 'RESOURCES_EDT_BTN', 'RESOURCES_DEL_BTN', 'RESOURCES_INFO_BTN', 'RESOURCES_PROV_BTN', 'RESOURCES_DEPROV_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('ENT_USR_RES_BTN_ROOT', 'RESOURCES_ADD_BTN', 'RESOURCES_EDT_BTN', 'RESOURCES_DEL_BTN', 'RESOURCES_INFO_BTN', 'RESOURCES_PROV_BTN', 'RESOURCES_DEPROV_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('ENT_USR_RES_BTN_ROOT', 'RESOURCES_ADD_BTN', 'RESOURCES_EDT_BTN', 'RESOURCES_DEL_BTN', 'RESOURCES_INFO_BTN', 'RESOURCES_PROV_BTN', 'RESOURCES_DEPROV_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('ENT_USR_RES_BTN_ROOT', 'RESOURCES_ADD_BTN', 'RESOURCES_EDT_BTN', 'RESOURCES_DEL_BTN', 'RESOURCES_INFO_BTN', 'RESOURCES_PROV_BTN', 'RESOURCES_DEPROV_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('ENT_USR_RES_BTN_ROOT', 'RESOURCES_ADD_BTN', 'RESOURCES_EDT_BTN', 'RESOURCES_DEL_BTN', 'RESOURCES_INFO_BTN', 'RESOURCES_PROV_BTN', 'RESOURCES_DEPROV_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN  ('ENT_USR_RES_BTN_ROOT', 'RESOURCES_ADD_BTN', 'RESOURCES_EDT_BTN', 'RESOURCES_DEL_BTN', 'RESOURCES_INFO_BTN', 'RESOURCES_PROV_BTN', 'RESOURCES_DEPROV_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('ENT_USR_RES_BTN_ROOT', 'RESOURCES_ADD_BTN', 'RESOURCES_EDT_BTN', 'RESOURCES_DEL_BTN', 'RESOURCES_INFO_BTN', 'RESOURCES_PROV_BTN', 'RESOURCES_DEPROV_BTN');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ENT_USR_RES_BTN_ROOT', 'MENU_ITEM', 'Root menu for UserRes Membership', 'ENT_USR_RES_BTN_ROOT', 'ENT_USR_RES_BTN_ROOT', null, 40, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_RES_BTN_ROOT_PUB', 'ENT_USR_RES_BTN_ROOT', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_RES_BTN_ROOT_DESC', 'ENT_USR_RES_BTN_ROOT', 'MENU_DISPLAY_NAME', 'Root menu for UserRes Membership');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('RESOURCES_ADD_BTN', 'MENU_ITEM', 'Add User To Resource', 'RESOURCES_ADD_BTN', 'RESOURCES_ADD_BTN', '/webconsole/addUserToResource.html', 41, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_ADD_BTN_PUB', 'RESOURCES_ADD_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_ADD_BTN_DESC', 'RESOURCES_ADD_BTN', 'MENU_DISPLAY_NAME', 'Add User To Resource');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('RESOURCES_EDT_BTN', 'MENU_ITEM', 'Edit Resource', 'RESOURCES_EDT_BTN', 'RESOURCES_EDT_BTN', null, 42, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_EDT_BTN_PUB', 'RESOURCES_EDT_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_EDT_BTN_DESC', 'RESOURCES_EDT_BTN', 'MENU_DISPLAY_NAME', 'Edit Resource');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('RESOURCES_DEL_BTN', 'MENU_ITEM', 'Delete User from Resource', 'RESOURCES_DEL_BTN', 'RESOURCES_DEL_BTN', '/webconsole/removeUserFromResource.html', 43, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_DEL_BTN_PUB', 'RESOURCES_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_DEL_BTN_DESC', 'RESOURCES_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete User from Resource');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('RESOURCES_INFO_BTN', 'MENU_ITEM', 'Resource Info', 'RESOURCES_INFO_BTN', 'RESOURCES_INFO_BTN', null, 44, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_INFO_BTN_PUB', 'RESOURCES_INFO_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_INFO_BTN_DESC', 'RESOURCES_INFO_BTN', 'MENU_DISPLAY_NAME', 'Resource Info');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('RESOURCES_PROV_BTN', 'MENU_ITEM', 'Provision User by Resource', 'RESOURCES_PROV_BTN', 'RESOURCES_PROV_BTN', '/webconsole/provisionUserByResource.html', 45, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_PROV_BTN_PUB', 'RESOURCES_PROV_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_PROV_BTN_DESC', 'RESOURCES_PROV_BTN', 'MENU_DISPLAY_NAME', 'Provision User by Resource');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('RESOURCES_DEPROV_BTN', 'MENU_ITEM', 'DeProvision User by Resource', 'RESOURCES_DEPROV_BTN', 'RESOURCES_DEPROV_BTN', '/webconsole/deprovisionUserByResource.html', 46, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_DEPROV_BTN_PUB', 'RESOURCES_DEPROV_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('RESOURCES_DEPROV_BTN_DESC', 'RESOURCES_DEPROV_BTN', 'MENU_DISPLAY_NAME', 'DeProvision User by Resource');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_RES_BTN_ROOT', 'RESOURCES_ADD_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_RES_BTN_ROOT', 'RESOURCES_EDT_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_RES_BTN_ROOT', 'RESOURCES_DEL_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_RES_BTN_ROOT', 'RESOURCES_INFO_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_RES_BTN_ROOT', 'RESOURCES_PROV_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_RES_BTN_ROOT', 'RESOURCES_DEPROV_BTN');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ENT_USR_RES_BTN_ROOT', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('RESOURCES_ADD_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('RESOURCES_EDT_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('RESOURCES_DEL_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('RESOURCES_INFO_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('RESOURCES_PROV_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('RESOURCES_DEPROV_BTN', '9');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ENT_USR_RES_BTN_ROOT','1','ENT_USR_RES_BTN_ROOT','ResourceEntity.displayNameMap','User Resource Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ENT_USR_RES_BTN_ROOT','2','ENT_USR_RES_BTN_ROOT','ResourceEntity.displayNameMap','User Resource Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ENT_USR_RES_BTN_ROOT','4','ENT_USR_RES_BTN_ROOT','ResourceEntity.displayNameMap','User Resource Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ENT_USR_RES_BTN_ROOT','8','ENT_USR_RES_BTN_ROOT','ResourceEntity.displayNameMap','User Resource Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ENT_USR_RES_BTN_ROOT','9','ENT_USR_RES_BTN_ROOT','ResourceEntity.displayNameMap','User Resource Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ENT_USR_RES_BTN_ROOT','10','ENT_USR_RES_BTN_ROOT','ResourceEntity.displayNameMap','User Resource Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ENT_USR_RES_BTN_ROOT','11','ENT_USR_RES_BTN_ROOT','ResourceEntity.displayNameMap','User Resource Membership Buttons');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_RESOURCES_ADD_BTN','1','RESOURCES_ADD_BTN','ResourceEntity.displayNameMap','Add Resource to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_RESOURCES_ADD_BTN','2','RESOURCES_ADD_BTN','ResourceEntity.displayNameMap','Add Resource to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_RESOURCES_ADD_BTN','4','RESOURCES_ADD_BTN','ResourceEntity.displayNameMap','Add Resource to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_RESOURCES_ADD_BTN','8','RESOURCES_ADD_BTN','ResourceEntity.displayNameMap','Add Resource to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_RESOURCES_ADD_BTN','9','RESOURCES_ADD_BTN','ResourceEntity.displayNameMap','Add Resource to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_RESOURCES_ADD_BTN','10','RESOURCES_ADD_BTN','ResourceEntity.displayNameMap','Add Resource to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_RESOURCES_ADD_BTN','11','RESOURCES_ADD_BTN','ResourceEntity.displayNameMap','Add Resource to User');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_RESOURCES_EDT_BTN','1','RESOURCES_EDT_BTN','ResourceEntity.displayNameMap','Edit Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_RESOURCES_EDT_BTN','2','RESOURCES_EDT_BTN','ResourceEntity.displayNameMap','Edit Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_RESOURCES_EDT_BTN','4','RESOURCES_EDT_BTN','ResourceEntity.displayNameMap','Edit Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_RESOURCES_EDT_BTN','8','RESOURCES_EDT_BTN','ResourceEntity.displayNameMap','Edit Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_RESOURCES_EDT_BTN','9','RESOURCES_EDT_BTN','ResourceEntity.displayNameMap','Edit Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_RESOURCES_EDT_BTN','10','RESOURCES_EDT_BTN','ResourceEntity.displayNameMap','Edit Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_RESOURCES_EDT_BTN','11','RESOURCES_EDT_BTN','ResourceEntity.displayNameMap','Edit Resource');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_RESOURCES_DEL_BTN','1','RESOURCES_DEL_BTN','ResourceEntity.displayNameMap','Remove Resource from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_RESOURCES_DEL_BTN','2','RESOURCES_DEL_BTN','ResourceEntity.displayNameMap','Remove Resource from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_RESOURCES_DEL_BTN','4','RESOURCES_DEL_BTN','ResourceEntity.displayNameMap','Remove Resource from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_RESOURCES_DEL_BTN','8','RESOURCES_DEL_BTN','ResourceEntity.displayNameMap','Remove Resource from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_RESOURCES_DEL_BTN','9','RESOURCES_DEL_BTN','ResourceEntity.displayNameMap','Remove Resource from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_RESOURCES_DEL_BTN','10','RESOURCES_DEL_BTN','ResourceEntity.displayNameMap','Remove Resource from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_RESOURCES_DEL_BTN','11','RESOURCES_DEL_BTN','ResourceEntity.displayNameMap','Remove Resource from User');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_RESOURCES_INFO_BTN','1','RESOURCES_INFO_BTN','ResourceEntity.displayNameMap','Resource Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_RESOURCES_INFO_BTN','2','RESOURCES_INFO_BTN','ResourceEntity.displayNameMap','Resource Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_RESOURCES_INFO_BTN','4','RESOURCES_INFO_BTN','ResourceEntity.displayNameMap','Resource Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_RESOURCES_INFO_BTN','8','RESOURCES_INFO_BTN','ResourceEntity.displayNameMap','Resource Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_RESOURCES_INFO_BTN','9','RESOURCES_INFO_BTN','ResourceEntity.displayNameMap','Resource Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_RESOURCES_INFO_BTN','10','RESOURCES_INFO_BTN','ResourceEntity.displayNameMap','Resource Info');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_RESOURCES_INFO_BTN','11','RESOURCES_INFO_BTN','ResourceEntity.displayNameMap','Resource Info');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_RESOURCES_PROV_BTN','1','RESOURCES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_RESOURCES_PROV_BTN','2','RESOURCES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_RESOURCES_PROV_BTN','4','RESOURCES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_RESOURCES_PROV_BTN','8','RESOURCES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_RESOURCES_PROV_BTN','9','RESOURCES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_RESOURCES_PROV_BTN','10','RESOURCES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_RESOURCES_PROV_BTN','11','RESOURCES_PROV_BTN','ResourceEntity.displayNameMap','Provision User By Resource');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_RESOURCES_DEPROV_BTN','1','RESOURCES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_RESOURCES_DEPROV_BTN','2','RESOURCES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_RESOURCES_DEPROV_BTN','4','RESOURCES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_RESOURCES_DEPROV_BTN','8','RESOURCES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_RESOURCES_DEPROV_BTN','9','RESOURCES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_RESOURCES_DEPROV_BTN','10','RESOURCES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_RESOURCES_DEPROV_BTN','11','RESOURCES_DEPROV_BTN','ResourceEntity.displayNameMap','DeProvision User By Resource');


DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ENT_USR_ORG_BTN_ROOT', 'MENU_ITEM', 'Root menu for UserOrg Membership', 'ENT_USR_ORG_BTN_ROOT', 'ENT_USR_ORG_BTN_ROOT', null, 50, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_ORG_BTN_ROOT_PUB', 'ENT_USR_ORG_BTN_ROOT', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_ORG_BTN_ROOT_DESC', 'ENT_USR_ORG_BTN_ROOT', 'MENU_DISPLAY_NAME', 'Root menu for UserOrg Membership');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ORGANIZATIONS_ADD_BTN', 'MENU_ITEM', 'Add User To Organization', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_ADD_BTN', '/webconsole/addUserToOrganization.html', 51, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_ADD_BTN_PUB', 'ORGANIZATIONS_ADD_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_ADD_BTN_DESC', 'ORGANIZATIONS_ADD_BTN', 'MENU_DISPLAY_NAME', 'Add User To Organization');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ORGANIZATIONS_EDT_BTN', 'MENU_ITEM', 'Edit Organization', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_EDT_BTN', null, 52, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_EDT_BTN_PUB', 'ORGANIZATIONS_EDT_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_EDT_BTN_DESC', 'ORGANIZATIONS_EDT_BTN', 'MENU_DISPLAY_NAME', 'Edit Organization');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ORGANIZATIONS_DEL_BTN', 'MENU_ITEM', 'Delete User from Organization', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_DEL_BTN', '/webconsole/removeUserFromOrganization.html', 53, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_DEL_BTN_PUB', 'ORGANIZATIONS_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_DEL_BTN_DESC', 'ORGANIZATIONS_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete User from Organization');


INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_EDT_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_DEL_BTN');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ENT_USR_ORG_BTN_ROOT', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORGANIZATIONS_ADD_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORGANIZATIONS_EDT_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORGANIZATIONS_DEL_BTN', '9');


INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ENT_USR_ORG_BTN_ROOT','1','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ENT_USR_ORG_BTN_ROOT','2','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ENT_USR_ORG_BTN_ROOT','4','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ENT_USR_ORG_BTN_ROOT','8','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ENT_USR_ORG_BTN_ROOT','9','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ENT_USR_ORG_BTN_ROOT','10','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ENT_USR_ORG_BTN_ROOT','11','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ORGANIZATIONS_ADD_BTN','1','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ORGANIZATIONS_ADD_BTN','2','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ORGANIZATIONS_ADD_BTN','4','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ORGANIZATIONS_ADD_BTN','8','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ORGANIZATIONS_ADD_BTN','9','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ORGANIZATIONS_ADD_BTN','10','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ORGANIZATIONS_ADD_BTN','11','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ORGANIZATIONS_EDT_BTN','1','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ORGANIZATIONS_EDT_BTN','2','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ORGANIZATIONS_EDT_BTN','4','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ORGANIZATIONS_EDT_BTN','8','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ORGANIZATIONS_EDT_BTN','9','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ORGANIZATIONS_EDT_BTN','10','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ORGANIZATIONS_EDT_BTN','11','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ORGANIZATIONS_DEL_BTN','1','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ORGANIZATIONS_DEL_BTN','2','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ORGANIZATIONS_DEL_BTN','4','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ORGANIZATIONS_DEL_BTN','8','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ORGANIZATIONS_DEL_BTN','9','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ORGANIZATIONS_DEL_BTN','10','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_ORGANIZATIONS_DEL_BTN','11','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');

commit;
/***************************************dml/9.ss_remove_user_entitlement_menu.sql***************************************/
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN  ('SELFSERV_USER_MEMSHP');
DELETE FROM RES WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');

/***************************************dml/10.fix_usr_org_btns.sql***************************************/

DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='OrganizationEntity.displayNameMap' and REFERENCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ENT_USR_ORG_BTN_ROOT', 'MENU_ITEM', 'Root menu for UserOrg Membership', 'ENT_USR_ORG_BTN_ROOT', 'ENT_USR_ORG_BTN_ROOT', null, 50, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_ORG_BTN_ROOT_PUB', 'ENT_USR_ORG_BTN_ROOT', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_ORG_BTN_ROOT_DESC', 'ENT_USR_ORG_BTN_ROOT', 'MENU_DISPLAY_NAME', 'Root menu for UserOrg Membership');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ORGANIZATIONS_ADD_BTN', 'MENU_ITEM', 'Add User To Organization', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_ADD_BTN', '/webconsole/addUserToOrganization.html', 51, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_ADD_BTN_PUB', 'ORGANIZATIONS_ADD_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_ADD_BTN_DESC', 'ORGANIZATIONS_ADD_BTN', 'MENU_DISPLAY_NAME', 'Add User To Organization');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ORGANIZATIONS_EDT_BTN', 'MENU_ITEM', 'Edit Organization', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_EDT_BTN', null, 52, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_EDT_BTN_PUB', 'ORGANIZATIONS_EDT_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_EDT_BTN_DESC', 'ORGANIZATIONS_EDT_BTN', 'MENU_DISPLAY_NAME', 'Edit Organization');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ORGANIZATIONS_DEL_BTN', 'MENU_ITEM', 'Delete User from Organization', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_DEL_BTN', '/webconsole/removeUserFromOrganization.html', 53, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_DEL_BTN_PUB', 'ORGANIZATIONS_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_DEL_BTN_DESC', 'ORGANIZATIONS_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete User from Organization');


INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_EDT_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_DEL_BTN');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ENT_USR_ORG_BTN_ROOT', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORGANIZATIONS_ADD_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORGANIZATIONS_EDT_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORGANIZATIONS_DEL_BTN', '9');


INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ENT_USR_ORG_BTN_ROOT','1','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ENT_USR_ORG_BTN_ROOT','2','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ENT_USR_ORG_BTN_ROOT','4','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ENT_USR_ORG_BTN_ROOT','8','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ENT_USR_ORG_BTN_ROOT','9','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ENT_USR_ORG_BTN_ROOT','10','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ORGANIZATIONS_ADD_BTN','1','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ORGANIZATIONS_ADD_BTN','2','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ORGANIZATIONS_ADD_BTN','4','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ORGANIZATIONS_ADD_BTN','8','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ORGANIZATIONS_ADD_BTN','9','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ORGANIZATIONS_ADD_BTN','10','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ORGANIZATIONS_EDT_BTN','1','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ORGANIZATIONS_EDT_BTN','2','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ORGANIZATIONS_EDT_BTN','4','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ORGANIZATIONS_EDT_BTN','8','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ORGANIZATIONS_EDT_BTN','9','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ORGANIZATIONS_EDT_BTN','10','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ORGANIZATIONS_DEL_BTN','1','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ORGANIZATIONS_DEL_BTN','2','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ORGANIZATIONS_DEL_BTN','4','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ORGANIZATIONS_DEL_BTN','8','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ORGANIZATIONS_DEL_BTN','9','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ORGANIZATIONS_DEL_BTN','10','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');

/***************************************dml/11.add_just_in_time_groovy_scirpt.sql***************************************/

INSERT INTO AUTH_ATTRIBUTE (AUTH_ATTRIBUTE_ID, ATTRIBUTE_NAME, PROVIDER_TYPE, DESCRIPTION, REQUIRED, DATA_TYPE)
	VALUES('SamlSpJITGroovyScript', 'Just-in-time provisioning groovy script', 'SAML_SP_PROVIDER', 'This groovy script controls just-in-time provisioning.', 'N', 'singleValue');

/***************************************dml/12.add_batch_task.sql***************************************/
delete from BATCH_CONFIG where TASK_ID='GROUP_ATTESTATION';
INSERT INTO BATCH_CONFIG (TASK_ID, TASK_NAME, LAST_EXEC_TIME,TASK_URL,EXECUTION_ORDER, STATUS,PARAM1,PARAM2,PARAM3,PARAM4,RULE_TYPE,ENABLED,LAST_MODIFIED_DATETIME,RUN_ON,CRON_EXPRESSION,SPRING_BEAN,SPRING_BEAN_METHOD) VALUES ('GROUP_ATTESTATION','Group Attestation', to_timestamp('18-11-14 11.32.01 PM','DD-MM-YY HH.MI.SS AM'),NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'N',to_timestamp('18-11-14 11.32.16 PM','DD-MM-YY HH.MI.SS AM'),NULL,'0 0 0 1 1/3 ?','groupAttestationInitializer','initializeAttestation');
/***************************************ddl/4.alter_table_content_provider.sql***************************************/
ALTER TABLE CONTENT_PROVIDER ADD COLUMN LOGIN_URL VARCHAR(300) NULL;
ALTER TABLE CONTENT_PROVIDER ADD COLUMN POSTBACK_URL_PARAM_NAME VARCHAR(50) NULL;
		
UPDATE CONTENT_PROVIDER SET LOGIN_URL='/idp/login.html';
UPDATE CONTENT_PROVIDER SET POSTBACK_URL_PARAM_NAME='postbackURL';
		
ALTER TABLE CONTENT_PROVIDER ALTER COLUMN LOGIN_URL SET NOT NULL;
ALTER TABLE CONTENT_PROVIDER ALTER COLUMN POSTBACK_URL_PARAM_NAME SET NOT NULL;
/***************************************dml/13.add_report_param.sql***************************************/

INSERT INTO REPORT_PARAMETER_METATYPE (PARAM_METATYPE_ID, PARAM_METATYPE_NAME, IS_MULTIPLE) VALUES ('RESOURCE_TYPE', 'Resource type', 'Y');

INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) 
					VALUES ('1096', '109', 'RES_TYPE_IDS', NULL, '1', 'RESOURCE_TYPE', 'Y', 'N', 'Resource type', 6, NULL);


commit;
