use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('DIR_LOOKUP_PAGE');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('DIR_LOOKUP_PAGE');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('DIR_LOOKUP_PAGE');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('DIR_LOOKUP_PAGE');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('DIR_LOOKUP_PAGE');
DELETE FROM RES WHERE RESOURCE_ID IN ('DIR_LOOKUP_PAGE');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, URL, DISPLAY_ORDER) VALUES ('DIR_LOOKUP_PAGE', 'MENU_ITEM', 'Directory Lookup', 'DIR_LOOKUP_PAGE', '/selfservice/dirLookup.html', 5);

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('DIR_LOOKUP_PAGE_PUB', 'DIR_LOOKUP_PAGE', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('DIR_LOOKUP_PAGE_DIS', 'DIR_LOOKUP_PAGE', 'MENU_DISPLAY_NAME', 'Directory Lookup');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFCENTER', 'DIR_LOOKUP_PAGE');
