use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS showHistoryMenus$$

CREATE PROCEDURE showHistoryMenus()
	BEGIN
		IF ((SELECT count(*) FROM RESOURCE_PROP WHERE RESOURCE_ID='MANAGEREQ' AND NAME='IS_VISIBLE') >= 1) THEN
			UPDATE RESOURCE_PROP SET PROP_VALUE='true' WHERE  RESOURCE_ID='MANAGEREQ' AND NAME='IS_VISIBLE';
		ELSE
			INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('MANAGEREQ_VISIBLE', 'MANAGEREQ', 'IS_VISIBLE', 'true');
		END IF;
	END$$

DELIMITER ;

call showHistoryMenus();

DROP PROCEDURE showHistoryMenus;

UPDATE RES SET URL='/selfservice/taskHistory.html' WHERE RESOURCE_ID='MANAGEREQ';