use openiam;


DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SYNCUSER_EDIT','SYNCUSER_EDIT_MENU_ROOT','SYNCUSER_POLICYMAP');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SYNCUSER_EDIT','SYNCUSER_EDIT_MENU_ROOT','SYNCUSER_POLICYMAP');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SYNCUSER_EDIT','SYNCUSER_EDIT_MENU_ROOT','SYNCUSER_POLICYMAP');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SYNCUSER_EDIT','SYNCUSER_EDIT_MENU_ROOT','SYNCUSER_POLICYMAP');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SYNCUSER_EDIT','SYNCUSER_EDIT_MENU_ROOT','SYNCUSER_POLICYMAP');
DELETE FROM RES WHERE RESOURCE_ID IN ('SYNCUSER_EDIT','SYNCUSER_EDIT_MENU_ROOT','SYNCUSER_POLICYMAP');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, URL) VALUES ('SYNCUSER_EDIT', 'MENU_ITEM', 'Edit sync', 'SYNCUSER_EDIT', '/webconsole-idm/provisioning/synchronization.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SYNCUSER_EDIT_PUB', 'SYNCUSER_EDIT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SYNCUSER_EDIT_DESC', 'SYNCUSER_EDIT', 'MENU_DISPLAY_NAME', 'Edit Synchronization');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, URL) VALUES ('SYNCUSER_POLICYMAP', 'MENU_ITEM', 'Policy map', 'SYNCUSER_POLICYMAP', '/webconsole/synchPolicyMap.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SYNCUSER_POLICYMAP_PUB', 'SYNCUSER_POLICYMAP', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SYNCUSER_POLICYMAP_DESC', 'SYNCUSER_POLICYMAP', 'MENU_DISPLAY_NAME', 'Policy Map');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME) VALUES ('SYNCUSER_EDIT_MENU_ROOT', 'MENU_ITEM', 'Edit sync', 'SYNCUSER_EDIT_MENU_ROOT');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SYNCUSER_EDIT_MENU_ROOT', 'SYNCUSER_EDIT');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SYNCUSER_EDIT_MENU_ROOT', 'SYNCUSER_POLICYMAP');
