use openiam;

DELETE FROM RES WHERE RESOURCE_ID = 'MNGSYS_EDIT_NO_RES_MENU_ROOT';

INSERT INTO RES 
(RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DISPLAY_ORDER, IS_PUBLIC, IS_SSL) VALUES 
('MNGSYS_EDIT_NO_RES_MENU_ROOT', 'MENU_ITEM','MNGSYS_EDIT_NO_RES_MENU_ROOT', 1,  'Y', 'N');
