use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('WEB_REPORT', 'WEB_REPORT_ROOT',  'WEB_REPORT_NEW');

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('WEB_REPORT', 'WEB_REPORT_ROOT',  'WEB_REPORT_NEW');

DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN (
'WEB_REPORT', 'WEB_REPORT_ROOT',  'WEB_REPORT_NEW');

DELETE FROM RES WHERE RESOURCE_ID IN('WEB_REPORT', 'WEB_REPORT_ROOT',  'WEB_REPORT_NEW');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL, DISPLAY_ORDER, IS_PUBLIC, IS_SSL) VALUES('WEB_REPORT', 'MENU_ITEM', 'WEB_REPORT', 'Report', '/webconsole/report.html', 6, 'Y', 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('WEB_REPORT_PUB', 'WEB_REPORT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('WEB_REPORT_DESC', 'WEB_REPORT', 'MENU_DISPLAY_NAME', 'Report');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('IDM', 'WEB_REPORT');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('WEB_REPORT_ROOT', 'MENU_ITEM', 'WEB_REPORT_ROOT', 'Report Root Menu');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('WEB_REPORT_ROOT_PUB', 'WEB_REPORT_ROOT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('WEB_REPORT_ROOT_DESC', 'WEB_REPORT_ROOT', 'MENU_DISPLAY_NAME', 'Report Root Menu');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('WEB_REPORT_NEW', 'MENU_ITEM', 'WEB_REPORT_NEW', 'New Report', '/webconsole/editReport.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('WEB_REPORT_NEW_PUB', 'WEB_REPORT_NEW', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('WEB_REPORT_NEW_DSC', 'WEB_REPORT_NEW', 'MENU_DISPLAY_NAME', 'Create New Report');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('WEB_REPORT_ROOT', 'WEB_REPORT_NEW');










