use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('CONF_POLICY_PAGE');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('CONF_POLICY_PAGE');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('CONF_POLICY_PAGE');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('CONF_POLICY_PAGE');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('CONF_POLICY_PAGE');
DELETE FROM RES WHERE RESOURCE_ID IN ('CONF_POLICY_PAGE');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, URL) VALUES ('CONF_POLICY_PAGE', 'MENU_ITEM', 'Configure IT Policy', 'IT_POLICY_PAGE', '/webconsole/configurePolicy.html');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('CONF_POLICY_PAGE_PUB', 'CONF_POLICY_PAGE', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('CONF_POLICY_PAGE_DIS', 'CONF_POLICY_PAGE', 'MENU_DISPLAY_NAME', 'Configure IT Policy');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ADMIN', 'CONF_POLICY_PAGE');
