use openiam;

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES ('ORG_APROVER_ASSOC', 'MENU_ITEM', 'ORG_APROVER_ASSOC', 'Approver Associations', '/webconsole-idm/provisioning/organizationApproverAssociations.html');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ORG_APROVER_ASSOC_DN', 'ORG_APROVER_ASSOC', 'MENU_DISPLAY_NAME', 'Approver Associations');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ORG_APROVER_ASSOC_PUB', 'ORG_APROVER_ASSOC', 'MENU_IS_PUBLIC', 'true');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES ('ORGANIZATION_EDIT_ID', 'ORG_APROVER_ASSOC');