use openiam;


DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('ORG_TYPE_SUBMENU_ROOT', 'ORG_TYPE_SUBMENU_EDIT', 'ORG_TYPE_SEARCH', 'NEW_ORG_TYPE', 'EDIT_ORG_TYPE', 'EDIT_ORG_MEMBERSHIP', 'EDIT_ORG_TYPE_IDMAN', 'ORG_TYPE_EDIT_SEARCH');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('ORG_TYPE_SUBMENU_ROOT', 'ORG_TYPE_SUBMENU_EDIT', 'ORG_TYPE_SEARCH', 'NEW_ORG_TYPE', 'EDIT_ORG_TYPE', 'EDIT_ORG_MEMBERSHIP', 'EDIT_ORG_TYPE_IDMAN', 'ORG_TYPE_EDIT_SEARCH');
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('ORG_TYPE_SUBMENU_ROOT', 'ORG_TYPE_SUBMENU_EDIT', 'ORG_TYPE_SEARCH', 'NEW_ORG_TYPE', 'EDIT_ORG_TYPE', 'EDIT_ORG_MEMBERSHIP', 'EDIT_ORG_TYPE_IDMAN', 'ORG_TYPE_EDIT_SEARCH');
DELETE FROM RES WHERE RESOURCE_ID IN('ORG_TYPE_SUBMENU_ROOT', 'ORG_TYPE_SUBMENU_EDIT', 'ORG_TYPE_SEARCH', 'NEW_ORG_TYPE', 'EDIT_ORG_TYPE', 'EDIT_ORG_MEMBERSHIP', 'EDIT_ORG_TYPE_IDMAN', 'ORG_TYPE_EDIT_SEARCH');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('ORG_TYPE_SUBMENU_ROOT', 'MENU_ITEM', 'ORG_TYPE_SUBMENU_ROOT', 'Organization Type Root');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ORG_TYPE_SUBMENU_ROOT_PUB', 'ORG_TYPE_SUBMENU_ROOT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ORG_TYPE_SUBMENU_ROOT_DESC', 'ORG_TYPE_SUBMENU_ROOT', 'MENU_DISPLAY_NAME', 'Organization Type Root');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION) VALUES('ORG_TYPE_SUBMENU_EDIT', 'MENU_ITEM', 'ORG_TYPE_SUBMENU_EDIT', 'Organization Type Edit');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ORG_TYPE_SUBMENU_EDIT_PUB', 'ORG_TYPE_SUBMENU_EDIT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ORG_TYPE_SUBMENU_EDIT_DESC', 'ORG_TYPE_SUBMENU_EDIT', 'MENU_DISPLAY_NAME', 'Organization Type Edit');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('ORG_TYPE_SEARCH', 'MENU_ITEM', 'ORG_TYPE_SEARCH', 'Organization Type Search', '/webconsole/organizationTypeSearch.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ORG_TYPE_SEARCH_PUB', 'ORG_TYPE_SEARCH', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ORG_TYPE_SEARCH_DESC', 'ORG_TYPE_SEARCH', 'MENU_DISPLAY_NAME', 'Search Organization Types');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('NEW_ORG_TYPE', 'MENU_ITEM', 'NEW_ORG_TYPE', 'Edit Organization Type', '/webconsole/organizationTypeEdit.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('NEW_ORG_TYPE_PUB', 'NEW_ORG_TYPE', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('NEW_ORG_TYPE_DESC', 'NEW_ORG_TYPE', 'MENU_DISPLAY_NAME', 'New Organization Type');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('EDIT_ORG_TYPE', 'MENU_ITEM', 'EDIT_ORG_TYPE', 'Edit Organization Type', '/webconsole/organizationTypeEdit.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('EDIT_ORG_TYPE_PUB', 'EDIT_ORG_TYPE', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('EDIT_ORG_TYPE_DESC', 'EDIT_ORG_TYPE', 'MENU_DISPLAY_NAME', 'Edit Organization Type');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('EDIT_ORG_MEMBERSHIP', 'MENU_ITEM', 'EDIT_ORG_MEMBERSHIP', 'Membership', '/webconsole/organizationTypeMembership.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('EDIT_ORG_MEMBERSHIP_PUB', 'EDIT_ORG_MEMBERSHIP', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('EDIT_ORG_MEMBERSHIP_DESC', 'EDIT_ORG_MEMBERSHIP', 'MENU_DISPLAY_NAME', 'Membership');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('ORG_TYPE_EDIT_SEARCH', 'MENU_ITEM', 'ORG_TYPE_EDIT_SEARCH', 'Organization Type Search', '/webconsole/organizationTypeSearch.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ORG_TYPE_EDIT_SEARCH_PUB', 'ORG_TYPE_EDIT_SEARCH', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('ORG_TYPE_EDIT_SEARCH_DESC', 'ORG_TYPE_EDIT_SEARCH', 'MENU_DISPLAY_NAME', 'Search Organization Types');


INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ORG_TYPE_SUBMENU_ROOT', 'ORG_TYPE_SEARCH');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ORG_TYPE_SUBMENU_ROOT', 'NEW_ORG_TYPE');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ORG_TYPE_SUBMENU_EDIT', 'ORG_TYPE_EDIT_SEARCH');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ORG_TYPE_SUBMENU_EDIT', 'EDIT_ORG_TYPE');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ORG_TYPE_SUBMENU_EDIT', 'EDIT_ORG_MEMBERSHIP');




INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL) VALUES('EDIT_ORG_TYPE_IDMAN', 'MENU_ITEM', 'EDIT_ORG_TYPE_IDMAN', 'Membership', '/webconsole/organizationTypeSearch.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('EDIT_ORG_TYPE_IDMAN_PUB', 'EDIT_ORG_TYPE_IDMAN', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('EDIT_ORG_TYPE_IDMAN_DESC', 'EDIT_ORG_TYPE_IDMAN', 'MENU_DISPLAY_NAME', 'Organization Types');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('IDMAN', 'EDIT_ORG_TYPE_IDMAN');