use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SUP_SUB_PAGE');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SUP_SUB_PAGE');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SUP_SUB_PAGE');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SUP_SUB_PAGE');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SUP_SUB_PAGE');
DELETE FROM RES WHERE RESOURCE_ID IN ('SUP_SUB_PAGE');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, URL, DISPLAY_ORDER) VALUES ('SUP_SUB_PAGE', 'MENU_ITEM', 'Configure IT Policy', 'SUP_SUB_PAGE', '/webconsole/supSub.html', '11');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SUP_SUB_PAGE_PUB', 'SUP_SUB_PAGE', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SUP_SUB_PAGE_DIS', 'SUP_SUB_PAGE', 'MENU_DISPLAY_NAME', 'Superiors & Subordinates');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('USER_EDIT_MENU', 'SUP_SUB_PAGE');
