USE openiam;

SET NAMES utf8;

/* Create database schema */

CREATE TABLE `APPROVER_ASSOC` (
	`APPROVER_ASSOC_ID` varchar(32) NOT NULL,
	`REQUEST_TYPE` varchar(32) DEFAULT NULL,
	`APPROVER_LEVEL` int(11) DEFAULT '1',
	`ASSOCIATION_TYPE` varchar(20) DEFAULT NULL,
	`ASSOCIATION_ENTITY_ID` varchar(32) DEFAULT NULL,
	`ON_APPROVE_ENTITY_ID` varchar(32) DEFAULT NULL,
	`ON_REJECT_ENTITY_ID` varchar(32) DEFAULT NULL,
	`ON_APPROVE_ENTITY_TYPE` varchar(20) DEFAULT NULL,
	`ON_REJECT_ENTITY_TYPE` varchar(20) DEFAULT NULL,
	`APPROVER_ENTITY_TYPE` varchar(20) DEFAULT NULL,
	`APPROVER_ENTITY_ID` varchar(32) DEFAULT NULL,
	`APPLY_DELEGATION_FILTER` char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`APPROVER_ASSOC_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `ATTRIBUTE_MAP` (
	`ATTRIBUTE_MAP_ID` varchar(32) NOT NULL,
	`MANAGED_SYS_ID` varchar(32) DEFAULT NULL,
	`RESOURCE_ID` varchar(32) DEFAULT NULL,
	`MAP_FOR_OBJECT_TYPE` varchar(20) DEFAULT 'USER',
	`ATTRIBUTE_NAME` varchar(50) DEFAULT NULL,
	`TARGET_ATTRIBUTE_NAME` varchar(50) DEFAULT NULL,
	`AUTHORITATIVE_SRC` int(11) DEFAULT '0',
	`ATTRIBUTE_POLICY_ID` varchar(32) DEFAULT NULL,
	`RULE_TEXT` text,
	`STATUS` varchar(20) DEFAULT 'ACTIVE',
	`START_DATE` date DEFAULT NULL,
	`END_DATE` date DEFAULT NULL,
	`STORE_IN_IAMDB` int(11) DEFAULT '0',
	`DATA_TYPE` varchar(20) DEFAULT NULL,
	`DEFAULT_VALUE` varchar(32) DEFAULT NULL,
	`SYNCH_CONFIG_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`ATTRIBUTE_MAP_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `AUTH_LEVEL` (
	`AUTH_LEVEL_ID` varchar(32) NOT NULL,
	`AUTH_LEVEL_NAME` varchar(100) NOT NULL,
	`REQUIRES_AUTHENTICATION` char(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (`AUTH_LEVEL_ID`),
	UNIQUE KEY `UNIQUE_AUTH_LEVEL_NAME` (`AUTH_LEVEL_NAME`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `AUTH_PROVIDER_TYPE` (
	`PROVIDER_TYPE` varchar(32) NOT NULL,
	`DESCRIPTION` varchar(40) DEFAULT NULL,
	`ACTIVE` char(1) DEFAULT 'Y',
	PRIMARY KEY (`PROVIDER_TYPE`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `AUTH_RESOURCE_AM_ATTRIBUTE` (
	`REFLECTION_KEY` varchar(255) NOT NULL,
	`ATTRIBUTE_NAME` varchar(100) NOT NULL,
	`AM_RES_ATTRIBUTE_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`AM_RES_ATTRIBUTE_ID`),
	UNIQUE KEY `REFLECTION_KEY_IDX` (`REFLECTION_KEY`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `BATCH_CONFIG` (
	`TASK_ID` varchar(32) NOT NULL,
	`TASK_NAME` varchar(50) DEFAULT NULL,
	`LAST_EXEC_TIME` datetime DEFAULT NULL,
	`TASK_URL` varchar(255) DEFAULT NULL,
	`EXECUTION_ORDER` int(11) DEFAULT '1',
	`STATUS` varchar(20) DEFAULT NULL,
	`PARAM1` varchar(255) DEFAULT NULL,
	`PARAM2` varchar(255) DEFAULT NULL,
	`PARAM3` varchar(255) DEFAULT NULL,
	`PARAM4` varchar(255) DEFAULT NULL,
	`RULE_TYPE` varchar(20) DEFAULT NULL,
	`ENABLED` char(1) NOT NULL DEFAULT 'N',
	`LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
	`RUN_ON` datetime DEFAULT NULL,
	`CRON_EXPRESSION` varchar(100) DEFAULT NULL,
	`SPRING_BEAN` varchar(100) DEFAULT NULL,
	`SPRING_BEAN_METHOD` varchar(100) DEFAULT NULL,
	PRIMARY KEY (`TASK_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DELIMITER ;;

CREATE TRIGGER ON_BATCH_TASK_INSERT 
BEFORE 
INSERT ON BATCH_CONFIG 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_MODIFIED_DATETIME = NOW();
	END ;;

CREATE TRIGGER ON_BATCH_TASK_UPDATE
BEFORE 
UPDATE ON BATCH_CONFIG 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_MODIFIED_DATETIME = NOW();
	END ;;

DELIMITER ;

CREATE TABLE `CATEGORY` (
	`CATEGORY_ID` varchar(32) NOT NULL,
	`PARENT_ID` varchar(32) DEFAULT NULL,
	`CATEGORY_NAME` varchar(40) DEFAULT NULL,
	`CATEGORY_DESC` varchar(80) DEFAULT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(20) DEFAULT NULL,
	`SHOW_LIST` int(11) DEFAULT '0',
	`DISPLAY_ORDER` int(11) DEFAULT '0',
	PRIMARY KEY (`CATEGORY_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `DEF_RECON_ATTR_MAP` (
	`DEF_ATTR_MAP_ID` varchar(32) NOT NULL,
	`DEF_ATTR_MAP_NAME` varchar(100) NOT NULL,
	PRIMARY KEY (`DEF_ATTR_MAP_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `ENTITLEMENT` (
	`ENTITLEMENT_ID` varchar(32) NOT NULL,
	`ENTITLEMENT_NAME` varchar(40) DEFAULT NULL,
	`ENTITLEMENT_VALUE` varchar(80) DEFAULT NULL,
	`DESCRIPTION` varchar(255) DEFAULT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(20) DEFAULT NULL,
	PRIMARY KEY (`ENTITLEMENT_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `IDENTITY` (
	`IDENTITY_ID` varchar(32) NOT NULL,
	`MANAGED_SYS_ID` varchar(32) NOT NULL,
	`IDENTITY` varchar(320) CHARACTER SET latin1 NOT NULL,
	`REFERRED_OBJECT_ID` varchar(32) NOT NULL,
	`IDENTITY_TYPE` varchar(20) DEFAULT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(32) DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `IDENTITY_QUEST_GRP` (
	`IDENTITY_QUEST_GRP_ID` varchar(32) NOT NULL,
	`NAME` varchar(60) DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT NULL,
	`COMPANY_OWNER_ID` varchar(32) DEFAULT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(20) DEFAULT NULL,
	`LAST_UPDATE` datetime DEFAULT NULL,
	`LAST_UPDATED_BY` varchar(20) DEFAULT NULL,
	PRIMARY KEY (`IDENTITY_QUEST_GRP_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `IMAGE` (
	`IMAGE_ID` varchar(20) NOT NULL,
	`IMAGE_FILE` varchar(80) DEFAULT NULL,
	`IMAGE_TYPE` varchar(20) DEFAULT NULL,
	`DESCRIPTION` varchar(250) DEFAULT NULL,
	`MIME_TYPE` varchar(30) DEFAULT NULL,
	`URL` varchar(100) DEFAULT NULL,
	`FILE_SIZE` int(11) DEFAULT NULL,
	`IMAGE_BLOB` blob,
	PRIMARY KEY (`IMAGE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `IT_POLICY` (
	`IT_POLICY_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`APPROVE_TYPE` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT 'Once',
	`ACTIVE` char(1) COLLATE utf8_bin NOT NULL DEFAULT 'N',
	`CREATE_DATE` timestamp NULL DEFAULT NULL,
	`UPDATE_DATE` timestamp NULL DEFAULT NULL,
	`CREATED_BY` varchar(32) COLLATE utf8_bin DEFAULT NULL,
	`UPDATED_BY` varchar(32) COLLATE utf8_bin DEFAULT NULL,
	`POLICY_CONTENT` longtext COLLATE utf8_bin,
	`CONFIRMATION` varchar(255) COLLATE utf8_bin DEFAULT NULL,
	PRIMARY KEY (`IT_POLICY_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `LANGUAGE` (
	`ID` varchar(32) NOT NULL,
	`LANGUAGE` varchar(20) DEFAULT NULL,
	`IS_USED` varchar(1) NOT NULL DEFAULT 'N',
	`LANGUAGE_CODE` varchar(2) NOT NULL,
	`IS_DEFAULT` char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `LOCATION` (
	`LOCATION_ID` varchar(32) NOT NULL,
	`NAME` varchar(80) DEFAULT NULL,
	`DESCRIPTION` varchar(255) DEFAULT NULL,
	`COUNTRY` varchar(30) DEFAULT NULL,
	`BLDG_NUM` varchar(10) DEFAULT NULL,
	`STREET_DIRECTION` varchar(20) DEFAULT NULL,
	`ADDRESS1` varchar(45) DEFAULT NULL,
	`ADDRESS2` varchar(45) DEFAULT NULL,
	`ADDRESS3` varchar(45) DEFAULT NULL,
	`CITY` varchar(30) DEFAULT NULL,
	`STATE` varchar(15) DEFAULT NULL,
	`POSTAL_CD` varchar(10) DEFAULT NULL,
	`ORGANIZATION_ID` varchar(32) DEFAULT NULL,
	`INTERNAL_LOCATION_ID` varchar(32) DEFAULT NULL,
	`ACTIVE` int(11) DEFAULT '1',
	`SENSITIVE_LOCATION` int(11) DEFAULT '0',
	PRIMARY KEY (`LOCATION_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `MANAGED_SYS_RULE` (
	`MANAGED_SYS_RULE_ID` varchar(32) NOT NULL,
	`MANAGED_SYS_ID` varchar(32) NOT NULL,
	`MANAGED_SYS_RULE_NAME` varchar(45) DEFAULT NULL,
	`MANAGED_SYS_RULE_VALUE` varchar(45) DEFAULT NULL,
	PRIMARY KEY (`MANAGED_SYS_RULE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `METADATA_TYPE` (
	`TYPE_ID` varchar(32) NOT NULL,
	`DESCRIPTION` varchar(40) DEFAULT NULL,
	`ACTIVE` char(1) NOT NULL DEFAULT 'N',
	`SYNC_MANAGED_SYS` char(1) NOT NULL DEFAULT 'N',
	`GROUPING` varchar(100) DEFAULT NULL,
	`IS_BINARY` char(1) NOT NULL DEFAULT 'N',
	`IS_SENSITIVE` char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `NOTIFICATION_CONFIG` (
	`NOTIFICATION_CONFIG_ID` varchar(32) NOT NULL,
	`NAME` varchar(40) DEFAULT NULL,
	`SELECTION_PARAM_XML` text,
	`MSG_SUBJECT` varchar(100) DEFAULT NULL,
	`MSG_TEMPLATE_URL` varchar(100) DEFAULT NULL,
	`MSG_FROM` varchar(100) DEFAULT NULL,
	`MSG_BCC` varchar(100) DEFAULT NULL,
	PRIMARY KEY (`NOTIFICATION_CONFIG_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `OPENIAM_LOG` (
	`OPENIAM_LOG_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`USER_ID` varchar(32) COLLATE utf8_bin DEFAULT NULL,
	`PRINCIPAL` varchar(320) COLLATE utf8_bin DEFAULT NULL,
	`MANAGED_SYS_ID` varchar(32) COLLATE utf8_bin DEFAULT NULL,
	`CREATED_DATETIME` datetime DEFAULT NULL,
	`SOURCE` varchar(50) COLLATE utf8_bin DEFAULT NULL,
	`CLIENT_IP` varchar(50) COLLATE utf8_bin DEFAULT NULL,
	`NODE_ID` varchar(50) COLLATE utf8_bin DEFAULT NULL,
	`LOG_ACTION` varchar(50) COLLATE utf8_bin DEFAULT NULL,
	`RESULT` varchar(50) COLLATE utf8_bin DEFAULT NULL,
	`SESSION_ID` varchar(100) COLLATE utf8_bin DEFAULT NULL,
	`HASH` varchar(100) COLLATE utf8_bin NOT NULL,
	`CORRELATION_ID` varchar(32) COLLATE utf8_bin DEFAULT NULL,
	PRIMARY KEY (`OPENIAM_LOG_ID`),
	KEY `CREATED_DATETIME` (`CREATED_DATETIME`),
	KEY `LOG_ACTION` (`LOG_ACTION`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `OPENIAM_LOG_ATTRIBUTE` (
	`OPENIAM_LOG_ATTRIBUTE_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`OPENIAM_LOG_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
	`VALUE` text COLLATE utf8_bin,
	`CREATED_TIMESTAMP` mediumtext COLLATE utf8_bin,
	PRIMARY KEY (`OPENIAM_LOG_ATTRIBUTE_ID`),
	KEY `FK_LOG_ATTRIBUTE_LOG` (`OPENIAM_LOG_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `OPENIAM_LOG_LOG_MEMBERSHIP` (
	`OPENIAM_LOG_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`OPENIAM_MEMBER_LOG_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	KEY `OPENIAM_LOG_ID` (`OPENIAM_LOG_ID`),
	KEY `OPENIAM_MEMBER_LOG_ID` (`OPENIAM_MEMBER_LOG_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `OPENIAM_LOG_TARGET` (
	`OPENIAM_LOG_TARGET_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`OPENIAM_LOG_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`TARGET_ID` varchar(32) COLLATE utf8_bin DEFAULT NULL,
	`TARGET_TYPE` varchar(70) COLLATE utf8_bin DEFAULT NULL,
	`OBJECT_PRINCIPAL` varchar(255) COLLATE utf8_bin DEFAULT NULL,
	PRIMARY KEY (`OPENIAM_LOG_TARGET_ID`),
	KEY `FK_LOG_TARGET_LOG` (`OPENIAM_LOG_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `ORGANIZATION_TYPE` (
	`ORG_TYPE_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) NOT NULL,
	`DESCRIPTION` varchar(100) DEFAULT NULL,
	PRIMARY KEY (`ORG_TYPE_ID`),
	UNIQUE KEY `UNIQUE_ORG_TYPE` (`NAME`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `ORG_POLICY` (
	`ORG_POLICY_ID` varchar(32) NOT NULL,
	`NAME` varchar(40) DEFAULT NULL,
	`TARGET_AUDIENCE_TYPE` varchar(20) DEFAULT NULL,
	`TARGET_AUDIENCE` varchar(255) DEFAULT NULL,
	`START_DATE` date DEFAULT NULL,
	`END_DATE` date DEFAULT NULL,
	`POLICY_TEXT` text,
	PRIMARY KEY (`ORG_POLICY_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `ORG_POLICY_USER_LOG` (
	`ORG_POLICY_LOG_ID` varchar(32) NOT NULL,
	`ORG_POLICY_ID` varchar(32) NOT NULL,
	`USER_ID` varchar(32) NOT NULL,
	`TIME_STAMP` datetime NOT NULL,
	`RESPONSE` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`ORG_POLICY_LOG_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `POLICY` (
	`POLICY_ID` varchar(32) NOT NULL,
	`POLICY_DEF_ID` varchar(32) DEFAULT NULL,
	`NAME` varchar(60) DEFAULT NULL,
	`DESCRIPTION` varchar(255) DEFAULT NULL,
	`STATUS` int(11) DEFAULT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(20) DEFAULT NULL,
	`LAST_UPDATE` datetime DEFAULT NULL,
	`LAST_UPDATED_BY` varchar(20) DEFAULT NULL,
	`RULE_SRC_URL` varchar(80) DEFAULT NULL,
	`RULE_TEXT` text,
	`ENABLEMENT` int(11) DEFAULT '1',
	PRIMARY KEY (`POLICY_ID`),
	KEY `FK_POLICY_POLICY_DEF` (`POLICY_DEF_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `POLICY_DEF` (
	`POLICY_DEF_ID` varchar(32) NOT NULL,
	`NAME` varchar(60) DEFAULT NULL,
	`DESCRIPTION` varchar(255) DEFAULT NULL,
	`POLICY_TYPE` varchar(20) DEFAULT NULL,
	`LOCATION_TYPE` varchar(20) DEFAULT NULL,
	`POLICY_RULE` varchar(500) DEFAULT NULL,
	`POLICY_HANDLER` varchar(255) DEFAULT NULL,
	`POLICY_ADVISE_HANDLER` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`POLICY_DEF_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `POLICY_OBJECT_ASSOC` (
	`POLICY_OBJECT_ID` varchar(32) NOT NULL,
	`POLICY_ID` varchar(32) DEFAULT NULL,
	`ASSOCIATION_LEVEL` varchar(20) DEFAULT NULL,
	`ASSOCIATION_VALUE` varchar(255) DEFAULT NULL,
	`OBJECT_TYPE` varchar(100) DEFAULT NULL,
	`OBJECT_ID` varchar(32) DEFAULT NULL,
	`PARENT_ASSOC_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`POLICY_OBJECT_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `PRIVILEGE` (
	`PRIVILEGE_ID` varchar(32) NOT NULL,
	`RESOURCE_ID` varchar(32) NOT NULL,
	`ABBRV` varchar(3) NOT NULL,
	`DESCRIPTION` varchar(40) DEFAULT NULL,
	PRIMARY KEY (`PRIVILEGE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `PROVISION_CONNECTOR` (
	`CONNECTOR_ID` varchar(32) NOT NULL,
	`NAME` varchar(40) DEFAULT NULL,
	`METADATA_TYPE_ID` varchar(20) DEFAULT NULL,
	`STD_COMPLIANCE_LEVEL` varchar(20) DEFAULT NULL,
	`CLIENT_COMM_PROTOCOL` varchar(20) DEFAULT NULL,
	`SERVICE_URL` varchar(100) DEFAULT NULL,
	`SERVICE_NAMESPACE` varchar(100) DEFAULT NULL,
	`SERVICE_PORT` varchar(100) DEFAULT NULL,
	`SERVICE_WSDL` varchar(100) DEFAULT NULL,
	`CLASS_NAME` varchar(60) DEFAULT NULL,
	`HOST` varchar(60) DEFAULT NULL,
	`PORT` varchar(10) DEFAULT NULL,
	`CONNECTOR_INTERFACE` varchar(20) DEFAULT NULL,
	PRIMARY KEY (`CONNECTOR_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `PROV_REQUEST` (
	`REQUEST_ID` varchar(32) NOT NULL,
	`REQUESTOR_ID` varchar(100) DEFAULT NULL,
	`REQUEST_DATE` datetime DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT NULL,
	`STATUS_DATE` datetime DEFAULT NULL,
	`REQUEST_REASON` varchar(500) DEFAULT NULL,
	`REQUEST_TYPE` varchar(20) DEFAULT NULL,
	`CHANGE_ACCESS_BY` varchar(32) DEFAULT NULL,
	`REQUEST_XML` text,
	`NEW_ROLE_ID` varchar(32) DEFAULT NULL,
	`NEW_SERVICE_ID` varchar(20) DEFAULT NULL,
	`MANAGED_RESOURCE_ID` varchar(32) DEFAULT NULL,
	`REQUEST_FOR_ORG_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`REQUEST_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `RECONCILIATION_CONFIG` (
	`RECON_CONFIG_ID` varchar(32) NOT NULL,
	`RESOURCE_ID` varchar(32) DEFAULT NULL,
	`FREQUENCY` varchar(20) DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT 'ACTIVE',
	`CSV_LINE_SEPARATOR` varchar(10) DEFAULT 'comma',
	`CSV_END_OF_LINE` varchar(10) DEFAULT 'enter',
	`NOTIFICATION_EMAIL_ADDRESS` varchar(120) DEFAULT NULL,
	`TARGET_SYS_MATCH_SCRIPT` varchar(120) DEFAULT NULL,
	`MANUAL_RECONCILIATION_FLAG` char(1) NOT NULL DEFAULT 'N',
	`CUSTOM_IDENTITY_MATCH_SCRIPT` varchar(120) DEFAULT NULL,
	`MATCH_FIELD_NAME` varchar(40) DEFAULT NULL,
	`CUSTOM_MATCH_ATTR` varchar(40) DEFAULT NULL,
	`CUSTOM_MATCH_SRC_ATTR` varchar(40) DEFAULT NULL,
	`MANAGED_SYS_ID` varchar(32) DEFAULT NULL,
	`SEARCH_FILTER` varchar(200) DEFAULT NULL,
	`UPDATED_SINCE` datetime DEFAULT NULL,
	`TARGET_SYS_SEARCH_FILTER` varchar(200) DEFAULT NULL,
	`MATCH_SCRIPT` varchar(120) DEFAULT NULL,
	`EXEC_STATUS` varchar(20) DEFAULT NULL,
	`LAST_EXEC_TIME` datetime DEFAULT NULL,
	PRIMARY KEY (`RECON_CONFIG_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `RECON_RES_ATTR_MAP` (
	`RECON_RES_ATTR_MAP_ID` varchar(32) NOT NULL,
	`ATTR_POLICY_ID` varchar(32) DEFAULT NULL,
	`DEF_RECON_ATTR_MAP_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`RECON_RES_ATTR_MAP_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `RELATION_SET` (
	`RELATION_SET_ID` varchar(20) NOT NULL,
	`DESCRIPTION` varchar(80) DEFAULT NULL,
	PRIMARY KEY (`RELATION_SET_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `RELATION_TYPE` (
	`RELATION_TYPE_ID` varchar(20) NOT NULL,
	`DESCRIPTION` varchar(80) NOT NULL,
	PRIMARY KEY (`RELATION_TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `REPORT_INFO` (
	`REPORT_INFO_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`REPORT_NAME` varchar(64) COLLATE utf8_bin NOT NULL,
	`DATASOURCE_FILE_PATH` varchar(255) COLLATE utf8_bin NOT NULL,
	`REPORT_FILE_PATH` varchar(255) COLLATE utf8_bin DEFAULT NULL,
	`BUILT_IN` char(1) COLLATE utf8_bin NOT NULL DEFAULT 'N',
	PRIMARY KEY (`REPORT_INFO_ID`),
	UNIQUE KEY `REPORT_NAME` (`REPORT_NAME`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `REPORT_PARAMETER_METATYPE` (
	`PARAM_METATYPE_ID` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
	`PARAM_METATYPE_NAME` varchar(45) NOT NULL,
	`IS_MULTIPLE` char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`PARAM_METATYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `REPORT_PARAMETER_TYPE` (
	`RCPT_ID` varchar(100) COLLATE utf8_bin DEFAULT NULL,
	`TYPE_NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
	`TYPE_DESCRIPTION` varchar(100) COLLATE utf8_bin DEFAULT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `REPORT_SUBSCRIPTIONS` (
	`REPORT_SUB_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`REPORT_INFO_ID` varchar(45) COLLATE utf8_bin DEFAULT NULL,
	`REPORT_NAME` varchar(64) COLLATE utf8_bin NOT NULL,
	`DELIVERY_METHOD` varchar(45) COLLATE utf8_bin DEFAULT NULL,
	`DELIVERY_FORMAT` varchar(45) COLLATE utf8_bin DEFAULT NULL,
	`DELIVERY_AUDIENCE` varchar(45) COLLATE utf8_bin DEFAULT NULL,
	`STATUS` varchar(45) COLLATE utf8_bin DEFAULT NULL,
	`USERID` varchar(45) COLLATE utf8_bin DEFAULT NULL,
	PRIMARY KEY (`REPORT_SUB_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `REPORT_SUB_CRITERIA_PARAM` (
	`RSCP_ID` varchar(45) COLLATE utf8_bin NOT NULL,
	`RCP_ID` varchar(32) COLLATE utf8_bin DEFAULT NULL,
	`REPORT_SUB_ID` varchar(32) COLLATE utf8_bin DEFAULT NULL,
	`PARAM_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL,
	`PARAM_VALUE` varchar(64) COLLATE utf8_bin DEFAULT NULL,
	PRIMARY KEY (`RSCP_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `REQ_APPROVER` (
	`REQ_APPROVER_ID` varchar(32) NOT NULL,
	`APPROVER_ID` varchar(32) DEFAULT NULL,
	`APPROVER_TYPE` varchar(20) DEFAULT NULL,
	`APPROVER_LEVEL` int(11) DEFAULT NULL,
	`REQUEST_ID` varchar(32) DEFAULT NULL,
	`ACTION_DATE` datetime DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT NULL,
	`ACTION` varchar(20) DEFAULT NULL,
	`CMT` varchar(1000) DEFAULT NULL,
	`MANAGED_SYS_ID` varchar(32) DEFAULT NULL,
	`MNG_SYS_GROUP_ID` varchar(32) DEFAULT NULL,
	`ROLE_DOMAIN` varchar(20) DEFAULT NULL,
	PRIMARY KEY (`REQ_APPROVER_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `RESOURCE_TYPE` (
	`RESOURCE_TYPE_ID` varchar(32) NOT NULL,
	`DESCRIPTION` varchar(100) DEFAULT NULL,
	`PROVISION_RESOURCE` int(11) DEFAULT NULL,
	`PROCESS_NAME` varchar(80) DEFAULT NULL,
	`SUPPORTS_HIERARCHY` char(1) NOT NULL DEFAULT 'Y',
	`SEARCHABLE` char(1) DEFAULT 'Y',
	`URL` mediumtext,
	`IMAGE_TYPE` varchar(16) DEFAULT NULL,
	PRIMARY KEY (`RESOURCE_TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `SEQUENCE_GEN` (
	`ATTRIBUTE` varchar(32) NOT NULL,
	`NEXT_ID` int(11) DEFAULT NULL,
	PRIMARY KEY (`ATTRIBUTE`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `SERVICE` (
	`SERVICE_ID` varchar(20) NOT NULL,
	`SERVICE_NAME` varchar(40) DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT NULL,
	`LOCATION_IP_ADDRESS` varchar(80) DEFAULT NULL,
	`COMPANY_OWNER_ID` varchar(20) DEFAULT NULL,
	`START_DATE` datetime DEFAULT NULL,
	`END_DATE` datetime DEFAULT NULL,
	`LICENSE_KEY` varchar(255) DEFAULT NULL,
	`SERVICE_TYPE` varchar(20) DEFAULT NULL,
	`PARENT_SERVICE_ID` varchar(20) DEFAULT NULL,
	`ROOT_RESOURCE_ID` varchar(20) DEFAULT NULL,
	`ACCESS_CONTROL_MODEL` varchar(20) DEFAULT NULL,
	`PARAM1` varchar(20) DEFAULT NULL,
	`PARAM2` varchar(20) DEFAULT NULL,
	`PARAM3` varchar(20) DEFAULT NULL,
	`PARAM4` varchar(20) DEFAULT NULL,
	`PARAM5` varchar(20) DEFAULT NULL,
	PRIMARY KEY (`SERVICE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `STATUS` (
	`STATUS_CD` varchar(40) NOT NULL,
	`STATUS_TYPE` varchar(20) DEFAULT NULL,
	`DESCRIPTION` varchar(80) DEFAULT NULL,
	`CODE_GROUP` varchar(40) NOT NULL,
	`LANGUAGE_CD` varchar(2) NOT NULL,
	`COMPANY_OWNER_ID` varchar(32) NOT NULL,
	`SERVICE_ID` varchar(20) NOT NULL,
	`WEIGHT` int(11) DEFAULT NULL,
	PRIMARY KEY (`CODE_GROUP`,`STATUS_CD`,`LANGUAGE_CD`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `SYNCH_CONFIG` (
	`SYNCH_CONFIG_ID` varchar(32) NOT NULL,
	`NAME` varchar(60) DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT NULL,
	`SYNCH_SRC` varchar(20) DEFAULT NULL,
	`FILE_NAME` varchar(80) DEFAULT NULL,
	`SRC_LOGIN_ID` varchar(100) DEFAULT NULL,
	`SRC_PASSWORD` varchar(100) DEFAULT NULL,
	`SRC_HOST` varchar(100) DEFAULT NULL,
	`DRIVER` varchar(100) DEFAULT NULL,
	`CONNECTION_URL` varchar(100) DEFAULT NULL,
	`QUERY` varchar(1000) DEFAULT NULL,
	`QUERY_TIME_FIELD` varchar(50) DEFAULT NULL,
	`BASE_DN` varchar(50) DEFAULT NULL,
	`LAST_EXEC_TIME` datetime DEFAULT NULL,
	`LAST_REC_PROCESSED` varchar(32) DEFAULT NULL,
	`MANAGED_SYS_ID` varchar(32) DEFAULT NULL,
	`LOAD_MATCH_ONLY` int(11) DEFAULT '0',
	`UPDATE_ATTRIBUTE` int(11) DEFAULT '1',
	`SYNCH_FREQUENCY` varchar(20) DEFAULT NULL,
	`SYNCH_TYPE` varchar(20) DEFAULT NULL,
	`DELETE_RULE` varchar(80) DEFAULT NULL,
	`PROCESS_RULE` varchar(80) DEFAULT NULL,
	`VALIDATION_RULE` varchar(80) DEFAULT NULL,
	`TRANSFORMATION_RULE` varchar(80) DEFAULT NULL,
	`MATCH_FIELD_NAME` varchar(40) DEFAULT NULL,
	`MATCH_MANAGED_SYS_ID` varchar(32) DEFAULT NULL,
	`MATCH_SRC_FIELD_NAME` varchar(40) DEFAULT NULL,
	`CUSTOM_MATCH_RULE` varchar(100) DEFAULT NULL,
	`CUSTOM_ADAPTER_SCRIPT` varchar(100) DEFAULT NULL,
	`CUSTOM_MATCH_ATTR` varchar(40) DEFAULT NULL,
	`WS_URL` varchar(100) DEFAULT NULL,
	`WS_SCRIPT` varchar(100) DEFAULT NULL,
	`USE_POLICY_MAP` char(1) DEFAULT 'Y',
	`USE_TRANSFORM_SCRIPT` char(1) DEFAULT 'Y',
	`POLICY_MAP_BEFORE_TRANSFORM` char(1) DEFAULT 'Y',
	`USE_SYSTEM_PATH` char(1) DEFAULT 'N',
	`PRE_SYNC_SCRIPT` varchar(80) DEFAULT NULL,
	`POST_SYNC_SCRIPT` varchar(80) DEFAULT NULL,
	`COMPANY_ID` varchar(32) DEFAULT NULL,
	`ATTRIBUTE_NAMES_LOOKUP` varchar(120) DEFAULT NULL,
	`SEARCH_SCOPE` int(11) NOT NULL DEFAULT '2',
	PRIMARY KEY (`SYNCH_CONFIG_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `UI_TEMPLATE_TYPE` (
	`TEMPLATE_TYPE_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) NOT NULL,
	`DESCRIPTION` varchar(200) DEFAULT NULL,
	PRIMARY KEY (`TEMPLATE_TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `UI_THEME` (
	`UI_THEME_ID` varchar(32) NOT NULL,
	`UI_THEME_NAME` varchar(100) NOT NULL,
	`URL` varchar(300) NOT NULL,
	PRIMARY KEY (`UI_THEME_ID`),
	UNIQUE KEY `UI_THEME_NAME_UNIUE` (`UI_THEME_NAME`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `URI_PATTERN_META_TYPE` (
	`URI_PATTERN_META_TYPE_ID` varchar(32) NOT NULL,
	`METADATA_TYPE_NAME` varchar(100) NOT NULL,
	`SPRING_BEAN_NAME` varchar(100) NOT NULL,
	PRIMARY KEY (`URI_PATTERN_META_TYPE_ID`),
	UNIQUE KEY `META_SPRING_BEAN_UNIQUE` (`SPRING_BEAN_NAME`),
	UNIQUE KEY `URI_META_TYPE_NAME_UNIQUE` (`METADATA_TYPE_NAME`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `WEB_RESOURCE_ATTRIBUTE` (
	`ATTRIBUTE_MAP_ID` varchar(32) NOT NULL,
	`RESOURCE_ID` varchar(32) NOT NULL,
	`TARGET_ATTRIBUTE_NAME` varchar(100) NOT NULL,
	`AM_ATTRIBUTE_NAME` varchar(100) DEFAULT NULL,
	`AM_POLICY_URL` varchar(100) DEFAULT NULL,
	PRIMARY KEY (`ATTRIBUTE_MAP_ID`),
	UNIQUE KEY `RESOURCE_ID` (`RESOURCE_ID`,`TARGET_ATTRIBUTE_NAME`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `AUTH_ATTRIBUTE` (
	`AUTH_ATTRIBUTE_ID` varchar(32) NOT NULL,
	`ATTRIBUTE_NAME` varchar(100) NOT NULL,
	`PROVIDER_TYPE` varchar(32) NOT NULL,
	`DESCRIPTION` varchar(255) DEFAULT NULL,
	`REQUIRED` char(1) DEFAULT 'N',
	`DATA_TYPE` varchar(20) NOT NULL DEFAULT 'singleValue',
	`DEFAULT_VALUE` varchar(4096) DEFAULT NULL,
	PRIMARY KEY (`AUTH_ATTRIBUTE_ID`),
	UNIQUE KEY `IDX_ATTRIBUTE_PT` (`ATTRIBUTE_NAME`,`PROVIDER_TYPE`),
	KEY `FK_PROVIDER_TYPE_ATTRIBUTE` (`PROVIDER_TYPE`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `AUTH_ATTRIBUTE`
	ADD CONSTRAINT `FK_PROVIDER_TYPE_ATTRIBUTE` FOREIGN KEY (`PROVIDER_TYPE`) REFERENCES `AUTH_PROVIDER_TYPE` (`PROVIDER_TYPE`);

CREATE TABLE `AUTH_LEVEL_GROUPING` (
	`AUTH_LEVEL_GROUPING_ID` varchar(32) NOT NULL,
	`AUTH_LEVEL_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) NOT NULL,
	PRIMARY KEY (`AUTH_LEVEL_GROUPING_ID`),
	KEY `AUTH_LEVEL_GROUPING_FK` (`AUTH_LEVEL_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `AUTH_LEVEL_GROUPING`
	ADD CONSTRAINT `AUTH_LEVEL_GROUPING_FK` FOREIGN KEY (`AUTH_LEVEL_ID`) REFERENCES `AUTH_LEVEL` (`AUTH_LEVEL_ID`);

CREATE TABLE `CATEGORY_LANGUAGE` (
	`CATEGORY_ID` varchar(32) NOT NULL,
	`LANGUAGE_ID` varchar(32) NOT NULL,
	`CATEGORY_NAME` varchar(40) DEFAULT NULL,
	PRIMARY KEY (`CATEGORY_ID`,`LANGUAGE_ID`),
	KEY `FK_CATEGORY_LANGUAGE_LANGUAGE` (`LANGUAGE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `CATEGORY_LANGUAGE`
	ADD CONSTRAINT `FK_CATEGORY_LANGUAGE_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`CATEGORY_ID`) ON DELETE CASCADE,
	ADD CONSTRAINT `FK_CATEGORY_LANGUAGE_LANGUAGE` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `LANGUAGE` (`ID`);

CREATE TABLE `CATEGORY_TYPE` (
	`CATEGORY_ID` varchar(32) NOT NULL,
	`TYPE_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`TYPE_ID`,`CATEGORY_ID`),
	KEY `FK_CATEGORY_TYPE_CATEGORY` (`CATEGORY_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `CATEGORY_TYPE`
	ADD CONSTRAINT `FK_CATEGORY_METADATA_TYPE` FOREIGN KEY (`TYPE_ID`) REFERENCES `METADATA_TYPE` (`TYPE_ID`),
	ADD CONSTRAINT `FK_CATEGORY_TYPE_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`CATEGORY_ID`);

CREATE TABLE `EXCLUDE_WORD_LIST` (
	`WORD` varchar(30) NOT NULL,
	`LANGUAGE_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`WORD`,`LANGUAGE_ID`),
	KEY `FK_EXCLUDE_WORD_LIST_LANGUAGE` (`LANGUAGE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `EXCLUDE_WORD_LIST`
	ADD CONSTRAINT `FK_EXCLUDE_WORD_LIST_LANGUAGE` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `LANGUAGE` (`ID`);

CREATE TABLE `IDENTITY_QUESTION` (
	`IDENTITY_QUESTION_ID` varchar(32) NOT NULL,
	`IDENTITY_QUEST_GRP_ID` varchar(32) DEFAULT NULL,
	`ACTIVE` char(1) DEFAULT 'Y',
	PRIMARY KEY (`IDENTITY_QUESTION_ID`),
	KEY `ID_QU_IDEN_QUEST_GRP_FK` (`IDENTITY_QUEST_GRP_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `IDENTITY_QUESTION`
	ADD CONSTRAINT `ID_QU_IDEN_QUEST_GRP_FK` FOREIGN KEY (`IDENTITY_QUEST_GRP_ID`) REFERENCES `IDENTITY_QUEST_GRP` (`IDENTITY_QUEST_GRP_ID`);

CREATE TABLE `LANGUAGE_LOCALE` (
	`ID` varchar(32) NOT NULL,
	`LANGUAGE_ID` varchar(32) NOT NULL,
	`LOCALE` varchar(32) NOT NULL,
	UNIQUE KEY `LANGUAGE_LOCALE_UNIQUE` (`LOCALE`),
	KEY `LANGUAGE_LOCALE_LANGUAGE_FK` (`LANGUAGE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `LANGUAGE_LOCALE`
	ADD CONSTRAINT `LANGUAGE_LOCALE_LANGUAGE_FK` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `LANGUAGE` (`ID`);

CREATE TABLE `LANGUAGE_MAPPING` (
	`ID` varchar(32) NOT NULL,
	`LANGUAGE_ID` varchar(32) NOT NULL,
	`REFERENCE_ID` varchar(32) NOT NULL,
	`REFERENCE_TYPE` varchar(100) NOT NULL,
	`TEXT_VALUE` varchar(400) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE KEY `LANGUAGE_MAPPING_UNIQUE` (`LANGUAGE_ID`,`REFERENCE_ID`,`REFERENCE_TYPE`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `LANGUAGE_MAPPING`
	ADD CONSTRAINT `LANGUAGE_MAPPING_LANGUAGE_FK` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `LANGUAGE` (`ID`);

CREATE TABLE `MANAGED_SYS` (
	`MANAGED_SYS_ID` varchar(32) NOT NULL,
	`NAME` varchar(40) DEFAULT NULL,
	`DESCRIPTION` varchar(80) DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT NULL,
	`CONNECTOR_ID` varchar(32) DEFAULT NULL,
	`HOST_URL` varchar(80) DEFAULT NULL,
	`APPL_URL` varchar(80) DEFAULT NULL,
	`PORT` int(11) DEFAULT NULL,
	`COMM_PROTOCOL` varchar(20) DEFAULT NULL,
	`USER_ID` varchar(150) DEFAULT NULL,
	`PSWD` varchar(255) DEFAULT NULL,
	`START_DATE` date DEFAULT NULL,
	`END_DATE` date DEFAULT NULL,
	`RESOURCE_ID` varchar(32) DEFAULT NULL,
	`PRIMARY_REPOSITORY` int(11) DEFAULT NULL,
	`SECONDARY_REPOSITORY_ID` varchar(32) DEFAULT NULL,
	`ALWAYS_UPDATE_SECONDARY` int(11) DEFAULT NULL,
	`RES_DEPENDENCY` varchar(32) DEFAULT NULL,
	`ADD_HNDLR` varchar(100) DEFAULT NULL,
	`MODIFY_HNDLR` varchar(100) DEFAULT NULL,
	`DELETE_HNDLR` varchar(100) DEFAULT NULL,
	`SETPASS_HNDLR` varchar(100) DEFAULT NULL,
	`SUSPEND_HNDLR` varchar(100) DEFAULT NULL,
	`SEARCH_HNDLR` varchar(100) DEFAULT NULL,
	`LOOKUP_HNDLR` varchar(100) DEFAULT NULL,
	`TEST_CONNECTION_HNDLR` varchar(100) DEFAULT NULL,
	`RECONCILE_RESOURCE_HNDLR` varchar(100) DEFAULT NULL,
	`HNDLR_5` varchar(100) DEFAULT NULL,
	`DRIVER_URL` varchar(100) DEFAULT NULL,
	`CONNECTION_STRING` varchar(100) DEFAULT NULL,
	`ATTRIBUTE_NAMES_LOOKUP` varchar(120) DEFAULT NULL,
	`ATTRIBUTE_NAMES_HNDLR` varchar(100) DEFAULT NULL,
	`SEARCH_SCOPE` int(11) NOT NULL DEFAULT '2',
	`RESUME_HNDLR` varchar(100) DEFAULT NULL,
	PRIMARY KEY (`MANAGED_SYS_ID`),
	KEY `FK_MNG_SYS_PROV_CON` (`CONNECTOR_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `MANAGED_SYS`
	ADD CONSTRAINT `FK_MNG_SYS_PROV_CON` FOREIGN KEY (`CONNECTOR_ID`) REFERENCES `PROVISION_CONNECTOR` (`CONNECTOR_ID`);

CREATE TABLE `ORG_TYPE_VALID_MEMBERSHIP` (
	`ORG_TYPE_ID` varchar(32) NOT NULL,
	`MEMBER_ORG_TYPE_ID` varchar(32) NOT NULL,
	UNIQUE KEY `UNIQUE_USER_ORG_TYPE` (`ORG_TYPE_ID`,`MEMBER_ORG_TYPE_ID`),
	KEY `ORG_T_VAL_MEM_TARGET_FK` (`MEMBER_ORG_TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ORG_TYPE_VALID_MEMBERSHIP`
	ADD CONSTRAINT `ORG_T_VAL_MEM_SOURCE_FK` FOREIGN KEY (`ORG_TYPE_ID`) REFERENCES `ORGANIZATION_TYPE` (`ORG_TYPE_ID`),
	ADD CONSTRAINT `ORG_T_VAL_MEM_TARGET_FK` FOREIGN KEY (`MEMBER_ORG_TYPE_ID`) REFERENCES `ORGANIZATION_TYPE` (`ORG_TYPE_ID`);

CREATE TABLE `POLICY_DEF_PARAM` (
	`DEF_PARAM_ID` varchar(32) NOT NULL,
	`POLICY_DEF_ID` varchar(32) DEFAULT NULL,
	`NAME` varchar(60) DEFAULT NULL,
	`DESCRIPTION` varchar(255) DEFAULT NULL,
	`OPERATION` varchar(20) DEFAULT NULL,
	`VALUE1` varchar(255) DEFAULT NULL,
	`VALUE2` varchar(255) DEFAULT NULL,
	`REPEATS` int(11) DEFAULT NULL,
	`PARAM_GROUP` varchar(20) DEFAULT NULL,
	`HANDLER_LANGUAGE` varchar(20) DEFAULT NULL,
	`POLICY_PARAM_HANDLER` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`DEF_PARAM_ID`),
	KEY `FK_POLICY_DEF_PARAM_POLICY_DEF` (`POLICY_DEF_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `POLICY_DEF_PARAM`
	ADD CONSTRAINT `FK_POLICY_DEF_PARAM_POLICY_DEF` FOREIGN KEY (`POLICY_DEF_ID`) REFERENCES `POLICY_DEF` (`POLICY_DEF_ID`);

CREATE TABLE `RECONCILIATION_SITUATION` (
	`RECON_SITUATION_ID` varchar(32) NOT NULL,
	`RECON_CONFIG_ID` varchar(32) DEFAULT NULL,
	`SITUATION` varchar(40) DEFAULT NULL,
	`SITUATION_RESP` varchar(40) DEFAULT NULL,
	`SCRIPT` varchar(80) DEFAULT NULL,
	PRIMARY KEY (`RECON_SITUATION_ID`),
	KEY `RECON_SITUATION` (`RECON_CONFIG_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RECONCILIATION_SITUATION`
	ADD CONSTRAINT `RECON_SITUATION` FOREIGN KEY (`RECON_CONFIG_ID`) REFERENCES `RECONCILIATION_CONFIG` (`RECON_CONFIG_ID`);

CREATE TABLE `RELATIONSHIP` (
	`RELATIONSHIP_ID` varchar(20) NOT NULL,
	`RELATION_SET_ID` varchar(20) DEFAULT NULL,
	`ITEM_OBJ` varchar(20) DEFAULT NULL,
	`ITEM_ID` varchar(20) DEFAULT NULL,
	`RANK` int(11) DEFAULT NULL,
	`ACTIVE` bit(1) DEFAULT NULL,
	PRIMARY KEY (`RELATIONSHIP_ID`),
	KEY `FK_RELATIONSHIP_RELATION_SET` (`RELATION_SET_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RELATIONSHIP`
	ADD CONSTRAINT `FK_RELATIONSHIP_RELATION_SET` FOREIGN KEY (`RELATION_SET_ID`) REFERENCES `RELATION_SET` (`RELATION_SET_ID`);

CREATE TABLE `RELATION_CATEGORY` (
	`RELATION_SET_ID` varchar(20) NOT NULL,
	`CATEGORY_ID` varchar(20) NOT NULL,
	PRIMARY KEY (`RELATION_SET_ID`,`CATEGORY_ID`),
	KEY `FK_RELATION_CATEGORY_CATEGORY` (`CATEGORY_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RELATION_CATEGORY`
	ADD CONSTRAINT `FK_RELATION_CATEGORY_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`CATEGORY_ID`),
	ADD CONSTRAINT `REL_CAT_REL_SET_FK` FOREIGN KEY (`RELATION_SET_ID`) REFERENCES `RELATION_SET` (`RELATION_SET_ID`);

CREATE TABLE `RELATION_SOURCE` (
	`RELATION_TYPE_ID` varchar(20) NOT NULL,
	`SOURCE_OBJ` varchar(20) NOT NULL,
	`SOURCE_ID` varchar(20) NOT NULL,
	`RELATION_SET_ID` varchar(20) DEFAULT NULL,
	PRIMARY KEY (`RELATION_TYPE_ID`,`SOURCE_OBJ`,`SOURCE_ID`),
	KEY `FK_RELATION_SOURCE_RELATION_SET` (`RELATION_SET_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RELATION_SOURCE`
	ADD CONSTRAINT `FK_RELATION_SOURCE_RELATION_SET` FOREIGN KEY (`RELATION_SET_ID`) REFERENCES `RELATION_SET` (`RELATION_SET_ID`),
	ADD CONSTRAINT `FK_RELATION_SOURCE_RELATION_TYPE` FOREIGN KEY (`RELATION_TYPE_ID`) REFERENCES `RELATION_TYPE` (`RELATION_TYPE_ID`);

CREATE TABLE `REPORT_CRITERIA_PARAMETER` (
	`RCP_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`REPORT_INFO_ID` varchar(32) COLLATE utf8_bin NOT NULL,
	`PARAM_NAME` varchar(64) COLLATE utf8_bin NOT NULL,
	`PARAM_VALUE` varchar(64) COLLATE utf8_bin DEFAULT NULL,
	`RCPT_ID` varchar(100) COLLATE utf8_bin DEFAULT NULL,
	`PARAM_META_TYPE_ID` varchar(32) COLLATE utf8_bin DEFAULT NULL,
	`IS_MULTIPLE` char(1) COLLATE utf8_bin NOT NULL DEFAULT 'N',
	`IS_REQUIRED` char(1) COLLATE utf8_bin NOT NULL DEFAULT 'N',
	`CAPTION` varchar(100) COLLATE utf8_bin NOT NULL,
	PRIMARY KEY (`RCP_ID`),
	KEY `RCP_PARAM_META_TYPE_FK` (`PARAM_META_TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `REPORT_CRITERIA_PARAMETER`
	ADD CONSTRAINT `RCP_PARAM_META_TYPE_FK` FOREIGN KEY (`PARAM_META_TYPE_ID`) REFERENCES `REPORT_PARAMETER_METATYPE` (`PARAM_METATYPE_ID`);

CREATE TABLE `REQUEST_ATTACHMENT` (
	`REQUEST_ATTACHMENT_ID` varchar(32) NOT NULL,
	`NAME` varchar(20) DEFAULT NULL,
	`ATTACHMENT` varchar(20) DEFAULT NULL,
	`USER_ID` varchar(32) DEFAULT NULL,
	`ATTACHMENT_DATE` datetime DEFAULT NULL,
	`REQUEST_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`REQUEST_ATTACHMENT_ID`),
	KEY `RefPROV_REQUEST1001` (`REQUEST_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `REQUEST_ATTACHMENT`
	ADD CONSTRAINT `RefPROV_REQUEST1001` FOREIGN KEY (`REQUEST_ID`) REFERENCES `PROV_REQUEST` (`REQUEST_ID`);

CREATE TABLE `REQUEST_ATTRIBUTE` (
	`REQUEST_ATTR_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) DEFAULT NULL,
	`VALUE` varchar(4096) DEFAULT NULL,
	`METADATA_ID` varchar(32) DEFAULT NULL,
	`REQUEST_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`REQUEST_ATTR_ID`),
	KEY `RefPROV_REQUEST1011` (`REQUEST_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `REQUEST_ATTRIBUTE`
	ADD CONSTRAINT `RefPROV_REQUEST1011` FOREIGN KEY (`REQUEST_ID`) REFERENCES `PROV_REQUEST` (`REQUEST_ID`);

CREATE TABLE `REQUEST_USER` (
	`REQ_USER_ID` varchar(32) NOT NULL,
	`USER_ID` varchar(32) DEFAULT NULL,
	`FIRST_NAME` varchar(20) DEFAULT NULL,
	`LAST_NAME` varchar(20) DEFAULT NULL,
	`MIDDLE_INIT` varchar(20) DEFAULT NULL,
	`DEPT_CD` varchar(20) DEFAULT NULL,
	`DIVISION` varchar(20) DEFAULT NULL,
	`LOCATION_CD` varchar(20) DEFAULT NULL,
	`AFFILIATION` varchar(20) DEFAULT NULL,
	`REQUEST_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`REQ_USER_ID`),
	KEY `RefPROV_REQUEST931` (`REQUEST_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `REQUEST_USER`
	ADD CONSTRAINT `RefPROV_REQUEST931` FOREIGN KEY (`REQUEST_ID`) REFERENCES `PROV_REQUEST` (`REQUEST_ID`);

CREATE TABLE `RES` (
	`RESOURCE_ID` varchar(32) NOT NULL,
	`RESOURCE_TYPE_ID` varchar(32) NOT NULL,
	`DESCRIPTION` varchar(100) DEFAULT NULL,
	`NAME` varchar(150) NOT NULL,
	`DISPLAY_ORDER` int(11) DEFAULT '1',
	`URL` varchar(255) DEFAULT NULL,
	`MIN_AUTH_LEVEL` varchar(32) DEFAULT NULL,
	`IS_PUBLIC` char(1) DEFAULT 'Y',
	`ADMIN_RESOURCE_ID` varchar(32) DEFAULT NULL,
	`RISK` varchar(10) DEFAULT NULL,
	`TYPE_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`RESOURCE_ID`),
	UNIQUE KEY `NAME` (`NAME`),
	KEY `FK_RESOURCE_RESOURCE_TYPE` (`RESOURCE_TYPE_ID`),
	KEY `RES_ADMIN_RES_FK` (`ADMIN_RESOURCE_ID`),
	KEY `RES_TYPE_FK` (`TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RES`
	ADD CONSTRAINT `FK_RESOURCE_RESOURCE_TYPE` FOREIGN KEY (`RESOURCE_TYPE_ID`) REFERENCES `RESOURCE_TYPE` (`RESOURCE_TYPE_ID`),
	ADD CONSTRAINT `RES_ADMIN_RES_FK` FOREIGN KEY (`ADMIN_RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `RES_TYPE_FK` FOREIGN KEY (`TYPE_ID`) REFERENCES `METADATA_TYPE` (`TYPE_ID`);

CREATE TABLE `SERVICE_CONFIG` (
	`SERVICE_CONFIG_ID` varchar(20) NOT NULL,
	`SERVICE_ID` varchar(20) DEFAULT NULL,
	`NAME` varchar(40) DEFAULT NULL,
	`VALUE` varchar(40) DEFAULT NULL,
	PRIMARY KEY (`SERVICE_CONFIG_ID`),
	KEY `FK_SRV_SRV_CONF` (`SERVICE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `SERVICE_CONFIG`
	ADD CONSTRAINT `FK_SRV_SRV_CONF` FOREIGN KEY (`SERVICE_ID`) REFERENCES `SERVICE` (`SERVICE_ID`);

CREATE TABLE `SYNCH_CONFIG_DATA_MAPPING` (
	`MAPPING_ID` varchar(32) NOT NULL,
	`SYNCH_CONFIG_ID` varchar(32) DEFAULT NULL,
	`IDM_FIELD_NAME` varchar(40) DEFAULT NULL,
	`SRC_FIELD_NAME` varchar(40) DEFAULT NULL,
	`MULTIVALUED` int(11) DEFAULT NULL,
	PRIMARY KEY (`MAPPING_ID`),
	KEY `SYNCH_DATA_MAP` (`SYNCH_CONFIG_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `SYNCH_CONFIG_DATA_MAPPING`
	ADD CONSTRAINT `SYNCH_DATA_MAP` FOREIGN KEY (`SYNCH_CONFIG_ID`) REFERENCES `SYNCH_CONFIG` (`SYNCH_CONFIG_ID`);

CREATE TABLE `UI_TEMPLATE_FIELDS` (
	`UI_FIELD_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) NOT NULL,
	`DESCRIPTION` varchar(200) DEFAULT NULL,
	`TEMPLATE_TYPE_ID` varchar(32) NOT NULL,
	`IS_REQUIRED` char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`UI_FIELD_ID`),
	KEY `TEMPLATE_TYPE_UI_TEMPL_FK` (`TEMPLATE_TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `UI_TEMPLATE_FIELDS`
	ADD CONSTRAINT `TEMPLATE_TYPE_UI_TEMPL_FK` FOREIGN KEY (`TEMPLATE_TYPE_ID`) REFERENCES `UI_TEMPLATE_TYPE` (`TEMPLATE_TYPE_ID`);

CREATE TABLE `USERS` (
	`USER_ID` varchar(32) NOT NULL,
	`FIRST_NAME` varchar(50) DEFAULT NULL,
	`LAST_NAME` varchar(50) DEFAULT NULL,
	`MIDDLE_INIT` varchar(50) DEFAULT NULL,
	`TYPE_ID` varchar(20) DEFAULT NULL,
	`CLASSIFICATION` varchar(20) DEFAULT NULL,
	`TITLE` varchar(100) DEFAULT NULL,
	`MAIL_CODE` varchar(50) DEFAULT NULL,
	`COST_CENTER` varchar(20) DEFAULT NULL,
	`STATUS` varchar(40) DEFAULT NULL,
	`SECONDARY_STATUS` varchar(40) DEFAULT NULL,
	`BIRTHDATE` datetime DEFAULT NULL,
	`SEX` char(1) DEFAULT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(40) DEFAULT NULL,
	`LAST_UPDATE` datetime DEFAULT NULL,
	`LAST_UPDATED_BY` varchar(40) DEFAULT NULL,
	`PREFIX` varchar(4) DEFAULT NULL,
	`SUFFIX` varchar(20) DEFAULT NULL,
	`USER_TYPE_IND` varchar(20) DEFAULT NULL,
	`EMPLOYEE_ID` varchar(32) DEFAULT NULL,
	`EMPLOYEE_TYPE` varchar(32) DEFAULT NULL,
	`LOCATION_CD` varchar(50) DEFAULT NULL,
	`LOCATION_NAME` varchar(100) DEFAULT NULL,
	`COMPANY_OWNER_ID` varchar(32) DEFAULT NULL,
	`JOB_CODE` varchar(32) DEFAULT NULL,
	`ALTERNATE_ID` varchar(32) DEFAULT NULL,
	`START_DATE` date DEFAULT NULL,
	`LAST_DATE` date DEFAULT NULL,
	`MAIDEN_NAME` varchar(40) DEFAULT NULL,
	`NICKNAME` varchar(40) DEFAULT NULL,
	`PASSWORD_THEME` varchar(20) DEFAULT NULL,
	`SHOW_IN_SEARCH` int(11) DEFAULT NULL,
	`USER_OWNER_ID` varchar(32) DEFAULT NULL,
	`DATE_PASSWORD_CHANGED` datetime DEFAULT NULL,
	`DATE_CHALLENGE_RESP_CHANGED` datetime DEFAULT NULL,
	`SYSTEM_FLAG` varchar(1) DEFAULT NULL,
	`DATE_IT_POLICY_APPROVED` timestamp NULL DEFAULT NULL,
	PRIMARY KEY (`USER_ID`),
	KEY `FK_USERS_METADATA_TYPE` (`TYPE_ID`),
	KEY `LAST_NAME` (`LAST_NAME`),
	KEY `USER_EMPLOYEE_INDX` (`EMPLOYEE_ID`),
	KEY `FK_JOB_CODE_METADATA_TYPE` (`JOB_CODE`),
	KEY `FK_EMPLOYEE_TYPE_METADATA_TYPE` (`EMPLOYEE_TYPE`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USERS`
	ADD CONSTRAINT `FK_EMPLOYEE_TYPE_METADATA_TYPE` FOREIGN KEY (`EMPLOYEE_TYPE`) REFERENCES `METADATA_TYPE` (`TYPE_ID`),
	ADD CONSTRAINT `FK_JOB_CODE_METADATA_TYPE` FOREIGN KEY (`JOB_CODE`) REFERENCES `METADATA_TYPE` (`TYPE_ID`),
	ADD CONSTRAINT `FK_USERS_METADATA_TYPE` FOREIGN KEY (`TYPE_ID`) REFERENCES `METADATA_TYPE` (`TYPE_ID`);

DELIMITER ;;

CREATE TRIGGER ON_USER_INSERT 
BEFORE 
INSERT ON USERS 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.LAST_UPDATE = NOW();
	END ;;

CREATE TRIGGER ON_USER_UPDATE
BEFORE 
UPDATE ON USERS 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_UPDATE = NOW();
	END ;;

DELIMITER ;

CREATE TABLE `ADDRESS` (
	`ADDRESS_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) DEFAULT NULL,
	`COUNTRY` varchar(100) DEFAULT NULL,
	`BLDG_NUM` varchar(100) DEFAULT NULL,
	`STREET_DIRECTION` varchar(20) DEFAULT NULL,
	`SUITE` varchar(20) DEFAULT NULL,
	`ADDRESS1` varchar(45) DEFAULT NULL,
	`ADDRESS2` varchar(45) DEFAULT NULL,
	`ADDRESS3` varchar(45) DEFAULT NULL,
	`ADDRESS4` varchar(45) DEFAULT NULL,
	`ADDRESS5` varchar(45) DEFAULT NULL,
	`ADDRESS6` varchar(45) DEFAULT NULL,
	`ADDRESS7` varchar(45) DEFAULT NULL,
	`CITY` varchar(100) DEFAULT NULL,
	`STATE` varchar(100) DEFAULT NULL,
	`POSTAL_CD` varchar(100) DEFAULT NULL,
	`IS_DEFAULT` char(1) DEFAULT 'N',
	`DESCRIPTION` varchar(100) DEFAULT NULL,
	`ACTIVE` char(1) DEFAULT 'Y',
	`PARENT_ID` varchar(32) DEFAULT NULL,
	`LAST_UPDATE` timestamp NULL DEFAULT NULL,
	`CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`TYPE_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`ADDRESS_ID`),
	KEY `ADDRESS_USER_FK` (`PARENT_ID`),
	KEY `ADDRESS_TYPE_FK` (`TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ADDRESS`
	ADD CONSTRAINT `ADDRESS_TYPE_FK` FOREIGN KEY (`TYPE_ID`) REFERENCES `METADATA_TYPE` (`TYPE_ID`),
	ADD CONSTRAINT `ADDRESS_USER_FK` FOREIGN KEY (`PARENT_ID`) REFERENCES `USERS` (`USER_ID`);

DELIMITER ;;

CREATE TRIGGER ON_ADDRESS_INSERT 
BEFORE 
INSERT ON ADDRESS 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.LAST_UPDATE = NOW();
	END ;;

CREATE TRIGGER ON_ADDRESS_UPDATE
BEFORE 
UPDATE ON ADDRESS 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_UPDATE = NOW();
	END ;;

DELIMITER ;

CREATE TABLE `AUTH_LEVEL_ATTRIBUTE` (
	`AUTH_LEVEL_ATTRIBUTE_ID` varchar(32) NOT NULL,
	`AUTH_LEVEL_GROUPING_ID` varchar(32) NOT NULL,
	`TYPE_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) NOT NULL,
	`VALUE_AS_BYTE_ARRAY` blob,
	`VALUE_AS_STRING` varchar(4096) DEFAULT NULL,
	PRIMARY KEY (`AUTH_LEVEL_ATTRIBUTE_ID`),
	KEY `AUTH_LEVEL_ATTR_GRP_FK` (`AUTH_LEVEL_GROUPING_ID`),
	KEY `AUTH_LEVEL_ATTR_TYPE_FK` (`TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `AUTH_LEVEL_ATTRIBUTE`
	ADD CONSTRAINT `AUTH_LEVEL_ATTR_GRP_FK` FOREIGN KEY (`AUTH_LEVEL_GROUPING_ID`) REFERENCES `AUTH_LEVEL_GROUPING` (`AUTH_LEVEL_GROUPING_ID`),
	ADD CONSTRAINT `AUTH_LEVEL_ATTR_TYPE_FK` FOREIGN KEY (`TYPE_ID`) REFERENCES `METADATA_TYPE` (`TYPE_ID`);

CREATE TABLE `AUTH_PROVIDER` (
	`PROVIDER_ID` varchar(32) NOT NULL,
	`PROVIDER_TYPE` varchar(32) NOT NULL,
	`MANAGED_SYS_ID` varchar(32) NOT NULL,
	`RESOURCE_ID` varchar(32) NOT NULL,
	`NAME` varchar(50) NOT NULL,
	`DESCRIPTION` varchar(255) DEFAULT NULL,
	`SIGN_REQUEST` char(1) NOT NULL DEFAULT 'N',
	`PUBLIC_KEY` blob,
	`PRIVATE_KEY` blob,
	PRIMARY KEY (`PROVIDER_ID`),
	KEY `FK_PROVIDER_TYPE_PROVIDER` (`PROVIDER_TYPE`),
	KEY `FK_MNG_AUTH_PROVIDER` (`MANAGED_SYS_ID`),
	KEY `FK_RES_AUTH_PROVIDER` (`RESOURCE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `AUTH_PROVIDER`
	ADD CONSTRAINT `FK_MNG_AUTH_PROVIDER` FOREIGN KEY (`MANAGED_SYS_ID`) REFERENCES `MANAGED_SYS` (`MANAGED_SYS_ID`),
	ADD CONSTRAINT `FK_PROVIDER_TYPE_PROVIDER` FOREIGN KEY (`PROVIDER_TYPE`) REFERENCES `AUTH_PROVIDER_TYPE` (`PROVIDER_TYPE`),
	ADD CONSTRAINT `FK_RES_AUTH_PROVIDER` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`);

CREATE TABLE `AUTH_STATE` (
	`USER_ID` varchar(32) NOT NULL,
	`AUTH_STATE` decimal(5,1) DEFAULT NULL,
	`TOKEN` varchar(2000) DEFAULT NULL,
	`AA` varchar(20) DEFAULT NULL,
	`EXPIRATION` decimal(18,0) DEFAULT NULL,
	`LAST_LOGIN` datetime DEFAULT NULL,
	`IP_ADDRESS` varchar(20) DEFAULT NULL,
	PRIMARY KEY (`USER_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `AUTH_STATE`
	ADD CONSTRAINT `FK_AUTH_STATE_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `COMPANY` (
	`COMPANY_ID` varchar(32) NOT NULL,
	`COMPANY_NAME` varchar(200) DEFAULT NULL,
	`LST_UPDATE` datetime DEFAULT NULL,
	`LST_UPDATED_BY` varchar(40) DEFAULT NULL,
	`PARENT_ID` varchar(32) DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(40) DEFAULT NULL,
	`ALIAS` varchar(200) DEFAULT NULL,
	`DESCRIPTION` varchar(200) DEFAULT NULL,
	`DOMAIN_NAME` varchar(250) DEFAULT NULL,
	`LDAP_STR` varchar(255) DEFAULT NULL,
	`CLASSIFICATION` varchar(40) DEFAULT NULL,
	`INTERNAL_COMPANY_ID` varchar(200) DEFAULT NULL,
	`ABBREVIATION` varchar(20) DEFAULT NULL,
	`SYMBOL` varchar(10) DEFAULT NULL,
	`ORG_TYPE_ID` varchar(32) DEFAULT NULL,
	`ADMIN_RESOURCE_ID` varchar(32) DEFAULT NULL,
	`IS_SELECTABLE` char(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (`COMPANY_ID`),
	KEY `COMPANY_ORG_TYPE_FK` (`ORG_TYPE_ID`),
	KEY `COMPANY_ADMIN_RES_FK` (`ADMIN_RESOURCE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `COMPANY`
	ADD CONSTRAINT `COMPANY_ADMIN_RES_FK` FOREIGN KEY (`ADMIN_RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `COMPANY_ORG_TYPE_FK` FOREIGN KEY (`ORG_TYPE_ID`) REFERENCES `ORGANIZATION_TYPE` (`ORG_TYPE_ID`);

CREATE TABLE `CONTENT_PROVIDER` (
	`CONTENT_PROVIDER_ID` varchar(32) NOT NULL,
	`CONTENT_PROVIDER_NAME` varchar(100) NOT NULL,
	`IS_PUBLIC` char(1) NOT NULL DEFAULT 'N',
	`DOMAIN_PATTERN` varchar(100) NOT NULL,
	`IS_SSL` char(1) DEFAULT NULL,
	`RESOURCE_ID` varchar(32) NOT NULL,
	`MANAGED_SYS_ID` varchar(32) NOT NULL,
	`UI_THEME_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`CONTENT_PROVIDER_ID`),
	UNIQUE KEY `UNIQUE_CP_NAME` (`CONTENT_PROVIDER_NAME`),
	UNIQUE KEY `UNIQUE_CP_PATTERN` (`DOMAIN_PATTERN`,`IS_SSL`),
	KEY `CP_RES_FK` (`RESOURCE_ID`),
	KEY `FK_CP_MANAGED_SYS` (`MANAGED_SYS_ID`),
	KEY `CP_UI_THEME` (`UI_THEME_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `CONTENT_PROVIDER`
	ADD CONSTRAINT `CP_RES_FK` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `CP_UI_THEME` FOREIGN KEY (`UI_THEME_ID`) REFERENCES `UI_THEME` (`UI_THEME_ID`),
	ADD CONSTRAINT `FK_CP_MANAGED_SYS` FOREIGN KEY (`MANAGED_SYS_ID`) REFERENCES `MANAGED_SYS` (`MANAGED_SYS_ID`);

CREATE TABLE `CREDENTIALS` (
	`USER_ID` varchar(32) NOT NULL,
	`CREDENTIAL_TYPE` varchar(20) NOT NULL,
	`VALUE` varchar(100) DEFAULT NULL,
	`IS_PUBLIC` bit(1) DEFAULT NULL,
	PRIMARY KEY (`USER_ID`,`CREDENTIAL_TYPE`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `CREDENTIALS`
	ADD CONSTRAINT `FK_CREDENTIALS_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `EMAIL_ADDRESS` (
	`EMAIL_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) DEFAULT NULL,
	`DESCRIPTION` varchar(100) DEFAULT NULL,
	`EMAIL_ADDRESS` varchar(320) DEFAULT NULL,
	`IS_DEFAULT` char(1) DEFAULT 'N',
	`ACTIVE` char(1) DEFAULT 'Y',
	`PARENT_ID` varchar(32) DEFAULT NULL,
	`LAST_UPDATE` timestamp NULL DEFAULT NULL,
	`CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`TYPE_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`EMAIL_ID`),
	KEY `EMAIL_ADDRESS_USER_FK` (`PARENT_ID`),
	KEY `EMAIL_ADDRESS_TYPE_FK` (`TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `EMAIL_ADDRESS`
	ADD CONSTRAINT `EMAIL_ADDRESS_TYPE_FK` FOREIGN KEY (`TYPE_ID`) REFERENCES `METADATA_TYPE` (`TYPE_ID`),
	ADD CONSTRAINT `EMAIL_ADDRESS_USER_FK` FOREIGN KEY (`PARENT_ID`) REFERENCES `USERS` (`USER_ID`);

DELIMITER ;;

CREATE TRIGGER ON_EMAIL_INSERT 
BEFORE 
INSERT ON EMAIL_ADDRESS 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.LAST_UPDATE = NOW();
	END ;;

CREATE TRIGGER ON_EMAIL_UPDATE
BEFORE 
UPDATE ON EMAIL_ADDRESS 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_UPDATE = NOW();
	END ;;

DELIMITER ;

CREATE TABLE `LOGIN` (
	`LOGIN` varchar(320) CHARACTER SET latin1 NOT NULL,
	`MANAGED_SYS_ID` varchar(32) NOT NULL,
	`IDENTITY_TYPE` varchar(20) DEFAULT NULL,
	`CANONICAL_NAME` varchar(100) DEFAULT NULL,
	`USER_ID` varchar(32) DEFAULT NULL,
	`PASSWORD` varchar(255) DEFAULT NULL,
	`PWD_EQUIVALENT_TOKEN` varchar(255) DEFAULT NULL,
	`PWD_CHANGED` datetime DEFAULT NULL,
	`PWD_EXP` datetime DEFAULT NULL,
	`RESET_PWD` int(11) NOT NULL DEFAULT '0',
	`FIRST_TIME_LOGIN` int(11) NOT NULL DEFAULT '1',
	`IS_LOCKED` int(11) NOT NULL DEFAULT '0',
	`STATUS` varchar(20) DEFAULT NULL,
	`GRACE_PERIOD` datetime DEFAULT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(32) DEFAULT NULL,
	`CURRENT_LOGIN_HOST` varchar(40) DEFAULT NULL,
	`AUTH_FAIL_COUNT` int(11) NOT NULL DEFAULT '0',
	`LAST_AUTH_ATTEMPT` datetime DEFAULT NULL,
	`LAST_LOGIN` datetime DEFAULT NULL,
	`LAST_LOGIN_IP` varchar(60) DEFAULT NULL,
	`PREV_LOGIN` datetime DEFAULT NULL,
	`PREV_LOGIN_IP` varchar(60) DEFAULT NULL,
	`IS_DEFAULT` int(11) DEFAULT '0',
	`PWD_CHANGE_COUNT` int(11) DEFAULT '0',
	`PSWD_RESET_TOKEN` varchar(80) DEFAULT NULL,
	`PSWD_RESET_TOKEN_EXP` datetime DEFAULT NULL,
	`LOGIN_ID` varchar(32) NOT NULL DEFAULT '',
	`LAST_UPDATE` timestamp NULL DEFAULT NULL,
	`LOWERCASE_LOGIN` varchar(320) NOT NULL,
	PRIMARY KEY (`LOGIN_ID`),
	UNIQUE KEY `UNIQUE_LOGIN` (`LOGIN`,`MANAGED_SYS_ID`),
	KEY `login_user_indx` (`USER_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `LOGIN`
	ADD CONSTRAINT `FK_LOGIN_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

DELIMITER ;;

CREATE TRIGGER ON_LOGIN_INSERT 
BEFORE 
INSERT ON LOGIN 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.LAST_UPDATE = NOW();
	END ;;

CREATE TRIGGER ON_LOGIN_UPDATE
BEFORE 
UPDATE ON LOGIN 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_UPDATE = NOW();
	END ;;

DELIMITER ;

CREATE TABLE `MANAGED_SYS_ATTRIBUTE` (
	`MNG_SYS_ATTR_ID` varchar(32) NOT NULL,
	`NAME` varchar(60) DEFAULT NULL,
	`VALUE1` varchar(255) DEFAULT NULL,
	`VALUE2` varchar(255) DEFAULT NULL,
	`MANAGED_SYS_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`MNG_SYS_ATTR_ID`),
	KEY `FK_MNG_MNG_ATTR` (`MANAGED_SYS_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `MANAGED_SYS_ATTRIBUTE`
	ADD CONSTRAINT `FK_MNG_MNG_ATTR` FOREIGN KEY (`MANAGED_SYS_ID`) REFERENCES `MANAGED_SYS` (`MANAGED_SYS_ID`);

CREATE TABLE `METADATA_ELEMENT_PAGE_TEMPLATE` (
	`ID` varchar(32) NOT NULL,
	`NAME` varchar(40) NOT NULL,
	`RESOURCE_ID` varchar(32) NOT NULL,
	`IS_PUBLIC` char(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE KEY `PAGE_TEMPLATE_UNIQUE` (`NAME`),
	KEY `METADATA_PAGE_TEMPLATE_RES_FK` (`RESOURCE_ID`),
	KEY `TEMPLATE_TYPE_FK` (`TEMPLATE_TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `METADATA_ELEMENT_PAGE_TEMPLATE`
	ADD CONSTRAINT `METADATA_PAGE_TEMPLATE_RES_FK` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `TEMPLATE_TYPE_FK` FOREIGN KEY (`TEMPLATE_TYPE_ID`) REFERENCES `UI_TEMPLATE_TYPE` (`TEMPLATE_TYPE_ID`);

CREATE TABLE `MNG_SYS_GROUP` (
	`MNG_SYS_GROUP_ID` varchar(32) NOT NULL,
	`MANAGED_SYS_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`MANAGED_SYS_ID`,`MNG_SYS_GROUP_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `MNG_SYS_GROUP`
	ADD CONSTRAINT `Refmanaged_sys831` FOREIGN KEY (`MANAGED_SYS_ID`) REFERENCES `MANAGED_SYS` (`MANAGED_SYS_ID`);

CREATE TABLE `MNG_SYS_LIST` (
	`MANAGED_SYS_ID` varchar(32) NOT NULL,
	`REQUEST_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`MANAGED_SYS_ID`,`REQUEST_ID`),
	KEY `RefPROV_REQUEST951` (`REQUEST_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `MNG_SYS_LIST`
	ADD CONSTRAINT `RefPROV_REQUEST951` FOREIGN KEY (`REQUEST_ID`) REFERENCES `PROV_REQUEST` (`REQUEST_ID`),
	ADD CONSTRAINT `Refmanaged_sys941` FOREIGN KEY (`MANAGED_SYS_ID`) REFERENCES `MANAGED_SYS` (`MANAGED_SYS_ID`);

CREATE TABLE `MNG_SYS_OBJECT_MATCH` (
	`OBJECT_SEARCH_ID` varchar(32) NOT NULL,
	`MANAGED_SYS_ID` varchar(32) NOT NULL,
	`OBJECT_TYPE` varchar(20) DEFAULT 'USER',
	`MATCH_METHOD` varchar(20) DEFAULT 'BASE_DN',
	`BASE_DN` varchar(200) DEFAULT NULL,
	`SEARCH_BASE_DN` varchar(200) DEFAULT NULL,
	`SEARCH_FILTER` varchar(1000) DEFAULT NULL,
	`KEY_FIELD` varchar(40) DEFAULT NULL,
	PRIMARY KEY (`OBJECT_SEARCH_ID`),
	KEY `FK_MNG_SYS_OBJ_MATC` (`MANAGED_SYS_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `MNG_SYS_OBJECT_MATCH`
	ADD CONSTRAINT `FK_MNG_SYS_OBJ_MATC` FOREIGN KEY (`MANAGED_SYS_ID`) REFERENCES `MANAGED_SYS` (`MANAGED_SYS_ID`);

CREATE TABLE `ORG_STRUCTURE` (
	`SUPERVISOR_ID` varchar(32) NOT NULL,
	`STAFF_ID` varchar(32) NOT NULL,
	`IS_PRIMARY_SUPER` varchar(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`SUPERVISOR_ID`,`STAFF_ID`),
	KEY `FK_SUPR_USER` (`SUPERVISOR_ID`),
	KEY `FK_STAFF_USER` (`STAFF_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ORG_STRUCTURE`
	ADD CONSTRAINT `FK_STAFF_USER` FOREIGN KEY (`STAFF_ID`) REFERENCES `USERS` (`USER_ID`),
	ADD CONSTRAINT `FK_SUPR_USER` FOREIGN KEY (`SUPERVISOR_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `PHONE` (
	`PHONE_ID` varchar(32) NOT NULL,
	`NAME` varchar(40) DEFAULT NULL,
	`AREA_CD` varchar(10) DEFAULT NULL,
	`COUNTRY_CD` varchar(3) DEFAULT NULL,
	`DESCRIPTION` varchar(100) DEFAULT NULL,
	`PHONE_NBR` varchar(50) DEFAULT NULL,
	`PHONE_EXT` varchar(20) DEFAULT NULL,
	`IS_DEFAULT` char(1) DEFAULT 'N',
	`ACTIVE` char(1) DEFAULT 'Y',
	`PARENT_ID` varchar(32) DEFAULT NULL,
	`LAST_UPDATE` timestamp NULL DEFAULT NULL,
	`CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`TYPE_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`PHONE_ID`),
	KEY `AREA_CD` (`AREA_CD`,`PHONE_NBR`),
	KEY `PHONE_USER_FK` (`PARENT_ID`),
	KEY `PHONE_TYPE_FK` (`TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `PHONE`
	ADD CONSTRAINT `PHONE_TYPE_FK` FOREIGN KEY (`TYPE_ID`) REFERENCES `METADATA_TYPE` (`TYPE_ID`),
	ADD CONSTRAINT `PHONE_USER_FK` FOREIGN KEY (`PARENT_ID`) REFERENCES `USERS` (`USER_ID`);

DELIMITER ;;

CREATE TRIGGER ON_PHONE_INSERT 
BEFORE 
INSERT ON PHONE 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.LAST_UPDATE = NOW();
	END ;;

CREATE TRIGGER ON_PHONE_UPDATE
BEFORE 
UPDATE ON PHONE 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_UPDATE = NOW();
	END ;;

DELIMITER ;

CREATE TABLE `POLICY_ATTRIBUTE` (
	`POLICY_ATTR_ID` varchar(32) NOT NULL,
	`DEF_PARAM_ID` varchar(32) DEFAULT NULL,
	`POLICY_ID` varchar(32) DEFAULT NULL,
	`NAME` varchar(100) DEFAULT NULL,
	`OPERATION` varchar(20) DEFAULT NULL,
	`VALUE1` varchar(4096) DEFAULT NULL,
	`VALUE2` varchar(4096) DEFAULT NULL,
	`RULE_TEXT` text,
	`REQUIRED` char(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (`POLICY_ATTR_ID`),
	KEY `FK_POLICY_ATTRIBUTE_POLICY` (`POLICY_ID`),
	KEY `POLI_ATTR_POL_DEF_PARAM` (`DEF_PARAM_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `POLICY_ATTRIBUTE`
	ADD CONSTRAINT `FK_POLICY_ATTRIBUTE_POLICY` FOREIGN KEY (`POLICY_ID`) REFERENCES `POLICY` (`POLICY_ID`),
	ADD CONSTRAINT `POLI_ATTR_POL_DEF_PARAM` FOREIGN KEY (`DEF_PARAM_ID`) REFERENCES `POLICY_DEF_PARAM` (`DEF_PARAM_ID`);

CREATE TABLE `RESOURCE_PRIVILEGE` (
	`RESOURCE_PRIVLEGE_ID` varchar(32) NOT NULL,
	`RESOURCE_ID` varchar(32) DEFAULT NULL,
	`PRIVILEGE_NAME` varchar(32) DEFAULT NULL,
	`PRIVILEGE_TYPE` varchar(20) DEFAULT NULL,
	`DESCRIPTION` varchar(40) DEFAULT NULL,
	PRIMARY KEY (`RESOURCE_PRIVLEGE_ID`),
	KEY `FK_RESOURCE_PRIVILEGE_RES` (`RESOURCE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RESOURCE_PRIVILEGE`
	ADD CONSTRAINT `FK_RESOURCE_PRIVILEGE_RES` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`);

CREATE TABLE `RESOURCE_USER` (
	`RESOURCE_ID` varchar(32) NOT NULL,
	`USER_ID` varchar(32) NOT NULL,
	`START_DATE` datetime DEFAULT NULL,
	PRIMARY KEY (`RESOURCE_ID`,`USER_ID`),
	KEY `FK_RESOURCE_USER_USERS` (`USER_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RESOURCE_USER`
	ADD CONSTRAINT `FK_RESOURCE_USER_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`),
	ADD CONSTRAINT `RESOURCE_USER_ibfk_1` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`);

CREATE TABLE `ROLE` (
	`ROLE_NAME` varchar(80) NOT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(32) DEFAULT NULL,
	`DESCRIPTION` varchar(255) DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT NULL,
	`ROLE_ID` varchar(32) NOT NULL,
	`MANAGED_SYS_ID` varchar(32) DEFAULT NULL,
	`ADMIN_RESOURCE_ID` varchar(32) DEFAULT NULL,
	`TYPE_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`ROLE_ID`),
	UNIQUE KEY `ROLE_NAME` (`ROLE_NAME`),
	KEY `ROLE_MNG_SYS_FK` (`MANAGED_SYS_ID`),
	KEY `ROLE_ADMIN_RES_FK` (`ADMIN_RESOURCE_ID`),
	KEY `ROLE_TYPE_FK` (`TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ROLE`
	ADD CONSTRAINT `ROLE_ADMIN_RES_FK` FOREIGN KEY (`ADMIN_RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `ROLE_MNG_SYS_FK` FOREIGN KEY (`MANAGED_SYS_ID`) REFERENCES `MANAGED_SYS` (`MANAGED_SYS_ID`),
	ADD CONSTRAINT `ROLE_TYPE_FK` FOREIGN KEY (`TYPE_ID`) REFERENCES `METADATA_TYPE` (`TYPE_ID`);

CREATE TABLE `USER_ATTACHMENT_REF` (
	`USER_ATTACH_REF_ID` varchar(20) NOT NULL,
	`USER_ID` varchar(20) DEFAULT NULL,
	`NAME` varchar(20) DEFAULT NULL,
	`VALUE` varchar(50) DEFAULT NULL,
	`URL` varchar(50) DEFAULT NULL,
	PRIMARY KEY (`USER_ATTACH_REF_ID`),
	KEY `FK_USER_ATTACHMENT_REF_USERS` (`USER_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER_ATTACHMENT_REF`
	ADD CONSTRAINT `FK_USER_ATTACHMENT_REF_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `USER_DELEGATION_ATTRIBUTE` (
	`ID` varchar(32) NOT NULL,
	`USER_ID` varchar(32) DEFAULT NULL,
	`OBJ_TYPE` varchar(50) DEFAULT NULL,
	`NAME` varchar(50) DEFAULT NULL,
	`VALUE` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `USER_ID` (`USER_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER_DELEGATION_ATTRIBUTE`
	ADD CONSTRAINT `USER_DELEGATION_ATTRIBUTE_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `USER_IDENTITY_ANS` (
	`IDENTITY_ANS_ID` varchar(32) NOT NULL,
	`IDENTITY_QUESTION_ID` varchar(32) NOT NULL,
	`USER_ID` varchar(32) DEFAULT NULL,
	`QUESTION_ANSWER` varchar(255) DEFAULT NULL,
	`IS_ENCRYPTED` varchar(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`IDENTITY_ANS_ID`),
	KEY `FK_USER_IDENTITY_ANS_USERS` (`USER_ID`),
	KEY `FK_ID_AND_QUEST_FK` (`IDENTITY_QUESTION_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER_IDENTITY_ANS`
	ADD CONSTRAINT `FK_ID_AND_QUEST_FK` FOREIGN KEY (`IDENTITY_QUESTION_ID`) REFERENCES `IDENTITY_QUESTION` (`IDENTITY_QUESTION_ID`),
	ADD CONSTRAINT `FK_USER_IDENTITY_ANS_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `USER_KEY` (
	`USER_KEY_ID` varchar(32) NOT NULL,
	`USER_ID` varchar(32) NOT NULL,
	`NAME` varchar(40) NOT NULL,
	`KEY_VALUE` varchar(255) NOT NULL,
	PRIMARY KEY (`USER_KEY_ID`),
	KEY `FK_USER_KEY_USER_ID` (`USER_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER_KEY`
	ADD CONSTRAINT `FK_USER_KEY_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `USER_NOTE` (
	`USER_NOTE_ID` varchar(32) NOT NULL,
	`USER_ID` varchar(32) DEFAULT NULL,
	`NOTE_TYPE` varchar(20) DEFAULT NULL,
	`DESCRIPTION` varchar(2000) DEFAULT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(20) DEFAULT NULL,
	PRIMARY KEY (`USER_NOTE_ID`),
	KEY `FK_USER_NOTE_USERS` (`USER_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER_NOTE`
	ADD CONSTRAINT `FK_USER_NOTE_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `res_to_res_membership` (
	`RESOURCE_ID` varchar(32) NOT NULL,
	`MEMBER_RESOURCE_ID` varchar(32) NOT NULL,
	`CREATE_DATE` timestamp NULL DEFAULT NULL,
	`UPDATE_DATE` timestamp NULL DEFAULT NULL,
	`CREATED_BY` varchar(32) DEFAULT NULL,
	`UPDATED_BY` varchar(32) DEFAULT NULL,
	UNIQUE KEY `RESOURCE_ID` (`RESOURCE_ID`,`MEMBER_RESOURCE_ID`),
	KEY `MEMBER_RESOURCE_ID` (`MEMBER_RESOURCE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `res_to_res_membership`
	ADD CONSTRAINT `res_to_res_membership_ibfk_1` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `res_to_res_membership_ibfk_2` FOREIGN KEY (`MEMBER_RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`);

DELIMITER ;;

CREATE TRIGGER res_res_mem_insert
BEFORE
INSERT ON res_to_res_membership
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.UPDATE_DATE = NOW();
	END ;;

DELIMITER ;

CREATE TABLE `AUTH_PROVIDER_ATTRIBUTE` (
	`PROVIDER_ATTRIBUTE_ID` varchar(32) NOT NULL,
	`PROVIDER_ID` varchar(32) NOT NULL,
	`AUTH_ATTRIBUTE_ID` varchar(32) NOT NULL,
	`VALUE` varchar(4096) DEFAULT NULL,
	`DATA_TYPE` varchar(20) NOT NULL DEFAULT 'singleValue',
	PRIMARY KEY (`PROVIDER_ATTRIBUTE_ID`),
	UNIQUE KEY `IDX_PROVIDER_ATTRIBUTE` (`PROVIDER_ID`,`AUTH_ATTRIBUTE_ID`),
	KEY `FK_PROVIDER_PROVIDER_ATTRIBUTE` (`PROVIDER_ID`),
	KEY `FK_PROVIDER_ATTRIBUTE` (`AUTH_ATTRIBUTE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `AUTH_PROVIDER_ATTRIBUTE`
	ADD CONSTRAINT `FK_PROVIDER_ATTRIBUTE` FOREIGN KEY (`AUTH_ATTRIBUTE_ID`) REFERENCES `AUTH_ATTRIBUTE` (`AUTH_ATTRIBUTE_ID`),
	ADD CONSTRAINT `FK_PROVIDER_PROVIDER_ATTRIBUTE` FOREIGN KEY (`PROVIDER_ID`) REFERENCES `AUTH_PROVIDER` (`PROVIDER_ID`);

CREATE TABLE `AUTH_RESOURCE_ATTRIBUTE_MAP` (
	`ATTRIBUTE_MAP_ID` varchar(32) NOT NULL,
	`PROVIDER_ID` varchar(32) NOT NULL,
	`TARGET_ATTRIBUTE_NAME` varchar(100) NOT NULL,
	`AM_RES_ATTRIBUTE_ID` varchar(32) DEFAULT NULL,
	`AM_POLICY_URL` varchar(100) DEFAULT NULL,
	`ATTRIBUTE_VALUE` varchar(100) DEFAULT NULL,
	`ATTRIBUTE_TYPE` varchar(32) NOT NULL,
	PRIMARY KEY (`ATTRIBUTE_MAP_ID`),
	UNIQUE KEY `IDX_PROVIDER_ATTRIBUTE` (`PROVIDER_ID`,`TARGET_ATTRIBUTE_NAME`),
	KEY `FK_AUTH_AM_ATTR` (`AM_RES_ATTRIBUTE_ID`),
	KEY `FK_PROVIDER_AUTH_RES_ATTR_MAP` (`PROVIDER_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `AUTH_RESOURCE_ATTRIBUTE_MAP`
	ADD CONSTRAINT `FK_AUTH_AM_ATTR` FOREIGN KEY (`AM_RES_ATTRIBUTE_ID`) REFERENCES `AUTH_RESOURCE_AM_ATTRIBUTE` (`AM_RES_ATTRIBUTE_ID`),
	ADD CONSTRAINT `FK_PROVIDER_AUTH_RES_ATTR_MAP` FOREIGN KEY (`PROVIDER_ID`) REFERENCES `AUTH_PROVIDER` (`PROVIDER_ID`);

CREATE TABLE `COMPANY_TO_COMPANY_MEMBERSHIP` (
	`COMPANY_ID` varchar(32) NOT NULL,
	`MEMBER_COMPANY_ID` varchar(32) NOT NULL,
	`CREATE_DATE` timestamp NULL DEFAULT NULL,
	`UPDATE_DATE` timestamp NULL DEFAULT NULL,
	`CREATED_BY` varchar(32) DEFAULT NULL,
	`UPDATED_BY` varchar(32) DEFAULT NULL,
	UNIQUE KEY `COMPANY_ID` (`COMPANY_ID`,`MEMBER_COMPANY_ID`),
	KEY `COMPANY_COMPANY_PARENT` (`MEMBER_COMPANY_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `COMPANY_TO_COMPANY_MEMBERSHIP`
	ADD CONSTRAINT `COMPANY_COMPANY_CHILD` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
	ADD CONSTRAINT `COMPANY_COMPANY_PARENT` FOREIGN KEY (`MEMBER_COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`);

DELIMITER ;;

CREATE TRIGGER ON_COMPANY_XREF_INSERT
BEFORE
INSERT ON COMPANY_TO_COMPANY_MEMBERSHIP
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.UPDATE_DATE = NOW();
	END ;;

DELIMITER ;

CREATE TABLE `CONTENT_PROVIDER_SERVER` (
	`CONTENT_PROVIDER_SERVER_ID` varchar(32) NOT NULL,
	`CONTENT_PROVIDER_ID` varchar(32) NOT NULL,
	`SERVER_URL` varchar(100) NOT NULL,
	PRIMARY KEY (`CONTENT_PROVIDER_SERVER_ID`),
	UNIQUE KEY `UNIQUE_CP_SERVER` (`CONTENT_PROVIDER_ID`,`SERVER_URL`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `CONTENT_PROVIDER_SERVER`
	ADD CONSTRAINT `CP_SERVER_CP_FK` FOREIGN KEY (`CONTENT_PROVIDER_ID`) REFERENCES `CONTENT_PROVIDER` (`CONTENT_PROVIDER_ID`);

CREATE TABLE `CP_AUTH_LEVEL_GRP_XREF` (
	`CONTENT_PROVIDER_ID` varchar(32) NOT NULL,
	`AUTH_LEVEL_GROUPING_ID` varchar(32) NOT NULL,
	`EXEC_ORDER` int(3) NOT NULL,
	UNIQUE KEY `UNIQUE_CP_AUTH_GROUP` (`CONTENT_PROVIDER_ID`,`AUTH_LEVEL_GROUPING_ID`,`EXEC_ORDER`),
	KEY `CP_AUTH_LEVEL_GRP_FK` (`AUTH_LEVEL_GROUPING_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `CP_AUTH_LEVEL_GRP_XREF`
	ADD CONSTRAINT `CP_AUTH_LEVEL_CP_FK` FOREIGN KEY (`CONTENT_PROVIDER_ID`) REFERENCES `CONTENT_PROVIDER` (`CONTENT_PROVIDER_ID`),
	ADD CONSTRAINT `CP_AUTH_LEVEL_GRP_FK` FOREIGN KEY (`AUTH_LEVEL_GROUPING_ID`) REFERENCES `AUTH_LEVEL_GROUPING` (`AUTH_LEVEL_GROUPING_ID`);

CREATE TABLE `GRP` (
	`GRP_ID` varchar(32) NOT NULL,
	`GRP_NAME` varchar(80) NOT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	`CREATED_BY` varchar(20) DEFAULT NULL,
	`COMPANY_ID` varchar(32) DEFAULT NULL,
	`GROUP_DESC` varchar(512) DEFAULT NULL,
	`STATUS` varchar(20) DEFAULT NULL,
	`LAST_UPDATE` datetime DEFAULT NULL,
	`LAST_UPDATED_BY` varchar(32) DEFAULT NULL,
	`MANAGED_SYS_ID` varchar(32) DEFAULT NULL,
	`ADMIN_RESOURCE_ID` varchar(32) DEFAULT NULL,
	`TYPE_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`GRP_ID`),
	UNIQUE KEY `GRP_NAME` (`GRP_NAME`),
	KEY `GRP_MNG_SYS_FK` (`MANAGED_SYS_ID`),
	KEY `GRP_ADMIN_RES_FK` (`ADMIN_RESOURCE_ID`),
	KEY `GRP_COMPANY_FK` (`COMPANY_ID`),
	KEY `GRP_TYPE_FK` (`TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `GRP`
	ADD CONSTRAINT `GRP_ADMIN_RES_FK` FOREIGN KEY (`ADMIN_RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `GRP_COMPANY_FK` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
	ADD CONSTRAINT `GRP_MNG_SYS_FK` FOREIGN KEY (`MANAGED_SYS_ID`) REFERENCES `MANAGED_SYS` (`MANAGED_SYS_ID`),
	ADD CONSTRAINT `GRP_TYPE_FK` FOREIGN KEY (`TYPE_ID`) REFERENCES `METADATA_TYPE` (`TYPE_ID`);

CREATE TABLE `METADATA_ELEMENT` (
	`METADATA_ID` varchar(32) NOT NULL,
	`TYPE_ID` varchar(32) NOT NULL,
	`ATTRIBUTE_NAME` varchar(100) DEFAULT NULL,
	`DESCRIPTION` varchar(40) DEFAULT NULL,
	`DATA_TYPE` varchar(20) DEFAULT NULL,
	`AUDITABLE` char(1) NOT NULL DEFAULT 'Y',
	`REQUIRED` char(1) NOT NULL DEFAULT 'N',
	`SELF_EDITABLE` char(1) NOT NULL DEFAULT 'N',
	`TEMPLATE_ID` varchar(32) DEFAULT NULL,
	`RESOURCE_ID` varchar(32) DEFAULT NULL,
	`VALIDATOR` varchar(150) DEFAULT NULL,
	`STATIC_DEFAULT_VALUE` varchar(4096) DEFAULT NULL,
	`IS_PUBLIC` char(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (`METADATA_ID`),
	KEY `METADATA_ELEMENT_TEMPLATE_FK` (`TEMPLATE_ID`),
	KEY `METADATA_ELEMENT_RES_FK` (`RESOURCE_ID`),
	KEY `FK_MD_ELMT_TYPE_FK` (`TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `METADATA_ELEMENT`
	ADD CONSTRAINT `FK_MD_ELMT_TYPE_FK` FOREIGN KEY (`TYPE_ID`) REFERENCES `METADATA_TYPE` (`TYPE_ID`),
	ADD CONSTRAINT `METADATA_ELEMENT_RES_FK` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `METADATA_ELEMENT_TEMPLATE_FK` FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `METADATA_ELEMENT_PAGE_TEMPLATE` (`ID`);

CREATE TABLE `PWD_HISTORY` (
	`PWD_HISTORY_ID` varchar(32) NOT NULL,
	`DATE_CREATED` datetime NOT NULL,
	`PASSWORD` varchar(255) DEFAULT NULL,
	`LOGIN_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`PWD_HISTORY_ID`),
	KEY `LOGIN_ID_PWD_HIST_FK` (`LOGIN_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `PWD_HISTORY`
	ADD CONSTRAINT `LOGIN_ID_PWD_HIST_FK` FOREIGN KEY (`LOGIN_ID`) REFERENCES `LOGIN` (`LOGIN_ID`);

CREATE TABLE `RESOURCE_POLICY` (
	`RESOURCE_POLICY_ID` varchar(32) NOT NULL,
	`RESOURCE_ID` varchar(32) DEFAULT NULL,
	`POLICY_START` datetime DEFAULT NULL,
	`POLICY_END` datetime DEFAULT NULL,
	`APPLY_TO_CHILDREN` int(11) DEFAULT NULL,
	`ROLE_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`RESOURCE_POLICY_ID`),
	KEY `RS_PL_RS_RSID` (`RESOURCE_ID`),
	KEY `FK_RESOURCE_POLICY_ROLE` (`ROLE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RESOURCE_POLICY`
	ADD CONSTRAINT `FK_RESOURCE_POLICY_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`),
	ADD CONSTRAINT `RS_PL_RS_RSID` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`);

CREATE TABLE `RESOURCE_ROLE` (
	`RESOURCE_ID` varchar(32) NOT NULL,
	`START_DATE` datetime DEFAULT NULL,
	`ROLE_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`RESOURCE_ID`,`ROLE_ID`),
	KEY `FK_RESOURCE_ROLE_ROLE` (`ROLE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RESOURCE_ROLE`
	ADD CONSTRAINT `FK_RESOURCE_ROLE_RESOURCE` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `FK_RESOURCE_ROLE_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`);

CREATE TABLE `ROLE_POLICY` (
	`ROLE_POLICY_ID` varchar(32) NOT NULL,
	`ACTION` varchar(20) DEFAULT NULL,
	`NAME` varchar(40) DEFAULT NULL,
	`VALUE1` varchar(40) DEFAULT NULL,
	`VALUE2` varchar(40) DEFAULT NULL,
	`ACTION_QUALIFIER` varchar(20) DEFAULT NULL,
	`EXECUTION_ORDER` int(11) DEFAULT NULL,
	`POLICY_SCRIPT` varchar(100) DEFAULT NULL,
	`ROLE_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`ROLE_POLICY_ID`),
	KEY `FK_ROLE_POLICY_ROLE` (`ROLE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ROLE_POLICY`
	ADD CONSTRAINT `FK_ROLE_POLICY_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`);

CREATE TABLE `UI_FIELD_TEMPLATE_XREF` (
	`UI_FIELD_ID` varchar(32) NOT NULL,
	`TEMPLATE_ID` varchar(32) NOT NULL,
	`IS_REQUIRED` char(1) NOT NULL DEFAULT 'N',
	`IS_EDITABLE` char(1) NOT NULL DEFAULT 'Y',
	`DISPLAY_ORDER` int(3) NOT NULL,
	`XREF_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`XREF_ID`),
	UNIQUE KEY `TEMPLATE_XREF_UNIQUE` (`TEMPLATE_ID`,`UI_FIELD_ID`),
	KEY `TEMPLATE_XREF_UI_FIELD_FK` (`UI_FIELD_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `UI_FIELD_TEMPLATE_XREF`
	ADD CONSTRAINT `TEMPLATE_XREF_TEMPLATE_FK` FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `METADATA_ELEMENT_PAGE_TEMPLATE` (`ID`),
	ADD CONSTRAINT `TEMPLATE_XREF_UI_FIELD_FK` FOREIGN KEY (`UI_FIELD_ID`) REFERENCES `UI_TEMPLATE_FIELDS` (`UI_FIELD_ID`);

CREATE TABLE `URI_PATTERN` (
	`URI_PATTERN_ID` varchar(32) NOT NULL,
	`CONTENT_PROVIDER_ID` varchar(32) NOT NULL,
	`PATTERN` varchar(100) NOT NULL,
	`IS_PUBLIC` char(1) NOT NULL DEFAULT 'N',
	`RESOURCE_ID` varchar(32) NOT NULL,
	`UI_THEME_ID` varchar(32) DEFAULT NULL,
	PRIMARY KEY (`URI_PATTERN_ID`),
	UNIQUE KEY `URI_PATTERN_UNIQUE` (`CONTENT_PROVIDER_ID`,`PATTERN`),
	KEY `URI_PATTERN_RES_FK` (`RESOURCE_ID`),
	KEY `URI_PATTERN_UI_THEME` (`UI_THEME_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `URI_PATTERN`
	ADD CONSTRAINT `URI_PATTERN_CP_FK` FOREIGN KEY (`CONTENT_PROVIDER_ID`) REFERENCES `CONTENT_PROVIDER` (`CONTENT_PROVIDER_ID`),
	ADD CONSTRAINT `URI_PATTERN_RES_FK` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `URI_PATTERN_UI_THEME` FOREIGN KEY (`UI_THEME_ID`) REFERENCES `UI_THEME` (`UI_THEME_ID`);

CREATE TABLE `USER_AFFILIATION` (
	`COMPANY_ID` varchar(32) NOT NULL,
	`USER_ID` varchar(32) NOT NULL,
	`CREATE_DATE` datetime DEFAULT NULL,
	PRIMARY KEY (`COMPANY_ID`,`USER_ID`),
	UNIQUE KEY `USER_AFFILIATION_UNIQUE` (`USER_ID`,`COMPANY_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER_AFFILIATION`
	ADD CONSTRAINT `FK_USR_ORG_AFFL` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
	ADD CONSTRAINT `FK_USR_USER_AFFIL` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `USER_ROLE` (
	`USER_ID` varchar(32) NOT NULL,
	`ROLE_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`ROLE_ID`,`USER_ID`),
	KEY `FK_USR_ROLE_USR` (`USER_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER_ROLE`
	ADD CONSTRAINT `FK_USR_ROLE_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`),
	ADD CONSTRAINT `FK_USR_ROLE_USR` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `role_to_role_membership` (
	`ROLE_ID` varchar(32) NOT NULL,
	`MEMBER_ROLE_ID` varchar(32) NOT NULL,
	`CREATE_DATE` timestamp NULL DEFAULT NULL,
	`UPDATE_DATE` timestamp NULL DEFAULT NULL,
	`CREATED_BY` varchar(32) DEFAULT NULL,
	`UPDATED_BY` varchar(32) DEFAULT NULL,
	UNIQUE KEY `ROLE_ID` (`ROLE_ID`,`MEMBER_ROLE_ID`),
	KEY `ROLE_ROLE_MMSP_MEMBER_ROLE_ID` (`MEMBER_ROLE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `role_to_role_membership`
	ADD CONSTRAINT `role_to_role_membership_ibfk_1` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`),
	ADD CONSTRAINT `role_to_role_membership_ibfk_2` FOREIGN KEY (`MEMBER_ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`);

DELIMITER ;;

CREATE TRIGGER role_role_mem_insert 
BEFORE 
INSERT ON role_to_role_membership 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.UPDATE_DATE = NOW();
	END ;;

DELIMITER ;

CREATE TABLE `COMPANY_ATTRIBUTE` (
	`COMPANY_ATTR_ID` varchar(32) NOT NULL,
	`COMPANY_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) DEFAULT NULL,
	`_VALUE` varchar(4096) DEFAULT NULL,
	`METADATA_ID` varchar(32) DEFAULT NULL,
	`IS_MULTIVALUED` char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`COMPANY_ATTR_ID`),
	KEY `FK_COMPANY_ATTRIBUTE_COMPANY` (`COMPANY_ID`),
	KEY `FK_COMPANY_METADATA_ELEMENT` (`METADATA_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `COMPANY_ATTRIBUTE`
	ADD CONSTRAINT `FK_COMPANY_ATTRIBUTE_COMPANY` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`),
	ADD CONSTRAINT `FK_COMPANY_METADATA_ELEMENT` FOREIGN KEY (`METADATA_ID`) REFERENCES `METADATA_ELEMENT` (`METADATA_ID`);

CREATE TABLE `GRP_ATTRIBUTES` (
	`ID` varchar(32) NOT NULL,
	`GRP_ID` varchar(32) NOT NULL,
	`METADATA_ID` varchar(32) DEFAULT NULL,
	`NAME` varchar(100) DEFAULT NULL,
	`_VALUE` varchar(4096) DEFAULT NULL,
	`IS_MULTIVALUED` char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`ID`),
	KEY `GRP_ID` (`GRP_ID`),
	KEY `GRP_ATTR_META_ELMT_FK` (`METADATA_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `GRP_ATTRIBUTES`
	ADD CONSTRAINT `GRP_ATTRIBUTES_ibfk_1` FOREIGN KEY (`GRP_ID`) REFERENCES `GRP` (`GRP_ID`),
	ADD CONSTRAINT `GRP_ATTR_META_ELMT_FK` FOREIGN KEY (`METADATA_ID`) REFERENCES `METADATA_ELEMENT` (`METADATA_ID`);

CREATE TABLE `GRP_ROLE` (
	`GRP_ID` varchar(32) NOT NULL,
	`ROLE_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`GRP_ID`,`ROLE_ID`),
	KEY `FK_GRP_ROLE_ROLE` (`ROLE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `GRP_ROLE`
	ADD CONSTRAINT `FK_GRP_ROLE_GRP` FOREIGN KEY (`GRP_ID`) REFERENCES `GRP` (`GRP_ID`),
	ADD CONSTRAINT `FK_GRP_ROLE_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`);

CREATE TABLE `LOGIN_ATTRIBUTE` (
	`LOGIN_ATTR_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) DEFAULT NULL,
	`VALUE` varchar(4096) DEFAULT NULL,
	`METADATA_ID` varchar(20) DEFAULT NULL,
	`LOGIN_ID` varchar(32) NOT NULL,
	PRIMARY KEY (`LOGIN_ATTR_ID`),
	KEY `LOGIN_ID_LOGIN_ATTR_FK` (`LOGIN_ID`),
	KEY `FK_LOGIN_METADATA_ELEMENT` (`METADATA_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `LOGIN_ATTRIBUTE`
	ADD CONSTRAINT `FK_LOGIN_METADATA_ELEMENT` FOREIGN KEY (`METADATA_ID`) REFERENCES `METADATA_ELEMENT` (`METADATA_ID`),
	ADD CONSTRAINT `LOGIN_ID_LOGIN_ATTR_FK` FOREIGN KEY (`LOGIN_ID`) REFERENCES `LOGIN` (`LOGIN_ID`);

CREATE TABLE `MD_ELEMENT_VALID_VALUES` (
	`ID` varchar(32) NOT NULL,
	`METADATA_ELEMENT_ID` varchar(32) NOT NULL,
	`UI_VALUE` varchar(200) NOT NULL,
	`DISPLAY_ORDER` int(11) NOT NULL,
	PRIMARY KEY (`ID`),
	KEY `VALID_VALUES_ELEMENT_FK` (`METADATA_ELEMENT_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `MD_ELEMENT_VALID_VALUES`
	ADD CONSTRAINT `VALID_VALUES_ELEMENT_FK` FOREIGN KEY (`METADATA_ELEMENT_ID`) REFERENCES `METADATA_ELEMENT` (`METADATA_ID`);

CREATE TABLE `METADATA_URI_XREF` (
	`TEMPLATE_ID` varchar(32) NOT NULL,
	`URI_PATTERN_ID` varchar(32) NOT NULL,
	KEY `TEMPLATE_PATTERN_XREF_PATTERN_FK` (`URI_PATTERN_ID`),
	KEY `TEMPLETE_PATTERN_XREF_FK` (`TEMPLATE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `METADATA_URI_XREF`
	ADD CONSTRAINT `TEMPLATE_PATTERN_XREF_PATTERN_FK` FOREIGN KEY (`URI_PATTERN_ID`) REFERENCES `URI_PATTERN` (`URI_PATTERN_ID`),
	ADD CONSTRAINT `TEMPLETE_PATTERN_XREF_FK` FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `METADATA_ELEMENT_PAGE_TEMPLATE` (`ID`);

CREATE TABLE `PAGE_TEMPLATE_XREF` (
	`TEMPLATE_ID` varchar(32) NOT NULL,
	`METADATA_ELEMENT_ID` varchar(32) NOT NULL,
	`DISPLAY_ORDER` int(11) NOT NULL,
	PRIMARY KEY (`TEMPLATE_ID`,`METADATA_ELEMENT_ID`),
	KEY `MD_ELMT_TEMPLATE_FK` (`METADATA_ELEMENT_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `PAGE_TEMPLATE_XREF`
	ADD CONSTRAINT `MD_ELMT_TEMPLATE_FK` FOREIGN KEY (`METADATA_ELEMENT_ID`) REFERENCES `METADATA_ELEMENT` (`METADATA_ID`),
	ADD CONSTRAINT `META_PG_TEMPLATE_FK` FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `METADATA_ELEMENT_PAGE_TEMPLATE` (`ID`);

CREATE TABLE `RESOURCE_GROUP` (
	`RESOURCE_ID` varchar(32) NOT NULL,
	`GRP_ID` varchar(32) NOT NULL,
	`START_DATE` datetime DEFAULT NULL,
	PRIMARY KEY (`RESOURCE_ID`,`GRP_ID`),
	UNIQUE KEY `UNIQUE_RESOURCE_GROUP` (`GRP_ID`,`RESOURCE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RESOURCE_GROUP`
	ADD CONSTRAINT `FK_RESOURCE_GRP` FOREIGN KEY (`GRP_ID`) REFERENCES `GRP` (`GRP_ID`),
	ADD CONSTRAINT `FK_RESOURCE_GRP_RESOURCE` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`);

CREATE TABLE `RESOURCE_PROP` (
	`RESOURCE_PROP_ID` varchar(32) NOT NULL,
	`RESOURCE_ID` varchar(32) DEFAULT NULL,
	`METADATA_ID` varchar(32) DEFAULT NULL,
	`NAME` varchar(100) DEFAULT NULL,
	`_VALUE` varchar(4096) DEFAULT NULL,
	`PROP_GROUP` varchar(20) DEFAULT NULL,
	`IS_MULTIVALUED` char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`RESOURCE_PROP_ID`),
	KEY `FK_RESOURCE_PROP_RESOURCE` (`RESOURCE_ID`),
	KEY `FK_RES_PROP_METADATA_ELEMENT` (`METADATA_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `RESOURCE_PROP`
	ADD CONSTRAINT `FK_RESOURCE_PROP_RESOURCE` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `RES` (`RESOURCE_ID`),
	ADD CONSTRAINT `FK_RES_PROP_METADATA_ELEMENT` FOREIGN KEY (`METADATA_ID`) REFERENCES `METADATA_ELEMENT` (`METADATA_ID`);

CREATE TABLE `ROLE_ATTRIBUTE` (
	`ROLE_ATTR_ID` varchar(32) NOT NULL,
	`NAME` varchar(100) DEFAULT NULL,
	`_VALUE` varchar(4096) DEFAULT NULL,
	`METADATA_ID` varchar(32) DEFAULT NULL,
	`ROLE_ID` varchar(32) NOT NULL,
	`IS_MULTIVALUED` char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`ROLE_ATTR_ID`),
	KEY `FK_ROLE_ROLE_ATTRIBUTE` (`ROLE_ID`),
	KEY `FK_ROLE_ATTR_METADATA_ELEMENT` (`METADATA_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ROLE_ATTRIBUTE`
	ADD CONSTRAINT `FK_ROLE_ATTR_METADATA_ELEMENT` FOREIGN KEY (`METADATA_ID`) REFERENCES `METADATA_ELEMENT` (`METADATA_ID`),
	ADD CONSTRAINT `FK_ROLE_ROLE_ATTRIBUTE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`);

CREATE TABLE `URI_AUTH_LEVEL_GRP_XREF` (
	`URI_PATTERN_ID` varchar(32) NOT NULL,
	`AUTH_LEVEL_GROUPING_ID` varchar(32) NOT NULL,
	`EXEC_ORDER` int(3) NOT NULL,
	UNIQUE KEY `UNIQUE_URI_AUTH_GROUP` (`URI_PATTERN_ID`,`AUTH_LEVEL_GROUPING_ID`,`EXEC_ORDER`),
	KEY `URI_AUTH_LEVEL_GRP_FK` (`AUTH_LEVEL_GROUPING_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `URI_AUTH_LEVEL_GRP_XREF`
	ADD CONSTRAINT `URI_AUTH_LEVEL_GRP_FK` FOREIGN KEY (`AUTH_LEVEL_GROUPING_ID`) REFERENCES `AUTH_LEVEL_GROUPING` (`AUTH_LEVEL_GROUPING_ID`),
	ADD CONSTRAINT `URI_AUTH_LEVEL_URI_FK` FOREIGN KEY (`URI_PATTERN_ID`) REFERENCES `URI_PATTERN` (`URI_PATTERN_ID`);

CREATE TABLE `URI_PATTERN_META` (
	`URI_PATTERN_META_ID` varchar(32) NOT NULL,
	`URI_PATTERN_ID` varchar(32) NOT NULL,
	`URI_PATTERN_META_TYPE_ID` varchar(32) NOT NULL,
	`URI_PATTERN_NAME` varchar(100) NOT NULL,
	PRIMARY KEY (`URI_PATTERN_META_ID`),
	KEY `URI_PATTERN_META_URI_PATTERN_FK` (`URI_PATTERN_ID`),
	KEY `URI_PATTERN_META_META_TYPE_FK` (`URI_PATTERN_META_TYPE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `URI_PATTERN_META`
	ADD CONSTRAINT `URI_PATTERN_META_META_TYPE_FK` FOREIGN KEY (`URI_PATTERN_META_TYPE_ID`) REFERENCES `URI_PATTERN_META_TYPE` (`URI_PATTERN_META_TYPE_ID`),
	ADD CONSTRAINT `URI_PATTERN_META_URI_PATTERN_FK` FOREIGN KEY (`URI_PATTERN_ID`) REFERENCES `URI_PATTERN` (`URI_PATTERN_ID`);

CREATE TABLE `USER_ATTRIBUTES` (
	`ID` varchar(32) NOT NULL,
	`USER_ID` varchar(32) DEFAULT NULL,
	`METADATA_ID` varchar(32) DEFAULT NULL,
	`NAME` varchar(100) DEFAULT NULL,
	`VALUE` varchar(4096) DEFAULT NULL,
	`VALUE_AS_BYTE_ARRAY` blob,
	`IS_MULTIVALUED` char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`ID`),
	KEY `USER_ID` (`USER_ID`),
	KEY `FK_USR_ATTR_ELMT_FK` (`METADATA_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER_ATTRIBUTES`
	ADD CONSTRAINT `FK_USR_ATTR_ELMT_FK` FOREIGN KEY (`METADATA_ID`) REFERENCES `METADATA_ELEMENT` (`METADATA_ID`),
	ADD CONSTRAINT `USER_ATTRIBUTES_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `USER_GRP` (
	`GRP_ID` varchar(32) NOT NULL,
	`USER_ID` varchar(32) NOT NULL,
	UNIQUE KEY `USER_GRP_UNIQUE_RECORD` (`USER_ID`,`GRP_ID`),
	KEY `FK_USR_GRP_GPR` (`GRP_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER_GRP`
	ADD CONSTRAINT `FK_USR_GRP_GPR` FOREIGN KEY (`GRP_ID`) REFERENCES `GRP` (`GRP_ID`),
	ADD CONSTRAINT `FK_USR_GRP_USR` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`);

CREATE TABLE `grp_to_grp_membership` (
	`GROUP_ID` varchar(32) NOT NULL,
	`MEMBER_GROUP_ID` varchar(32) NOT NULL,
	`CREATE_DATE` timestamp NULL DEFAULT NULL,
	`UPDATE_DATE` timestamp NULL DEFAULT NULL,
	`CREATED_BY` varchar(32) DEFAULT NULL,
	`UPDATED_BY` varchar(32) DEFAULT NULL,
	UNIQUE KEY `GROUP_ID` (`GROUP_ID`,`MEMBER_GROUP_ID`),
	KEY `MEMBER_GROUP_ID` (`MEMBER_GROUP_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `grp_to_grp_membership`
	ADD CONSTRAINT `grp_to_grp_membership_ibfk_1` FOREIGN KEY (`GROUP_ID`) REFERENCES `GRP` (`GRP_ID`),
	ADD CONSTRAINT `grp_to_grp_membership_ibfk_2` FOREIGN KEY (`MEMBER_GROUP_ID`) REFERENCES `GRP` (`GRP_ID`);

DELIMITER ;;

CREATE TRIGGER grp_grp_mem_insert 
BEFORE 
INSERT ON grp_to_grp_membership 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.UPDATE_DATE = NOW();
	END ;;

DELIMITER ;

CREATE TABLE `COMPANY_ATTRIBUTE_VALUES` (
	`COMPANY_ATTRIBUTE_ID` varchar(32) NOT NULL,
	`VALUE` varchar(255) DEFAULT NULL,
	KEY `COMPANY_ATTRIBUTE_VALUES_FK` (`COMPANY_ATTRIBUTE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `COMPANY_ATTRIBUTE_VALUES`
	ADD CONSTRAINT `COMPANY_ATTRIBUTE_VALUES_FK` FOREIGN KEY (`COMPANY_ATTRIBUTE_ID`) REFERENCES `COMPANY_ATTRIBUTE` (`COMPANY_ATTR_ID`);

CREATE TABLE `GROUP_ATTRIBUTE_VALUES` (
	`GROUP_ATTRIBUTE_ID` varchar(32) NOT NULL,
	`VALUE` varchar(255) DEFAULT NULL,
	KEY `GROUP_ATTRIBUTE_VALUES_FK` (`GROUP_ATTRIBUTE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `GROUP_ATTRIBUTE_VALUES`
	ADD CONSTRAINT `GROUP_ATTRIBUTE_VALUES_FK` FOREIGN KEY (`GROUP_ATTRIBUTE_ID`) REFERENCES `GRP_ATTRIBUTES` (`ID`);

CREATE TABLE `ROLE_ATTRIBUTE_VALUES` (
	`ROLE_ATTRIBUTE_ID` varchar(32) NOT NULL,
	`VALUE` varchar(255) DEFAULT NULL,
	KEY `ROLE_ATTRIBUTE_VALUES_FK` (`ROLE_ATTRIBUTE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ROLE_ATTRIBUTE_VALUES`
	ADD CONSTRAINT `ROLE_ATTRIBUTE_VALUES_FK` FOREIGN KEY (`ROLE_ATTRIBUTE_ID`) REFERENCES `ROLE_ATTRIBUTE` (`ROLE_ATTR_ID`);

CREATE TABLE `URI_PATTERN_META_VALUE` (
	`URI_PATTERN_META_VALUE_ID` varchar(32) NOT NULL,
	`URI_PATTERN_META_ID` varchar(32) NOT NULL,
	`META_ATTRIBUTE_NAME` varchar(100) NOT NULL,
	`AM_RES_ATTRIBUTE_ID` varchar(32) DEFAULT NULL,
	`STATIC_VALUE` varchar(4096) DEFAULT NULL,
	`GROOVY_SCRIPT` varchar(200) DEFAULT NULL,
	PRIMARY KEY (`URI_PATTERN_META_VALUE_ID`),
	KEY `URI_PATTERN_META_VALUE_META_FK` (`URI_PATTERN_META_ID`),
	KEY `URI_PATTERN_META_VALUE_AM_FK` (`AM_RES_ATTRIBUTE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `URI_PATTERN_META_VALUE`
	ADD CONSTRAINT `URI_PATTERN_META_VALUE_AM_FK` FOREIGN KEY (`AM_RES_ATTRIBUTE_ID`) REFERENCES `AUTH_RESOURCE_AM_ATTRIBUTE` (`AM_RES_ATTRIBUTE_ID`),
	ADD CONSTRAINT `URI_PATTERN_META_VALUE_META_FK` FOREIGN KEY (`URI_PATTERN_META_ID`) REFERENCES `URI_PATTERN_META` (`URI_PATTERN_META_ID`);

CREATE TABLE `USER_ATTRIBUTE_VALUES` (
	`USER_ATTRIBUTE_ID` varchar(32) NOT NULL,
	`VALUE` varchar(255) DEFAULT NULL,
	KEY `USER_ATTRIBUTE_VALUES_FK` (`USER_ATTRIBUTE_ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER_ATTRIBUTE_VALUES`
	ADD CONSTRAINT `USER_ATTRIBUTE_VALUES_FK` FOREIGN KEY (`USER_ATTRIBUTE_ID`) REFERENCES `USER_ATTRIBUTES` (`ID`);


CREATE VIEW `USER_PSWD_EXPIRED_YESTERDAY_VW` AS 
	select `l`.`LOGIN` AS `LOGIN`,`l`.`MANAGED_SYS_ID` AS `MANAGED_SYS_ID`,`l`.`USER_ID` AS `USER_ID`,`l`.`GRACE_PERIOD` AS `EXPIRATION_DATE`,`u`.`FIRST_NAME` AS `FIRST_NAME`,`u`.`LAST_NAME` AS `LAST_NAME`,`u`.`STATUS` AS `STATUS` from (`LOGIN` `l` join `USERS` `u`) where ((`l`.`USER_ID` = `u`.`USER_ID`) and (`l`.`MANAGED_SYS_ID` = 0) and (((`l`.`GRACE_PERIOD` is not null) and (cast(`l`.`GRACE_PERIOD` as date) = (curdate() - 1))) or ((`l`.`PWD_EXP` is not null) and isnull(`l`.`GRACE_PERIOD`) and (cast(`l`.`PWD_EXP` as date) = (curdate() - 1)))));

