use openiam;

ALTER TABLE USER_IDENTITY_ANS ALTER COLUMN QUESTION_ANSWER NVARCHAR(1024) NULL;
ALTER TABLE USER_IDENTITY_ANS ADD DEFAULT 'NULL' FOR QUESTION_ANSWER;

ALTER TABLE MANAGED_SYS ALTER COLUMN PSWD NVARCHAR(512) NULL;
ALTER TABLE MANAGED_SYS ADD DEFAULT 'NULL' FOR PSWD;
