use openiam; 

EXEC sp_RENAME 'IDENTITY.IDENTITY', 'IDENTIFICATION', 'COLUMN'
ALTER TABLE "IDENTITY" ALTER COLUMN IDENTIFICATION nvarchar(320) NOT NULL;

EXEC sp_rename 'IDENTITY', 'IDENTIFICATION';


