/***************************************RELEASE.3.3.1***************************************/
/***************************************dml/1.add_report_param.sql***************************************/

DECLARE
 tCount NUMBER := 0;
BEGIN
  SELECT count(*) INTO tCount FROM RES WHERE RESOURCE_ID = 'USER_ACCESS_REPORT_109';
  IF (tCount > 0) THEN
    SELECT count(*) INTO tCount FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID = '1097';
    IF (tCount = 0) THEN
      INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES ('1097', '109', 'RESOURCE_IDS', NULL, '1', 'RESOURCE', 'Y', 'N', 'Resource', 7, NULL);
    END IF;
  END IF;
END;
/



/***************************************dml/2.add_user_org_menu.sql***************************************/

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SS_USR_ORG';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'SS_USR_ORG';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'SS_USR_ORG_PUB';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'SS_USR_ORG_DESC';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID = 'SS_USR_ORG';
DELETE FROM RES WHERE RESOURCE_ID = 'SS_USR_ORG';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL, DISPLAY_ORDER) VALUES('SS_USR_ORG', 'MENU_ITEM', 'USR_ORG_MEM', 'User Organizations','/selfservice/userOrganizations.html',4);
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_USR_ORG_PUB', 'SS_USR_ORG', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_USR_ORG_DESC', 'SS_USR_ORG', 'MENU_DISPLAY_NAME', 'User Organizations');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERV_USER_EDIT_ROOT', 'SS_USR_ORG');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('SS_USR_ORG', '9');

INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ENSS_USR_ORG','1','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('DESS_USR_ORG','2','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESSS_USR_ORG','4','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUSS_USR_ORG','8','SS_USR_ORG','ResourceEntity.displayNameMap','Организации');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JASS_USR_ORG','9','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHSS_USR_ORG','10','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('PTSS_USR_ORG','11','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');

/***************************************ddl/1.alter_nickname.sql***************************************/
ALTER TABLE USERS MODIFY NICKNAME VARCHAR(100);

/***************************************dml/3.initial_cp_setup.sql***************************************/
CREATE OR REPLACE PROCEDURE SETUP_CONTENT_PROVIDERS (cpDomain IN VARCHAR, serverDomain IN VARCHAR) AS
  cnt NUMBER := 0;
BEGIN 
  SELECT count(1) INTO cnt FROM CONTENT_PROVIDER;
  IF (cnt = 0) THEN
    INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC, URL) VALUES('DEFAULT_CP', 'CONTENT_PROVIDER', 'Default Content Provider', 'Y', CONCAT(CONCAT('http://', cpDomain), '/selfservice'));
			INSERT INTO CONTENT_PROVIDER (CONTENT_PROVIDER_ID, CONTENT_PROVIDER_NAME, IS_PUBLIC, DOMAIN_PATTERN, IS_SSL, RESOURCE_ID, MANAGED_SYS_ID, LOGIN_URL, POSTBACK_URL_PARAM_NAME)
								   VALUES('DEFAULT_CP', 'Default Content Provider', 'Y', cpDomain, NULL, 'DEFAULT_CP', '0', '/idp/login.html', 'postbackURL');
			INSERT INTO CP_AUTH_LEVEL_GRP_XREF (CONTENT_PROVIDER_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES ('DEFAULT_CP', 'PASSWORD_AUTH', 0);
			INSERT INTO CONTENT_PROVIDER_SERVER (CONTENT_PROVIDER_SERVER_ID, CONTENT_PROVIDER_ID, SERVER_URL) VALUES ('DEFAULT_CP', 'DEFAULT_CP', serverDomain);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('DEF_CP_SELSERVICE_SLASH', 'URL_PATTERN', 'Default Content Provider /selfservice/*', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('DEF_CP_SELSERVICE_SLASH', 'DEFAULT_CP', '/selfservice/*', 'Y', 'DEF_CP_SELSERVICE_SLASH');

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('DEF_CP_WEBCONSOLE_AM_SLASH', 'URL_PATTERN', 'Default Content Provider /webconsole-am/*', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('DEF_CP_WEBCONSOLE_AM_SLASH', 'DEFAULT_CP', '/webconsole-am/*', 'Y', 'DEF_CP_WEBCONSOLE_AM_SLASH');

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('DEF_CP_WEBCONSOLE_IDM_SLASH', 'URL_PATTERN', 'Default Content Provider /webconsole-idm/*', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('DEF_CP_WEBCONSOLE_IDM_SLASH', 'DEFAULT_CP', '/webconsole-idm/*', 'Y', 'DEF_CP_WEBCONSOLE_IDM_SLASH');

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('DEF_CP_WEBCONSOLE_SLASH', 'URL_PATTERN', 'Default Content Provider /webconsole/*', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('DEF_CP_WEBCONSOLE_SLASH', 'DEFAULT_CP', '/webconsole/*', 'Y', 'DEF_CP_WEBCONSOLE_SLASH');

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('NEW_USER_TEMPLATE', 'UI_TEMPLATE', 'New User Template', 'Y');
			INSERT INTO METADATA_ELEMENT_PAGE_TEMPLATE (ID, NAME, RESOURCE_ID, IS_PUBLIC, TEMPLATE_TYPE_ID) VALUES('NEW_USER_TEMPLATE', 'New User Template', 'NEW_USER_TEMPLATE', 'Y', 'USER_TEMPLATE');
			INSERT INTO METADATA_URI_XREF (TEMPLATE_ID, URI_PATTERN_ID) VALUES('NEW_USER_TEMPLATE', 'DEF_CP_SELSERVICE_SLASH');

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('SELFREG_PATTERN', 'URL_PATTERN', 'Default Content Provider /selfservice/selfRegistration.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('SELFREG_PATTERN', 'DEFAULT_CP', '/selfservice/selfRegistration.html', 'Y', 'SELFREG_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('SELFREG_PATTERN', 'NONE', 0);
			INSERT INTO METADATA_URI_XREF (TEMPLATE_ID, URI_PATTERN_ID) VALUES('NEW_USER_TEMPLATE', 'SELFREG_PATTERN');

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('UI_STATIC', 'URL_PATTERN', 'Default Content Provider /openiam-ui-static/*', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('UI_STATIC', 'DEFAULT_CP', '/openiam-ui-static/*', 'Y', 'UI_STATIC');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('UI_STATIC', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('CHANGE_PASSWORD', 'URL_PATTERN', 'Default Content Provider /idp/changePassword.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('CHANGE_PASSWORD', 'DEFAULT_CP', '/idp/changePassword.html', 'Y', 'CHANGE_PASSWORD');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('CHANGE_PASSWORD', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('UNLOCK_PASSWORD', 'URL_PATTERN', 'Default Content Provider /idp/unlockPassword.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('UNLOCK_PASSWORD', 'DEFAULT_CP', '/idp/unlockPassword.html', 'Y', 'UNLOCK_PASSWORD');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('UNLOCK_PASSWORD', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('LOGOUT_PATTERN', 'URL_PATTERN', 'Default Content Provider /idp/logout.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('LOGOUT_PATTERN', 'DEFAULT_CP', '/idp/logout.html', 'Y', 'LOGOUT_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('LOGOUT_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('SAML_LOGIN_PATTERN', 'URL_PATTERN', 'Default Content Provider /idp/SAMLLogin.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('SAML_LOGIN_PATTERN', 'DEFAULT_CP', '/idp/SAMLLogin.html', 'Y', 'SAML_LOGIN_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('SAML_LOGIN_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('SAML_METADATA_PATTERN', 'URL_PATTERN', 'Default Content Provider /idp/SAMLMetadata.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('SAML_METADATA_PATTERN', 'DEFAULT_CP', '/idp/SAMLMetadata.html', 'Y', 'SAML_METADATA_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('SAML_METADATA_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('UNLOCK_PASSWORD_QUESTIONS', 'URL_PATTERN', 'Default Content Provider /idp/unlockPasswordQuestions.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('UNLOCK_PASSWORD_QUESTIONS', 'DEFAULT_CP', '/idp/unlockPasswordQuestions.html', 'Y', 'UNLOCK_PASSWORD_QUESTIONS');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('UNLOCK_PASSWORD_QUESTIONS', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('UNLOCK_USER_RESET_FORM', 'URL_PATTERN', 'Default Content Provider /idp/unlockUserResetPasswordForm.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('UNLOCK_USER_RESET_FORM', 'DEFAULT_CP', '/idp/unlockUserResetPasswordForm.html', 'Y', 'UNLOCK_USER_RESET_FORM');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('UNLOCK_USER_RESET_FORM', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('ACTIVATE_USER_FORM', 'URL_PATTERN', 'Default Content Provider /idp/activate.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('ACTIVATE_USER_FORM', 'DEFAULT_CP', '/idp/activate.html', 'Y', 'ACTIVATE_USER_FORM');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('ACTIVATE_USER_FORM', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('WEBCONSOLE_CLEAR_CNTX', 'URL_PATTERN', 'Default Content Provider /webconsole/clearContext.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('WEBCONSOLE_CLEAR_CNTX', 'DEFAULT_CP', '/webconsole/clearContext.html', 'Y', 'WEBCONSOLE_CLEAR_CNTX');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('WEBCONSOLE_CLEAR_CNTX', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('WEBCONSOLE_AM_CLEAR_CNTX', 'URL_PATTERN', 'Default Content Provider /webconsole-am/clearContext.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('WEBCONSOLE_AM_CLEAR_CNTX', 'DEFAULT_CP', '/webconsole-am/clearContext.html', 'Y', 'WEBCONSOLE_AM_CLEAR_CNTX');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('WEBCONSOLE_AM_CLEAR_CNTX', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('WEBCONSOLE_IDM_CLEAR_CNTX', 'URL_PATTERN', 'Default Content Provider /webconsole-idm/clearContext.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('WEBCONSOLE_IDM_CLEAR_CNTX', 'DEFAULT_CP', '/webconsole-idm/clearContext.html', 'Y', 'WEBCONSOLE_IDM_CLEAR_CNTX');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('WEBCONSOLE_IDM_CLEAR_CNTX', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('SELFSERVICE_CLEAR_CNTX', 'URL_PATTERN', 'Default Content Provider /selfservice/clearContext.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('SELFSERVICE_CLEAR_CNTX', 'DEFAULT_CP', '/selfservice/clearContext.html', 'Y', 'SELFSERVICE_CLEAR_CNTX');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('SELFSERVICE_CLEAR_CNTX', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('SELFSERVICE_EXT_CLEAR_CNTX', 'URL_PATTERN', 'Default Content Provider /selfservice-ext/clearContext.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('SELFSERVICE_EXT_CLEAR_CNTX', 'DEFAULT_CP', '/selfservice-ext/clearContext.html', 'Y', 'SELFSERVICE_EXT_CLEAR_CNTX');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('SELFSERVICE_EXT_CLEAR_CNTX', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('SEARCH_ORG_PATTERN', 'URL_PATTERN', 'Default Content Provider /selfservice/rest/api/entitlements/searchOrganizations', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('SEARCH_ORG_PATTERN', 'DEFAULT_CP', '/selfservice/rest/api/entitlements/searchOrganizations', 'Y', 'SEARCH_ORG_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('SEARCH_ORG_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('REPORTVIEWER_PATTERN', 'URL_PATTERN', 'Default Content Provider /reportviewer/*', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('REPORTVIEWER_PATTERN', 'DEFAULT_CP', '/reportviewer/*', 'Y', 'REPORTVIEWER_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('REPORTVIEWER_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('LANGUAGE_SUPPORT_PATTERN', 'URL_PATTERN', 'Default Content Provider /selfservice/language/languageSupport.html', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('LANGUAGE_SUPPORT_PATTERN', 'DEFAULT_CP', '/selfservice/language/languageSupport.html', 'Y', 'LANGUAGE_SUPPORT_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('LANGUAGE_SUPPORT_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('ROLE_METADATA_PATTERN', 'URL_PATTERN', 'Default Content Provider /selfservice/rest/api/metadata/roleMetadata', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('ROLE_METADATA_PATTERN', 'DEFAULT_CP', '/selfservice/rest/api/metadata/roleMetadata', 'Y', 'ROLE_METADATA_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('ROLE_METADATA_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('SEARCH_ROLES_PATTERN', 'URL_PATTERN', 'Default Content Provider /selfservice/rest/api/entitlements/searchRoles', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('SEARCH_ROLES_PATTERN', 'DEFAULT_CP', '/selfservice/rest/api/entitlements/searchRoles', 'Y', 'SEARCH_ROLES_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('SEARCH_ROLES_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('GROUP_METADATA_PATTERN', 'URL_PATTERN', 'Default Content Provider /selfservice/rest/api/metadata/groupMetadata', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('GROUP_METADATA_PATTERN', 'DEFAULT_CP', '/selfservice/rest/api/metadata/groupMetadata', 'Y', 'GROUP_METADATA_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('GROUP_METADATA_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('SEARCH_GROUPS_PATTERN', 'URL_PATTERN', 'Default Content Provider /selfservice/rest/api/entitlements/searchGroups', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('SEARCH_GROUPS_PATTERN', 'DEFAULT_CP', '/selfservice/rest/api/entitlements/searchGroups', 'Y', 'SEARCH_GROUPS_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('SEARCH_GROUPS_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('ORG_METADATA_PATTERN', 'URL_PATTERN', 'Default Content Provider /selfservice/rest/api/metadata/organizationMetadata', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('ORG_METADATA_PATTERN', 'DEFAULT_CP', '/selfservice/rest/api/metadata/organizationMetadata', 'Y', 'ORG_METADATA_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('ORG_METADATA_PATTERN', 'NONE', 0);

			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, IS_PUBLIC) VALUES('SP_PATTERN', 'URL_PATTERN', 'Default Content Provider /idp/sp/*', 'Y');
			INSERT INTO URI_PATTERN (URI_PATTERN_ID, CONTENT_PROVIDER_ID, PATTERN, IS_PUBLIC, RESOURCE_ID) VALUES('SP_PATTERN', 'DEFAULT_CP', '/idp/sp/*', 'Y', 'SP_PATTERN');
			INSERT INTO URI_AUTH_LEVEL_GRP_XREF (URI_PATTERN_ID, AUTH_LEVEL_GROUPING_ID, EXEC_ORDER) VALUES('SP_PATTERN', 'NONE', 0);
  END IF;
END SETUP_CONTENT_PROVIDERS;
/

/***************************************dml/4.add_access_review_btns.sql***************************************/

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_VIEW_ROOT', 'MENU_ITEM', 'Root menu for Access Review Tabs', 'AR_VIEW_ROOT', 'AR_VIEW_ROOT', null, 20, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_ROOT_PUB', 'AR_VIEW_ROOT', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_ROOT_DESC', 'AR_VIEW_ROOT', 'MENU_DISPLAY_NAME', 'Root menu for Access Review Tabs');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_VIEW_RES_BTN', 'MENU_ITEM', 'Resource View', 'AR_VIEW_RES_BTN', 'AR_VIEW_RES_BTN', '/selfservice/accessReview/getResourcesView.html', 21, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_RES_BTN_PUB', 'AR_VIEW_RES_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_RES_BTN_DESC', 'AR_VIEW_RES_BTN', 'MENU_DISPLAY_NAME', 'Resource View');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_VIEW_ROLE_BTN', 'MENU_ITEM', 'Role View', 'AR_VIEW_ROLE_BTN', 'AR_VIEW_ROLE_BTN', '/selfservice/accessReview/getRolesView.html', 22, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_ROLE_BTN_PUB', 'AR_VIEW_ROLE_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_ROLE_BTN_DESC', 'AR_VIEW_ROLE_BTN', 'MENU_DISPLAY_NAME', 'Role View');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_VIEW_ROOT', 'AR_VIEW_ROLE_BTN');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_VIEW_ROOT', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_VIEW_RES_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_VIEW_ROLE_BTN', '9');


INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_VIEW_ROOT','1','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_VIEW_ROOT','2','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_VIEW_ROOT','4','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_VIEW_ROOT','8','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_VIEW_ROOT','9','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_VIEW_ROOT','10','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_VIEW_ROOT','11','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_VIEW_RES_BTN','1','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_VIEW_RES_BTN','2','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_VIEW_RES_BTN','4','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_VIEW_RES_BTN','8','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_VIEW_RES_BTN','9','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_VIEW_RES_BTN','10','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_VIEW_RES_BTN','11','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_VIEW_ROLE_BTN','1','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_VIEW_ROLE_BTN','2','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_VIEW_ROLE_BTN','4','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_VIEW_ROLE_BTN','8','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_VIEW_ROLE_BTN','9','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_VIEW_ROLE_BTN','10','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_VIEW_ROLE_BTN','11','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');


DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_BTN_ROOT', 'MENU_ITEM', 'Root buttons for Access Review', 'AR_BTN_ROOT', 'AR_BTN_ROOT', null, 20, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_BTN_ROOT_PUB', 'AR_BTN_ROOT', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_BTN_ROOT_DESC', 'AR_BTN_ROOT', 'MENU_DISPLAY_NAME', 'Root buttons for Access Review');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_ADD_RES_BTN', 'MENU_ITEM', 'Resource View', 'AR_ADD_RES_BTN', 'AR_ADD_RES_BTN', '/selfservice/addUserToResource.html', 21, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_RES_BTN_PUB', 'AR_ADD_RES_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_RES_BTN_DESC', 'AR_ADD_RES_BTN', 'MENU_DISPLAY_NAME', 'Add Resource');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_ADD_ROLE_BTN', 'MENU_ITEM', 'Add Role', 'AR_ADD_ROLE_BTN', 'AR_ADD_ROLE_BTN', '/selfservice/addUserToRole.html', 22, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_ROLE_BTN_PUB', 'AR_ADD_ROLE_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_ROLE_BTN_DESC', 'AR_ADD_ROLE_BTN', 'MENU_DISPLAY_NAME', 'Add Role');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_ADD_GRP_BTN', 'MENU_ITEM', 'Add Group', 'AR_ADD_GRP_BTN', 'AR_ADD_GRP_BTN', '/selfservice/addUserToGroup.html', 23, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_GRP_BTN_PUB', 'AR_ADD_GRP_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_GRP_BTN_DESC', 'AR_ADD_GRP_BTN', 'MENU_DISPLAY_NAME', 'Add Group');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_RES_DEL_BTN', 'MENU_ITEM', 'Delete Resource', 'AR_RES_DEL_BTN', 'AR_RES_DEL_BTN', '/selfservice/removeUserFromResource.html', 24, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_RES_DEL_BTN_PUB', 'AR_RES_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_RES_DEL_BTN_DESC', 'AR_RES_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete Resource');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_ROLE_DEL_BTN', 'MENU_ITEM', 'Delete Role', 'AR_ROLE_DEL_BTN', 'AR_ROLE_DEL_BTN', '/selfservice/removeUserFromRole.html', 25, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ROLE_DEL_BTN_PUB', 'AR_ROLE_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ROLE_DEL_BTN_DESC', 'AR_ROLE_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete Role');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_GRP_DEL_BTN', 'MENU_ITEM', 'Delete Group', 'AR_GRP_DEL_BTN', 'AR_GRP_DEL_BTN', '/selfservice/removeUserFromGroup.html', 26, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_GRP_DEL_BTN_PUB', 'AR_GRP_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_GRP_DEL_BTN_DESC', 'AR_GRP_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete Group');


INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_ADD_RES_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_ADD_ROLE_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_ADD_GRP_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_RES_DEL_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_ROLE_DEL_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_GRP_DEL_BTN');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_BTN_ROOT', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_ADD_RES_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_ADD_ROLE_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_ADD_GRP_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_RES_DEL_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_ROLE_DEL_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_GRP_DEL_BTN', '9');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_BTN_ROOT','1','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_BTN_ROOT','2','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_BTN_ROOT','4','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_BTN_ROOT','8','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_BTN_ROOT','9','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_BTN_ROOT','10','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_BTN_ROOT','11','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_ADD_RES_BTN','1','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_ADD_RES_BTN','2','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_ADD_RES_BTN','4','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_ADD_RES_BTN','8','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_ADD_RES_BTN','9','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_ADD_RES_BTN','10','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_ADD_RES_BTN','11','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_ADD_ROLE_BTN','1','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_ADD_ROLE_BTN','2','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_ADD_ROLE_BTN','4','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_ADD_ROLE_BTN','8','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_ADD_ROLE_BTN','9','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_ADD_ROLE_BTN','10','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_ADD_ROLE_BTN','11','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_ADD_GRP_BTN','1','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_ADD_GRP_BTN','2','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_ADD_GRP_BTN','4','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_ADD_GRP_BTN','8','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_ADD_GRP_BTN','9','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_ADD_GRP_BTN','10','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_ADD_GRP_BTN','11','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_RES_DEL_BTN','1','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_RES_DEL_BTN','2','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_RES_DEL_BTN','4','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_RES_DEL_BTN','8','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_RES_DEL_BTN','9','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_RES_DEL_BTN','10','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_RES_DEL_BTN','11','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_ROLE_DEL_BTN','1','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_ROLE_DEL_BTN','2','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_ROLE_DEL_BTN','4','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_ROLE_DEL_BTN','8','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_ROLE_DEL_BTN','9','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_ROLE_DEL_BTN','10','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_ROLE_DEL_BTN','11','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');


INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_GRP_DEL_BTN','1','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_GRP_DEL_BTN','2','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_GRP_DEL_BTN','4','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_GRP_DEL_BTN','8','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_GRP_DEL_BTN','9','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_GRP_DEL_BTN','10','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_GRP_DEL_BTN','11','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');

/***************************************dml/5.add_save_btn.sql***************************************/

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('SS_SAVE_USER_BTN', 'MENU_ITEM', 'Save User Button', 'SS_SAVE_USER_BTN', 'SS_SAVE_USER_BTN', null, 20, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_SAVE_USER_BTN_PUB', 'SS_SAVE_USER_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_SAVE_USER_BTN_DESC', 'SS_SAVE_USER_BTN', 'MENU_DISPLAY_NAME', 'Save User Button');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('SS_SAVE_USER_BTN', '9');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_SS_SAVE_USER_BTN','1','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_SS_SAVE_USER_BTN','2','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_SS_SAVE_USER_BTN','4','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_SS_SAVE_USER_BTN','8','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_SS_SAVE_USER_BTN','9','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_SS_SAVE_USER_BTN','10','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_SS_SAVE_USER_BTN','11','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');

/***************************************oracle fix ( change field from clob to varchar2(4000)***************************************/
ALTER TABLE USER_ATTRIBUTES ADD VALUE_CHAR VARCHAR2(4000);

DECLARE
 v_v varchar2(4000);
 CURSOR curl is SELECT ID, VALUE FROM USER_ATTRIBUTES WHERE VALUE IS NOT NULL;
BEGIN 
  FOR get_cur IN curl LOOP
    v_v := get_cur.VALUE;
    UPDATE USER_ATTRIBUTES SET VALUE_CHAR=v_v WHERE ID=get_cur.ID;				
	END LOOP;			
END;
/

ALTER TABLE USER_ATTRIBUTES DROP COLUMN VALUE;
ALTER TABLE USER_ATTRIBUTES RENAME COLUMN VALUE_CHAR TO VALUE;


/***************************************dml/6.add_sp_attributes.sql***************************************/
INSERT INTO AUTH_ATTRIBUTE (AUTH_ATTRIBUTE_ID, ATTRIBUTE_NAME, PROVIDER_TYPE, DESCRIPTION, REQUIRED, DATA_TYPE)
	VALUES('SpNameQualifierForSP', 'SP Name Qualifier', 'SAML_SP_PROVIDER', 'This is the SP Name Qualifier inside of the NameIdPolicy', 'N', 'singleValue');
	
	
INSERT INTO AUTH_ATTRIBUTE (AUTH_ATTRIBUTE_ID, ATTRIBUTE_NAME, PROVIDER_TYPE, DESCRIPTION, REQUIRED, DATA_TYPE)
	VALUES('SpAuthnRequestDestination', 'Destination attribute enabled', 'SAML_SP_PROVIDER', 'Does the AuthnRequest has a Destination attribute?  If true, it will be set to the value of the ACS of this Service Provider', 'N', 'booleanValue');
	
INSERT INTO AUTH_ATTRIBUTE (AUTH_ATTRIBUTE_ID, ATTRIBUTE_NAME, PROVIDER_TYPE, DESCRIPTION, REQUIRED, DATA_TYPE)
	VALUES('SpNameIdAllowCreate', 'AllowCreate on the NameIdPolicy', 'SAML_SP_PROVIDER', 'Sets the value of the AllowCreate attribute on the NameIdPolicy to true, or false', 'N', 'booleanValue');
	
INSERT INTO AUTH_ATTRIBUTE (AUTH_ATTRIBUTE_ID, ATTRIBUTE_NAME, PROVIDER_TYPE, DESCRIPTION, REQUIRED, DATA_TYPE)
	VALUES('SpAuthnContextClassRef', 'AuthnContextClassRef element value', 'SAML_SP_PROVIDER', 'If present, the AuthnRequest will contain a RequestedAuthnContext element with a AuthnContextClassRef', 'N', 'singleValue');
		

INSERT INTO AUTH_ATTRIBUTE (AUTH_ATTRIBUTE_ID, ATTRIBUTE_NAME, PROVIDER_TYPE, DESCRIPTION, REQUIRED, DATA_TYPE)
	VALUES('SamlRequestIssuerFormat', 'Issuer Format', 'SAML_SP_PROVIDER', 'The Format of the AuthnRequest Issuer', 'N', 'singleValue');
  
/***************************************dml/7.update_res_cert_report.sql***************************************/
DECLARE
 num1 NUMBER:= 0;
 num2 NUMBER:= 0;
 num3 NUMBER:= 0;
BEGIN
  SELECT count(*) INTO num1 FROM REPORT_INFO WHERE REPORT_INFO_ID = '106';
  SELECT count(*) INTO num2 FROM REPORT_PARAMETER_METATYPE WHERE PARAM_METATYPE_ID = 'RESOURCE_TYPE';
  SELECT count(*) INTO num3 FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID = '1065';
  IF ((num1 > 0) AND (num2 > 0) AND (num3 < 1)) THEN
    INSERT INTO REPORT_CRITERIA_PARAMETER 
          (RCP_ID,REPORT_INFO_ID,PARAM_NAME,PARAM_VALUE,RCPT_ID,PARAM_META_TYPE_ID,IS_MULTIPLE,IS_REQUIRED,CAPTION,DISPLAY_ORDER,REQUEST_PARAMS) 
          VALUES ('1065', '106', 'RES_TYPE_ID', NULL, 1, 'RESOURCE_TYPE', 'N', 'N', 'Resource Type', 4, NULL);
      
      UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 1 WHERE RCP_ID = '1063';
      UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 2 WHERE RCP_ID = '1064';
      UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 3 WHERE RCP_ID = '1061';
      UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 5, IS_MULTIPLE = 'Y', PARAM_NAME = 'RES_IDS', 
          REQUEST_PARAMS = '{"resourceTypeId":"${RES_TYPE_ID}","ownerId":"${OWNER_ID}"}' WHERE RCP_ID = '1062';
  END IF;
END;
/


/***************************************dml/8.add_sp_attributes.sql***************************************/
INSERT INTO AUTH_ATTRIBUTE (AUTH_ATTRIBUTE_ID, ATTRIBUTE_NAME, PROVIDER_TYPE, DESCRIPTION, REQUIRED, DATA_TYPE)
	VALUES('SendNameIdInSAMLRequest', 'Send NameID in SAMLRequest', 'SAML_SP_PROVIDER', 'Sends the NameID in SAML Request', 'N', 'booleanValue');

/***************************************dml/9.add_sp_attributes.sql***************************************/
DELETE FROM AUTH_PROVIDER_ATTRIBUTE WHERE AUTH_ATTRIBUTE_ID IN('SendNameIdInSAMLRequest', 'SPNameIdToSendInSAMLRequest');
DELETE FROM AUTH_ATTRIBUTE WHERE AUTH_ATTRIBUTE_ID IN('SendNameIdInSAMLRequest', 'SPNameIdToSendInSAMLRequest');

INSERT INTO AUTH_ATTRIBUTE (AUTH_ATTRIBUTE_ID, ATTRIBUTE_NAME, PROVIDER_TYPE, DESCRIPTION, REQUIRED, DATA_TYPE)
	VALUES('SPNameIdToSendInSAMLRequest', 'NameID IN SAML Request', 'SAML_SP_PROVIDER', 'NameID Format to send in the NameIDPolicy of the SAMLRequest', 'N', 'singleValue');


commit;