USE openiam;

ALTER TABLE SYNCH_REVIEW_RECORD_VALUE MODIFY COLUMN  VALUE VARCHAR(4000);
ALTER TABLE REQUEST_ATTRIBUTE MODIFY COLUMN  VALUE VARCHAR(4000);
ALTER TABLE METADATA_ELEMENT MODIFY COLUMN  STATIC_DEFAULT_VALUE VARCHAR(4000);
ALTER TABLE LOGIN_ATTRIBUTE MODIFY COLUMN  VALUE VARCHAR(4000);
ALTER TABLE URI_PATTERN_META_VALUE MODIFY COLUMN  STATIC_VALUE VARCHAR(4000);
ALTER TABLE AUTH_PROVIDER_ATTRIBUTE MODIFY COLUMN  VALUE VARCHAR(4000);
ALTER TABLE AUTH_LEVEL_ATTRIBUTE MODIFY COLUMN  VALUE_AS_STRING VARCHAR(4000);
ALTER TABLE AUTH_ATTRIBUTE MODIFY COLUMN  DEFAULT_VALUE VARCHAR(4000);
ALTER TABLE ROLE_ATTRIBUTE MODIFY COLUMN  ATTR_VALUE VARCHAR(4000);
ALTER TABLE RESOURCE_PROP MODIFY COLUMN  ATTR_VALUE VARCHAR(4000);
ALTER TABLE COMPANY_ATTRIBUTE MODIFY COLUMN  ATTR_VALUE VARCHAR(4000);
ALTER TABLE GRP_ATTRIBUTES MODIFY COLUMN  ATTR_VALUE VARCHAR(4000);

