use openiam;

ALTER TABLE LOCATION MODIFY ACTIVE CHAR(1) NULL DEFAULT 'Y';
ALTER TABLE LOCATION MODIFY NAME VARCHAR(100) NULL;
ALTER TABLE LOCATION MODIFY COUNTRY VARCHAR(100) NULL;
ALTER TABLE LOCATION MODIFY CITY VARCHAR(100) NULL;
ALTER TABLE LOCATION MODIFY STATE VARCHAR(100) NULL;
ALTER TABLE LOCATION MODIFY POSTAL_CD VARCHAR(100) NULL;
ALTER TABLE LOCATION MODIFY BLDG_NUM VARCHAR(100) NULL;

ALTER TABLE ADDRESS ADD COLUMN COPY_FROM_LOCATION_ID VARCHAR(32) NULL;
commit;

