use openiam;

ALTER TABLE LOCATION MODIFY ADDRESS1 VARCHAR(400) NULL;
ALTER TABLE LOCATION MODIFY ADDRESS2 VARCHAR(400) NULL;
ALTER TABLE LOCATION MODIFY ADDRESS3 VARCHAR(400) NULL;

ALTER TABLE ADDRESS MODIFY ADDRESS1 VARCHAR(400) NULL;
ALTER TABLE ADDRESS MODIFY ADDRESS2 VARCHAR(400) NULL;
ALTER TABLE ADDRESS MODIFY ADDRESS3 VARCHAR(400) NULL;
ALTER TABLE ADDRESS MODIFY ADDRESS4 VARCHAR(400) NULL;
ALTER TABLE ADDRESS MODIFY ADDRESS5 VARCHAR(400) NULL;
ALTER TABLE ADDRESS MODIFY ADDRESS6 VARCHAR(400) NULL;
ALTER TABLE ADDRESS MODIFY ADDRESS7 VARCHAR(400) NULL;


