use openiam;

ALTER TABLE GRP
	ADD COLUMN GRP_CLASSIFICATION VARCHAR(32) NULL,
	ADD COLUMN AD_GRP_TYPE VARCHAR(32) NULL,
	ADD COLUMN AD_GRP_SCOPE VARCHAR(32) NULL,
	ADD COLUMN GRP_RISK VARCHAR(32) NULL,
	ADD COLUMN MAX_USER_NUMBER INT NULL,
	ADD COLUMN MEMBERSHIP_DURATION_SECONDS bigint(20) NULL;

ALTER TABLE GRP
	ADD CONSTRAINT GRP_CLASS_FK FOREIGN KEY (GRP_CLASSIFICATION) REFERENCES METADATA_TYPE (TYPE_ID),
	ADD CONSTRAINT GRP_AD_TYPE_FK FOREIGN KEY (AD_GRP_TYPE) REFERENCES METADATA_TYPE (TYPE_ID),
	ADD CONSTRAINT GRP_AD_SCOPE_FK FOREIGN KEY (AD_GRP_SCOPE) REFERENCES METADATA_TYPE (TYPE_ID),
	ADD CONSTRAINT GRP_RISK_FK FOREIGN KEY (GRP_RISK) REFERENCES METADATA_TYPE (TYPE_ID);

CREATE TABLE GROUP_ORGANIZATION (
  GRP_ID VARCHAR(32) NULL,
  COMPANY_ID VARCHAR(32) NULL,
  CONSTRAINT FK_GRP FOREIGN KEY (GRP_ID)REFERENCES GRP (GRP_ID),
  CONSTRAINT FK_ORG FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID));

ALTER TABLE GRP DROP FOREIGN KEY GRP_COMPANY_FK;
ALTER TABLE GRP DROP COLUMN COMPANY_ID, DROP INDEX GRP_COMPANY_FK ;
