use openiam;


DELIMITER $$

DROP PROCEDURE IF EXISTS ALTER_CP$$

CREATE PROCEDURE ALTER_CP()
	BEGIN
		IF EXISTS (SELECT * FROM information_schema.columns WHERE table_schema='openiam' AND table_name = 'CONTENT_PROVIDER' AND column_name = 'LOGIN_URL') THEN
			ALTER TABLE CONTENT_PROVIDER DROP COLUMN LOGIN_URL;
 		END IF;
 		
 		IF EXISTS (SELECT * FROM information_schema.columns WHERE table_schema='openiam' AND table_name = 'CONTENT_PROVIDER' AND column_name = 'POSTBACK_URL_PARAM_NAME') THEN
			ALTER TABLE CONTENT_PROVIDER DROP COLUMN POSTBACK_URL_PARAM_NAME;
 		END IF;

 		
		ALTER TABLE CONTENT_PROVIDER ADD COLUMN LOGIN_URL VARCHAR(300) NULL;
		ALTER TABLE CONTENT_PROVIDER ADD COLUMN POSTBACK_URL_PARAM_NAME VARCHAR(50) NULL;
		
		UPDATE CONTENT_PROVIDER SET LOGIN_URL='/idp/login.html';
		UPDATE CONTENT_PROVIDER SET POSTBACK_URL_PARAM_NAME='postbackURL';
		
		ALTER TABLE CONTENT_PROVIDER MODIFY COLUMN LOGIN_URL VARCHAR(300) NOT NULL;
		ALTER TABLE CONTENT_PROVIDER MODIFY COLUMN POSTBACK_URL_PARAM_NAME VARCHAR(50) NOT NULL;
	END$$
DELIMITER ;

call ALTER_CP();
DROP PROCEDURE ALTER_CP;
