use openiam;

delete from LANGUAGE_MAPPING where ID like '%UI_FIELD_TEMPLATE_EN%';



DECLARE @cnt INT;
SET @cnt = 0;
DECLARE @uifieldid NVARCHAR(32);
DECLARE @xrefid NVARCHAR(32);
DECLARE @name NVARCHAR(100);
DECLARE cur123 CURSOR FOR (SELECT a1.UI_FIELD_ID, a1.XREF_ID, a2.NAME FROM UI_FIELD_TEMPLATE_XREF a1 INNER JOIN UI_TEMPLATE_FIELDS a2 ON a1.UI_FIELD_ID=a2.UI_FIELD_ID);
OPEN cur123;		

FETCH NEXT FROM cur123 INTO @uifieldid, @xrefid, @name;
WHILE @@FETCH_STATUS = 0
BEGIN
	IF (@xrefid IS NOT NULL) 
	BEGIN
		IF NOT EXISTS (SELECT * FROM LANGUAGE_MAPPING WHERE LANGUAGE_ID='1' AND REFERENCE_ID=@xrefid) 
		BEGIN
			SET @cnt = @cnt + 1;
			INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ({fn CONCAT('UI_FIELD_TEMPLATE_EN_',CAST(@cnt AS VARCHAR(10)))},'1',@xrefid,'MetadataFieldTemplateXrefEntity.languageMap', @name);
		END;
	END;
END;
CLOSE cur123;


