/* 1 */

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM RES WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('ACCESSCENTER');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('ACCESSCENTER_MENU_DISPLAY', 'ACCESSCENTER', 'MENU_DISPLAY_NAME', 'Access Management');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('ACCESSCENTER_MENU_ICON', 'ACCESSCENTER', 'MENU_ICON', '/openiam-ui-static/images/common/icons/access_control.png');

/* 2 */

DELETE FROM POLICY_ATTRIBUTE WHERE DEF_PARAM_ID IN('131','141', '180', '181', '182', '183');
DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID IN('131','141', '182','183');
INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, VALUE1, REQUIRED) VALUES ('4052', '180', '4000', 'MIN_WORDS_PASSPHRASE', '', 'Y');
INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, VALUE1, REQUIRED) VALUES ('4053', '181', '4000', 'REPEAT_SAME_WORD_PASSPHRASE', '', 'Y');
INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID, POLICY_DEF_ID, NAME, DESCRIPTION, PARAM_GROUP, POLICY_PARAM_HANDLER) VALUES ('182', '100', 'LIMIT_NUM_REPEAT_CHAR', 'Limit the repetition of same character', 'PSWD_COMPOSITION', 'org.openiam.idm.srvc.pswd.rule.LimitNumberRepeatCharRule');
INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, REQUIRED) VALUES ('4054', '182', '4000', 'LIMIT_NUM_REPEAT_CHAR', 'Y');
INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID, POLICY_DEF_ID, NAME, DESCRIPTION, PARAM_GROUP, POLICY_PARAM_HANDLER) VALUES ('183', '100', 'PWD_PASSWORD', 'Cannot repeat same Password', 'PSWD_COMPOSITION','org.openiam.idm.srvc.pswd.rule.PasswordNotPasswordRule');
INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, REQUIRED) VALUES ('4200', '183', '4000', 'PWD_PASSWORD', 'Y');

/* 3 */

DELETE FROM POLICY_ATTRIBUTE WHERE POLICY_ATTR_ID IN('NUM_DAYS_FRGT_PWD_TOKEN_VALID');
DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID IN('NUM_DAYS_FRGT_PWD_TOKEN_VALID');

INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID, POLICY_DEF_ID, NAME, DESCRIPTION, PARAM_GROUP) VALUES ('NUM_DAYS_FRGT_PWD_TOKEN_VALID', '100', 'NUM_DAYS_FORGET_PWD_TOKEN_VALID', 'Number of days the forgot password token is valid', 'FORGET_PSWD');
INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, REQUIRED) VALUES ('NUM_DAYS_FRGT_PWD_TOKEN_VALID', 'NUM_DAYS_FRGT_PWD_TOKEN_VALID', '4000', 'NUM_DAYS_FORGET_PWD_TOKEN_VALID', 'Y');


/* 4 */

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('WEB_REPORT', 'SELFSERVICE_REPORT');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('WEB_REPORT_DESC', 'WEB_REPORT', 'MENU_DISPLAY_NAME', 'Report');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('WEB_REPORT_PUB', 'WEB_REPORT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('WEB_REPORT_DISPLAY', 'WEB_REPORT', 'MENU_ICON', '/openiam-ui-static/images/common/icons/reports.png');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('SELFSERVICE_REPORT_DESC', 'SELFSERVICE_REPORT', 'MENU_DISPLAY_NAME', 'Report');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('SELFSERVICE_REPORT_PUB', 'SELFSERVICE_REPORT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('SELFSERVICE_REPORT_DISPLAY', 'SELFSERVICE_REPORT', 'MENU_ICON', '/openiam-ui-static/images/common/icons/reports.png');


/* 5 */

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT_ORG';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT_ORG';
DELETE FROM RES WHERE RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT_ORG';

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT';
DELETE FROM RES WHERE RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT';

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELF_SUB_ORGS_NEW';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELF_SUB_ORGS_NEW';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_NEW';

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELF_SUB_ORGS_SEARCH';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELF_SUB_ORGS_SEARCH';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_SEARCH';

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELF_SUB_ORGS_EDIT';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELF_SUB_ORGS_EDIT';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_EDIT';

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELF_SUB_ORGS_MEMEBERSHIP';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELF_SUB_ORGS_MEMEBERSHIP';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_MEMEBERSHIP';

DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_ROOT';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_EDIT_ROOT';


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELFSRVS_ACCESS_MNGMNT', 'MENU_ITEM', 'Access Managment', 'SELFSRVS_ACCESS_MNGMNT', 6, '');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ACC_MNGMNT_DESC', 'SELFSRVS_ACCESS_MNGMNT', 'MENU_DISPLAY_NAME', 'Access managment');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ACC_MNGMNT_MENU_ICON', 'SELFSRVS_ACCESS_MNGMNT', 'MENU_ICON', '/openiam-ui-static/images/common/icons/access_control.png');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ACC_MNGMNT_MENU_PUB', 'SELFSRVS_ACCESS_MNGMNT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELFSRVS_ACCESS_MNGMNT', 'SELFSERVICE');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELFSRVS_ACCESS_MNGMNT_ORG', 'MENU_ITEM', 'Selfservice organization', 'SELFSRVS_ACCESS_MNGMNT_ORG', 1, '/selfservice/organizations.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSRVS_ACCESS_MNGMNT_ORG_DESC', 'SELFSRVS_ACCESS_MNGMNT_ORG', 'MENU_DISPLAY_NAME', 'Organizations');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELFSRVS_ACCESS_MNGMNT_ORG', 'SELFSRVS_ACCESS_MNGMNT');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_ROOT', 'MENU_ITEM', 'organizations menu', 'SELF_SUB_ORGS_ROOT', 2, '');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_NEW', 'MENU_ITEM', 'add organization', 'SELF_SUB_ORGS_NEW', 1, '/selfservice/editOrganization.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ACC_MNGMNT_ORG_NEW_DESC', 'SELF_SUB_ORGS_NEW', 'MENU_DISPLAY_NAME', 'New Organization');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELF_SUB_ORGS_NEW', 'SELF_SUB_ORGS_ROOT');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_SEARCH', 'MENU_ITEM', 'add organization', 'SELF_SUB_ORGS_SEARCH', 1, '/selfservice/organizations.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ACC_MG_ORG_SEARCH_DESC', 'SELF_SUB_ORGS_SEARCH', 'MENU_DISPLAY_NAME', 'Search Organization');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELF_SUB_ORGS_SEARCH', 'SELF_SUB_ORGS_ROOT');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_EDIT_ROOT', 'MENU_ITEM', 'organizations menu', 'SELF_SUB_ORGS_EDIT_ROOT', 2, '');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_EDIT', 'MENU_ITEM', 'add organization', 'SELF_SUB_ORGS_EDIT', 1, '/selfservice/editOrganization.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ACC_MNGMNT_ORG_EDIT_DESC', 'SELF_SUB_ORGS_EDIT', 'MENU_DISPLAY_NAME', 'Edit Organization');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELF_SUB_ORGS_EDIT', 'SELF_SUB_ORGS_EDIT_ROOT');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_MEMEBERSHIP', 'MENU_ITEM', 'add organization', 'SELF_SUB_ORGS_MEMEBERSHIP', 1, '/selfservice/membership-organizations.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ACC_ORG_MEM_DESC', 'SELF_SUB_ORGS_MEMEBERSHIP', 'MENU_DISPLAY_NAME', 'Organization Membership');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELF_SUB_ORGS_MEMEBERSHIP', 'SELF_SUB_ORGS_EDIT_ROOT');



/* 6 */

DELETE FROM MNG_SYS_OBJECT_MATCH WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM MANAGED_SYS_ATTRIBUTE WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM MNG_SYS_GROUP WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM REQ_APPROVER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM MNG_SYS_LIST WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM ATTRIBUTE_MAP WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM SYNCH_CONFIG WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM SYNCH_CONFIG WHERE MATCH_MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM AUTH_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM MANAGED_SYS_RULE WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM CONTENT_PROVIDER_SERVER WHERE CONTENT_PROVIDER_ID IN(
	SELECT CONTENT_PROVIDER_ID FROM CONTENT_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202')
);
DELETE FROM URI_PATTERN_META_VALUE WHERE URI_PATTERN_META_ID IN(
	SELECT URI_PATTERN_META_ID FROM URI_PATTERN_META WHERE URI_PATTERN_ID IN(
		SELECT URI_PATTERN_ID FROM URI_PATTERN WHERE CONTENT_PROVIDER_ID IN(	
			SELECT CONTENT_PROVIDER_ID FROM CONTENT_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202')
		)
	)
);
DELETE FROM URI_PATTERN_META WHERE URI_PATTERN_ID IN(
	SELECT URI_PATTERN_ID FROM URI_PATTERN WHERE CONTENT_PROVIDER_ID IN(	
		SELECT CONTENT_PROVIDER_ID FROM CONTENT_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202')
	)
);
DELETE FROM URI_PATTERN WHERE CONTENT_PROVIDER_ID IN(
	SELECT CONTENT_PROVIDER_ID FROM CONTENT_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202')
);
DELETE FROM CONTENT_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM GRP WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM LOGIN WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM RES WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN (SELECT RESOURCE_ID FROM RES WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202'));
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN (SELECT RESOURCE_ID FROM RES WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202'));
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN (SELECT RESOURCE_ID FROM RES WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202'));
DELETE FROM MANAGED_SYS WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');



/* 7 */
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SYNCLOG');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('SYNCLOG');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SYNCLOG');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SYNCLOG');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SYNCLOG');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SYNCLOG');
DELETE FROM RES WHERE RESOURCE_ID IN ('SYNCLOG');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SYNCLOG', 'MENU_ITEM', 'Log Viewer', 'SYNCLOG', 1, '/webconsole/viewAuditLog.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SYNCLOG_ADMIN_DESC', 'SYNCLOG', 'MENU_DISPLAY_NAME', 'Log Viewer');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SYNCLOG_ADMIN_PUB', 'SYNCLOG', 'MENU_IS_PUBLIC', 'true');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SYNCLOG', 'ADMIN');


/* 8 */

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SELFSRVS_ACCESS_MNGMNT', 'SELFSRVS_ACCESS_MNGMNT_ORG');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('SELFSRVS_ACCESS_MNGMNT', 'SELFSRVS_ACCESS_MNGMNT_ORG');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SELFSRVS_ACCESS_MNGMNT');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SELFSRVS_ACCESS_MNGMNT');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SELFSRVS_ACCESS_MNGMNT');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SELFSRVS_ACCESS_MNGMNT');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('SELFSRVS_ACCESS_MNGMNT');
DELETE FROM RES WHERE RESOURCE_ID IN ('SELFSRVS_ACCESS_MNGMNT');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ACCESSCENTER', 'SELFSRVS_ACCESS_MNGMNT_ORG');




/* 9 */
UPDATE ATTRIBUTE_MAP SET DATA_TYPE='STRING' WHERE DATA_TYPE='string';
UPDATE ATTRIBUTE_MAP SET DATA_TYPE='MEMBER_OF' WHERE DATA_TYPE='memberOf';
DELETE FROM MNG_SYS_OBJECT_MATCH WHERE MANAGED_SYS_ID = '101' AND OBJECT_SEARCH_ID='100';

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('254');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('254');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('254');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('254');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('254');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('254');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('254');
DELETE FROM RES WHERE RESOURCE_ID IN ('254');
