ALTER TABLE COMPANY
ADD COLUMN INTERNAL_COMPANY_NAME  VARCHAR(200) NULL;


INSERT INTO NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('402888ea3d9ad61c013d9adce1b2000a','USER_PASSWORD_EMAIL','UserPasswordNotification.groovy','SYSTEM');


commit;