ALTER TABLE COMPANY
ADD COLUMN INTERNAL_COMPANY_NAME  VARCHAR(200) NULL;

ALTER TABLE `RECONCILIATION_CONFIG`
ADD COLUMN `CSV_LINE_SEPARATOR` VARCHAR(10) NULL DEFAULT 'comma',
ADD COLUMN `CSV_END_OF_LINE` VARCHAR(10) NULL DEFAULT 'enter';

ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN NOTIFICATION_EMAIL_ADDRESS VARCHAR(80) NULL;

INSERT INTO NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('402888ea3d9ad61c013d9adce1b2000a','USER_PASSWORD_EMAIL','UserPasswordNotification.groovy','SYSTEM');


commit;