use openiam;
ALTER TABLE USERS modify column ADDRESS1 VARCHAR(255) NULL;
ALTER TABLE USERS modify column ADDRESS2 VARCHAR(255) NULL;

ALTER TABLE USERS modify column ADDRESS3 VARCHAR(255) NULL;
ALTER TABLE USERS modify column ADDRESS4 VARCHAR(255) NULL;
ALTER TABLE USERS modify column ADDRESS5 VARCHAR(255) NULL;
ALTER TABLE USERS modify column ADDRESS6 VARCHAR(255) NULL;
ALTER TABLE USERS modify column ADDRESS7 VARCHAR(255) NULL;
ALTER TABLE USERS modify column CITY VARCHAR(45) NULL;
ALTER TABLE USERS modify column STATE VARCHAR(45) NULL;
