USE openiam;

GO
ALTER TABLE APPROVER_ASSOC ADD APPROVER_ENTITY_TYPE NVARCHAR(20);
ALTER TABLE APPROVER_ASSOC ADD APPROVER_ENTITY_ID NVARCHAR(32);
ALTER TABLE APPROVER_ASSOC ADD APPLY_DELEGATION_FILTER_T char(1);
ALTER TABLE CONTENT_PROVIDER ADD MANAGED_SYS_ID NVARCHAR(32);
GO

ALTER TABLE RECONCILIATION_CONFIG ADD CSV_LINE_SEPARATOR NVARCHAR(10) DEFAULT 'comma';
ALTER TABLE RECONCILIATION_CONFIG ADD CSV_END_OF_LINE NVARCHAR(10) DEFAULT 'enter';
ALTER TABLE RECONCILIATION_CONFIG ADD NOTIFICATION_EMAIL_ADDRESS NVARCHAR(120);
ALTER TABLE RECONCILIATION_CONFIG ADD TARGET_SYS_MATCH_SCRIPT NVARCHAR(120);
   


UPDATE USERS SET DIVISION=null WHERE DIVISION='';
UPDATE USERS SET DEPT_CD=null WHERE DEPT_CD='';
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_DEPARTMENT FOREIGN KEY (DEPT_CD) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_DIVISION FOREIGN KEY (DIVISION) REFERENCES COMPANY (COMPANY_ID);
CREATE INDEX FK_USERS_DEPARTMENT ON USERS(DEPT_CD);
CREATE INDEX FK_USERS_DIVISION ON USERS(DIVISION);


EXEC sp_RENAME 'APPROVER_ASSOC.[ASSOCIATION_OBJ_ID]' , 'ASSOCIATION_ENTITY_ID', 'COLUMN';
ALTER TABLE APPROVER_ASSOC ALTER COLUMN ASSOCIATION_ENTITY_ID NVARCHAR(32);


EXEC sp_RENAME 'APPROVER_ASSOC.[ON_APPROVE_NOTIFY_USER_ID]' , 'ON_APPROVE_ENTITY_ID', 'COLUMN';
EXEC sp_RENAME 'APPROVER_ASSOC.[ON_REJECT_NOTIFY_USER_ID]' , 'ON_REJECT_ENTITY_ID', 'COLUMN';
ALTER TABLE APPROVER_ASSOC ALTER COLUMN ON_APPROVE_ENTITY_ID NVARCHAR(32);
ALTER TABLE APPROVER_ASSOC ALTER COLUMN ON_REJECT_ENTITY_ID NVARCHAR(32);


EXEC sp_RENAME 'APPROVER_ASSOC.[APPROVE_NOTIFY_USER_TYPE]' , 'ON_APPROVE_ENTITY_TYPE', 'COLUMN';
EXEC sp_RENAME 'APPROVER_ASSOC.[REJECT_NOTIFY_USER_TYPE]' , 'ON_REJECT_ENTITY_TYPE', 'COLUMN';
ALTER TABLE APPROVER_ASSOC ALTER COLUMN ON_APPROVE_ENTITY_TYPE NVARCHAR(20);
ALTER TABLE APPROVER_ASSOC ALTER COLUMN ON_REJECT_ENTITY_TYPE NVARCHAR(20);

--ALTER TABLE APPROVER_ASSOC DROP COLUMN ACTN;

ALTER TABLE APPROVER_ASSOC DROP COLUMN APPROVER_ROLE_DOMAIN;


UPDATE APPROVER_ASSOC SET APPROVER_ENTITY_TYPE='USER', APPROVER_ENTITY_ID=APPROVER_USER_ID WHERE APPROVER_USER_ID IS NOT NULL;
UPDATE APPROVER_ASSOC SET APPROVER_ENTITY_TYPE='ROLE', APPROVER_ENTITY_ID=APPROVER_ROLE_ID WHERE APPROVER_ROLE_ID IS NOT NULL;

ALTER TABLE APPROVER_ASSOC DROP COLUMN APPROVER_ROLE_ID;
ALTER TABLE APPROVER_ASSOC DROP COLUMN APPROVER_USER_ID;

UPDATE APPROVER_ASSOC SET APPLY_DELEGATION_FILTER_T='Y' WHERE APPLY_DELEGATION_FILTER=1;
UPDATE APPROVER_ASSOC SET APPLY_DELEGATION_FILTER_T='N' WHERE APPLY_DELEGATION_FILTER=0;
UPDATE APPROVER_ASSOC SET APPLY_DELEGATION_FILTER_T='N' WHERE APPLY_DELEGATION_FILTER IS NULL;
ALTER TABLE APPROVER_ASSOC DROP COLUMN APPLY_DELEGATION_FILTER;
ALTER TABLE APPROVER_ASSOC ALTER COLUMN APPLY_DELEGATION_FILTER_T char(1) NOT NULL;
ALTER TABLE APPROVER_ASSOC ADD DEFAULT 'N' FOR APPLY_DELEGATION_FILTER_T
EXEC sp_RENAME 'APPROVER_ASSOC.[APPLY_DELEGATION_FILTER_T]' , 'APPLY_DELEGATION_FILTER', 'COLUMN';


ALTER TABLE POLICY_ATTRIBUTE ADD REQUIRED CHAR(1) DEFAULT 'Y' NOT NULL;


CREATE  TABLE DEF_RECON_ATTR_MAP (
  DEF_ATTR_MAP_ID NVARCHAR(32) NOT NULL ,
  DEF_ATTR_MAP_NAME NVARCHAR(100) NOT NULL ,
  PRIMARY KEY (DEF_ATTR_MAP_ID)
);

CREATE  TABLE RECON_RES_ATTR_MAP (
  RECON_RES_ATTR_MAP_ID INT IDENTITY(1,1) NOT NULL,
  ATTR_POLICY_ID NVARCHAR(32) NULL ,
  DEF_RECON_ATTR_MAP_ID NVARCHAR(32) NULL ,
  ATTR_MAP_ID NVARCHAR(32) NOT NULL ,
  CONSTRAINT PK_RECON_RES_ATTR_MAP_RECON_RES_ATTR_MAP_ID PRIMARY KEY (RECON_RES_ATTR_MAP_ID)
);


INSERT INTO RECON_RES_ATTR_MAP (ATTR_MAP_ID, ATTR_POLICY_ID) (SELECT ATTRIBUTE_MAP_ID, ATTRIBUTE_POLICY_ID FROM ATTRIBUTE_MAP);
INSERT INTO DEF_RECON_ATTR_MAP (DEF_ATTR_MAP_ID, DEF_ATTR_MAP_NAME) VALUES ('Login.login','Principal');
INSERT INTO DEF_RECON_ATTR_MAP (DEF_ATTR_MAP_ID, DEF_ATTR_MAP_NAME) VALUES ('User.title','Functional Title');

UPDATE ATTRIBUTE_MAP SET ATTRIBUTE_POLICY_ID = (
  SELECT RECON_RES_ATTR_MAP_ID
  FROM RECON_RES_ATTR_MAP 
  WHERE ATTRIBUTE_MAP.ATTRIBUTE_MAP_ID=RECON_RES_ATTR_MAP.ATTR_MAP_ID
);

ALTER TABLE RECON_RES_ATTR_MAP ADD RECON_RES_ATTR_MAP_ID_T NVARCHAR(32);
UPDATE RECON_RES_ATTR_MAP SET RECON_RES_ATTR_MAP_ID_T = CONVERT(CHAR, RECON_RES_ATTR_MAP_ID);
ALTER TABLE RECON_RES_ATTR_MAP DROP CONSTRAINT PK_RECON_RES_ATTR_MAP_RECON_RES_ATTR_MAP_ID;
ALTER TABLE RECON_RES_ATTR_MAP DROP COLUMN RECON_RES_ATTR_MAP_ID;
EXEC sp_RENAME 'RECON_RES_ATTR_MAP.[RECON_RES_ATTR_MAP_ID_T]' , 'RECON_RES_ATTR_MAP_ID', 'COLUMN';
ALTER TABLE RECON_RES_ATTR_MAP ALTER COLUMN RECON_RES_ATTR_MAP_ID NVARCHAR(32) NOT NULL;
ALTER TABLE RECON_RES_ATTR_MAP ADD PRIMARY KEY (RECON_RES_ATTR_MAP_ID);


ALTER TABLE RECON_RES_ATTR_MAP DROP COLUMN ATTR_MAP_ID ;


CREATE  TABLE MANAGED_SYS_RULE (
  MANAGED_SYS_RULE_ID NVARCHAR(32) NOT NULL ,
  MANAGED_SYS_ID NVARCHAR(32) NOT NULL ,
  MANAGED_SYS_RULE_NAME NVARCHAR(45) NULL ,
  MANAGED_SYS_RULE_VALUE NVARCHAR(45) NULL ,
  PRIMARY KEY (MANAGED_SYS_RULE_ID)
);

ALTER TABLE USER_ATTRIBUTES ADD VALUE_AS_BYTE_ARRAY VARBINARY(MAX);





ALTER TABLE URI_PATTERN_META_VALUE ADD GROOVY_SCRIPT NVARCHAR(200);

UPDATE CONTENT_PROVIDER SET MANAGED_SYS_ID='0';

ALTER TABLE CONTENT_PROVIDER ALTER COLUMN MANAGED_SYS_ID NVARCHAR(32) NOT NULL;

ALTER TABLE CONTENT_PROVIDER ADD CONSTRAINT FK_CP_MANAGED_SYS FOREIGN KEY(MANAGED_SYS_ID) REFERENCES MANAGED_SYS(MANAGED_SYS_ID);