use openiam;

DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='a' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='AD_GROUP' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='DISTRIBUTION_GROUP' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='Domain_Local' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='g' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='GENERAL_GROUP' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='Global' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='GROUP_IDENTITY' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='HIGH_RISK' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='LOW_RISK' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='m' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='SECURITY_GROUP' AND LANGUAGE_ID='8';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='Universal' AND LANGUAGE_ID='8';

INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUa','8','a','MetadataTypeEntity.displayNameMap','Группа приложений');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUAD_GROUP','8','AD_GROUP','MetadataTypeEntity.displayNameMap','Тип группы AD');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUDISTRIBUTION_GROUP','8','DISTRIBUTION_GROUP','MetadataTypeEntity.displayNameMap','Группа распространения');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUDomain_Local','8','Domain_Local','MetadataTypeEntity.displayNameMap','Локальный домен');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUg','8','g','MetadataTypeEntity.displayNameMap','Другая группа');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUGENERAL_GROUP','8','GENERAL_GROUP','MetadataTypeEntity.displayNameMap','Тип главной группы');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUGlobal','8','Global','MetadataTypeEntity.displayNameMap','Глобальный');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUGROUP_IDENTITY','8','GROUP_IDENTITY','ResourceEntity.displayNameMap','Идентификатор');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUHIGH_RISK','8','HIGH_RISK','MetadataTypeEntity.displayNameMap','Высокий');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RULOW_RISK','8','LOW_RISK','MetadataTypeEntity.displayNameMap','Низкий');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUm','8','m','MetadataTypeEntity.displayNameMap','Группа Администратора');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUSECURITY_GROUP','8','SECURITY_GROUP','MetadataTypeEntity.displayNameMap','Группа безопасности');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUUniversal','8','Universal','MetadataTypeEntity.displayNameMap','Универсальный');
