use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS UPDATE_USER_ACCESS_REPORT$$
CREATE PROCEDURE UPDATE_USER_ACCESS_REPORT()
    BEGIN
        IF EXISTS (SELECT * FROM RES WHERE RESOURCE_ID = 'USER_ACCESS_REPORT_109') THEN
            IF NOT EXISTS (SELECT * FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID = '1098') THEN
                UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = DISPLAY_ORDER * 10 WHERE REPORT_INFO_ID = '109' AND DISPLAY_ORDER < 10;
                INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
                    IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) 
                    VALUES ('1098', '109', 'GROUP_ID', NULL, '1', 'GROUP', 'N', 'N', 'Group', 25, NULL);
             END IF;
         END IF;

    END$$
DELIMITER ;

call UPDATE_USER_ACCESS_REPORT();
DROP PROCEDURE UPDATE_USER_ACCESS_REPORT;
