use openiam;

DELETE FROM LANGUAGE_MAPPING WHERE ID IN ('JAENT_USR_ORG_BTN_ROOT','JAORGANIZATIONS_ADD_BTN','JAORGANIZATIONS_DEL_BTN','JAORGANIZATIONS_EDT_BTN',
                                          'JAPRIMARY_LOCATION','JASECURITY_GROUP','JALanguageEntity12', 'JASECURITY_GROUP_MENU_DISPLAY')  AND LANGUAGE_ID ='9';


-- INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JALanguageEntity12','9','12','LanguageEntity.displayNameMap','イタリア語');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JAENT_USR_ORG_BTN_ROOT','9','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','ユーザー組織メンバーシップボタン');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JAORGANIZATIONS_ADD_BTN','9','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','組織をユーザーに追加');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JAORGANIZATIONS_DEL_BTN','9','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','組織をユーザーから削除');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JAORGANIZATIONS_EDT_BTN','9','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','組織を編集');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JAPRIMARY_LOCATION','9','PRIMARY_LOCATION','MetadataTypeEntity.displayNameMap','プライマリロケーション');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JASECURITY_GROUP','9','SECURITY_GROUP','MetadataTypeEntity.displayNameMap','セキュリティグループ');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JASECURITY_GROUP_MENU_DISPLAY','9','SECURITY_GROUP','ResourceEntity.displayNameMap','グループ');



DELETE FROM LANGUAGE_MAPPING WHERE ID IN ('ESENT_USR_ORG_BTN_ROOT','ESGROUP_IDENTITY','ESORGANIZATIONS_ADD_BTN','ESORGANIZATIONS_DEL_BTN',
                                          'ESORGANIZATIONS_EDT_BTN','ESPRIMARY_LOCATION','ESSECURITY_GROUP', 'ESSECURITY_GROUP_MENU_DISPLAY','ESLanguageEntity12')  AND LANGUAGE_ID ='4';

-- INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESLanguageEntity12','4','12','LanguageEntity.displayNameMap','Italiano');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESENT_USR_ORG_BTN_ROOT','4','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','Botones de pertenecia del Usuario a la Organización');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESGROUP_IDENTITY','4','GROUP_IDENTITY','ResourceEntity.displayNameMap','Identidades');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESORGANIZATIONS_ADD_BTN','4','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Añadir Organización al Usuario');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESORGANIZATIONS_DEL_BTN','4','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Quitar Organización al Usuario');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESORGANIZATIONS_EDT_BTN','4','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Editar Organización');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESPRIMARY_LOCATION','4','PRIMARY_LOCATION','MetadataTypeEntity.displayNameMap','Localización Principal');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESSECURITY_GROUP','4','SECURITY_GROUP','MetadataTypeEntity.displayNameMap','Grupo de Seguridad');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESSECURITY_GROUP_MENU_DISPLAY','4','SECURITY_GROUP','ResourceEntity.displayNameMap','Grupo');


DELETE FROM LANGUAGE_MAPPING WHERE ID IN ('ZHENT_USR_ORG_BTN_ROOT','ZHGROUP_IDENTITY','ZHORGANIZATIONS_ADD_BTN','ZHORGANIZATIONS_DEL_BTN',
                                          'ZHORGANIZATIONS_EDT_BTN','ZHPRIMARY_LOCATION','ZHSECURITY_GROUP', 'ZHSYNCUSER_REVIEW',
                                          'ZHSECURITY_GROUP_MENU_DISPLAY', 'ZHLanguageEntity12')  AND LANGUAGE_ID ='10';

--INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHLanguageEntity12','10','12','LanguageEntity.displayNameMap','意大利语');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHENT_USR_ORG_BTN_ROOT','10','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','用户组织成员按钮');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHGROUP_IDENTITY','10','GROUP_IDENTITY','ResourceEntity.displayNameMap','身份');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHORGANIZATIONS_ADD_BTN','10','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','为用户增加组织');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHORGANIZATIONS_DEL_BTN','10','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','为用户移除组织');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHORGANIZATIONS_EDT_BTN','10','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','编辑组织');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHPRIMARY_LOCATION','10','PRIMARY_LOCATION','MetadataTypeEntity.displayNameMap','主要地点');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHSECURITY_GROUP','10','SECURITY_GROUP','MetadataTypeEntity.displayNameMap','安全群组');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHSYNCUSER_REVIEW','10','SYNCUSER_REVIEW','ResourceEntity.displayNameMap','检视同步');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHSECURITY_GROUP_MENU_DISPLAY','10','SECURITY_GROUP','ResourceEntity.displayNameMap','群组');


DELETE FROM LANGUAGE_MAPPING WHERE ID IN ('RU12','RUSECURITY_GROUP', 'RUSECURITY_GROUP_MENU_DISPLAY') AND LANGUAGE_ID='8';
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RU12','8','12','LanguageEntity.displayNameMap','Итальянский');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUSECURITY_GROUP_MENU_DISPLAY','8','SECURITY_GROUP','ResourceEntity.displayNameMap','Группа');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUSECURITY_GROUP','8','SECURITY_GROUP','MetadataTypeEntity.displayNameMap','Группа безопасности');
