use openiam;
ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN PRE_PROCESSOR VARCHAR(255) NULL DEFAULT NULL; 
ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN POST_PROCESSOR VARCHAR(255) NULL DEFAULT NULL; 
		
