use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS ADD_MENU_ENTITLEMENTS$$
CREATE PROCEDURE ADD_MENU_ENTITLEMENTS()
	BEGIN
		IF EXISTS (SELECT * FROM ROLE WHERE ROLE_ID='2') THEN
			DELETE FROM RESOURCE_ROLE WHERE (RESOURCE_ID, ROLE_ID) IN (('USER_EDIT_MENU', '2'), ('SUP_SUB_PAGE', '2'), ('USER_ATTRIBUTES', '2'), ('USER_EDIT_CONTACT_INFO', '2'), ('USER_EDIT_INFO', '2'), ('USER_ENTITLEMENTS', '2'), ('USER_HISTORY', '2'), ('USER_IDENTITY', '2'), ('USER_SEARCH', '2'));
			INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('USER_EDIT_MENU', '2'), ('SUP_SUB_PAGE', '2'), ('USER_ATTRIBUTES', '2'), ('USER_EDIT_CONTACT_INFO', '2'), ('USER_EDIT_INFO', '2'), ('USER_ENTITLEMENTS', '2'), ('USER_HISTORY', '2'), ('USER_IDENTITY', '2'), ('USER_SEARCH', '2');
 		END IF;

	END$$
DELIMITER ;

call ADD_MENU_ENTITLEMENTS();
DROP PROCEDURE ADD_MENU_ENTITLEMENTS;
		
