USE openiam;
/* 1 */
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SELFSERVE_SUP_SUB');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SELFSERVE_SUP_SUB');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SELFSERVE_SUP_SUB');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SELFSERVE_SUP_SUB');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SELFSERVE_SUP_SUB');
DELETE FROM RES WHERE RESOURCE_ID IN ('SELFSERVE_SUP_SUB');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, URL) VALUES ('SELFSERVE_SUP_SUB', 'MENU_ITEM', 'Superiors and Subordinates', 'SELFSERVE_SUP_SUB', '/selfservice/supSub.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERVE_SUP_SUB_PUB', 'SELFSERVE_SUP_SUB', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERVE_SUP_SUB_DESC', 'SELFSERVE_SUP_SUB', 'MENU_DISPLAY_NAME', 'Superiors and Subordinates');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERV_USER_EDIT_ROOT', 'SELFSERVE_SUP_SUB');


/* 2 */

UPDATE RES SET URL = '/webconsole/mngsysAttributes.html' WHERE RESOURCE_ID = 'MNGSYS_ATTR_PAGE';

/* 3 */

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SELF_USERIDENTITY', 'SELF_LOGIN_LIST', 'SELF_LOGIN_NEW', 'SELF_LOGIN_LIST', 'SELF_LOGIN_ROOT', 'SELFSER_USER_LOGIN', 'SELFSER_USER_NEW_LOGIN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('SELF_USERIDENTITY', 'SELF_LOGIN_LIST', 'SELF_LOGIN_NEW', 'SELF_LOGIN_LIST', 'SELF_LOGIN_ROOT', 'SELFSER_USER_LOGIN', 'SELFSER_USER_NEW_LOGIN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SELF_USERIDENTITY', 'SELF_LOGIN_LIST', 'SELF_LOGIN_NEW', 'SELF_LOGIN_LIST', 'SELF_LOGIN_ROOT', 'SELFSER_USER_LOGIN', 'SELFSER_USER_NEW_LOGIN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SELF_USERIDENTITY', 'SELF_LOGIN_LIST', 'SELF_LOGIN_NEW', 'SELF_LOGIN_LIST', 'SELF_LOGIN_ROOT', 'SELFSER_USER_LOGIN', 'SELFSER_USER_NEW_LOGIN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SELF_USERIDENTITY', 'SELF_LOGIN_LIST', 'SELF_LOGIN_NEW', 'SELF_LOGIN_LIST', 'SELF_LOGIN_ROOT', 'SELFSER_USER_LOGIN', 'SELFSER_USER_NEW_LOGIN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SELF_USERIDENTITY', 'SELF_LOGIN_LIST', 'SELF_LOGIN_NEW', 'SELF_LOGIN_LIST', 'SELF_LOGIN_ROOT', 'SELFSER_USER_LOGIN', 'SELFSER_USER_NEW_LOGIN');
DELETE FROM RES WHERE RESOURCE_ID IN ('SELF_USERIDENTITY', 'SELF_LOGIN_LIST', 'SELF_LOGIN_NEW', 'SELF_LOGIN_LIST', 'SELF_LOGIN_ROOT', 'SELFSER_USER_LOGIN', 'SELFSER_USER_NEW_LOGIN');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, URL) VALUES ('SELFSER_USER_LOGIN', 'MENU_ITEM', 'Identities', 'SELFSER_USER_LOGIN', '/selfservice/userIdenties.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSER_USER_LOGIN_PUB', 'SELFSER_USER_LOGIN', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSER_USER_LOGIN_DESC', 'SELFSER_USER_LOGIN', 'MENU_DISPLAY_NAME', 'Identities');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, URL) VALUES ('SELFSER_USER_NEW_LOGIN', 'MENU_ITEM', 'Create New Identity', 'SELFSER_USER_NEW_LOGIN', '/selfservice/identity.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSER_USER_NEW_LOGIN_PUB', 'SELFSER_USER_NEW_LOGIN', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSER_USER_NEW_LOGIN_DESC', 'SELFSER_USER_NEW_LOGIN', 'MENU_DISPLAY_NAME', 'Create New Identity');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERV_USER_EDIT_ROOT', 'SELFSER_USER_LOGIN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERV_USER_EDIT_ROOT', 'SELFSER_USER_NEW_LOGIN');


/* 4 */
UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_COMPOSITION' WHERE DEF_PARAM_ID='180';
UPDATE POLICY_DEF_PARAM SET PARAM_GROUP='PSWD_COMPOSITION' WHERE DEF_PARAM_ID='181';