ALTER TABLE RECONCILIATION_CONFIG ADD (SEARCH_FILTER VARCHAR2(200) NULL);
ALTER TABLE RECONCILIATION_CONFIG ADD (UPDATED_SINCE TIMESTAMP NULL);
ALTER TABLE RECONCILIATION_CONFIG ADD (TARGET_SYS_SEARCH_FILTER VARCHAR(200) NULL);
ALTER TABLE RECONCILIATION_CONFIG ADD (MATCH_SCRIPT VARCHAR2(120) NULL);

ALTER TABLE MANAGED_SYS ADD (ATTRIBUTE_NAMES_LOOKUP VARCHAR2(120) NULL);
ALTER TABLE MANAGED_SYS ADD (ATTRIBUTE_NAMES_HNDLR VARCHAR2(100) NULL);