/********************** v 3.2.2 - RC5***********************/
/**********************ddl/1.alter_report_parameter.sql*********************************************/
ALTER TABLE REPORT_CRITERIA_PARAMETER ADD  (DISPLAY_ORDER NUMBER(11,0) DEFAULT (0)  NOT NULL);
ALTER TABLE REPORT_CRITERIA_PARAMETER ADD  (REQUEST_PARAMS VARCHAR(512) NULL);

UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 1 WHERE RCP_ID IN ('1011','1021','1031','1041','1051');
UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 2 WHERE RCP_ID IN ('1012','1022','1042','1052');
UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 3 WHERE RCP_ID IN ('1013','1023','1053');
UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 4 WHERE RCP_ID IN ('1014','1024','1054');

DECLARE
 tCount NUMBER := 0;
BEGIN
  SELECT count(*) INTO tCount FROM REPORT_PARAMETER_METATYPE WHERE PARAM_METATYPE_ID = 'RESOURCE';
  IF (tCount = 0) THEN
    INSERT INTO REPORT_PARAMETER_METATYPE (PARAM_METATYPE_ID, PARAM_METATYPE_NAME, IS_MULTIPLE) VALUES ('RESOURCE', 'Resource', 'Y');
  END IF;
END;
/

/**********************dml/1.add_resource_cert_report.sql*********************************************/
DECLARE
 tCount NUMBER := 0;
BEGIN
  SELECT count(*) INTO tCount FROM RES WHERE RESOURCE_ID = 'RESOURCE_CERT_REPORT_106';
  IF (tCount = 0) THEN
    INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, MIN_AUTH_LEVEL, IS_PUBLIC,
			  		ADMIN_RESOURCE_ID, RISK, TYPE_ID, COORELATED_NAME) VALUES
				('RESOURCE_CERT_REPORT_106', 'REPORT', NULL, 'RESOURCE_CERT_REPORT_106', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'RESOURCE_CERT_REPORT');
  END IF;
  
  SELECT count(*) INTO tCount FROM REPORT_INFO WHERE REPORT_INFO_ID = '106';
  IF (tCount = 0) THEN
    INSERT INTO REPORT_INFO (REPORT_INFO_ID, REPORT_NAME, DATASOURCE_FILE_PATH, REPORT_FILE_PATH, BUILT_IN, RESOURCE_ID) VALUES
				('106', 'RESOURCE_CERT_REPORT', 'ResourceCertReport.groovy', 'ResourceCertReport.rptdesign', 'Y', 'RESOURCE_CERT_REPORT_106');
  END IF;
  
  SELECT count(*) INTO tCount FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID IN ('1061','1062','1063','1064');
  IF (tCount = 0) THEN
    INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1061', '106', 'OWNER_ID', NULL, '1', 'USER', 'N', 'N', 'Owner', 1, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1062', '106', 'RES_ID', NULL, '1', 'RESOURCE', 'N', 'N', 'Admin Resource', 2, '{"resourceTypeId":"ADMIN_RESOURCE", "userId":"${OWNER_ID}"}');
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1063', '106', 'PERIOD_START', NULL, '2', NULL, 'N', 'Y', 'Period Start', 3, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1064', '106', 'PERIOD_END', NULL, '2', NULL, 'N', 'N', 'Period End', 4, NULL);
  END IF;
END;
/
/**********************ddl/2.password_policy_improvement.sql*********************************************/
ALTER TABLE POLICY_DEF_PARAM MODIFY (VALUE1 varchar(3072));
ALTER TABLE POLICY_DEF_PARAM MODIFY (VALUE2 varchar(3072));
ALTER TABLE POLICY_ATTRIBUTE DROP COLUMN NAME;
ALTER TABLE POLICY_ATTRIBUTE DROP COLUMN OPERATION;


ALTER TABLE POLICY_ATTRIBUTE ADD (VALUE1_tmp varchar(3072));
UPDATE POLICY_ATTRIBUTE SET VALUE1_tmp=VALUE1;
ALTER TABLE POLICY_ATTRIBUTE DROP (VALUE1 );
ALTER TABLE POLICY_ATTRIBUTE RENAME COLUMN VALUE1_tmp to VALUE1;

ALTER TABLE POLICY_ATTRIBUTE ADD (VALUE2_tmp varchar(3072));
UPDATE POLICY_ATTRIBUTE SET VALUE2_tmp=VALUE2;
ALTER TABLE POLICY_ATTRIBUTE DROP (VALUE2);
ALTER TABLE POLICY_ATTRIBUTE RENAME COLUMN VALUE2_tmp to VALUE2;

/**********************dml/2.refactor_password_policy.sql*********************************************/
UPDATE POLICY_DEF_PARAM SET OPERATION='select' WHERE NAME='QUEST_LIST';
UPDATE POLICY_DEF_PARAM SET VALUE2='QUESTION_BANK' WHERE NAME='QUEST_LIST';
UPDATE POLICY_ATTRIBUTE SET VALUE2='QUESTION_BANK' WHERE POLICY_ATTR_ID='4015';
UPDATE POLICY_DEF_PARAM SET OPERATION='boolean' WHERE NAME = 'CHNG_PSWD_ON_RESET';
UPDATE POLICY_DEF_PARAM SET OPERATION='boolean' WHERE NAME = 'RESET_BY_USER' ;
UPDATE POLICY_DEF_PARAM SET OPERATION='boolean' WHERE NAME = 'PWD_EQ_PWD';
UPDATE POLICY_DEF_PARAM SET OPERATION='boolean' WHERE NAME = 'REPEAT_SAME_WORD_PASSPHRASE' ;
UPDATE POLICY_DEF_PARAM SET OPERATION='String' WHERE POLICY_DEF_ID = '100' AND OPERATION IS NULL;

/**********************ddl/3.group_identity_fix.sql*********************************************/
insert into IDENTITY (IDENTITY_ID,MANAGED_SYS_ID, IDENTITY, REFERRED_OBJECT_ID, IDENTITY_TYPE, CREATE_DATE, CREATED_BY, STATUS) 
  select CONCAT(CONCAT(GRP_NAME,'_0_'),'GROUP'), '0', GRP_NAME, GRP_ID, 'GROUP', SYSDATE, '3000', 'ACTIVE' from GRP where GRP.GRP_ID not in (select REFERRED_OBJECT_ID from IDENTITY); 

/**********************dml/3.remove_mng_sys_rules_menu.sql*********************************************/
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID = 'MNGSYSRULES';

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'MNGSYSRULES';

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID = 'MNGSYSRULES';

DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'MNGSYSRULES';

DELETE FROM RES WHERE RESOURCE_ID = 'MNGSYSRULES';

/**********************dml/4.IDMAPPS-2183.sql*********************************************/
DELETE FROM POLICY_ATTRIBUTE  WHERE DEF_PARAM_ID IN ('183','184');
DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID  IN ('183','184');

INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID, POLICY_DEF_ID, NAME, DESCRIPTION, OPERATION, VALUE1, VALUE2, REPEATS, PARAM_GROUP, HANDLER_LANGUAGE, POLICY_PARAM_HANDLER) VALUES ('184', '100', 'INITIAL_PASSWORD', 'Initial Password configuration', 'select', 'STATIC', 'STATIC,RANDOM', 0, 'PSWD_COMPOSITION', null, null);
INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, VALUE1, VALUE2, RULE_TEXT, REQUIRED) VALUES ('4201', '184', '4000', 'STATIC', 'STATIC,RANDOM', null, 'Y');


/**********************dml/5.IDMAPPS-2183.sql*********************************************/

DELETE FROM POLICY_ATTRIBUTE  WHERE DEF_PARAM_ID IN ('185');
DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID  IN ('185');

INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID, POLICY_DEF_ID, NAME, DESCRIPTION, OPERATION, VALUE1, VALUE2, REPEATS, PARAM_GROUP, HANDLER_LANGUAGE, POLICY_PARAM_HANDLER) VALUES ('185', '100', 'REJECT_WORDS_IN_PSWD', 'Words not allowed in a password', 'boolean', 'false', '', 0, 'PSWD_COMPOSITION', null, 'org.openiam.idm.srvc.pswd.rule.RejectWordsRule');
INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, VALUE1, VALUE2, RULE_TEXT, REQUIRED) VALUES ('4202', '185', '4000', 'false', '', '', 'Y');


/**********************ddl/4.default_ldap_recon_config.sql*********************************************/
DELETE FROM RECONCILIATION_SITUATION WHERE RECON_CONFIG_ID IN ('1011', '4028b881373b90e501373b92ec180001');
DELETE FROM RECONCILIATION_CONFIG WHERE RECON_CONFIG_ID IN ('1011', '4028b881373b90e501373b92ec180001');

INSERT INTO RECONCILIATION_CONFIG (RECON_CONFIG_ID,RESOURCE_ID,STATUS,TARGET_SYS_MATCH_SCRIPT,MATCH_FIELD_NAME,CUSTOM_MATCH_ATTR,MANAGED_SYS_ID,SEARCH_FILTER,TARGET_SYS_SEARCH_FILTER,MATCH_SCRIPT,RECON_TYPE)
VALUES ('1011','101','ACTIVE','recon/LDAPSearchQuery.groovy','PRINCIPAL','uid','101','{"employeeId":"not_found"}','(&(objectclass=inetOrgPerson)(uid=*))','recon/UserSearchScript.groovy','USER');

INSERT INTO RECONCILIATION_SITUATION (RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP,SCRIPT) VALUES
('10111','1011','IDM[exists] and Resource[not exists]','DELETE_FROM_IDM','recon/LDAPPopulationScript.groovy');
INSERT INTO RECONCILIATION_SITUATION (RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP,SCRIPT) VALUES
('10112','1011','IDM[not exists] and Resource[exists]','ADD_TO_IDM','recon/LDAPPopulationScript.groovy');
INSERT INTO RECONCILIATION_SITUATION (RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP,SCRIPT) VALUES
('10113','1011','IDM[deleted] and Resource[exists]','NOTHING','recon/LDAPPopulationScript.groovy');
INSERT INTO RECONCILIATION_SITUATION (RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP,SCRIPT) VALUES
('10114','1011','IDM[exists] and Resource[exists]','UPDATE_IDM_FROM_RES','recon/LDAPPopulationScript.groovy');


/**********************dml/6.add_term_accounts_report.sql*********************************************/
DECLARE
 tCount NUMBER := 0;
BEGIN
  SELECT count(*) INTO tCount FROM RES WHERE RESOURCE_ID = 'TERM_ACCOUNT_REPORT_107';
  IF (tCount = 0) THEN
    INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, MIN_AUTH_LEVEL, IS_PUBLIC,
			  		ADMIN_RESOURCE_ID, RISK, TYPE_ID, COORELATED_NAME) VALUES
				('TERM_ACCOUNT_REPORT_107', 'REPORT', NULL, 'TERM_ACCOUNT_REPORT_107', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'TERMINATING_ACCOUNTS_REPORT');
  END IF;
  
  SELECT count(*) INTO tCount FROM REPORT_INFO WHERE REPORT_INFO_ID = '107';
  IF (tCount = 0) THEN
    INSERT INTO REPORT_INFO (REPORT_INFO_ID, REPORT_NAME, DATASOURCE_FILE_PATH, REPORT_FILE_PATH, BUILT_IN, RESOURCE_ID) VALUES
				('107', 'TERMINATING_ACCOUNTS', 'TerminatingAccountsReport.groovy', 'TerminatingAccountsReport.rptdesign', 'Y', 'TERM_ACCOUNT_REPORT_107');
  END IF;
  
  SELECT count(*) INTO tCount FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID IN ('1071','1072','1073');
  IF (tCount = 0) THEN
    INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1071', '107', 'ORG_ID', NULL, '1', 'ORGANIZATION', 'N', 'N', 'Organization', 1, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1072', '107', 'PERIOD_START', NULL, '2', NULL, 'N', 'Y', 'Period Start', 2, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1073', '107', 'PERIOD_END', NULL, '2', NULL, 'N', 'N', 'Period End', 3, NULL);
  END IF;
END;
/

/**********************dml/7.add_top_active_users_report.sql*********************************************/
DECLARE
 tCount NUMBER := 0;
BEGIN
  SELECT count(*) INTO tCount FROM RES WHERE RESOURCE_ID = 'TOP_ACTIVE_USERS_REPORT_108';
  IF (tCount = 0) THEN
    INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, MIN_AUTH_LEVEL, IS_PUBLIC,
			  		ADMIN_RESOURCE_ID, RISK, TYPE_ID, COORELATED_NAME) VALUES
				('TOP_ACTIVE_USERS_REPORT_108', 'REPORT', NULL, 'TOP_ACTIVE_USERS_REPORT_108', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'TOP_ACTIVE_USERS_REPORT');
  END IF;
  
  SELECT count(*) INTO tCount FROM REPORT_INFO WHERE REPORT_INFO_ID = '108';
  IF (tCount = 0) THEN
    INSERT INTO REPORT_INFO (REPORT_INFO_ID, REPORT_NAME, DATASOURCE_FILE_PATH, REPORT_FILE_PATH, BUILT_IN, RESOURCE_ID) VALUES
				('108', 'TOP_ACTIVE_USERS', 'TopActiveUsersReport.groovy', 'TopActiveUsersReport.rptdesign', 'Y', 'TOP_ACTIVE_USERS_REPORT_108');
  END IF;
  
  SELECT count(*) INTO tCount FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID IN ('1081','1082','1083','1084','1085');
  IF (tCount = 0) THEN
    INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1081', '108', 'ORG_ID', NULL, '1', 'ORGANIZATION', 'N', 'N', 'Organization', 1, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1082', '108', 'ROLE_ID', NULL, '1', 'ROLE', 'N', 'N', 'Role', 2, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1083', '108', 'PERIOD_START', NULL, '2', NULL, 'N', 'Y', 'Period Start', 3, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1084', '108', 'PERIOD_END', NULL, '2', NULL, 'N', 'N', 'Period End', 4, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1085', '108', 'RECORDS', NULL, '3', NULL, 'N', 'N', 'Total records', 5, NULL);
  END IF;
END;
/

/**********************dml/8.notification_password_expiration.sql*********************************************/
UPDATE POLICY_DEF_PARAM SET OPERATION = 'RANGE' WHERE DEF_PARAM_ID='129';
UPDATE POLICY_DEF_PARAM SET VALUE1 = '1' WHERE DEF_PARAM_ID='129';
UPDATE POLICY_DEF_PARAM SET VALUE2 = '5' WHERE DEF_PARAM_ID='129';
UPDATE POLICY_ATTRIBUTE SET VALUE1 = '1' WHERE DEF_PARAM_ID='129';
UPDATE POLICY_ATTRIBUTE SET VALUE2 = '5' WHERE DEF_PARAM_ID='129';
UPDATE POLICY_ATTRIBUTE SET REQUIRED = 'N' WHERE DEF_PARAM_ID='129';

/**********************dml/9.add_user_access_report.sql*********************************************/
DECLARE
 tCount NUMBER := 0;
BEGIN
  SELECT count(*) INTO tCount FROM REPORT_PARAMETER_METATYPE WHERE PARAM_METATYPE_ID = 'RISK';
  IF (tCount = 0) THEN
    INSERT INTO REPORT_PARAMETER_METATYPE (PARAM_METATYPE_ID, PARAM_METATYPE_NAME, IS_MULTIPLE) VALUES ('RISK', 'Risk', 'N');
  END IF;
  
  SELECT count(*) INTO tCount FROM RES WHERE RESOURCE_ID = 'USER_ACCESS_REPORT_109';
  IF (tCount = 0) THEN
    INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, MIN_AUTH_LEVEL, IS_PUBLIC,
			  		ADMIN_RESOURCE_ID, RISK, TYPE_ID, COORELATED_NAME) VALUES
				('USER_ACCESS_REPORT_109', 'REPORT', NULL, 'USER_ACCESS_REPORT_109', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'USER_ACCESS_REPORT');
  END IF;
  
  SELECT count(*) INTO tCount FROM REPORT_INFO WHERE REPORT_INFO_ID = '109';
  IF (tCount = 0) THEN
    INSERT INTO REPORT_INFO (REPORT_INFO_ID, REPORT_NAME, DATASOURCE_FILE_PATH, REPORT_FILE_PATH, BUILT_IN, RESOURCE_ID) VALUES
				('109', 'USER_ACCESS_REPORT', 'UserAccessReport.groovy', 'UserAccessReport.rptdesign', 'Y', 'USER_ACCESS_REPORT_109');
  END IF;
  
  SELECT count(*) INTO tCount FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID IN ('1091','1092','1093','1094','1095');
  IF (tCount = 0) THEN
    INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1091', '109', 'ORG_ID', NULL, '1', 'ORGANIZATION', 'N', 'N', 'Organization', 1, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1092', '109', 'ROLE_ID', NULL, '1', 'ROLE', 'N', 'N', 'Role', 2, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1093', '109', 'RISK', NULL, '1', 'RISK', 'N', 'N', 'Risk', 3, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1094', '109', 'MANAGED_SYS_ID', NULL, '1', 'MANAGED_SYSTEM', 'N', 'N', 'Managed System', 4, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1095', '109', 'USER_ID', NULL, '1', 'USER', 'N', 'N', 'User', 5, NULL);
  END IF;
END;
/

/**********************dml/10.add_param_audit_report.sql*********************************************/
INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
		IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS)
VALUES ('1025', '102', 'ORG_ID', NULL, '1', 'ORGANIZATION', 'N', 'N', 'Organization', '5', NULL);

/**********************dml/11.add_pass_changes_report.sql*********************************************/
DECLARE
 tCount NUMBER := 0;
BEGIN
  SELECT count(*) INTO tCount FROM RES WHERE RESOURCE_ID = 'PASSWORD_CHANGES_REPORT_110';
  IF (tCount = 0) THEN
    INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, MIN_AUTH_LEVEL, IS_PUBLIC,
			  		ADMIN_RESOURCE_ID, RISK, TYPE_ID, COORELATED_NAME) VALUES
				('PASSWORD_CHANGES_REPORT_110', 'REPORT', NULL, 'PASSWORD_CHANGES_REPORT_110', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'PASSWORD_CHANGES_REPORT');
  END IF;
  
  SELECT count(*) INTO tCount FROM REPORT_INFO WHERE REPORT_INFO_ID = '110';
  IF (tCount = 0) THEN
    INSERT INTO REPORT_INFO (REPORT_INFO_ID, REPORT_NAME, DATASOURCE_FILE_PATH, REPORT_FILE_PATH, BUILT_IN, RESOURCE_ID) VALUES
				('110', 'PASSWORD_CHANGES_REPORT', 'PasswordChangesReport.groovy', 'PasswordChangesReport.rptdesign', 'Y', 'PASSWORD_CHANGES_REPORT_110');
  END IF;
  
  SELECT count(*) INTO tCount FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID IN ('1101','1102','1103');
  IF (tCount = 0) THEN
    INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1101', '110', 'ORG_ID', NULL, '1', 'ORGANIZATION', 'N', 'N', 'Organization', 1, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1102', '110', 'PERIOD_START', NULL, '2', NULL, 'N', 'Y', 'Period Start', 2, NULL);
        INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1103', '110', 'PERIOD_END', NULL, '2', NULL, 'N', 'N', 'Period End', 3, NULL);
  END IF;
END;
/
/**********************dml/12.add_csv_synch_config.sql*********************************************/
insert into SYNCH_CONFIG(SYNCH_CONFIG_ID,NAME,STATUS,SYNCH_SRC,FILE_NAME,MANAGED_SYS_ID,SYNCH_TYPE,PROCESS_RULE,VALIDATION_RULE,TRANSFORMATION_RULE,MATCH_FIELD_NAME,CUSTOM_MATCH_ATTR,USE_POLICY_MAP,USE_TRANSFORM_SCRIPT,POLICY_MAP_BEFORE_TRANSFORM,USE_SYSTEM_PATH,SEARCH_SCOPE) 
 values('csv_users_sample_id','CSV to IDM Users Sample','ACTIVE','CSV','test-user.csv','0','FULL','USER','sync/idmapps/csv/CSVSampleValidationScript.groovy','sync/idmapps/csv/CSVSampleTransformationScript.groovy','EMPLOYEE_ID','EMPLOYEE_ID','N','Y','Y','Y','2');
 
/**********************dml/13.add_ad_powershell_system.sql*********************************************/
-- add WIN02-POWERSHELL-AD connector
insert into PROVISION_CONNECTOR(CONNECTOR_ID,NAME,METADATA_TYPE_ID,STD_COMPLIANCE_LEVEL,CLIENT_COMM_PROTOCOL,SERVICE_URL,SERVICE_NAMESPACE,SERVICE_PORT,SERVICE_WSDL,CLASS_NAME,HOST,PORT,CONNECTOR_INTERFACE)
values('powershell_ad_rem_connector_id','AD Win02 Remote','RemoteConnector',null,'CLEAR','win02.openiamdemo.com/PowershellConnectorAD/PowershellConnector.svc','urn:idm.openiam.org/spml2/service','443',null,null,null,null,'REMOTE');

insert into MANAGED_SYS(MANAGED_SYS_ID,NAME,DESCRIPTION,STATUS,CONNECTOR_ID,HOST_URL,APPL_URL,PORT,COMM_PROTOCOL,USER_ID, PSWD,START_DATE,END_DATE, RESOURCE_ID,PRIMARY_REPOSITORY,SECONDARY_REPOSITORY_ID,ALWAYS_UPDATE_SECONDARY,RES_DEPENDENCY, ADD_HNDLR, MODIFY_HNDLR, DELETE_HNDLR, SETPASS_HNDLR, SUSPEND_HNDLR,SEARCH_HNDLR,LOOKUP_HNDLR,TEST_CONNECTION_HNDLR,RECONCILE_RESOURCE_HNDLR,HNDLR_5,DRIVER_URL,CONNECTION_STRING,SEARCH_SCOPE)
values('active_dir_win02_managed_sys_id','AD Win02 [Remote Connector]','','ACTIVE','powershell_ad_rem_connector_id', 'LDAP://win02.ad.openiamdemo.info', NULL, '', '', 'AD\Administrator', '=tdWk2eqV8P',NULL, NULL, '8a70a63f3f079e58013f0e9e8a160053', NULL, '', NULL, NULL, 'ADPowershell.ps1', 'ADPowershell.ps1','ADPowershell.ps1', 'ADPowershell.ps1', 'ADPowershell.ps1', 'ADPowershell.ps1', 'ADPowershell.ps1', 'ADPowershell.ps1', 'ADPowershell.ps1', '', '', '','2');

insert into MANAGED_SYS_RULE(MANAGED_SYS_RULE_ID,MANAGED_SYS_ID,MANAGED_SYS_RULE_NAME,MANAGED_SYS_RULE_VALUE)
values('ad_win02_managed_sys_rule_id', 'active_dir_win02_managed_sys_id', 'SamAccountName', 'provision/ad/sAMAccount.groovy');

insert into MNG_SYS_OBJECT_MATCH(OBJECT_SEARCH_ID,MANAGED_SYS_ID,OBJECT_TYPE,MATCH_METHOD,BASE_DN,SEARCH_BASE_DN,SEARCH_FILTER,KEY_FIELD)
values('ad_win02_mng_sys_obj_match_0_id', 'active_dir_win02_managed_sys_id', 'USER', NULL, 'ou=idm-test,dc=ad,dc=openiamdemo,dc=info', 'ou=idm-test,dc=ad,dc=openiamdemo,dc=info', '', 'sAMAccountName');

insert into MNG_SYS_OBJECT_MATCH(OBJECT_SEARCH_ID,MANAGED_SYS_ID,OBJECT_TYPE,MATCH_METHOD,BASE_DN,SEARCH_BASE_DN,SEARCH_FILTER,KEY_FIELD)
values('ad_win02_mng_sys_obj_match_1_id', 'active_dir_win02_managed_sys_id', 'GROUP', NULL, 'ou=idm-test,dc=ad,dc=openiamdemo,dc=info', 'ou=idm-test,dc=ad,dc=openiamdemo,dc=info', '', 'sAMAccountName');

insert into RES(RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,URL,MIN_AUTH_LEVEL,IS_PUBLIC)
values('active_dir_win02_mng_sys_res_id', 'MANAGED_SYS', NULL, 'RES_AD_WIN02_REMOTE', '0', NULL, NULL, 'Y');


insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f13d3e2013f13ecc1d40005', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'PRINCIPAL', 'sAMAccountName', NULL, NULL, '8a70a63f3f13d3e2013f13ecc1cc0004', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f13d3e2013f13ecf5f8000b', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'SamAccountName', NULL, NULL, '8a70a63f3f13d3e2013f13ecf5f1000a', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1eb31c14002a', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'Surname', NULL, NULL, '8a70a63f3f1c34b4013f1eb31bf20029', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1eb432220034', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'GivenName', NULL, NULL, '8a70a63f3f1c34b4013f1eb432050033', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1eb4f2470040', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'DisplayName', NULL, NULL, '8a70a63f3f1c34b4013f1eb4f22a003f', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1eb5a40e004e', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'HomeDirectory', NULL, NULL, '8a70a63f3f1c34b4013f1eb5a3ec004d', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1eb6ee5e006a', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'Path', NULL, NULL, '8a70a63f3f1c34b4013f1eb6ee580069', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1eb7babd007c', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'ProfilePath', NULL, NULL, '8a70a63f3f1c34b4013f1eb7bab7007b', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ebd84a10090', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'HomeDrive', NULL, NULL, '8a70a63f3f1c34b4013f1ebd849b008f', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ebe819b00a6', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'ScriptPath', NULL, NULL, '8a70a63f3f1c34b4013f1ebe819500a5', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ebed6df00be', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'Company', NULL, NULL, '8a70a63f3f1c34b4013f1ebed6d800bd', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ebf472300d8', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'Initials', NULL, NULL, '8a70a63f3f1c34b4013f1ebf471e00d7', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ebf984b00f4', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'Department', NULL, NULL, '8a70a63f3f1c34b4013f1ebf984500f3', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ec143510112', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'Title', NULL, NULL, '8a70a63f3f1c34b4013f1ec1434c0111', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ec2f0730132', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'UserPrincipalName', NULL, NULL, '8a70a63f3f1c34b4013f1ec2f06e0131', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ec6c7a70154', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'StreetAddress', NULL, NULL, '8a70a63f3f1c34b4013f1ec6c7a30153', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ec7fa1b0178', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'City', NULL, NULL, '8a70a63f3f1c34b4013f1ec7fa170177', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ec88057019e', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'State', NULL, NULL, '8a70a63f3f1c34b4013f1ec8803d019d', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ec996af01c6', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'PostalCode', NULL, NULL, '8a70a63f3f1c34b4013f1ec996a001c5', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1eca30fb01f0', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'OfficePhone', NULL, NULL, '8a70a63f3f1c34b4013f1eca30f601ef', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1eca8128021c', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'Name', NULL, NULL, '8a70a63f3f1c34b4013f1eca8122021b', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1eccbd77024a', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'AccountPassword', NULL, NULL, '8a70a63f3f1c34b4013f1eccbd720249', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ecd3a2c027a', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'EmployeeID', NULL, NULL, '8a70a63f3f1c34b4013f1ecd3a280279', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ecf05b002ac', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'Manager', NULL, NULL, '8a70a63f3f1c34b4013f1ecf05ac02ab', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ecf6bce02e0', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'Office', NULL, NULL, '8a70a63f3f1c34b4013f1ecf6bc902df', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f1c34b4013f1ed092a80348', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'USER', 'EmailAddress', NULL, NULL, '8a70a63f3f1c34b4013f1ed0926e0347', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);
insert into ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,TARGET_ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,RULE_TEXT,STATUS,START_DATE,END_DATE,STORE_IN_IAMDB,DATA_TYPE,DEFAULT_VALUE,SYNCH_CONFIG_ID)
values('8a70a63f3f5841b5013f587586110023', 'active_dir_win02_managed_sys_id', 'active_dir_win02_mng_sys_res_id', 'EMAIL', 'Enabled', NULL, NULL, '8a70a63f3f5841b5013f5875860a0022', NULL, 'ACTIVE', NULL, NULL, NULL, 'STRING', NULL, NULL);




INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f13d3e2013f13ecc1cc0004','4630',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f13d3e2013f13ecf5f1000a','8a70a63f3f5841b5013f585def970003',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1eb31bf20029','4506',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1eb432050033','4631',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1eb4f22a003f','4517',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1eb5a3ec004d','4636',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1eb6ee580069','4633',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1eb7bab7007b','4635',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ebd849b008f','4637',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ebe819500a5','4639',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ebed6d800bd','4640',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ebf471e00d7','4642',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ebf984500f3','4643',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ec1434c0111','4645',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ec2f06e0131','297ec33c3ced62d2013ced83e3640086',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ec6c7a30153','297ec33c3ced62d2013ced8547880097',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ec7fa170177','297ec33c3ced62d2013ced8647c100a9',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ec8803d019d','297ec33c3ced62d2013ced87182100bc',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ec996a001c5','297ec33c3ced62d2013ced883c3e00d0',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1eca30f601ef','4511',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1eca8122021b','4501',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1eccbd720249','4563',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ecd3a280279','4543',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ecf05ac02ab','297ec33c3ced62d2013ced883c3f00e0',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ecf6bc902df','4503',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f1c34b4013f1ed0926e0347','4540',NULL);
INSERT INTO recon_res_attr_map (RECON_RES_ATTR_MAP_ID, ATTR_POLICY_ID, DEF_RECON_ATTR_MAP_ID) VALUES ('8a70a63f3f5841b5013f5875860a0022','8a70a63f3f5841b5013f586a9743001d',NULL);



INSERT INTO policy(POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,LAST_UPDATE,LAST_UPDATED_BY,RULE_SRC_URL, RULE_TEXT,ENABLEMENT) VALUES  ('297ec33c3ced62d2013ced83e3640086','104','ad-userPrincipalName','User principal name',1,NULL,NULL,NULL,NULL,'provision/ad/userPrincipalName.groovy',NULL,1);
INSERT INTO policy(POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,LAST_UPDATE,LAST_UPDATED_BY,RULE_SRC_URL, RULE_TEXT,ENABLEMENT) VALUES  ('297ec33c3ced62d2013ced8547880097','104','ad-streetAddress','Street Address',1,to_date('2013-02-18','RRRR-MM-DD'),'3000',to_date('2013-02-18','RRRR-MM-DD'),NULL,'provision/ad/street.groovy',NULL,1);
INSERT INTO policy(POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,LAST_UPDATE,LAST_UPDATED_BY,RULE_SRC_URL, RULE_TEXT,ENABLEMENT) VALUES  ('297ec33c3ced62d2013ced8647c100a9','104','ad-city','City',1,to_date('2013-02-18','RRRR-MM-DD'),'3000',to_date('2013-02-18','RRRR-MM-DD'),NULL,'provision/ad/city.groovy',NULL,1);
INSERT INTO policy(POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,LAST_UPDATE,LAST_UPDATED_BY,RULE_SRC_URL, RULE_TEXT,ENABLEMENT) VALUES  ('297ec33c3ced62d2013ced87182100bc','104','ad-state','State',1,to_date('2013-02-18','RRRR-MM-DD'),'3000',to_date('2013-02-18 ','RRRR-MM-DD'),NULL,'provision/ad/state.groovy',NULL,1);
INSERT INTO policy(POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,LAST_UPDATE,LAST_UPDATED_BY,RULE_SRC_URL, RULE_TEXT,ENABLEMENT) VALUES  ('297ec33c3ced62d2013ced883c3e00d0','104','ad-zip','Postal code',1,to_date('2013-02-18','RRRR-MM-DD'),'3000',to_date('2013-02-18','RRRR-MM-DD'),NULL,'provision/ad/zip.groovy',NULL,1);
INSERT INTO policy(POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,LAST_UPDATE,LAST_UPDATED_BY,RULE_SRC_URL, RULE_TEXT,ENABLEMENT) VALUES  ('297ec33c3ced62d2013ced883c3f00e0','104','ad-manager','Manager',1,to_date('2013-02-18','RRRR-MM-DD'),'3000',to_date('2013-02-18','RRRR-MM-DD'),NULL,'provision/ad/manager.groovy',NULL,1);
INSERT INTO policy(POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,LAST_UPDATE,LAST_UPDATED_BY,RULE_SRC_URL, RULE_TEXT,ENABLEMENT) VALUES  ('8a70a63f3f5841b5013f586a9743001d','104','ad-status','Status',1,NULL,NULL,NULL,NULL,'provision/ad/adStatus.groovy',NULL,NULL);
INSERT INTO policy(POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,LAST_UPDATE,LAST_UPDATED_BY,RULE_SRC_URL, RULE_TEXT,ENABLEMENT) VALUES  ('8a70a63f3f5841b5013f585def970003','104','ad-sAMAccountName-NP','ad-sAMAccountName-NoPrincipal',1,NULL,NULL,NULL,NULL,'provision/ad/win02/sAMAccountName-NP.groovy',NULL,NULL);



DECLARE
 tCount NUMBER := 0;
BEGIN
  SELECT count(*) INTO tCount FROM user_tab_cols WHERE TABLE_NAME = 'RECONCILIATION_CONFIG' AND COLUMN_NAME = 'MANUAL_RECONCILIATION_FLAG';
  IF (tCount = 0) THEN
    execute immediate 'ALTER TABLE RECONCILIATION_CONFIG ADD (MANUAL_RECONCILIATION_FLAG CHAR(1) DEFAULT ''N'' NOT NULL)';
  END IF;
END;
/
-- Reconciliation config
insert into RECONCILIATION_CONFIG(RECON_CONFIG_ID, RESOURCE_ID, STATUS, TARGET_SYS_MATCH_SCRIPT, MANUAL_RECONCILIATION_FLAG, MATCH_FIELD_NAME, CUSTOM_MATCH_ATTR, MANAGED_SYS_ID, SEARCH_FILTER, TARGET_SYS_SEARCH_FILTER, MATCH_SCRIPT, RECON_CUSTOM_PROCESSOR, RECON_TYPE) 
values('297e25c047cf76fc0147cfb2874c0002', 'active_dir_win02_mng_sys_res_id', 'ACTIVE', '', 'N', 'PRINCIPAL', 'cn', 'active_dir_win02_managed_sys_id', '', '(objectClass=group)', 'recon/GroupSearchScript.groovy', 'recon/GroupProcessor.groovy', 'GROUP');
insert into RECONCILIATION_SITUATION(RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP) 
values('297e25c047cf76fc0147cfb2874f0003','297e25c047cf76fc0147cfb2874c0002','IDM[deleted] and Resource[exists]','NOTHING');
insert into RECONCILIATION_SITUATION(RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP) 
values('297e25c047cf76fc0147cfb287510004','297e25c047cf76fc0147cfb2874c0002','IDM[exists] and Resource[exists]','NOTHING');
insert into RECONCILIATION_SITUATION(RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP) 
values('297e25c047cf76fc0147cfb287510005','297e25c047cf76fc0147cfb2874c0002','IDM[not exists] and Resource[exists]','ADD_TO_IDM');
insert into RECONCILIATION_SITUATION(RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP) 
values('297e25c047cf76fc0147cfb287510006','297e25c047cf76fc0147cfb2874c0002','IDM[exists] and Resource[not exists]','ADD_TO_RES');


insert into RECONCILIATION_CONFIG(RECON_CONFIG_ID, RESOURCE_ID, STATUS, TARGET_SYS_MATCH_SCRIPT, MANUAL_RECONCILIATION_FLAG, MATCH_FIELD_NAME, CUSTOM_MATCH_ATTR, MANAGED_SYS_ID, SEARCH_FILTER, TARGET_SYS_SEARCH_FILTER, MATCH_SCRIPT, RECON_CUSTOM_PROCESSOR, RECON_TYPE) 
values('0000000043567beb014358f5c604028f', 'active_dir_win02_mng_sys_res_id', 'ACTIVE', 'recon/PowershellADSearchQuery.groovy', 'N', 'PRINCIPAL', 'SamAccountName', 'active_dir_win02_managed_sys_id', '{"employeeId": "notexists"}', '(&(objectCategory=person)(objectClass=user)(SamAccountName=*))', 'recon/UserSearchScript.groovy', null, 'USER');
insert into RECONCILIATION_SITUATION(RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP,SCRIPT) 
values('0000000043567beb014358f5c6140290','0000000043567beb014358f5c604028f','IDM[deleted] and Resource[exists]','ADD_TO_IDM','recon/PowershellADPopulationScript.groovy');
insert into RECONCILIATION_SITUATION(RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP,SCRIPT) 
values('0000000043567beb014358f5c62c0291','0000000043567beb014358f5c604028f','IDM[exists] and Resource[not exists]','DELETE_FROM_IDM','recon/PowershellADPopulationScript.groovy');
insert into RECONCILIATION_SITUATION(RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP,SCRIPT) 
values('0000000043567beb014358f5c6360292','0000000043567beb014358f5c604028f','IDM[not exists] and Resource[exists]','ADD_TO_IDM','recon/PowershellADPopulationScript.groovy');
insert into RECONCILIATION_SITUATION(RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP,SCRIPT) 
values('0000000043567beb014358f5c6d60293','0000000043567beb014358f5c604028f','IDM[exists] and Resource[exists]','UPDATE_IDM_FROM_RES','recon/PowershellADPopulationScript.groovy');







commit;