set define off;

/* Batch Tasks */
insert into openiam.BATCH_CONFIG(TASK_ID, TASK_NAME, FREQUENCY_UNIT_OF_MEASURE, ENABLED, TASK_URL, EXECUTION_ORDER) VALUES('100','ACCOUNT_LOCKED_NOTIFICATION', 'MINUTE','0','batch/accountLockedNotification.groovy','2');
insert into openiam.BATCH_CONFIG(TASK_ID, TASK_NAME, FREQUENCY_UNIT_OF_MEASURE, ENABLED, TASK_URL, EXECUTION_ORDER) VALUES('101','INACTIVE_USER', 'NIGHTLY','0','batch/inactiveUser.groovy','1');
insert into openiam.BATCH_CONFIG(TASK_ID, TASK_NAME, FREQUENCY_UNIT_OF_MEASURE, ENABLED, TASK_URL, EXECUTION_ORDER) VALUES('102','PASSWORD_NEAR_EXP', 'NIGHTLY','0','batch/passwordNearExpNotification.groovy','2');
insert into openiam.BATCH_CONFIG(TASK_ID, TASK_NAME, FREQUENCY_UNIT_OF_MEASURE, ENABLED, TASK_URL, EXECUTION_ORDER) VALUES('107','PASSWORD_EXPIRED', 'NIGHTLY','0','batch/passwordExpiredNotification.groovy','4');
insert into openiam.BATCH_CONFIG(TASK_ID, TASK_NAME, FREQUENCY_UNIT_OF_MEASURE, ENABLED, TASK_URL, EXECUTION_ORDER) VALUES('103','TERMINATE_EXP_ACCT', 'NIGHTLY','0','batch/terminateOnExpiration.groovy','3');
insert into openiam.BATCH_CONFIG(TASK_ID, TASK_NAME, FREQUENCY_UNIT_OF_MEASURE, ENABLED, TASK_URL, EXECUTION_ORDER) VALUES('104','AUTO_UNLOCK', 'MINUTE','0','batch/autoUnlock.groovy','1');

insert into openiam.BATCH_CONFIG(TASK_ID, TASK_NAME, FREQUENCY_UNIT_OF_MEASURE, ENABLED, TASK_URL, EXECUTION_ORDER) VALUES('105','RESET_PSWD_CHNG_COUNT', 'MINUTE','0','batch/resetPasswordChangeCount.groovy','2');
insert into openiam.BATCH_CONFIG(TASK_ID, TASK_NAME, FREQUENCY_UNIT_OF_MEASURE, ENABLED, TASK_URL, EXECUTION_ORDER) VALUES('106','PUBLISH_AUDIT_EVENT', 'NIGHTLY','0','batch/publishAuditEvent.groovy','3');
insert into openiam.BATCH_CONFIG(TASK_ID, TASK_NAME, FREQUENCY_UNIT_OF_MEASURE, ENABLED, TASK_URL, EXECUTION_ORDER) VALUES('108','PROV_ON_STARTDATE', 'NIGHTLY','0','batch/provisionOnStartDate.groovy','4');
insert into openiam.BATCH_CONFIG(TASK_ID, TASK_NAME, FREQUENCY_UNIT_OF_MEASURE, ENABLED, TASK_URL, EXECUTION_ORDER) VALUES('109','SESSION_CLEANUP', 'MINUTE','0','batch/SessionCleanup.groovy','2');




/* Messages  */
insert into openiam.NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('402881823ba67a37013ba68159740001','BulkUsersMessage','BulkNotificationByUserIds.groovy','SYSTEM');
insert into openiam.NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8e9af410001','NEW_USER_EMAIL','NewUserCreateNotification.groovy','SYSTEM');
insert into openiam.NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8ea53030002','NEW_USER_EMAIL_SUPERVISOR','NewUserCreateToSupervisorNotification.groovy','SYSTEM');
insert into openiam.NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8ea91d10003','REQUEST_APPROVED','RequestApproveNotification.groovy','SYSTEM');
insert into openiam.NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8eb000c0004','REQUEST_REJECTED','RequestRejectNotification.groovy','SYSTEM');
insert into openiam.NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8ebe3380005','NEW_PENDING_REQUEST','RequestNotification.groovy','SYSTEM');
insert into openiam.NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8ec3e580006','REQUEST_PASSWORD_RESET','RequestPasswordResetNotification.groovy','SYSTEM');

insert into openiam.NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('402888ea3d9ad61c013d9adce1b2000a','USER_PASSWORD_EMAIL','UserPasswordNotification.groovy','SYSTEM');
insert into openiam.NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('402888ea3d9ad61c013d9adce1b2000b','ACCOUNT_INACTIVE','AccountInactiveNotification.groovy','SYSTEM');



insert into openiam.REPORT_PARAMETER_TYPE(RCPT_ID, TYPE_NAME,TYPE_DESCRIPTION) VALUES ('1', 'STRING','String');
insert into openiam.REPORT_PARAMETER_TYPE(RCPT_ID, TYPE_NAME,TYPE_DESCRIPTION) VALUES ('2', 'DATE','Date');

insert into openiam.REPORT_INFO(report_info_id, report_name, DATASOURCE_FILE_PATH, report_file_path) values('b75e18298e534899afa61a8d44ecc210', 'AUDIT_REPORT', 'AuditReport.groovy', 'AuditReport.rptdesign');
insert into openiam.REPORT_INFO(report_info_id, report_name, DATASOURCE_FILE_PATH, report_file_path) values('b75e18298e534899afa61a8d44ecc212', 'USER_REPORT', 'UserReport.groovy', 'UserReport1.rptdesign');

insert into openiam.SYNCH_CONFIG (SYNCH_CONFIG_ID,NAME,STATUS,SYNCH_SRC,FILE_NAME,SRC_LOGIN_ID,SRC_PASSWORD,SRC_HOST,DRIVER,CONNECTION_URL,QUERY,QUERY_TIME_FIELD,BASE_DN,LAST_EXEC_TIME, LAST_REC_PROCESSED,MANAGED_SYS_ID,LOAD_MATCH_ONLY,UPDATE_ATTRIBUTE,SYNCH_FREQUENCY,SYNCH_TYPE,DELETE_RULE,PROCESS_RULE,VALIDATION_RULE, TRANSFORMATION_RULE,MATCH_FIELD_NAME,MATCH_MANAGED_SYS_ID,MATCH_SRC_FIELD_NAME,CUSTOM_MATCH_RULE,CUSTOM_ADAPTER_SCRIPT,CUSTOM_MATCH_ATTR, WS_URL,WS_SCRIPT,WS_ENDPOINT) 
 VALUES ('40288f823ccb4e59013ccb743caf0003','ACTIVE DIR SYNC TEMPLATE','ACTIVE','LDAP','',null, null, null,'', '','(&(objectclass=user)(objectClass=person))','','DC=ad,DC=openiamdemo,DC=info;CN=Users,DC=ad,DC=openiamdemo,DC=info',null,NULL,NULL,NULL,NULL,'','FULL',NULL,'USER','/sync/ValidateActiveDirRecord.groovy','/sync/TransformActiveDirRecord.groovy','ATTRIBUTE',NULL,'sAMAccountName','','','sAMAccountName','','','');
insert into openiam.SYNCH_CONFIG (SYNCH_CONFIG_ID,NAME,STATUS,SYNCH_SRC,FILE_NAME,SRC_LOGIN_ID,SRC_PASSWORD,SRC_HOST,DRIVER,CONNECTION_URL,QUERY,QUERY_TIME_FIELD,BASE_DN,LAST_EXEC_TIME, LAST_REC_PROCESSED,MANAGED_SYS_ID,LOAD_MATCH_ONLY,UPDATE_ATTRIBUTE,SYNCH_FREQUENCY,SYNCH_TYPE,DELETE_RULE,PROCESS_RULE,VALIDATION_RULE, TRANSFORMATION_RULE,MATCH_FIELD_NAME,MATCH_MANAGED_SYS_ID,MATCH_SRC_FIELD_NAME,CUSTOM_MATCH_RULE,CUSTOM_ADAPTER_SCRIPT,CUSTOM_MATCH_ATTR, WS_URL,WS_SCRIPT,WS_ENDPOINT)
VALUES ('40288f823ccca124013cccefeba0029d','CSV LOAD TEMPLATE','ACTIVE','CSV','/PATH/MYDATAFILE.csv','','','','','','','','',NULL,'',NULL,NULL,NULL,'','FULL',NULL,'USER','/sync/ValidateSrcRecord.groovy','/sync/TransformCSVRecord.groovy','ATTRIBUTE',NULL,'LOGINID','','','LOGINID','','','');

insert into openiam.SYNCH_CONFIG (SYNCH_CONFIG_ID,NAME,STATUS,SYNCH_SRC,FILE_NAME,SRC_LOGIN_ID,SRC_PASSWORD,SRC_HOST,DRIVER,CONNECTION_URL,QUERY,QUERY_TIME_FIELD,BASE_DN,LAST_EXEC_TIME, LAST_REC_PROCESSED,MANAGED_SYS_ID,LOAD_MATCH_ONLY,UPDATE_ATTRIBUTE,SYNCH_FREQUENCY,SYNCH_TYPE,DELETE_RULE,PROCESS_RULE,VALIDATION_RULE, TRANSFORMATION_RULE,MATCH_FIELD_NAME,MATCH_MANAGED_SYS_ID,MATCH_SRC_FIELD_NAME,CUSTOM_MATCH_RULE,CUSTOM_ADAPTER_SCRIPT,CUSTOM_MATCH_ATTR, WS_URL,WS_SCRIPT,WS_ENDPOINT)
 VALUES ('402888e83f507589013f507e44040002','LDAP SYNC TEMPLATE','ACTIVE','LDAP','',null, null, null,'', '','(&(objectclass=inetOrgPerson))','','ou=people,dc=openiamdev,dc=local',null,NULL,NULL,NULL,NULL,'','FULL',NULL,'USER','/sync/ValidateLDAPRecord.groovy','/sync/TransformLDAPRecord.groovy','ATTRIBUTE',NULL,'uid','','','uid','','','');

commit;