use openiam;

UPDATE pa 
SET pa.REQUIRED='N'
FROM POLICY_ATTRIBUTE AS pa
JOIN POLICY_DEF_PARAM AS pd 
ON pa.DEF_PARAM_ID = pd.DEF_PARAM_ID
WHERE pa.POLICY_ID= '4000' AND (
  ((pd.OPERATION = 'RANGE' AND (pa.VALUE1 IS NULL OR pa.VALUE1 = '') AND (pa.VALUE2 IS NULL OR pa.VALUE2 = ''))
   OR (pd.OPERATION = 'String' AND (pa.VALUE1 IS NULL OR pa.VALUE1 = '') )
   OR (pd.OPERATION = 'select' AND (pa.VALUE1 IS NULL OR pa.VALUE1 = '') )
  ));
