use openiam;

ALTER TABLE RECONCILIATION_CONFIG ADD MATCH_FIELD_NAME NVARCHAR(40) NULL;
ALTER TABLE RECONCILIATION_CONFIG ADD CUSTOM_MATCH_ATTR NVARCHAR(40) NULL;
ALTER TABLE RECONCILIATION_CONFIG ADD CUSTOM_MATCH_SRC_ATTR NVARCHAR(40) NULL;