use openiam;

DELIMITER $$
DROP PROCEDURE IF EXISTS ALTERNATE_RECONCILIATION_CONFIG$$
CREATE PROCEDURE ALTERNATE_RECONCILIATION_CONFIG()
BEGIN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='RECONCILIATION_CONFIG' AND column_name='EXEC_STATUS') THEN
	ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN EXEC_STATUS VARCHAR(20) NULL;
END IF;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='RECONCILIATION_CONFIG' AND column_name='LAST_EXEC_TIME') THEN
	ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN LAST_EXEC_TIME DATETIME NULL;
END IF;

END$$
DELIMITER ;
call ALTERNATE_RECONCILIATION_CONFIG();
DROP PROCEDURE ALTERNATE_RECONCILIATION_CONFIG;