use openiam;

UPDATE POLICY_DEF_PARAM SET OPERATION="select" WHERE NAME="QUEST_LIST";
UPDATE POLICY_DEF_PARAM SET VALUE2="QUESTION_BANK" WHERE NAME="QUEST_LIST";
UPDATE POLICY_ATTRIBUTE SET VALUE2="QUESTION_BANK" WHERE POLICY_ATTR_ID="4015";
UPDATE POLICY_DEF_PARAM SET OPERATION="boolean" WHERE NAME = "CHNG_PSWD_ON_RESET";
UPDATE POLICY_DEF_PARAM SET OPERATION="boolean" WHERE NAME = "RESET_BY_USER" ;
UPDATE POLICY_DEF_PARAM SET OPERATION="boolean" WHERE NAME = "PWD_EQ_PWD";
UPDATE POLICY_DEF_PARAM SET OPERATION="boolean" WHERE NAME = "REPEAT_SAME_WORD_PASSPHRASE" ;
UPDATE POLICY_DEF_PARAM SET OPERATION="String" WHERE POLICY_DEF_ID = "100" AND OPERATION IS NULL;
