use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS ADD_TOP_REPORT$$
CREATE PROCEDURE ADD_TOP_REPORT()
	BEGIN
		IF NOT EXISTS (SELECT * FROM RES WHERE RESOURCE_ID = 'TOP_ACTIVE_USERS_REPORT_108') THEN
			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, MIN_AUTH_LEVEL, IS_PUBLIC,
			  		ADMIN_RESOURCE_ID, RISK, TYPE_ID, COORELATED_NAME) VALUES
				('TOP_ACTIVE_USERS_REPORT_108', 'REPORT', NULL, 'TOP_ACTIVE_USERS_REPORT_108', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'TOP_ACTIVE_USERS_REPORT');
 		END IF;

		IF NOT EXISTS (SELECT * FROM REPORT_INFO WHERE REPORT_INFO_ID = '108') THEN
			INSERT INTO REPORT_INFO (REPORT_INFO_ID, REPORT_NAME, DATASOURCE_FILE_PATH, REPORT_FILE_PATH, BUILT_IN, RESOURCE_ID) VALUES
				('108', 'TOP_ACTIVE_USERS', 'TopActiveUsersReport.groovy', 'TopActiveUsersReport.rptdesign', 'Y', 'TOP_ACTIVE_USERS_REPORT_108');
 		END IF;

		IF NOT EXISTS (SELECT * FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID IN ('1081','1082','1083','1084','1085')) THEN
			INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
				('1081', '108', 'ORG_ID', NULL, '1', 'ORGANIZATION', 'N', 'N', 'Organization', 1, NULL),
				('1082', '108', 'ROLE_ID', NULL, '1', 'ROLE', 'N', 'N', 'Role', 2, NULL),
				('1083', '108', 'PERIOD_START', NULL, '2', NULL, 'N', 'Y', 'Period Start', 3, NULL),
				('1084', '108', 'PERIOD_END', NULL, '2', NULL, 'N', 'N', 'Period End', 4, NULL),
				('1085', '108', 'RECORDS', NULL, '3', NULL, 'N', 'N', 'Total records', 5, NULL);
 		END IF;
	END$$
DELIMITER ;

call ADD_TOP_REPORT();
DROP PROCEDURE ADD_TOP_REPORT;
