use openiam;

UPDATE POLICY_DEF_PARAM SET OPERATION = "RANGE" WHERE DEF_PARAM_ID="129";
UPDATE POLICY_DEF_PARAM SET VALUE1 = "1" WHERE DEF_PARAM_ID="129";
UPDATE POLICY_DEF_PARAM SET VALUE2 = "5" WHERE DEF_PARAM_ID="129";
UPDATE POLICY_ATTRIBUTE SET VALUE1 = "1" WHERE DEF_PARAM_ID="129";
UPDATE POLICY_ATTRIBUTE SET VALUE2 = "5" WHERE DEF_PARAM_ID="129";
UPDATE POLICY_ATTRIBUTE SET REQUIRED = "N" WHERE DEF_PARAM_ID="129";
