use openiam;


ALTER TABLE RES ALTER COLUMN DESCRIPTION NVARCHAR(512);
ALTER TABLE RES ADD DEFAULT NULL FOR DESCRIPTION;

UPDATE COMPANY SET LST_UPDATED_BY=SUBSTRING(LST_UPDATED_BY, 1, 32);

ALTER TABLE COMPANY ALTER COLUMN CREATED_BY NVARCHAR(32);
ALTER TABLE COMPANY ADD DEFAULT NULL FOR CREATED_BY;

ALTER TABLE COMPANY ALTER COLUMN LST_UPDATED_BY NVARCHAR(32);
ALTER TABLE COMPANY ADD DEFAULT NULL FOR LST_UPDATED_BY;

ALTER TABLE COMPANY ALTER COLUMN DESCRIPTION NVARCHAR(512);
ALTER TABLE COMPANY ADD DEFAULT NULL FOR DESCRIPTION;