use openiam;

ALTER TABLE "IDENTITY" ADD PROV_STATUS NVARCHAR(20) NULL;
ALTER TABLE "IDENTITY" ADD LAST_UPDATE DATETIME NULL;

GO
UPDATE "IDENTITY" SET LAST_UPDATE = CREATE_DATE WHERE LAST_UPDATE IS NULL;

GO
CREATE TRIGGER ON_IDENTITY_INSERT 
ON "IDENTITY" 
AFTER INSERT 
	AS
	BEGIN
	UPDATE "IDENTITY" 
		SET CREATE_DATE = GETDATE(), LAST_UPDATE = GETDATE()
	FROM inserted, "IDENTITY"
	WHERE inserted.IDENTITY_ID = "IDENTITY".IDENTITY_ID
	END;	
GO
	
CREATE TRIGGER ON_IDENTITY_UPDATE
ON "IDENTITY" 
AFTER UPDATE 
	AS
	BEGIN
	UPDATE "IDENTITY" 
		SET LAST_UPDATE = GETDATE()
	FROM inserted, "IDENTITY"
	WHERE inserted.IDENTITY_ID = "IDENTITY".IDENTITY_ID
	END;	
GO

