use openiam;

delete from LANGUAGE_MAPPING where REFERENCE_ID in ('MULTI_SELECT','SELECT','TEXT');

INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('MetadataTypeEntityEngl','1','MULTI_SELECT','MetadataTypeEntity.displayNameMap','MultiSelect List');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('DEMetadataTypeEntity48','2','MULTI_SELECT','MetadataTypeEntity.displayNameMap','Mehrfachauswahl Liste');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESMetadataTypeEntity48','4','MULTI_SELECT','MetadataTypeEntity.displayNameMap','Lista MultiSelección');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity24','8','MULTI_SELECT','MetadataTypeEntity.displayNameMap','Список мультивыбора');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JPMetadataTypeEntity46','9','MULTI_SELECT','MetadataTypeEntity.displayNameMap','複数選択リスト');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHMetadataTypeEntity46','10','MULTI_SELECT','MetadataTypeEntity.displayNameMap','多选列表');

INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('MetadataTypeEntitySelectEngl','1','SELECT','MetadataTypeEntity.displayNameMap','Combo box');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('DEMetadataTypeEntity70','2','SELECT','MetadataTypeEntity.displayNameMap','Combo box');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESMetadataTypeEntity70','4','SELECT','MetadataTypeEntity.displayNameMap','Combo box');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity31','8','SELECT','MetadataTypeEntity.displayNameMap','Поле со списком');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JPMetadataTypeEntity66','9','SELECT','MetadataTypeEntity.displayNameMap','コンボボックス');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHMetadataTypeEntity66','10','SELECT','MetadataTypeEntity.displayNameMap','组合框');



INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('MetadataTypeEntityTextEngl','1','TEXT','MetadataTypeEntity.displayNameMap','Text Field');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('DEMetadataTypeEntity77','2','TEXT','MetadataTypeEntity.displayNameMap','Text Feld');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESMetadataTypeEntity77','4','TEXT','MetadataTypeEntity.displayNameMap','Campo Texto');
Insert into LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) values ('RUMetadataTypeEntity35','8','TEXT','MetadataTypeEntity.displayNameMap','Текстовое поле');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JPMetadataTypeEntity73','9','TEXT','MetadataTypeEntity.displayNameMap','テキストフィールド');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHMetadataTypeEntity73','10','TEXT','MetadataTypeEntity.displayNameMap','文本字段');
