use openiam

DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID = 'ORG_IDENTITY';
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID = 'ORG_IDENTITY';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'ORG_IDENTITY';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID = 'ORG_IDENTITY';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'ORG_IDENTITY';
DELETE FROM RES WHERE RESOURCE_ID = 'ORG_IDENTITY';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='ORG_IDENTITY';


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL, DISPLAY_ORDER) VALUES('ORG_IDENTITY', 'MENU_ITEM', 'ORG_IDENTITY', 'Organization Identities','/webconsole/editOrgIdentity.html',10);
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORG_IDENTITY_PUB', 'ORG_IDENTITY', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORG_IDENTITY_DESC', 'ORG_IDENTITY', 'MENU_DISPLAY_NAME', 'Identities');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ORGANIZATION_EDIT_ID', 'ORG_IDENTITY');

INSERT INTO RESOURCE_ROLE (ROLE_ID, RESOURCE_ID) VALUES('9', 'ORG_IDENTITY');
INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES
  ('EN_ORG_IDENTITY_DESC', '1', 'ResourceEntity.displayNameMap', 'ORG_IDENTITY', 'Identities'),
  ('DE_ORG_IDENTITY_DESC', '2', 'ResourceEntity.displayNameMap', 'ORG_IDENTITY', 'Identities'),
  ('ES_ORG_IDENTITY_DESC', '4', 'ResourceEntity.displayNameMap', 'ORG_IDENTITY', 'Identities'),
  ('RU_ORG_IDENTITY_DESC', '8', 'ResourceEntity.displayNameMap', 'ORG_IDENTITY', 'Identities'),
  ('JP_ORG_IDENTITY_DESC', '9', 'ResourceEntity.displayNameMap', 'ORG_IDENTITY', 'Identities'),
  ('ZH_ORG_IDENTITY_DESC', '10', 'ResourceEntity.displayNameMap', 'ORG_IDENTITY', 'Identities');

-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Identities' WHERE ID = 'EN_ORG_IDENTITY_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Identities' WHERE ID = 'DE_ORG_IDENTITY_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Identities' WHERE ID = 'ES_ORG_IDENTITY_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Identities' WHERE ID = 'RU_ORG_IDENTITY_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Identities' WHERE ID = 'JP_ORG_IDENTITY_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Identities' WHERE ID = 'ZH_ORG_IDENTITY_DESC';
