ALTER TABLE RECONCILIATION_CONFIG ADD (CUSTOM_IDENTITY_MATCH_SCRIPT VARCHAR(120) NULL);
ALTER TABLE RECONCILIATION_CONFIG ADD (MATCH_FIELD_NAME VARCHAR(40) NULL);
ALTER TABLE RECONCILIATION_CONFIG ADD (CUSTOM_MATCH_ATTR VARCHAR(40) NULL);
ALTER TABLE RECONCILIATION_CONFIG ADD (CUSTOM_MATCH_SRC_ATTR VARCHAR(40) NULL);