use openiam;

delete from BATCH_CONFIG where TASK_ID='GROUP_ATTESTATION';
INSERT INTO BATCH_CONFIG (TASK_ID, TASK_NAME, LAST_EXEC_TIME,TASK_URL,EXECUTION_ORDER, STATUS,PARAM1,PARAM2,PARAM3,PARAM4,RULE_TYPE,ENABLED,LAST_MODIFIED_DATETIME,RUN_ON,CRON_EXPRESSION,SPRING_BEAN,SPRING_BEAN_METHOD)
VALUES ('GROUP_ATTESTATION','Group Attestation', '2014-11-18 11:32:01',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,'N','2014-11-18 11:32:16',NULL,'0 0 0 1 1/3 ?','groupAttestationInitializer','initializeAttestation');
