use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS UPDATE_USER_ACCESS_REPORT$$
CREATE PROCEDURE UPDATE_USER_ACCESS_REPORT()
	BEGIN

    IF NOT EXISTS (SELECT * FROM REPORT_PARAMETER_METATYPE WHERE PARAM_METATYPE_ID = 'RESOURCE_TYPE') THEN
      INSERT INTO REPORT_PARAMETER_METATYPE (PARAM_METATYPE_ID, PARAM_METATYPE_NAME, IS_MULTIPLE) VALUES ('RESOURCE_TYPE', 'Resource type', 'Y');
    END IF;

		IF EXISTS (SELECT * FROM RES WHERE RESOURCE_ID = 'USER_ACCESS_REPORT_109') THEN
			IF NOT EXISTS (SELECT * FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID = '1096') THEN
				INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
					IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) 
					VALUES ('1096', '109', 'RES_TYPE_IDS', NULL, '1', 'RESOURCE_TYPE', 'Y', 'N', 'Resource type', 6, NULL);
	 		END IF;
 		END IF;

	END$$
DELIMITER ;

call UPDATE_USER_ACCESS_REPORT();
DROP PROCEDURE UPDATE_USER_ACCESS_REPORT;
