use openiam;

INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('m', 'Admin Group', 'Y', 'Y', 'GROUP_CLASSIFICATION', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('a', 'Application Group', 'Y', 'Y', 'GROUP_CLASSIFICATION', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('g', 'Other Group', 'Y', 'Y', 'GROUP_CLASSIFICATION', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('SECURITY_GROUP', 'Security Group', 'Y', 'Y', 'AD_GROUP_TYPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('DISTRIBUTION_GROUP', 'Distribution Group', 'Y', 'Y', 'AD_GROUP_TYPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('Universal', 'Universal', 'Y', 'Y', 'AD_GROUP_SCOPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('Global', 'Global', 'Y', 'Y', 'AD_GROUP_SCOPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('Domain_Local', 'Domain Local', 'Y', 'Y', 'AD_GROUP_SCOPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('HIGH_RISK', 'High Risk', 'N', 'N', 'RISK', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('LOW_RISK', 'Low Risk', 'N', 'N', 'RISK', 'N', 'N');

INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('AD_GROUP', 'AD GROUP', 'Y', 'N', 'GROUP_TYPE', 'N', 'N');
INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS, GROUPING, IS_BINARY, IS_SENSITIVE) VALUES ('GENERAL_GROUP', 'General Group', 'Y', 'N', 'GROUP_TYPE', 'N', 'N');



insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENApplicationGroup','1','a','MetadataTypeEntity.displayNameMap','Application Group');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENOtherGroup','1','g','MetadataTypeEntity.displayNameMap','Other Group');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENAdminGroup','1','m','MetadataTypeEntity.displayNameMap','Admin Group');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENDISTRIBUTION_GROUP','1','DISTRIBUTION_GROUP','MetadataTypeEntity.displayNameMap','Distribution Group');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENSECURITY_GROUP','1','SECURITY_GROUP','MetadataTypeEntity.displayNameMap','Security Group');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENDomain_Local','1','Domain_Local','MetadataTypeEntity.displayNameMap','Domain Local');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENGlobal','1','Global','MetadataTypeEntity.displayNameMap','Global');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENUniversal','1','Universal','MetadataTypeEntity.displayNameMap','Universal');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENHIGH_RISK','1','HIGH_RISK','MetadataTypeEntity.displayNameMap','High');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENLOW_RISK','1','LOW_RISK','MetadataTypeEntity.displayNameMap','Low');

insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENAD_GROUP','1','AD_GROUP','MetadataTypeEntity.displayNameMap','AD Group Type');
insert into LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES('ENGENERAL_GROUP','1','GENERAL_GROUP','MetadataTypeEntity.displayNameMap','General Group Type');
