use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SS_GRP_BULK_OP';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'SS_GRP_BULK_OP';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'SS_GRP_BULK_OP_PUB';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'SS_GRP_BULK_OP_DESC';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID = 'SS_GRP_BULK_OP';
DELETE FROM RES WHERE RESOURCE_ID = 'SS_GRP_BULK_OP';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL, DISPLAY_ORDER) VALUES('SS_GRP_BULK_OP', 'MENU_ITEM', 'GRP_BULK_OP', 'Bulk Operations','/selfservice/groupsBulkOperations.html',4);
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_GRP_BULK_OP_PUB', 'SS_GRP_BULK_OP', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_GRP_BULK_OP_DESC', 'SS_GRP_BULK_OP', 'MENU_DISPLAY_NAME', 'Bulk Operations');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSRV_GRP_SRCH_ROOT', 'SS_GRP_BULK_OP');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('SS_GRP_BULK_OP', '9');

INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ENSS_GRP_BULK_OP','1','SS_GRP_BULK_OP','ResourceEntity.displayNameMap','Bulk Operations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUSS_GRP_BULK_OP','8','SS_GRP_BULK_OP','ResourceEntity.displayNameMap','Пакетная обработка');
