/********************** v 3.2.4***********************/
/**********************ddl/1.add_profile_pic.sql*********************************************/
CREATE TABLE PROFILE_PIC (
	PROFILE_PIC_ID VARCHAR(32) NOT NULL,
	USER_ID VARCHAR(32) UNIQUE NOT NULL,
	NAME VARCHAR(256) NULL,
    PICTURE BLOB NOT NULL,
	PRIMARY KEY (PROFILE_PIC_ID),
	CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE);


/**********************dml/1.add_profile_pic_to_selfserv_center.sql*********************************************/
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RES WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='PROFILE_PIC';


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, DISPLAY_ORDER, IS_PUBLIC, URL) 
	VALUES('PROFILE_PIC', 'MENU_ITEM', 'PROFILE_PIC', 'Edit Your Profile Picture', 10, 'Y', '/selfservice/editProfilePic.html');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('PROFILE_PIC_PUB', 'PROFILE_PIC', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('PROFILE_PIC_DESC', 'PROFILE_PIC', 'MENU_DISPLAY_NAME', 'Edit Your Profile Picture');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFCENTER', 'PROFILE_PIC');

DELETE FROM RESOURCE_ROLE WHERE ROLE_ID='9' and RESOURCE_ID='PROFILE_PIC';
INSERT INTO RESOURCE_ROLE (ROLE_ID, RESOURCE_ID) VALUES('9', 'PROFILE_PIC');

DELETE FROM LANGUAGE_MAPPING WHERE ID IN ('EN_PROFILE_PIC_DESC', 'DE_PROFILE_PIC_DESC',
  'ES_PROFILE_PIC_DESC', 'RU_PROFILE_PIC_DESC', 'JP_PROFILE_PIC_DESC');

INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES
  ('EN_PROFILE_PIC_DESC', '1', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture');
INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES
  ('DE_PROFILE_PIC_DESC', '2', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture');
INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES
  ('ES_PROFILE_PIC_DESC', '4', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture');
INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES
  ('RU_PROFILE_PIC_DESC', '8', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture');
INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES
  ('JP_PROFILE_PIC_DESC', '9', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture');
/**********************ddl/2.alter_grp.sql*********************************************/
ALTER TABLE GRP MODIFY CREATED_BY VARCHAR(32)  DEFAULT NULL;

/**********************ddl/3.alter_grp_res.sql*********************************************/
ALTER TABLE GRP MODIFY GRP_NAME VARCHAR(255);
ALTER TABLE RES MODIFY NAME VARCHAR(255);

/**********************dml/2.fix_metadatatype_user_status.sql*********************************************/
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED' WHERE ID='DEMetadataTypeEntity76';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED' WHERE ID='ESMetadataTypeEntity76';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED' WHERE ID='JPMetadataTypeEntity72';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED', TEXT_VALUE='TERMINATED' WHERE ID='MetadataTypeEntity72';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED', TEXT_VALUE='Удален' WHERE ID='RUMetadataTypeEntity78';
UPDATE METADATA_TYPE SET TYPE_ID='TERMINATED', DESCRIPTION='TERMINATED'  WHERE TYPE_ID='TERMINATE';

/**********************dml/3.fix_initial_password_policy.sql*********************************************/
UPDATE (SELECT pa.REQUIRED as requir, pa.VALUE1, pd.OPERATION  FROM POLICY_ATTRIBUTE pa INNER JOIN POLICY_DEF_PARAM pd ON pa.DEF_PARAM_ID = pd.DEF_PARAM_ID
  WHERE pa.POLICY_ID= '4000' AND (
  ((pd.OPERATION = 'RANGE' AND (pa.VALUE1 IS NULL OR pa.VALUE1 = '') AND (pa.VALUE2 IS NULL OR pa.VALUE2 = ''))
   OR (pd.OPERATION = 'String' AND (pa.VALUE1 IS NULL OR pa.VALUE1 = '') )
   OR (pd.OPERATION = 'select' AND (pa.VALUE1 IS NULL OR pa.VALUE1 = '') )
  ))) SET requir='N';

/**********************ddl/4.add_constraint_to_USER_IDENTITY_ANS.sql********************************************/
DECLARE
 tCount NUMBER := 0;
 CURSOR curl is SELECT IDENTITY_QUESTION_ID, USER_ID FROM USER_IDENTITY_ANS;
BEGIN 
 FOR get_cur IN curl LOOP
   SELECT count(*) INTO tCount FROM USER_IDENTITY_ANS WHERE IDENTITY_QUESTION_ID=get_cur.IDENTITY_QUESTION_ID AND USER_ID=get_cur.USER_ID;
   IF (tCount = 0) THEN
     DELETE FROM USER_IDENTITY_ANS WHERE IDENTITY_QUESTION_ID=get_cur.IDENTITY_QUESTION_ID AND USER_ID=get_cur.USER_ID;
   END IF;
 				
	END LOOP;			
END;
/

ALTER TABLE USER_IDENTITY_ANS ADD CONSTRAINT UNQ_ROW UNIQUE(IDENTITY_QUESTION_ID, USER_ID);

commit;
