delete from USER_ATTRIBUTES;
DELETE FROM AUTH_STATE;
DELETE FROM LOGIN_ATTRIBUTE;

DELETE FROM USER_ROLE;
DELETE FROM USER_GRP;
DELETE FROM USER_IDENTITY_ANS;
DELETE FROM USER_NOTE;
DELETE FROM EMAIL_ADDRESS;
DELETE FROM PHONE;
DELETE FROM ADDRESS;
DELETE FROM ORG_STRUCTURE;
DELETE FROM USER_AFFILIATION;

DELETE FROM CREDENTIALS;
DELETE FROM RESOURCE_USER;
DELETE FROM USER_ATTACHMENT_REF;
DELETE FROM USER_DELEGATION_ATTRIBUTE;

DELETE FROM PWD_HISTORY WHERE LOGIN_ID NOT IN (SELECT LOGIN_ID FROM LOGIN where USER_ID in ('0001','3000','3001','3006','3010'));

DELETE FROM USER_KEY where USER_ID not in ('0001','3000','3001','3006','3010');
DELETE FROM LOGIN where USER_ID not in ('0001','3000','3001','3006','3010');
DELETE FROM USERS where USER_ID not in ('0001','3000','3001','3006','3010');
commit;




INSERT INTO USER_ROLE (ROLE_ID, USER_ID) VALUES('2','3010');
INSERT INTO USER_ROLE (ROLE_ID, USER_ID) VALUES('1','3006');
INSERT INTO USER_ROLE (ROLE_ID, USER_ID) VALUES('9','3000');
INSERT INTO USER_ROLE (ROLE_ID, USER_ID) VALUES('9','3001');

update LOGIN set reset_pwd = 0, is_locked = 0;
commit;


