use openiam;


ALTER TABLE RES MODIFY COLUMN DESCRIPTION VARCHAR(512) DEFAULT NULL;

UPDATE COMPANY SET LST_UPDATED_BY=SUBSTRING(LST_UPDATED_BY, 1, 32);

ALTER TABLE COMPANY MODIFY COLUMN CREATED_BY VARCHAR(32) DEFAULT NULL,
                                       MODIFY COLUMN LST_UPDATED_BY VARCHAR(32) DEFAULT NULL,
                                       MODIFY COLUMN DESCRIPTION VARCHAR(512) DEFAULT NULL;