use openiam;

ALTER TABLE IDENTITY ADD COLUMN PROV_STATUS VARCHAR(20) NULL;
ALTER TABLE IDENTITY ADD COLUMN LAST_UPDATE TIMESTAMP NULL;

UPDATE IDENTITY SET LAST_UPDATE = CREATE_DATE WHERE LAST_UPDATE IS NULL;

DELIMITER $$

CREATE TRIGGER ON_IDENTITY_INSERT 
BEFORE 
INSERT ON IDENTITY 
	FOR EACH ROW
	BEGIN
		SET NEW.CREATE_DATE = NOW();
		SET NEW.LAST_UPDATE = NOW();
	END$$
	
CREATE TRIGGER ON_IDENTITY_UPDATE
BEFORE 
UPDATE ON IDENTITY 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_UPDATE = NOW();
	END$$
	
DELIMITER ;
