use openiam;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='RECONCILIATION_CONFIG' AND column_name='EXEC_STATUS') 
	ALTER TABLE RECONCILIATION_CONFIG ADD  EXEC_STATUS NVARCHAR(20) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='RECONCILIATION_CONFIG' AND column_name='LAST_EXEC_TIME') 
	ALTER TABLE RECONCILIATION_CONFIG ADD  LAST_EXEC_TIME DATETIME NULL;
