USE openiam;

DELETE  FROM MNG_SYS_OBJECT_MATCH WHERE MANAGED_SYS_ID = '104';
DELETE  FROM ATTRIBUTE_MAP WHERE MANAGED_SYS_ID = '104';
DELETE FROM RES WHERE RESOURCE_ID = '104';
DELETE FROM MANAGED_SYS WHERE CONNECTOR_ID = '62';
DELETE FROM PROVISION_CONNECTOR WHERE CONNECTOR_ID = '62';


INSERT INTO PROVISION_CONNECTOR (CONNECTOR_ID,NAME,METADATA_TYPE_ID,CLIENT_COMM_PROTOCOL,SERVICE_URL,SERVICE_NAMESPACE,SERVICE_PORT) VALUES ('62','Groovy Script CONNECTOR','SCRIPT_Connector','CLEAR','localhost:9080/openiam-esb/idmsrvc/ScriptConnectorService','http://www.openiam.org/service/connector','NA');

INSERT INTO RES (RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,IS_PUBLIC) VALUES ('104','MANAGED_SYS','','Groovy Script Con',4,'Y');


INSERT INTO MANAGED_SYS (MANAGED_SYS_ID,NAME,DESCRIPTION,STATUS,CONNECTOR_ID,COMM_PROTOCOL,RESOURCE_ID,PRIMARY_REPOSITORY,ADD_HNDLR,MODIFY_HNDLR,DELETE_HNDLR,SEARCH_HNDLR,LOOKUP_HNDLR,TEST_CONNECTION_HNDLR)
VALUES 
('104','Script_CONNECTOR','Groovy script connector','ACTIVE','62','CLEAR', '104','0','example/AddScriptConnector.groovy','example/ModifyScriptConnector.groovy','example/DeleteScriptConnector.groovy','example/SearchScriptConnector.groovy','example/LookupScriptConnector.groovy','example/TestScriptConnector.groovy');

INSERT INTO ATTRIBUTE_MAP 
(ATTRIBUTE_MAP_ID,MANAGED_SYS_ID,RESOURCE_ID,MAP_FOR_OBJECT_TYPE,ATTRIBUTE_NAME,AUTHORITATIVE_SRC,ATTRIBUTE_POLICY_ID,STATUS,DATA_TYPE)
VALUES 
('621','104','104','PRINCIPAL','principal',0,'26','ACTIVE','STRING'),('622','104','104','USER','firstname',0,'27','ACTIVE','STRING');
