use openiam;

DELETE FROM UI_FIELD_TEMPLATE_XREF WHERE UI_FIELD_ID IN('USER_PHONES_REQUIRED', 'USER_EMAILS_REQUIRED', 'USER_ADDRESS_REQUIRED');
DELETE FROM UI_TEMPLATE_FIELDS WHERE UI_FIELD_ID IN('USER_PHONES_REQUIRED', 'USER_EMAILS_REQUIRED', 'USER_ADDRESS_REQUIRED');