use openiam;

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID = 'SELFSERV_ACCESS_REVIEW';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELFSERV_ACCESS_REVIEW';
DELETE FROM RES WHERE RESOURCE_ID = 'SELFSERV_ACCESS_REVIEW';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, IS_PUBLIC, URL) VALUES('SELFSERV_ACCESS_REVIEW', 'MENU_ITEM', 'SELFSERV_ACCESS_REVIEW', 'Access Review','Y', '/selfservice/accessReview.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ACCESS_REVIEW_PUB', 'SELFSERV_ACCESS_REVIEW', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SS_ACCESS_REVIEW_DESC', 'SELFSERV_ACCESS_REVIEW', 'MENU_DISPLAY_NAME', 'Access Review');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERV_USER_EDIT_ROOT', 'SELFSERV_ACCESS_REVIEW');
