use openiam;

DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN('IMPERSONATION_ACCESS', 'IMPERSIONATION_MENU');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('IMPERSONATION_ACCESS', 'IMPERSIONATION_MENU');
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('IMPERSONATION_ACCESS', 'IMPERSIONATION_MENU');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('IMPERSONATION_ACCESS', 'IMPERSIONATION_MENU');
DELETE FROM RES WHERE RESOURCE_ID IN('IMPERSONATION_ACCESS', 'IMPERSIONATION_MENU');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, IS_PUBLIC) VALUES('IMPERSONATION_ACCESS', 'SYS_ACTION', 'IMPERSONATION_ACCESS', 'Ability to Impersonate','N');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, IS_PUBLIC, URL) VALUES('IMPERSIONATION_MENU', 'MENU_ITEM', 'IMPERSIONATION_MENU', 'Impersonation','N', '/webconsole/impersonate.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('IMPERSIONATION_MENU_PUB', 'IMPERSIONATION_MENU', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('IMPERSIONATION_MENU_DESC', 'IMPERSIONATION_MENU', 'MENU_DISPLAY_NAME', 'Impersonation');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ADMIN', 'IMPERSIONATION_MENU');


IF EXISTS (SELECT * FROM ROLE WHERE ROLE_ID='9') 
BEGIN
	INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES('IMPERSIONATION_MENU', '9');
	INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES('IMPERSONATION_ACCESS', '9');
END;

