use openiam;

DELETE FROM REPORT_SUB_CRITERIA_PARAM WHERE REPORT_SUB_ID IN
	(SELECT REPORT_SUB_ID FROM REPORT_SUBSCRIPTIONS WHERE REPORT_INFO_ID IN 
		(SELECT REPORT_INFO_ID FROM REPORT_INFO WHERE REPORT_NAME IN ('USER_REPORT','AUDIT_REPORT','RECONCILIATION_REPORT','SYNCHRONIZATION_REPORT')));
DELETE FROM REPORT_SUBSCRIPTIONS WHERE REPORT_INFO_ID IN 
	(SELECT REPORT_INFO_ID FROM REPORT_INFO WHERE REPORT_NAME IN ('USER_REPORT','AUDIT_REPORT','RECONCILIATION_REPORT','SYNCHRONIZATION_REPORT'));
DELETE FROM REPORT_CRITERIA_PARAMETER WHERE REPORT_INFO_ID IN 
	(SELECT REPORT_INFO_ID FROM REPORT_INFO WHERE REPORT_NAME IN ('USER_REPORT','AUDIT_REPORT','RECONCILIATION_REPORT','SYNCHRONIZATION_REPORT'));
DELETE FROM REPORT_INFO WHERE REPORT_NAME IN ('USER_REPORT','AUDIT_REPORT','RECONCILIATION_REPORT','SYNCHRONIZATION_REPORT');

INSERT INTO REPORT_INFO (REPORT_INFO_ID, REPORT_NAME, DATASOURCE_FILE_PATH, REPORT_FILE_PATH, BUILT_IN) VALUES 
	('101','USER_REPORT','UserReport.groovy','UserReport.rptdesign', 'Y'),
	('102','AUDIT_REPORT','AuditReport.groovy','AuditReport.rptdesign', 'Y'),
	('103','RECONCILIATION_REPORT','ReconciliationReport.groovy','ReconciliationReport.rptdesign', 'Y'),
	('104','SYNCHRONIZATION_REPORT','SynchronizationReport.groovy','SynchronizationReport.rptdesign', 'Y');

INSERT INTO REPORT_CRITERIA_PARAMETER (REPORT_INFO_ID, RCP_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID) VALUES 
	('101','1011','ROLE',NULL,'1'), ('101','1012','STATUS',NULL,'1'), ('101','1013','SECONDARY_STATUS',NULL,'1'), ('101','1014','ORG_ID',NULL,'1'),
	('102','1021','ACTION_ID',NULL,'1'), ('102','1022','ACTION_DATETIME_START',NULL,'2'), ('102','1023','ACTION_DATETIME_END',NULL,'2'),
	('103','1031','MANAGED_SYS_ID',NULL,'1'), ('104','1041','CONFIG_ID',NULL,'1'), ('104','1042','AUDIT_LOG_ID',NULL,'1');
