use openiam;

DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE IN('ResourceEntity');


DECLARE @_id VARCHAR(32);
DECLARE @_resourceId VARCHAR(32);
DECLARE @_value VARCHAR(40);
DECLARE cur1 CURSOR FOR SELECT RESOURCE_PROP_ID, RESOURCE_ID, PROP_VALUE FROM RESOURCE_PROP 
		WHERE RESOURCE_ID IN(SELECT RESOURCE_ID FROM RES WHERE RESOURCE_TYPE_ID IN('MENU_ITEM')) AND NAME='MENU_DISPLAY_NAME';

BEGIN
	OPEN cur1;
	FETCH NEXT FROM cur1 INTO @_id, @_resourceId, @_value;
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF (@_id IS NOT NULL) 
		BEGIN
			IF (@_resourceId IS NOT NULL) 
			BEGIN
				IF (@_value IS NOT NULL) 
				BEGIN
					IF ((SELECT count(*) FROM LANGUAGE_MAPPING WHERE ID=@_id)= 0) 
					BEGIN
						INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES(@_id, '1', 'ResourceEntity', @_resourceId, @_value);
					END;
				END;
			END;
		END;
		FETCH NEXT FROM cur1 INTO @_id, @_resourceId, @_value;
	END;
	CLOSE cur1;
END;