USE openiam;

DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID IN('LANGUAGE_SEARCH', 'LANGUAGE_EDIT', 'LANGUAGE_ROOT_MENU', 'LANGUAGE_ADMIN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN('LANGUAGE_SEARCH', 'LANGUAGE_EDIT', 'LANGUAGE_ROOT_MENU', 'LANGUAGE_ADMIN');
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN('LANGUAGE_SEARCH', 'LANGUAGE_EDIT', 'LANGUAGE_ROOT_MENU', 'LANGUAGE_ADMIN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID IN('LANGUAGE_SEARCH', 'LANGUAGE_EDIT', 'LANGUAGE_ROOT_MENU', 'LANGUAGE_ADMIN');
DELETE FROM RES WHERE RESOURCE_ID IN('LANGUAGE_SEARCH', 'LANGUAGE_EDIT', 'LANGUAGE_ROOT_MENU', 'LANGUAGE_ADMIN');


INSERT INTO RES (RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,IS_PUBLIC,URL) VALUES ('LANGUAGE_ADMIN','MENU_ITEM','languages','LANGUAGE_ADMIN',1,'Y','/webconsole/languages.html');
INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES('LANGUAGE_ADMIN1', '1', 'ResourceEntity', 'LANGUAGE_ADMIN', 'Languages');
INSERT INTO res_to_res_membership (RESOURCE_ID,MEMBER_RESOURCE_ID) VALUES ('ADMIN','LANGUAGE_ADMIN');

INSERT INTO RES (RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,IS_PUBLIC) VALUES ('LANGUAGE_ROOT_MENU','MENU_ITEM','languages root menu','LANGUAGE_ROOT_MENU',1,'Y'); 

INSERT INTO RES (RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,IS_PUBLIC,URL) VALUES ('LANGUAGE_EDIT','MENU_ITEM','languages edit','LANGUAGE_EDIT',1,'Y','/webconsole/languageEdit.html'); 
INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES('LANGUAGE_EDIT1', '1', 'ResourceEntity', 'LANGUAGE_EDIT', 'New Language');

INSERT INTO RES (RESOURCE_ID,RESOURCE_TYPE_ID,DESCRIPTION,NAME,DISPLAY_ORDER,IS_PUBLIC,URL) VALUES ('LANGUAGE_SEARCH','MENU_ITEM','language search','LANGUAGE_SEARCH',3,'Y','/webconsole/languages.html'); 
INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES('LANGUAGE_SEARCH1', '1', 'ResourceEntity', 'LANGUAGE_SEARCH', 'Languages');

INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('LANGUAGE_SEARCH', 'LANGUAGE_ROOT_MENU');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('LANGUAGE_EDIT', 'LANGUAGE_ROOT_MENU');


