use openiam;

DELETE FROM LANGUAGE_MAPPING WHERE ID LIKE '%ElementMigrate%';


DECLARE @_id VARCHAR(32);
DECLARE @_value VARCHAR(40);
DECLARE cur1 CURSOR FOR SELECT METADATA_ID, ATTRIBUTE_NAME FROM METADATA_ELEMENT WHERE METADATA_ID NOT IN(
		SELECT REFERENCE_ID FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='MetadataElementEntity');

BEGIN
	OPEN cur1;
	FETCH NEXT FROM cur1 INTO @_id, @_value;	
	WHILE @@FETCH_STATUS = 0
	BEGIN		
		IF (@_id IS NOT NULL) 
		BEGIN
			IF (@_value IS NOT NULL) 
			BEGIN
				IF ((SELECT count(*) FROM LANGUAGE_MAPPING WHERE ID={fn CONCAT('ElementMigrate',CAST(@_id as VARCHAR(10)))})= 0) 
				BEGIN
					INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES({fn CONCAT('ElementMigrate',CAST(@_id as VARCHAR(10)))}, '1', 'MetadataElementEntity', @_id, @_value);
				END;
			END;
		END;
		FETCH NEXT FROM cur1 INTO @_id, @_value;
	END;
	CLOSE cur1;
END;
