use openiam;

DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE ='OrganizationTypeEntity';


DECLARE @_id VARCHAR(32);
DECLARE @_value VARCHAR(100);
DECLARE cur1 CURSOR FOR SELECT ORG_TYPE_ID, NAME FROM ORGANIZATION_TYPE;

BEGIN
	OPEN cur1;
	FETCH NEXT FROM cur1 INTO @_id, @_value;	
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF (@_id IS NOT NULL) 
		BEGIN
			IF (@_value IS NOT NULL) 
			BEGIN
				IF ((SELECT count(*) FROM LANGUAGE_MAPPING WHERE REFERENCE_ID=@_id AND REFERENCE_TYPE='OrganizationTypeEntity')= 0) 
				BEGIN
					INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES(@_id, '1', 'OrganizationTypeEntity', @_id, @_value);
				END;
			END;
		END;
		FETCH NEXT FROM cur1 INTO @_id, @_value;
	END;
	CLOSE cur1;
END;
