use openiam;


IF NOT EXISTS (SELECT * FROM REPORT_PARAMETER_METATYPE WHERE PARAM_METATYPE_ID='SUPERVISOR') 
BEGIN
	INSERT INTO REPORT_PARAMETER_METATYPE (PARAM_METATYPE_ID, PARAM_METATYPE_NAME, IS_MULTIPLE) VALUES ('SUPERVISOR','Supervisor','Y');
END;
IF NOT EXISTS (SELECT * FROM REPORT_PARAMETER_METATYPE WHERE PARAM_METATYPE_ID='MANAGED_SYSTEM') 
BEGIN
	INSERT INTO REPORT_PARAMETER_METATYPE (PARAM_METATYPE_ID, PARAM_METATYPE_NAME, IS_MULTIPLE) VALUES ('MANAGED_SYSTEM','Managed system','Y');
END;



UPDATE REPORT_CRITERIA_PARAMETER SET CAPTION='Role', PARAM_META_TYPE_ID='ROLE' WHERE RCP_ID=1011;
UPDATE REPORT_CRITERIA_PARAMETER SET CAPTION='Status', PARAM_META_TYPE_ID='USER_STATUS' WHERE RCP_ID=1012;
UPDATE REPORT_CRITERIA_PARAMETER SET CAPTION='User secondary status', PARAM_META_TYPE_ID='USER_SEC_STATUS' WHERE RCP_ID=1013;
UPDATE REPORT_CRITERIA_PARAMETER SET CAPTION='Organization', PARAM_META_TYPE_ID='ORGANIZATION', IS_REQUIRED='Y' WHERE RCP_ID=1014;
UPDATE REPORT_CRITERIA_PARAMETER SET CAPTION='Audit action', PARAM_META_TYPE_ID='ACTION' WHERE RCP_ID=1021;
UPDATE REPORT_CRITERIA_PARAMETER SET CAPTION='Start date', IS_REQUIRED='Y' WHERE RCP_ID=1022;
UPDATE REPORT_CRITERIA_PARAMETER SET CAPTION='End date' WHERE RCP_ID=1023;
UPDATE REPORT_CRITERIA_PARAMETER SET CAPTION='Managed system', PARAM_META_TYPE_ID='MANAGED_SYSTEM', IS_REQUIRED='Y' WHERE RCP_ID=1031;
UPDATE REPORT_CRITERIA_PARAMETER SET CAPTION='Configuration', IS_REQUIRED='Y' WHERE RCP_ID=1041;
UPDATE REPORT_CRITERIA_PARAMETER SET CAPTION='Audit' WHERE RCP_ID=1042;
