use openiam;

DELETE FROM POLICY WHERE NAME = 'linuxGroups';

INSERT INTO POLICY (POLICY_ID,POLICY_DEF_ID,NAME,DESCRIPTION,STATUS,CREATE_DATE,CREATED_BY,RULE_SRC_URL,RULE_TEXT,ENABLEMENT) VALUES ('4658','104','linuxGroups','Default Linux Groups provision rule',1,CURRENT_TIMESTAMP,'3000','provision/linuxGroups.groovy','',1);

UPDATE RECON_RES_ATTR_MAP SET ATTR_POLICY_ID = '4658' WHERE RECON_RES_ATTR_MAP_ID = '62';
