use openiam;

DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID = 'MNG_SYS_VIEWER';
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID = 'MNG_SYS_VIEWER';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'MNG_SYS_VIEWER';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID = 'MNG_SYS_VIEWER';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'MNG_SYS_VIEWER';
DELETE FROM RES WHERE RESOURCE_ID = 'MNG_SYS_VIEWER';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='MNG_SYS_VIEWER';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, DISPLAY_ORDER, IS_PUBLIC, URL) VALUES('MNG_SYS_VIEWER', 'MENU_ITEM', 'USR_MNG_SYS_VIEWER', 'Managed System Viewer', 12, 'N', '/webconsole/mngSysViewerList.html');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, _VALUE) VALUES ('MNG_SYS_VIEWER_PUB', 'MNG_SYS_VIEWER', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, _VALUE) VALUES ('MNG_SYS_VIEWER_DESC', 'MNG_SYS_VIEWER', 'MENU_DISPLAY_NAME', 'Managed System Viewer');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('USER_EDIT_MENU', 'MNG_SYS_VIEWER');

IF EXISTS (SELECT * FROM ROLE WHERE ROLE_ID='9') 
BEGIN
	IF NOT EXISTS (SELECT * FROM RESOURCE_ROLE WHERE ROLE_ID='9' and RESOURCE_ID='MNG_SYS_VIEWER') 
	BEGIN
		INSERT INTO RESOURCE_ROLE (ROLE_ID, RESOURCE_ID) VALUES('9', 'MNG_SYS_VIEWER');
	END;
END;



IF NOT EXISTS (SELECT * FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='MNG_SYS_VIEWER') 
BEGIN
	INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES('MNG_SYS_VIEWER_DESC', '1', 'ResourceEntity.displayNameMap', 'MNG_SYS_VIEWER', 'Managed System Viewer');
END;
