use openiam;

update LANGUAGE SET IS_USED='Y' WHERE ID='4';

delete from LANGUAGE_MAPPING WHERE LANGUAGE_ID in (SELECT ID FROM LANGUAGE WHERE IS_USED='N');
delete from LANGUAGE_LOCALE WHERE LANGUAGE_ID in (SELECT ID FROM LANGUAGE WHERE IS_USED='N');
delete FROM LANGUAGE WHERE IS_USED='N';
