use openiam;

DELETE FROM GRP_ROLE WHERE GRP_ID = 'END_USER_GRP';
DELETE FROM GRP_ROLE WHERE GRP_ID = 'MNGR_GRP';
DELETE FROM GRP_ROLE WHERE GRP_ID = 'SEC_ADMIN_GRP';

DELETE FROM USER_GRP WHERE GRP_ID = 'END_USER_GRP';
DELETE FROM USER_GRP WHERE GRP_ID = 'MNGR_GRP';
DELETE FROM USER_GRP WHERE GRP_ID = 'SEC_ADMIN_GRP';

DELETE FROM GRP_ATTRIBUTES WHERE GRP_ID = 'END_USER_GRP';
DELETE FROM GRP_ATTRIBUTES WHERE GRP_ID = 'MNGR_GRP';
DELETE FROM GRP_ATTRIBUTES WHERE GRP_ID = 'SEC_ADMIN_GRP';

DELETE FROM grp_to_grp_membership WHERE GROUP_ID = 'END_USER_GRP' OR MEMBER_GROUP_ID = 'END_USER_GRP';
DELETE FROM grp_to_grp_membership WHERE GROUP_ID = 'MNGR_GRP' OR MEMBER_GROUP_ID = 'MNGR_GRP';
DELETE FROM grp_to_grp_membership WHERE GROUP_ID = 'SEC_ADMIN_GRP' OR MEMBER_GROUP_ID = 'SEC_ADMIN_GRP';

DELETE FROM GRP WHERE GRP_ID = 'END_USER_GRP';
DELETE FROM GRP WHERE GRP_ID = 'MNGR_GRP';
DELETE FROM GRP WHERE GRP_ID = 'SEC_ADMIN_GRP';
