use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS ADD_CLAIM_DATE$$

CREATE PROCEDURE ADD_CLAIM_DATE()
	BEGIN
		IF NOT EXISTS (SELECT * FROM information_schema.columns WHERE table_schema='openiam' AND table_name = 'USERS' AND column_name = 'CLAIM_DATE') THEN
			ALTER TABLE USERS ADD COLUMN CLAIM_DATE DATE NULL;
 		END IF;
 		
	END$$
DELIMITER ;

call ADD_CLAIM_DATE();
DROP PROCEDURE ADD_CLAIM_DATE;
