use openiam;


DROP TABLE IF EXISTS SYNCH_REVIEW_RECORD_VALUE;
DROP TABLE IF EXISTS SYNCH_REVIEW_RECORD;
DROP TABLE IF EXISTS SYNCH_REVIEW;

CREATE TABLE SYNCH_REVIEW (
	SYNCH_REVIEW_ID VARCHAR(32) NOT NULL,
	SYNCH_CONFIG_ID VARCHAR(32) NOT NULL,
	SRC_REJECTED VARCHAR(1) NOT NULL DEFAULT 'N',
	SKIP_SRC_VALID VARCHAR(1) NOT NULL DEFAULT 'N',
	SKIP_REC_VALID VARCHAR(1) NOT NULL DEFAULT 'N',
	CREATE_TIME DATETIME NOT NULL,
	MODIFY_TIME DATETIME NULL,
	EXEC_TIME DATETIME NULL,
	PRIMARY KEY (SYNCH_REVIEW_ID),
	CONSTRAINT SYNCH_CONFIG_FK FOREIGN KEY (SYNCH_CONFIG_ID) REFERENCES SYNCH_CONFIG(SYNCH_CONFIG_ID) ON DELETE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SYNCH_REVIEW_RECORD (
	SYNCH_REVIEW_RECORD_ID VARCHAR(32) NOT NULL,
	SYNCH_REVIEW_ID VARCHAR(32) NOT NULL,
	HEADER VARCHAR(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (SYNCH_REVIEW_RECORD_ID),
	CONSTRAINT SYNCH_REVIEW_FK FOREIGN KEY (SYNCH_REVIEW_ID) REFERENCES SYNCH_REVIEW(SYNCH_REVIEW_ID) ON DELETE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SYNCH_REVIEW_RECORD_VALUE (
	SYNCH_REVIEW_RECORD_VALUE_ID VARCHAR(32) NOT NULL,
	SYNCH_REVIEW_RECORD_ID VARCHAR(32) NOT NULL,
	VALUE VARCHAR(4096) NULL,
	PRIMARY KEY (SYNCH_REVIEW_RECORD_VALUE_ID),
	CONSTRAINT SYNCH_REVIEW_RECORD_FK FOREIGN KEY (SYNCH_REVIEW_RECORD_ID) REFERENCES SYNCH_REVIEW_RECORD(SYNCH_REVIEW_RECORD_ID) ON DELETE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE SYNCH_REVIEW ADD INDEX SYNCH_CONFIG_IDX (SYNCH_CONFIG_ID);
ALTER TABLE SYNCH_REVIEW_RECORD ADD INDEX SYNCH_REVIEW_IDX (SYNCH_REVIEW_ID);
ALTER TABLE SYNCH_REVIEW_RECORD_VALUE ADD INDEX SYNCH_REVIEW_RECORD_IDX (SYNCH_REVIEW_RECORD_ID);