use openiam;

ALTER TABLE AUTH_STATE DROP FOREIGN KEY FK_AUTH_STATE_USERS;

ALTER TABLE AUTH_STATE DROP PRIMARY KEY;

ALTER TABLE AUTH_STATE ADD COLUMN TOKEN_TYPE VARCHAR(32);

UPDATE AUTH_STATE SET TOKEN_TYPE='OPENIAM';

ALTER TABLE AUTH_STATE MODIFY COLUMN TOKEN_TYPE VARCHAR(32) NOT NULL; 

ALTER TABLE AUTH_STATE ADD PRIMARY KEY(USER_ID, TOKEN_TYPE);