use openiam;


DROP TABLE IF EXISTS PROFILE_PIC;

CREATE TABLE PROFILE_PIC (
	PROFILE_PIC_ID VARCHAR(32) NOT NULL,
	USER_ID VARCHAR(32) UNIQUE NOT NULL,
	NAME VARCHAR(256) NULL,
    PICTURE BLOB NOT NULL,
	PRIMARY KEY (PROFILE_PIC_ID),
	CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PROFILE_PIC ADD INDEX PROFILE_PIC_IDX (PROFILE_PIC_ID);
ALTER TABLE PROFILE_PIC ADD INDEX USERS_IDX (USER_ID);