use openiam;

DELIMITER $$
DROP PROCEDURE IF EXISTS ALTERNATE_SYNCH_CONFIG$$
CREATE PROCEDURE ALTERNATE_SYNCH_CONFIG()
BEGIN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='SYNCH_CONFIG' AND column_name='PRE_SYNC_SCRIPT') THEN
	ALTER TABLE SYNCH_CONFIG ADD COLUMN PRE_SYNC_SCRIPT VARCHAR(80) NULL;
END IF;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='SYNCH_CONFIG' AND column_name='POST_SYNC_SCRIPT') THEN
	ALTER TABLE SYNCH_CONFIG ADD COLUMN POST_SYNC_SCRIPT VARCHAR(80) NULL;
END IF;

END$$
DELIMITER ;
call ALTERNATE_SYNCH_CONFIG();
DROP PROCEDURE ALTERNATE_SYNCH_CONFIG;