use openiam;

DELIMITER $$
DROP PROCEDURE IF EXISTS ALTERNATE_SYNCH_CONFIG$$
CREATE PROCEDURE ALTERNATE_SYNCH_CONFIG()
BEGIN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='SYNCH_CONFIG' AND column_name='COMPANY_ID') THEN
	ALTER TABLE SYNCH_CONFIG ADD COLUMN COMPANY_ID VARCHAR(32) NULL;
END IF;

END$$
DELIMITER ;
call ALTERNATE_SYNCH_CONFIG();
DROP PROCEDURE ALTERNATE_SYNCH_CONFIG;