use openiam;
delete from STATUS where STATUS_CD='AFFILIATE' or STATUS_CD='CONTRACTOR' or STATUS_CD='PERM FULL TIME' or STATUS_CD='PERM PART TIME' or STATUS_CD='SYS ACCOUNT' or STATUS_CD='VENDOR'

-- select * from STATUS where CODE_GROUP='USER_TYPE'

insert into STATUS(STATUS_CD, STATUS_TYPE, DESCRIPTION, CODE_GROUP, LANGUAGE_CD, COMPANY_OWNER_ID, SERVICE_ID) values('K0','String','Board members','USER_TYPE','en','100','USR_SEC_DOMAIN')
insert into STATUS(STATUS_CD, STATUS_TYPE, DESCRIPTION, CODE_GROUP, LANGUAGE_CD, COMPANY_OWNER_ID, SERVICE_ID) values('K1','String','Full-time','USER_TYPE','en','100','USR_SEC_DOMAIN')
insert into STATUS(STATUS_CD, STATUS_TYPE, DESCRIPTION, CODE_GROUP, LANGUAGE_CD, COMPANY_OWNER_ID, SERVICE_ID) values('K2','String','Part-time','USER_TYPE','en','100','USR_SEC_DOMAIN')
insert into STATUS(STATUS_CD, STATUS_TYPE, DESCRIPTION, CODE_GROUP, LANGUAGE_CD, COMPANY_OWNER_ID, SERVICE_ID) values('K3','String','Temporary','USER_TYPE','en','100','USR_SEC_DOMAIN')
insert into STATUS(STATUS_CD, STATUS_TYPE, DESCRIPTION, CODE_GROUP, LANGUAGE_CD, COMPANY_OWNER_ID, SERVICE_ID) values('K4','String','Student FT','USER_TYPE','en','100','USR_SEC_DOMAIN')
insert into STATUS(STATUS_CD, STATUS_TYPE, DESCRIPTION, CODE_GROUP, LANGUAGE_CD, COMPANY_OWNER_ID, SERVICE_ID) values('K9','String','Subcontractors','USER_TYPE','en','100','USR_SEC_DOMAIN')