use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SS_USR_ORG';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'SS_USR_ORG';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'SS_USR_ORG_PUB';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'SS_USR_ORG_DESC';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID = 'SS_USR_ORG';
DELETE FROM RES WHERE RESOURCE_ID = 'SS_USR_ORG';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL, DISPLAY_ORDER) VALUES('SS_USR_ORG', 'MENU_ITEM', 'USR_ORG_MEM', 'User Organizations','/selfservice/userOrganizations.html',4);
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_USR_ORG_PUB', 'SS_USR_ORG', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_USR_ORG_DESC', 'SS_USR_ORG', 'MENU_DISPLAY_NAME', 'User Organizations');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERV_USER_EDIT_ROOT', 'SS_USR_ORG');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('SS_USR_ORG', '9');

INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ENSS_USR_ORG','1','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('DESS_USR_ORG','2','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESSS_USR_ORG','4','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUSS_USR_ORG','8','SS_USR_ORG','ResourceEntity.displayNameMap','Организации');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JASS_USR_ORG','9','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHSS_USR_ORG','10','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('PTSS_USR_ORG','11','SS_USR_ORG','ResourceEntity.displayNameMap','User Organizations');
