USE openiam;

DROP PROCEDURE IF EXISTS UPDATE_RES_CERT_REPORT;

DELIMITER $$

CREATE PROCEDURE UPDATE_RES_CERT_REPORT()
  BEGIN
    IF EXISTS (SELECT * FROM REPORT_INFO WHERE REPORT_INFO_ID = '106') 
    AND EXISTS (SELECT * FROM REPORT_PARAMETER_METATYPE WHERE PARAM_METATYPE_ID = 'RESOURCE_TYPE') 
    AND NOT EXISTS (SELECT * FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID = '1065') THEN
      INSERT INTO REPORT_CRITERIA_PARAMETER 
          (RCP_ID,REPORT_INFO_ID,PARAM_NAME,PARAM_VALUE,RCPT_ID,PARAM_META_TYPE_ID,IS_MULTIPLE,IS_REQUIRED,CAPTION,DISPLAY_ORDER,REQUEST_PARAMS) 
          VALUES ('1065', '106', 'RES_TYPE_ID', NULL, 1, 'RESOURCE_TYPE', 'N', 'N', 'Resource Type', 4, NULL);
      
      UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 1 WHERE RCP_ID = '1063';
      UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 2 WHERE RCP_ID = '1064';
      UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 3 WHERE RCP_ID = '1061';
      UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 5, IS_MULTIPLE = 'Y', PARAM_NAME = 'RES_IDS', 
          REQUEST_PARAMS = '{"resourceTypeId":"${RES_TYPE_ID}","ownerId":"${OWNER_ID}"}' WHERE RCP_ID = '1062';
    END IF;
  END$$

DELIMITER ;

CALL UPDATE_RES_CERT_REPORT();
DROP PROCEDURE UPDATE_RES_CERT_REPORT;
