use openiam;

DELETE FROM AUTH_PROVIDER_ATTRIBUTE WHERE AUTH_ATTRIBUTE_ID IN('SendNameIdInSAMLRequest', 'SPNameIdToSendInSAMLRequest');
DELETE FROM AUTH_ATTRIBUTE WHERE AUTH_ATTRIBUTE_ID IN('SendNameIdInSAMLRequest', 'SPNameIdToSendInSAMLRequest');

INSERT INTO AUTH_ATTRIBUTE (AUTH_ATTRIBUTE_ID, ATTRIBUTE_NAME, PROVIDER_TYPE, DESCRIPTION, REQUIRED, DATA_TYPE)
	VALUES('SPNameIdToSendInSAMLRequest', 'NameID IN SAML Request', 'SAML_SP_PROVIDER', 'NameID Format to send in the NameIDPolicy of the SAMLRequest', 'N', 'singleValue');