use openiam;


IF NOT EXISTS (SELECT * FROM information_schema.columns WHERE TABLE_CATALOG='openiam' AND table_name = 'REPORT_CRITERIA_PARAMETER' AND column_name = 'DISPLAY_ORDER') 
BEGIN
	ALTER TABLE REPORT_CRITERIA_PARAMETER ADD DISPLAY_ORDER INT;
END;
IF NOT EXISTS (SELECT * FROM information_schema.columns WHERE TABLE_CATALOG='openiam' AND table_name = 'REPORT_CRITERIA_PARAMETER' AND column_name = 'REQUEST_PARAMS')
BEGIN
	ALTER TABLE REPORT_CRITERIA_PARAMETER ADD REQUEST_PARAMS NVARCHAR(512) NULL;
END;

GO
UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 1 WHERE RCP_ID IN ('1011','1021','1031','1041','1051');
UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 2 WHERE RCP_ID IN ('1012','1022','1042','1052');
UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 3 WHERE RCP_ID IN ('1013','1023','1053');
UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 4 WHERE RCP_ID IN ('1014','1024','1054');

IF NOT EXISTS (SELECT * FROM REPORT_PARAMETER_METATYPE WHERE PARAM_METATYPE_ID = 'RESOURCE') 
BEGIN
	INSERT INTO REPORT_PARAMETER_METATYPE (PARAM_METATYPE_ID, PARAM_METATYPE_NAME, IS_MULTIPLE) VALUES ('RESOURCE', 'Resource', 'Y');
END;

