use openiam;

ALTER TABLE POLICY_DEF_PARAM ALTER COLUMN VALUE1 nvarchar(3072);
ALTER TABLE POLICY_DEF_PARAM ALTER COLUMN VALUE2 nvarchar(3072);
ALTER TABLE POLICY_ATTRIBUTE DROP COLUMN NAME;
ALTER TABLE POLICY_ATTRIBUTE DROP COLUMN OPERATION;
ALTER TABLE POLICY_ATTRIBUTE ALTER COLUMN VALUE1 nvarchar(3072);
ALTER TABLE POLICY_ATTRIBUTE ALTER COLUMN VALUE2 nvarchar(3072);


