use openiam;

DELIMITER $$
DROP PROCEDURE IF EXISTS ALTERNATE_RECONCILIATION_CONFIG$$
CREATE PROCEDURE ALTERNATE_RECONCILIATION_CONFIG()
BEGIN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='RECONCILIATION_CONFIG' AND column_name='SEARCH_FILTER') THEN
	ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN SEARCH_FILTER VARCHAR(200) NULL;
END IF;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='RECONCILIATION_CONFIG' AND column_name='UPDATED_SINCE') THEN
	ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN UPDATED_SINCE DATETIME NULL;
END IF;

END$$
DELIMITER ;
call ALTERNATE_RECONCILIATION_CONFIG();
DROP PROCEDURE ALTERNATE_RECONCILIATION_CONFIG;