use openiam;

DELIMITER $$
DROP PROCEDURE IF EXISTS ALTERNATE_MANAGED_SYS$$
CREATE PROCEDURE ALTERNATE_MANAGED_SYS()
BEGIN

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='MANAGED_SYS' AND column_name='ATTRIBUTE_NAMES_LOOKUP') THEN
	ALTER TABLE MANAGED_SYS ADD COLUMN ATTRIBUTE_NAMES_LOOKUP VARCHAR(120) NULL;
END IF;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='MANAGED_SYS' AND column_name='ATTRIBUTE_NAMES_HNDLR') THEN
	ALTER TABLE MANAGED_SYS ADD COLUMN ATTRIBUTE_NAMES_HNDLR VARCHAR(100) NULL;
END IF;

END$$
DELIMITER ;
call ALTERNATE_MANAGED_SYS();
DROP PROCEDURE ALTERNATE_MANAGED_SYS;