use openiam;


ALTER TABLE AUTH_STATE DROP FK_AUTH_STATE_USERS;

DECLARE @table NVARCHAR(512), @sql NVARCHAR(MAX);
SELECT @table = 'AUTH_STATE';
SELECT @sql = 'ALTER TABLE ' + @table 
	+ ' DROP CONSTRAINT ' + name + ';'
	FROM sys.key_constraints
	WHERE [type] = 'PK'
	AND [parent_object_id] = OBJECT_ID(@table);
EXEC sp_executeSQL @sql;
	

ALTER TABLE AUTH_STATE ADD TOKEN_TYPE NVARCHAR(32);

GO
UPDATE AUTH_STATE SET TOKEN_TYPE='OPENIAM';
GO
ALTER TABLE AUTH_STATE ALTER COLUMN TOKEN_TYPE NVARCHAR(32) NOT NULL; 

GO
ALTER TABLE AUTH_STATE ADD PRIMARY KEY(USER_ID, TOKEN_TYPE);