use openiam;

IF OBJECT_ID('PROFILE_PIC', 'U') IS NOT NULL
  DROP TABLE PROFILE_PIC

CREATE TABLE PROFILE_PIC (
	PROFILE_PIC_ID NVARCHAR(32) NOT NULL,
	USER_ID NVARCHAR(32) UNIQUE NOT NULL,
	NAME NVARCHAR(256) NULL,
    PICTURE varbinary(MAX) NOT NULL,
	PRIMARY KEY (PROFILE_PIC_ID),
	CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE);

CREATE INDEX PROFILE_PIC_IDX ON PROFILE_PIC(PROFILE_PIC_ID);
CREATE INDEX USERS_IDX ON PROFILE_PIC(USER_ID);
