use openiam;

ALTER TABLE ATTRIBUTE_MAP ADD SYNCH_CONFIG_ID VARCHAR(32) NULL;
ALTER TABLE ATTRIBUTE_MAP MODIFY MANAGED_SYS_ID VARCHAR(32) NULL DEFAULT NULL;
ALTER TABLE SYNCH_CONFIG ADD USE_POLICY_MAP CHAR(1) DEFAULT 'N';


