use openiam;

ALTER TABLE BATCH_CONFIG ADD COLUMN LAST_MODIFIED_DATETIME DATETIME NULL;
ALTER TABLE BATCH_CONFIG ADD COLUMN RUN_ON DATETIME NULL;
ALTER TABLE BATCH_CONFIG ADD COLUMN CRON_EXPRESSION VARCHAR(100) NULL;
ALTER TABLE BATCH_CONFIG ADD COLUMN SPRING_BEAN VARCHAR(100) NULL;
ALTER TABLE BATCH_CONFIG ADD COLUMN SPRING_BEAN_METHOD VARCHAR(100) NULL;

UPDATE BATCH_CONFIG SET CRON_EXPRESSION='0 0/1 * 1/1 * ? *' WHERE FREQUENCY_UNIT_OF_MEASURE='MINUTE';
UPDATE BATCH_CONFIG SET CRON_EXPRESSION='0 0 0 1/1 * ? *' WHERE FREQUENCY_UNIT_OF_MEASURE='NIGHTLY';

UPDATE BATCH_CONFIG SET CRON_EXPRESSION='0 0/1 * * * ?' WHERE CRON_EXPRESSION='0 0/1 * 1/1 * ? *';
UPDATE BATCH_CONFIG SET CRON_EXPRESSION='0 0 0 1/1 * ?' WHERE CRON_EXPRESSION='0 0 0 1/1 * ? *';

ALTER TABLE BATCH_CONFIG DROP COLUMN FREQUENCY;
ALTER TABLE BATCH_CONFIG DROP COLUMN FREQUENCY_UNIT_OF_MEASURE;

DROP TRIGGER IF EXISTS ON_BATCH_TASK_INSERT;
DROP TRIGGER IF EXISTS ON_BATCH_TASK_UPDATE;

DELIMITER $$

CREATE TRIGGER ON_BATCH_TASK_INSERT 
BEFORE 
INSERT ON BATCH_CONFIG 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_MODIFIED_DATETIME = NOW();
	END$$
	
CREATE TRIGGER ON_BATCH_TASK_UPDATE
BEFORE 
UPDATE ON BATCH_CONFIG 
	FOR EACH ROW
	BEGIN
		SET NEW.LAST_MODIFIED_DATETIME = NOW();
	END$$
	
DELIMITER ;