use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS MODIFY_RECONCILIATION_CONFIG$$
CREATE PROCEDURE MODIFY_RECONCILIATION_CONFIG()
	BEGIN

IF EXISTS (SELECT * FROM information_schema.columns WHERE TABLE_SCHEMA='openiam' and table_name = 'RECONCILIATION_CONFIG' AND column_name = 'MANUAL_RECONCILIATION_FLAG') THEN
			ALTER TABLE RECONCILIATION_CONFIG DROP COLUMN MANUAL_RECONCILIATION_FLAG;
 		END IF;

ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN MANUAL_RECONCILIATION_FLAG CHAR(1) DEFAULT 'N' NOT NULL;

END$$
DELIMITER ;

call MODIFY_RECONCILIATION_CONFIG();
DROP PROCEDURE MODIFY_RECONCILIATION_CONFIG;
