use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS DROP_CONTACT_INFO_CONSTRAINT$$
CREATE PROCEDURE DROP_CONTACT_INFO_CONSTRAINT()
	BEGIN
		IF EXISTS (SELECT * FROM information_schema.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA='openiam' and TABLE_NAME = 'EMAIL_ADDRESS' AND CONSTRAINT_NAME = 'EMAIL_ADDRESS_TYPE_FK') THEN
			ALTER TABLE EMAIL_ADDRESS DROP FOREIGN KEY EMAIL_ADDRESS_TYPE_FK, DROP COLUMN TYPE_ID;
 		END IF;
 		IF EXISTS (SELECT * FROM information_schema.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA='openiam' and table_name = 'ADDRESS' AND CONSTRAINT_NAME = 'ADDRESS_TYPE_FK') THEN
 			ALTER TABLE ADDRESS DROP FOREIGN KEY ADDRESS_TYPE_FK, DROP COLUMN TYPE_ID;
 		END IF;
 		IF EXISTS (SELECT * FROM information_schema.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA='openiam' and table_name = 'PHONE' AND CONSTRAINT_NAME = 'PHONE_TYPE_FK') THEN
 			ALTER TABLE PHONE DROP FOREIGN KEY PHONE_TYPE_FK, DROP COLUMN TYPE_ID;
 		END IF;
        IF EXISTS (SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='openiam' and TABLE_NAME = 'EMAIL_ADDRESS' AND column_name  = 'TYPE_ID') THEN
			ALTER TABLE EMAIL_ADDRESS DROP COLUMN TYPE_ID;
 		END IF;
 		IF EXISTS (SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='openiam' and table_name = 'ADDRESS' AND column_name  = 'TYPE_ID') THEN
 			ALTER TABLE ADDRESS DROP COLUMN TYPE_ID;
 		END IF;
 		IF EXISTS (SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='openiam' and table_name = 'PHONE' AND column_name  = 'TYPE_ID') THEN
 			ALTER TABLE PHONE DROP COLUMN TYPE_ID;
 		END IF;
 		IF EXISTS (SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='openiam' and table_name = 'PHONE' AND column_name  = 'PHONE_TYPE') THEN
 			ALTER TABLE PHONE DROP COLUMN PHONE_TYPE;
 		END IF;
	END$$
DELIMITER ;

call DROP_CONTACT_INFO_CONSTRAINT();
DROP PROCEDURE DROP_CONTACT_INFO_CONSTRAINT;


DELETE FROM METADATA_TYPE WHERE GROUPING IN ('EMAIL', 'PHONE', 'ADDRESS');  

INSERT INTO METADATA_TYPE(TYPE_ID,DESCRIPTION,ACTIVE,GROUPING)
VALUES('WORK_EMAIL','Work Email','Y','EMAIL'),
      ('PRIMARY_EMAIL','Primary Email','Y','EMAIL'),
      ('HOME_EMAIL','Home Email','Y','EMAIL');

INSERT INTO METADATA_TYPE(TYPE_ID,DESCRIPTION,ACTIVE,GROUPING)
VALUES('OFFICE_PHONE','Office phone','Y','PHONE'),
      ('CELL_PHONE','Cell phone','Y','PHONE'),
      ('HOME_PHONE','Home phone','Y','PHONE');


INSERT INTO METADATA_TYPE(TYPE_ID,DESCRIPTION,ACTIVE,GROUPING)
VALUES('OFFICE_ADDRESS','Office Address','Y','ADDRESS'),
      ('HOME_ADDRESS','Home Address','Y','ADDRESS');

ALTER TABLE EMAIL_ADDRESS ADD COLUMN TYPE_ID VARCHAR(32) NOT NULL;
ALTER TABLE ADDRESS ADD COLUMN TYPE_ID VARCHAR(32) NOT NULL;
ALTER TABLE PHONE ADD COLUMN TYPE_ID VARCHAR(32) NOT NULL;

UPDATE EMAIL_ADDRESS SET TYPE_ID='WORK_EMAIL';
UPDATE ADDRESS SET TYPE_ID='OFFICE_ADDRESS';
UPDATE PHONE SET TYPE_ID='OFFICE_PHONE';


ALTER TABLE EMAIL_ADDRESS ADD CONSTRAINT EMAIL_ADDRESS_TYPE_FK
  FOREIGN KEY (TYPE_ID) REFERENCES METADATA_TYPE(TYPE_ID); 
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_TYPE_FK
  FOREIGN KEY (TYPE_ID) REFERENCES METADATA_TYPE(TYPE_ID);
ALTER TABLE PHONE ADD CONSTRAINT PHONE_TYPE_FK
  FOREIGN KEY (TYPE_ID) REFERENCES METADATA_TYPE(TYPE_ID);


