use openiam;

DROP TABLE IF EXISTS REPORT_PARAMETER_TYPE;
DROP TABLE IF EXISTS REPORT_INFO;
DROP TABLE IF EXISTS REPORT_CRITERIA_PARAMETER;
DROP TABLE IF EXISTS REPORT_SUBSCRIPTIONS;
DROP TABLE IF EXISTS REPORT_SUB_CRITERIA_PARAM;

CREATE TABLE REPORT_PARAMETER_TYPE (
  RCPT_ID varchar(100) DEFAULT NULL,
  TYPE_NAME varchar(100) DEFAULT NULL,
  TYPE_DESCRIPTION varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE REPORT_INFO (
  REPORT_INFO_ID varchar(32) NOT NULL,
  REPORT_NAME varchar(64) NOT NULL,
  DATASOURCE_FILE_PATH varchar(255) NOT NULL,
  REPORT_FILE_PATH varchar(255) DEFAULT NULL,
  PRIMARY KEY (REPORT_INFO_ID),
  UNIQUE KEY REPORT_NAME (REPORT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE  REPORT_CRITERIA_PARAMETER(
  RCP_ID varchar(32) NOT NULL,
  REPORT_INFO_ID varchar(32) NOT NULL,
  PARAM_NAME varchar(64) NOT NULL,
  PARAM_VALUE varchar(64) DEFAULT NULL,
  RCPT_ID varchar(100) DEFAULT NULL,
  PRIMARY KEY (RCP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;


CREATE TABLE REPORT_SUBSCRIPTIONS (
  REPORT_SUB_ID varchar(32) NOT NULL,
  REPORT_INFO_ID varchar(45) DEFAULT NULL,
  REPORT_NAME varchar(64) NOT NULL,
  DELIVERY_METHOD varchar(45) DEFAULT NULL,
  DELIVERY_FORMAT varchar(45) DEFAULT NULL,
  DELIVERY_AUDIENCE varchar(45) DEFAULT NULL,
  STATUS varchar(45) DEFAULT NULL,
  USERID varchar(45) DEFAULT NULL,
  PRIMARY KEY (REPORT_SUB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;


CREATE TABLE  REPORT_SUB_CRITERIA_PARAM (
  RSCP_ID varchar(45) NOT NULL,
  RCP_ID varchar(32) DEFAULT NULL,
  REPORT_SUB_ID varchar(32) DEFAULT NULL,
  PARAM_NAME varchar(64) DEFAULT NULL,
  PARAM_VALUE varchar(64) DEFAULT NULL,
  PRIMARY KEY (RSCP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;




