use openiam;

ALTER TABLE SYNCH_CONFIG ALTER USE_POLICY_MAP SET DEFAULT 'Y';
ALTER TABLE SYNCH_CONFIG ADD USE_TRANSFORM_SCRIPT CHAR(1) DEFAULT 'Y';
ALTER TABLE SYNCH_CONFIG ADD POLICY_MAP_BEFORE_TRANSFORM CHAR(1) DEFAULT 'Y';