use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS MIGRATE_USER_COMPANIES$$
CREATE PROCEDURE MIGRATE_USER_COMPANIES()
	BEGIN
	    DECLARE done INT DEFAULT FALSE;
		DECLARE division VARCHAR(50);
		DECLARE deptCode VARCHAR(50);
		DECLARE deptName VARCHAR(100);
		DECLARE companyId VARCHAR(32);
		DECLARE userId VARCHAR(32);
		DECLARE attrId INT DEFAULT 1;
		DECLARE cur1 CURSOR FOR (SELECT USER_ID, COMPANY_ID, DEPT_CD, DEPT_NAME FROM USERS);
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
		OPEN cur1;
		
		REPEAT 
			FETCH cur1 INTO userId, companyId, deptCode, deptName;
			IF (userId IS NOT NULL) THEN
				IF (companyId IS NOT NULL) THEN
					IF ((SELECT count(*) FROM COMPANY WHERE COMPANY_ID=companyId) = 1) THEN
						IF ((SELECT count(*) FROM USER_AFFILIATION WHERE COMPANY_ID=companyId AND USER_ID=userId) <= 0) THEN
							INSERT INTO USER_AFFILIATION (USER_AFFILIATION_ID, USER_ID, COMPANY_ID) VALUES(attrId, userId, companyId);
							set attrId:=attrId+1;
						END IF;
					END IF;
				END IF;

				IF (deptCode IS NOT NULL) THEN
					IF ((SELECT count(*) FROM COMPANY WHERE COMPANY_ID=deptCode) = 1) THEN
						IF ((SELECT count(*) FROM USER_AFFILIATION WHERE COMPANY_ID=deptCode AND USER_ID=userId) <= 0) THEN
							INSERT INTO USER_AFFILIATION (USER_AFFILIATION_ID, USER_ID, COMPANY_ID) VALUES(attrId, userId, deptCode);
							set attrId:=attrId+1;
						END IF;
					END IF;
				END IF;
				
				IF (deptName IS NOT NULL) THEN
					IF ((SELECT count(*) FROM COMPANY WHERE COMPANY_ID=deptName) = 1) THEN
						IF ((SELECT count(*) FROM USER_AFFILIATION WHERE COMPANY_ID=deptName AND USER_ID=userId) <= 0) THEN
							INSERT INTO USER_AFFILIATION (USER_AFFILIATION_ID, USER_ID, COMPANY_ID) VALUES(attrId, userId, deptName);
							set attrId:=attrId+1;
						END IF;
					END IF;
				END IF;
			END IF;
		UNTIL done END REPEAT; 
		CLOSE cur1;
	END$$
DELIMITER ;

call MIGRATE_USER_COMPANIES();
DROP PROCEDURE MIGRATE_USER_COMPANIES;


ALTER TABLE USERS DROP FOREIGN KEY FK_USERS_DEPARTMENT;
ALTER TABLE USERS DROP COLUMN DEPT_CD;
ALTER TABLE USERS DROP COLUMN DEPT_NAME;
ALTER TABLE USERS DROP FOREIGN KEY FK_USERS_DIVISION;
ALTER TABLE USERS DROP COLUMN DIVISION;
ALTER TABLE USERS DROP FOREIGN KEY FK_USERS_COMPANY;
ALTER TABLE USERS DROP COLUMN COMPANY_ID;