use openiam;

ALTER TABLE BATCH_CONFIG ADD COLUMN T_ENABLED CHAR(1) DEFAULT 'N';
UPDATE BATCH_CONFIG SET T_ENABLED='Y' WHERE ENABLED = 1;
ALTER TABLE BATCH_CONFIG DROP COLUMN ENABLED;
ALTER TABLE BATCH_CONFIG CHANGE T_ENABLED ENABLED CHAR(1) DEFAULT 'N' NOT NULL;