use openiam;

DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID = 'SELF_REPORT_VIEWER';
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID = 'SELF_REPORT_VIEWER';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'SELF_REPORT_VIEWER';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID = 'SELF_REPORT_VIEWER';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELF_REPORT_VIEWER';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_REPORT_VIEWER';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='SELF_REPORT_VIEWER';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, DISPLAY_ORDER, IS_PUBLIC, URL) 
	VALUES('SELF_REPORT_VIEWER', 'MENU_ITEM', 'SELF_REPORT_VIEWER', 'Report Viewer', 10, 'N', '/selfservice/report.html');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SELF_REPORT_VIEWER_PUB', 'SELF_REPORT_VIEWER', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SELF_REPORT_VIEWER_DESC', 'SELF_REPORT_VIEWER', 'MENU_DISPLAY_NAME', 'Report Viewer');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERVICE_REPORT', 'SELF_REPORT_VIEWER');

DELETE FROM RESOURCE_ROLE WHERE ROLE_ID='9' and RESOURCE_ID='SELF_REPORT_VIEWER';
INSERT INTO RESOURCE_ROLE (ROLE_ID, RESOURCE_ID) VALUES('9', 'SELF_REPORT_VIEWER');

DELETE FROM LANGUAGE_MAPPING WHERE ID IN ('SELF_REPORT_VIEWER_DESC', 'DESELF_REPORT_VIEWER_DESC',
  'ESSELF_REPORT_VIEWER_DESC', 'RUSELF_REPORT_VIEWER_DESC', 'JPSELF_REPORT_VIEWER_DESC');

INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES
  ('SELF_REPORT_VIEWER_DESC', '1', 'ResourceEntity.displayNameMap', 'SELF_REPORT_VIEWER', 'Report Viewer'),
  ('DESELF_REPORT_VIEWER_DESC', '2', 'ResourceEntity.displayNameMap', 'SELF_REPORT_VIEWER', 'Report Viewer'),
  ('ESSELF_REPORT_VIEWER_DESC', '4', 'ResourceEntity.displayNameMap', 'SELF_REPORT_VIEWER', 'Report Viewer'),
  ('RUSELF_REPORT_VIEWER_DESC', '8', 'ResourceEntity.displayNameMap', 'SELF_REPORT_VIEWER', 'Просмотрщик Отчетов'),
  ('JPSELF_REPORT_VIEWER_DESC', '9', 'ResourceEntity.displayNameMap', 'SELF_REPORT_VIEWER', 'Report Viewer');

UPDATE RES SET DISPLAY_ORDER = 20 WHERE RESOURCE_ID = 'SUBSCRIBE';
UPDATE RES SET DISPLAY_ORDER = 30, DESCRIPTION = 'View Report Files' WHERE RESOURCE_ID = 'VIEW';

UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'View Files' WHERE ID = 'VIEW_MENU_DESC';
UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Dateien anzeigen' WHERE ID = 'DEVIEW_MENU_DESC';
UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Ver archivos' WHERE ID = 'ESVIEW_MENU_DESC';
UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Просмотр Файлов' WHERE ID = 'RUVIEW_MENU_DESC';
UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'ファイルの表示' WHERE ID = 'JPVIEW_MENU_DESC';
