drop TABLE openiam.ORG_POLICY_USER_LOG;
drop TABLE openiam.ORG_POLICY;
drop TABLE openiam.IDM_AUDIT_LOG;
drop TABLE openiam.CREDENTIALS;
drop TABLE openiam.PWD_HISTORY;
DROP TABLE openiam.AUTH_STATE;
DROP TABLE openiam.LOGIN_ATTRIBUTE;
DROP TABLE openiam.LOGIN;
DROP TABLE openiam.RESOURCE_COMPANY;
DROP TABLE openiam.RESOURCE_GROUP;
DROP TABLE openiam.RESOURCE_ROLE;
DROP TABLE openiam.RESOURCE_USER;
DROP TABLE openiam.PRIVILEGE;
DROP TABLE openiam.RESOURCE_PROP;

DROP TABLE openiam.resource_privilege;
DROP TABLE openiam.resource_type;
DROP TABLE openiam.user_privilege;

DROP TABLE openiam.RES;
DROP TABLE openiam.RESOURCE_TYPE;
DROP TABLE openiam.USER_ROLE;
DROP TABLE openiam.GRP_ROLE;
DROP TABLE openiam.ROLE_POLICY;
DROP TABLE openiam.ROLE_ATTRIBUTE;
DROP TABLE openiam.ROLE;
DROP TABLE openiam.PHONE; 
DROP TABLE openiam.EMAIL_ADDRESS;
DROP TABLE openiam.ADDRESS;
DROP TABLE openiam.LOCATION;
DROP TABLE openiam.IMAGE;
DROP TABLE openiam.CATEGORY_TYPE;
DROP TABLE openiam.RELATION_SOURCE;
DROP TABLE openiam.RELATION_TYPE;
DROP TABLE openiam.RELATIONSHIP;
DROP TABLE openiam.RELATION_CATEGORY; 
DROP TABLE openiam.RELATION_SET;
DROP TABLE openiam.SEQUENCE_GEN;
DROP TABLE openiam.PERMISSIONS;
DROP TABLE openiam.USER_GRP;
DROP TABLE openiam.GRP_ATTRIBUTES;
DROP TABLE openiam.GRP;
DROP TABLE openiam.MENU;
DROP TABLE openiam.STATUS; 
DROP TABLE openiam.SERVICE_CONFIG; 
DROP TABLE openiam.SERVICE;
DROP TABLE openiam.USER_DELEGATION_ATTRIBUTE; 
DROP TABLE openiam.USER_ATTRIBUTES;
DROP TABLE openiam.USER_ATTACHMENT_REF;
DROP TABLE openiam.USER_NOTE;
DROP TABLE openiam.ORG_STRUCTURE;
DROP TABLE openiam.USER_AFFILIATION;

DROP TABLE openiam.USERS;
DROP TABLE openiam.COMPANY_ATTRIBUTE;
DROP TABLE openiam.COMPANY;
DROP TABLE openiam.METADATA_ELEMENT;
DROP TABLE openiam.METADATA_TYPE;
DROP TABLE openiam.CATEGORY_LANGUAGE;
DROP TABLE openiam.CATEGORY;
DROP TABLE openiam.EXCLUDE_WORD_LIST;
DROP TABLE openiam.BATCH_CONFIG;
DROP TABLE openiam.LANGUAGE;
DROP TABLE openiam.SECURITY_DOMAIN;
DROP TABLE openiam.NOTIFICATION_CONFIG;
DROP TABLE openiam.REPORT_CRITERIA_PARAMETER;
DROP TABLE openiam.REPORT_INFO;
DROP TABLE openiam.REPORT_SUB_CRITERIA_PARAM;
DROP TABLE openiam.REPORT_SUBSCRIPTIONS;
DROP TABLE openiam.REPORT_PARAMETER_TYPE;

commit;




