use openiam;


IF OBJECT_ID ( 'MIGRATE_COORELATED_NAME', 'P' ) IS NOT NULL 
    DROP PROCEDURE MIGRATE_COORELATED_NAME;
GO
CREATE PROCEDURE MIGRATE_COORELATED_NAME
AS
	DECLARE @theId NVARCHAR(32);
	DECLARE @theName NVARCHAR(250);
	DECLARE cur9 CURSOR FOR (SELECT RESOURCE_ID, NAME FROM MANAGED_SYS WHERE RESOURCE_ID IS NOT NULL);
	OPEN cur9;
	
	FETCH NEXT FROM cur9 INTO @theId, @theName;
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF (@theId IS NOT NULL AND @theName IS NOT NULL) 
		BEGIN
			UPDATE RES SET COORELATED_NAME=@theName WHERE RESOURCE_ID=@theId;
		END;
	END;
	CLOSE cur9;

EXECUTE  MIGRATE_COORELATED_NAME;


