use openiam;


IF EXISTS (SELECT * FROM ROLE WHERE ROLE_ID='2') 
BEGIN
	DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('USER_EDIT_MENU', 'SUP_SUB_PAGE', 'USER_ATTRIBUTES', 'USER_EDIT_CONTACT_INFO', 'USER_EDIT_INFO', 'USER_ENTITLEMENTS', 'USER_HISTORY', 'USER_IDENTITY', 'USER_SEARCH') AND ROLE_ID = '2';
	INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('USER_EDIT_MENU', '2'), ('SUP_SUB_PAGE', '2'), ('USER_ATTRIBUTES', '2'), ('USER_EDIT_CONTACT_INFO', '2'), ('USER_EDIT_INFO', '2'), ('USER_ENTITLEMENTS', '2'), ('USER_HISTORY', '2'), ('USER_IDENTITY', '2'), ('USER_SEARCH', '2');
END;
