

ALTER TABLE RECONCILIATION_CONFIG ADD (CSV_LINE_SEPARATOR VARCHAR2(10) DEFAULT 'comma');
ALTER TABLE RECONCILIATION_CONFIG ADD (CSV_END_OF_LINE VARCHAR2(10) DEFAULT 'enter');
ALTER TABLE RECONCILIATION_CONFIG ADD (NOTIFICATION_EMAIL_ADDRESS VARCHAR2(120));
ALTER TABLE RECONCILIATION_CONFIG ADD (TARGET_SYS_MATCH_SCRIPT VARCHAR2(120));
   





UPDATE USERS SET DIVISION=null WHERE DIVISION='';
UPDATE USERS SET DEPT_CD=null WHERE DEPT_CD='';
ALTER TABLE USERS DROP COLUMN DEL_ADMIN;
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_DEPARTMENT FOREIGN KEY (DEPT_CD) REFERENCES COMPANY (COMPANY_ID);
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_DIVISION FOREIGN KEY (DIVISION) REFERENCES COMPANY (COMPANY_ID);
CREATE INDEX FK_USERS_DEPARTMENT ON USERS(DEPT_CD);
CREATE INDEX FK_USERS_DIVISION ON USERS(DIVISION);






ALTER TABLE APPROVER_ASSOC RENAME COLUMN ASSOCIATION_OBJ_ID TO ASSOCIATION_ENTITY_ID;
ALTER TABLE APPROVER_ASSOC MODIFY (ASSOCIATION_ENTITY_ID VARCHAR2(32));

ALTER TABLE APPROVER_ASSOC ADD (APPROVER_ENTITY_TYPE VARCHAR2(20));
ALTER TABLE APPROVER_ASSOC ADD (APPROVER_ENTITY_ID VARCHAR2(32));

ALTER TABLE APPROVER_ASSOC RENAME COLUMN ON_APPROVE_NOTIFY_USER_ID TO ON_APPROVE_ENTITY_ID;
ALTER TABLE APPROVER_ASSOC RENAME COLUMN ON_REJECT_NOTIFY_USER_ID TO ON_REJECT_ENTITY_ID;
ALTER TABLE APPROVER_ASSOC MODIFY (ON_APPROVE_ENTITY_ID VARCHAR2(32));
ALTER TABLE APPROVER_ASSOC MODIFY (ON_REJECT_ENTITY_ID VARCHAR2(32));

ALTER TABLE APPROVER_ASSOC RENAME COLUMN APPROVE_NOTIFY_USER_TYPE TO ON_APPROVE_ENTITY_TYPE;
ALTER TABLE APPROVER_ASSOC RENAME COLUMN REJECT_NOTIFY_USER_TYPE TO ON_REJECT_ENTITY_TYPE;
ALTER TABLE APPROVER_ASSOC MODIFY (ON_APPROVE_ENTITY_TYPE VARCHAR2(20));
ALTER TABLE APPROVER_ASSOC MODIFY (ON_REJECT_ENTITY_TYPE VARCHAR2(20));

ALTER TABLE APPROVER_ASSOC DROP COLUMN ACTN;

ALTER TABLE APPROVER_ASSOC DROP COLUMN APPROVER_ROLE_DOMAIN;

UPDATE APPROVER_ASSOC SET APPROVER_ENTITY_TYPE='USER', APPROVER_ENTITY_ID=APPROVER_USER_ID WHERE APPROVER_USER_ID IS NOT NULL;
UPDATE APPROVER_ASSOC SET APPROVER_ENTITY_TYPE='ROLE', APPROVER_ENTITY_ID=APPROVER_ROLE_ID WHERE APPROVER_ROLE_ID IS NOT NULL;

ALTER TABLE APPROVER_ASSOC DROP COLUMN APPROVER_ROLE_ID;
ALTER TABLE APPROVER_ASSOC DROP COLUMN APPROVER_USER_ID;

ALTER TABLE APPROVER_ASSOC ADD (APPLY_DELEGATION_FILTER_T char(1));
UPDATE APPROVER_ASSOC SET APPLY_DELEGATION_FILTER_T='Y' WHERE APPLY_DELEGATION_FILTER=1;
UPDATE APPROVER_ASSOC SET APPLY_DELEGATION_FILTER_T='N' WHERE APPLY_DELEGATION_FILTER=0;
UPDATE APPROVER_ASSOC SET APPLY_DELEGATION_FILTER_T='N' WHERE APPLY_DELEGATION_FILTER IS NULL;
ALTER TABLE APPROVER_ASSOC DROP COLUMN APPLY_DELEGATION_FILTER;
ALTER TABLE APPROVER_ASSOC MODIFY (APPLY_DELEGATION_FILTER_T char(1) DEFAULT 'N' NOT NULL);
ALTER TABLE APPROVER_ASSOC RENAME COLUMN APPLY_DELEGATION_FILTER_T TO APPLY_DELEGATION_FILTER;






ALTER TABLE POLICY_ATTRIBUTE ADD (REQUIRED CHAR(1) DEFAULT 'Y' NOT NULL );




CREATE  TABLE DEF_RECON_ATTR_MAP (
  DEF_ATTR_MAP_ID VARCHAR2(32) NOT NULL ,
  DEF_ATTR_MAP_NAME VARCHAR2(100) NOT NULL ,
  PRIMARY KEY (DEF_ATTR_MAP_ID)
);

CREATE  TABLE RECON_RES_ATTR_MAP (
  RECON_RES_ATTR_MAP_ID INT NOT NULL,
  ATTR_POLICY_ID VARCHAR2(32) NULL ,
  DEF_RECON_ATTR_MAP_ID VARCHAR2(32) NULL ,
  ATTR_MAP_ID VARCHAR2(32) NOT NULL ,
  PRIMARY KEY (RECON_RES_ATTR_MAP_ID)
);

CREATE SEQUENCE RECON_RES_ATTR_MAP_SEQ;

CREATE OR REPLACE TRIGGER RECON_RES_ATTR_MAP_TRG 
BEFORE INSERT ON RECON_RES_ATTR_MAP 
FOR EACH ROW

BEGIN
  SELECT RECON_RES_ATTR_MAP_SEQ.NEXTVAL
  INTO   :new.RECON_RES_ATTR_MAP_ID
  FROM   dual;
END;
/


INSERT INTO RECON_RES_ATTR_MAP (ATTR_MAP_ID, ATTR_POLICY_ID) (SELECT ATTRIBUTE_MAP_ID, ATTRIBUTE_POLICY_ID FROM ATTRIBUTE_MAP);
INSERT INTO DEF_RECON_ATTR_MAP (DEF_ATTR_MAP_ID, DEF_ATTR_MAP_NAME) VALUES ('Login.login','Principal');
INSERT INTO DEF_RECON_ATTR_MAP (DEF_ATTR_MAP_ID, DEF_ATTR_MAP_NAME) VALUES ('User.title','Functional Title');

UPDATE ATTRIBUTE_MAP am SET ATTRIBUTE_POLICY_ID = (
  SELECT RECON_RES_ATTR_MAP_ID
  FROM RECON_RES_ATTR_MAP rram
  WHERE am.ATTRIBUTE_MAP_ID=rram.ATTR_MAP_ID
);

ALTER TABLE RECON_RES_ATTR_MAP ADD (RECON_RES_ATTR_MAP_ID_T VARCHAR2(32));
UPDATE RECON_RES_ATTR_MAP SET RECON_RES_ATTR_MAP_ID_T = to_char(RECON_RES_ATTR_MAP_ID);
ALTER TABLE RECON_RES_ATTR_MAP DROP PRIMARY KEY;
ALTER TABLE RECON_RES_ATTR_MAP DROP COLUMN RECON_RES_ATTR_MAP_ID;
ALTER TABLE RECON_RES_ATTR_MAP RENAME COLUMN RECON_RES_ATTR_MAP_ID_T TO RECON_RES_ATTR_MAP_ID;
ALTER TABLE RECON_RES_ATTR_MAP MODIFY (RECON_RES_ATTR_MAP_ID VARCHAR2(32) NOT NULL);
ALTER TABLE RECON_RES_ATTR_MAP ADD PRIMARY KEY (RECON_RES_ATTR_MAP_ID);


ALTER TABLE RECON_RES_ATTR_MAP DROP COLUMN ATTR_MAP_ID ;

DROP SEQUENCE RECON_RES_ATTR_MAP_SEQ;




CREATE  TABLE MANAGED_SYS_RULE (
  MANAGED_SYS_RULE_ID VARCHAR2(32) NOT NULL ,
  MANAGED_SYS_ID VARCHAR2(32) NOT NULL ,
  MANAGED_SYS_RULE_NAME VARCHAR2(45) NULL ,
  MANAGED_SYS_RULE_VALUE VARCHAR2(45) NULL ,
  PRIMARY KEY (MANAGED_SYS_RULE_ID)
);

ALTER TABLE USER_ATTRIBUTES ADD (VALUE_AS_BYTE_ARRAY BLOB);





ALTER TABLE URI_PATTERN_META_VALUE ADD (GROOVY_SCRIPT VARCHAR2(200));

ALTER TABLE CONTENT_PROVIDER ADD (MANAGED_SYS_ID VARCHAR2(32));

UPDATE CONTENT_PROVIDER SET MANAGED_SYS_ID='0';

ALTER TABLE CONTENT_PROVIDER MODIFY (MANAGED_SYS_ID VARCHAR2(32) NOT NULL);

ALTER TABLE CONTENT_PROVIDER ADD CONSTRAINT FK_CP_MANAGED_SYS FOREIGN KEY(MANAGED_SYS_ID) REFERENCES MANAGED_SYS(MANAGED_SYS_ID);