DROP SCHEMA MY_CUSTOM_APPLICATION;
commit;
CREATE SCHEMA MY_CUSTOM_APPLICATION;
CREATE TABLE MY_CUSTOM_APPLICATION.USERS
(
    LOGIN VARCHAR(32) PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    STATUS VARCHAR(32) NOT NULL
);
ALTER TABLE MY_CUSTOM_APPLICATION.USERS ADD CONSTRAINT unique_LOGIN UNIQUE (LOGIN);

CREATE TABLE MY_CUSTOM_APPLICATION.GRP
(
    GRP_ID VARCHAR(32) PRIMARY KEY NOT NULL,
    GRP_NAME VARCHAR(32) NOT NULL
);
ALTER TABLE MY_CUSTOM_APPLICATION.GRP ADD CONSTRAINT unique_GRP_ID UNIQUE (GRP_ID);



CREATE TABLE  MY_CUSTOM_APPLICATION.USER_TO_GRP
(
  USER_ID VARCHAR(32) NOT NULL,
  GRP_ID VARCHAR(32) NOT NULL,
  MEMBERSHIP_ID VARCHAR(70) PRIMARY KEY NOT NULL
);
CREATE UNIQUE INDEX unique_MEMBERSHIP_ID ON MY_CUSTOM_APPLICATION.USER_TO_GRP (MEMBERSHIP_ID);

CREATE TABLE MY_CUSTOM_APPLICATION.GRP_TO_GRP
(
    GRP_ID VARCHAR(32) NOT NULL,
    CHILD_GRP_ID VARCHAR(32) NOT NULL,
  MEMBERSHIP_ID VARCHAR(70) PRIMARY KEY NOT NULL
);
CREATE UNIQUE INDEX unique_MEMBERSHIP_GP_ID ON MY_CUSTOM_APPLICATION.USER_TO_GRP (MEMBERSHIP_ID);

