use openiam;

UPDATE BATCH_CONFIG SET TASK_NAME='Re-Certification' WHERE TASK_ID='ATTESTATION';

DELETE FROM BATCH_CONFIG WHERE TASK_ID='TASK_EMAIL_NOTIFICATION';

INSERT INTO BATCH_CONFIG (TASK_ID, TASK_NAME, CRON_EXPRESSION, SPRING_BEAN, SPRING_BEAN_METHOD) VALUES('TASK_EMAIL_NOTIFICATION', 'Task Email Notification', '0 0 0 1 1/3 ?', 'taskEmailNotifier', 'sweep');