package org.openiam.idm.srvc.recon.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

// Generated May 29, 2010 8:20:09 PM by Hibernate Tools 3.2.2.GA

/**
 * ReconiliationSituation generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReconciliationSituation", 
		propOrder = { "reconSituationId",
		"reconConfigId",
		"situation", 
		"situationResp",
		"script"})
public class ReconciliationSituation implements java.io.Serializable {

    private static final long serialVersionUID = -8870989951105414407L;
    private String reconSituationId;
	private String reconConfigId;
	private String situation;
	private String situationResp;
	private String script;


	
	public ReconciliationSituation() {
	}

	public ReconciliationSituation(String reconSituationId) {
		this.reconSituationId = reconSituationId;
	}

	public ReconciliationSituation(String reconSituationId, String situation) {
		this.reconSituationId = reconSituationId;
		this.situation = situation;
	}
	
	public ReconciliationSituation(String reconSituationId,
			String reconConfigId, String situation, String situationResp) {
		this.reconSituationId = reconSituationId;
		this.reconConfigId = reconConfigId;
		this.situation = situation;
		this.situationResp = situationResp;
	}

	public String getReconSituationId() {
		return this.reconSituationId;
	}

	public void setReconSituationId(String reconSituationId) {
		this.reconSituationId = reconSituationId;
	}

	public String getReconConfigId() {
		return this.reconConfigId;
	}

	public void setReconConfigId(String reconConfigId) {
		this.reconConfigId = reconConfigId;
	}

	public String getSituation() {
		return this.situation;
	}

	public void setSituation(String situation) {
		this.situation = situation;
	}

	public String getSituationResp() {
		return this.situationResp;
	}

	public void setSituationResp(String situationResp) {
		this.situationResp = situationResp;
	}

    public String getScript() {
        return script;
    }

    public void setScript(String script) {
        this.script = script;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ReconciliationSituation situation1 = (ReconciliationSituation) o;

        if (reconConfigId != null ? !reconConfigId.equals(situation1.reconConfigId) : situation1.reconConfigId != null)
            return false;
        if (script != null ? !script.equals(situation1.script) : situation1.script != null) return false;
        if (situation != null ? !situation.equals(situation1.situation) : situation1.situation != null) return false;
        if (situationResp != null ? !situationResp.equals(situation1.situationResp) : situation1.situationResp != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = reconConfigId != null ? reconConfigId.hashCode() : 0;
        result = 31 * result + (situation != null ? situation.hashCode() : 0);
        result = 31 * result + (situationResp != null ? situationResp.hashCode() : 0);
        result = 31 * result + (script != null ? script.hashCode() : 0);
        return result;
    }
}
