USE openiam;

/* POWERSHELL-EXCHANGE Connector */
insert into PROVISION_CONNECTOR(CONNECTOR_ID, NAME, METADATA_TYPE_ID, SERVICE_URL,SERVICE_NAMESPACE, SERVICE_PORT, CLIENT_COMM_PROTOCOL, CONNECTOR_INTERFACE) VALUES ('67','POWERSHELL-EXCHANGE', 'POWERSHELL-EXCHANGE','localhost:8080/openiam-idm-esb/idmsrvc/PowershellConnectorExchange2010/PowershellConnector.svc','urn:idm.openiam.org/spml2/service', '443', 'CLEAR', 'REMOTE');

/* POWERSHELL-EXCHANGE Connector */
INSERT INTO MANAGED_SYS (MANAGED_SYS_ID, NAME, DESCRIPTION, STATUS, CONNECTOR_ID, DOMAIN_ID, HOST_URL, PORT, COMM_PROTOCOL, RESOURCE_ID, ADD_HNDLR, MODIFY_HNDLR, DELETE_HNDLR, SETPASS_HNDLR, SUSPEND_HNDLR, SEARCH_HNDLR, LOOKUP_HNDLR, TEST_CONNECTION_HNDLR, RECONCILE_RESOURCE_HNDLR) VALUES('113','POWERSHELL-EXCHANGE', 'POWERSHELL-EXCHANGE', 'ACTIVE', '67', 'USR_SEC_DOMAIN', '', null,'CLEAR', '113', 'Exchange2010Connector.ps1', 'Exchange2010Connector.ps1', 'Exchange2010Connector.ps1', 'Exchange2010Connector.ps1', 'Exchange2010Connector.ps1', 'Exchange2010Connector.ps1', 'Exchange2010Connector.ps1', 'Exchange2010Connector.ps1', 'Exchange2010Connector.ps1');


/* POWERSHELL-EXCHANGE Connector */
insert into MNG_SYS_OBJECT_MATCH(OBJECT_SEARCH_ID, MANAGED_SYS_ID, OBJECT_TYPE, MATCH_METHOD, SEARCH_FILTER, BASE_DN, SEARCH_BASE_DN ,KEY_FIELD) VALUES('113', '113', 'USER', 'BASE_DN', '(&(objectclass=inetOrgPerson)(?))',null,null,'uid');

/* POWERSHELL-EXCHANGE Connector */
insert into RES (RESOURCE_ID, RESOURCE_TYPE_ID,NAME, DISPLAY_ORDER, MANAGED_SYS_ID ) VALUES ('113', 'MANAGED_SYS', 'POWERSHELL-EXCHANGE', 2, '113');

/* POWERSHELL-EXCHANGE Connector */
/* MAP FOR POWERSHELL-EXCHANGE Connector */
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('801', '113', '113','PRINCIPAL', 'SamAccountName', '4630');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('802', '113', '113','USER', 'SamAccountName', '4660');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('803', '113', '113','USER', 'LastName', '4506');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('804', '113', '113','USER', 'FirstName', '4631');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('805', '113', '113','USER', 'DisplayName', '4517');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('806', '113', '113','USER', 'OrganizationalUnit', '4633');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('807', '113', '113','USER', 'Company', '4640');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('808', '113', '113','USER', 'Initials', '4642');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('809', '113', '113','USER', 'Department', '4643');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('810', '113', '113','USER', 'Title', '4645');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('811', '113', '113','USER', 'UserPrincipalName', '4651');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('812', '113', '113','USER', 'StreetAddress', '4653');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('813', '113', '113','USER', 'City', '4654');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('814', '113', '113','USER', 'PostalCode', '4656');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('815', '113', '113','USER', 'Phone', '4644');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('816', '113', '113','USER', 'Name', '4661');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('817', '113', '113','USER', 'Password', '4509');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('818', '113', '113','USER', 'WindowsEmailAddress', '4540');
INSERT INTO ATTRIBUTE_MAP(ATTRIBUTE_MAP_ID, MANAGED_SYS_ID, RESOURCE_ID, MAP_FOR_OBJECT_TYPE, ATTRIBUTE_NAME, ATTRIBUTE_POLICY_ID) VALUES ('819', '113', '113','USER', 'Group', '4652');

UPDATE ATTRIBUTE_MAP
SET DATA_TYPE = 'string'
where DATA_TYPE IS NULL AND MANAGED_SYS_ID = '113';