use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS ALTER_REPORT_CRITERIA_PARAMETER$$
CREATE PROCEDURE ALTER_REPORT_CRITERIA_PARAMETER()
	BEGIN
		IF NOT EXISTS (SELECT * FROM information_schema.columns WHERE table_name = 'REPORT_CRITERIA_PARAMETER' AND column_name = 'DISPLAY_ORDER') THEN
			ALTER TABLE REPORT_CRITERIA_PARAMETER ADD COLUMN DISPLAY_ORDER INT(11) NOT NULL;
 		END IF;
		IF NOT EXISTS (SELECT * FROM information_schema.columns WHERE table_name = 'REPORT_CRITERIA_PARAMETER' AND column_name = 'REQUEST_PARAMS') THEN
			ALTER TABLE REPORT_CRITERIA_PARAMETER ADD COLUMN REQUEST_PARAMS VARCHAR(512) NULL;
 		END IF;
	END$$
DELIMITER ;

CALL ALTER_REPORT_CRITERIA_PARAMETER();
DROP PROCEDURE ALTER_REPORT_CRITERIA_PARAMETER;


UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 1 WHERE RCP_ID IN ('1011','1021','1031','1041','1051');
UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 2 WHERE RCP_ID IN ('1012','1022','1042','1052');
UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 3 WHERE RCP_ID IN ('1013','1023','1053');
UPDATE REPORT_CRITERIA_PARAMETER SET DISPLAY_ORDER = 4 WHERE RCP_ID IN ('1014','1024','1054');

DELIMITER $$

DROP PROCEDURE IF EXISTS ADD_PARAMETER_METATYPE$$
CREATE PROCEDURE ADD_PARAMETER_METATYPE()
	BEGIN
		IF NOT EXISTS (SELECT * FROM REPORT_PARAMETER_METATYPE WHERE PARAM_METATYPE_ID = 'RESOURCE') THEN
			INSERT INTO REPORT_PARAMETER_METATYPE (PARAM_METATYPE_ID, PARAM_METATYPE_NAME, IS_MULTIPLE) VALUES ('RESOURCE', 'Resource', 'Y');
 		END IF;
	END$$
DELIMITER ;

CALL ADD_PARAMETER_METATYPE();
DROP PROCEDURE ADD_PARAMETER_METATYPE;
