use openiam;

DELETE FROM RECONCILIATION_SITUATION WHERE RECON_CONFIG_ID IN ('1011', '4028b881373b90e501373b92ec180001');
DELETE FROM RECONCILIATION_CONFIG WHERE RECON_CONFIG_ID IN ('1011', '4028b881373b90e501373b92ec180001');

INSERT INTO RECONCILIATION_CONFIG (RECON_CONFIG_ID,RESOURCE_ID,STATUS,TARGET_SYS_MATCH_SCRIPT,MATCH_FIELD_NAME,CUSTOM_MATCH_ATTR,MANAGED_SYS_ID,SEARCH_FILTER,TARGET_SYS_SEARCH_FILTER,MATCH_SCRIPT,RECON_TYPE)
VALUES ('1011','101','ACTIVE','recon/LDAPSearchQuery.groovy','PRINCIPAL','uid','101','{"employeeId":"not_found"}','(&(objectclass=inetOrgPerson)(uid=*))','recon/UserSearchScript.groovy','USER');

INSERT INTO RECONCILIATION_SITUATION (RECON_SITUATION_ID,RECON_CONFIG_ID,SITUATION,SITUATION_RESP,SCRIPT) VALUES
('10111','1011','IDM[exists] and Resource[not exists]','DELETE_FROM_IDM','recon/LDAPPopulationScript.groovy'),
('10112','1011','IDM[not exists] and Resource[exists]','ADD_TO_IDM','recon/LDAPPopulationScript.groovy'),
('10113','1011','IDM[deleted] and Resource[exists]','NOTHING','recon/LDAPPopulationScript.groovy'),
('10114','1011','IDM[exists] and Resource[exists]','UPDATE_IDM_FROM_RES','recon/LDAPPopulationScript.groovy');
