use openiam;

DELIMITER $$

DROP PROCEDURE IF EXISTS ADD_RES_REPORT$$
CREATE PROCEDURE ADD_RES_REPORT()
	BEGIN
 		IF NOT EXISTS (SELECT * FROM RESOURCE_TYPE WHERE RESOURCE_TYPE_ID = 'REPORT') THEN
			INSERT INTO RESOURCE_TYPE (RESOURCE_TYPE_ID, DESCRIPTION, PROVISION_RESOURCE, PROCESS_NAME, SUPPORTS_HIERARCHY, SEARCHABLE, URL, IMAGE_TYPE)
				VALUES ('REPORT', 'Report', NULL, NULL, 'N', 'Y', 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAY9JREFUeNpiZC5lZgADRoY+IKnPQBy4yPCfoQjOE1NQYAitr0/7TyRgLmHeB8QMIMwINSPt7t27M+/du8cAwqmpqQz3n//AarWiFCcDazHLfiDTCUUioLIy8++/f////P2LF4PUMOcz7wdiBhDG6oLE5GSGh89/YneBNCcDez7rASDTEUXCo7Aw5xfQhh+/f+PFIDXMmcwHgJgBhLG6IDYhgeHhs19YXaAkx8XAmcl6EMh0QJFwSE8v+P7nz//PP37gxSA1TMlMB4GYAYSxuiA8Lo7hydPf2MNAnpOBN4X9MJBpB0k+UGAeG1uyZ+7c7t+/f+NNQaysrAz8iRxHgExbZANQXBAcHc3w5Mkf7GGgxMUgEItpAINuYGDFkRUr2n/+/InXBezs7AyCUZxHgUwbnC7wj4hgePrkL3YXKHMxCIdyHQMyrf+f+I+Q4NXVbf8EDOF3wJDGh0FqGO0YTzIKQuxmAWIhIJb6/POyHJ8Zyxmi8uIXhjsM7xl0gKxnIGM4QQ6AGkYKAIXyZ4AAAwDo2Ez5UkE+nAAAAABJRU5ErkJggg==', 'png');
 		END IF;

		IF NOT EXISTS (SELECT * FROM LANGUAGE_MAPPING WHERE ID = 'REPORT') THEN
			INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
			  ('REPORT', '1', 'REPORT', 'ResourceTypeEntity.displayNameMap', 'Report'),
			  ('DEREPORT', '2', 'REPORT', 'ResourceTypeEntity.displayNameMap', 'Bericht'),
			  ('ESREPORT', '4', 'REPORT', 'ResourceTypeEntity.displayNameMap', 'Informe'),
			  ('JPREPORT', '9', 'REPORT', 'ResourceTypeEntity.displayNameMap', '報告'),
			  ('RUREPORT', '8', 'REPORT', 'ResourceTypeEntity.displayNameMap', 'Отчет');
 		END IF;

		IF NOT EXISTS (SELECT * FROM RES WHERE RESOURCE_ID = 'USER_REPORT_101') THEN
			INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, MIN_AUTH_LEVEL, IS_PUBLIC,
			    ADMIN_RESOURCE_ID, RISK, TYPE_ID, COORELATED_NAME) VALUES
			  ('USER_REPORT_101', 'REPORT', NULL, 'USER_REPORT_101', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'USER_REPORT'),
			  ('AUDIT_REPORT_102', 'REPORT', NULL, 'AUDIT_REPORT_102', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'AUDIT_REPORT'),
			  ('RECONCILIATION_REPORT_103', 'REPORT', NULL, 'RECONCILIATION_REPORT_103', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'RECONCILIATION_REPORT'),
			  ('SYNCHRONIZATION_REPORT_104', 'REPORT', NULL, 'SYNCHRONIZATION_REPORT_104', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'SYNCHRONIZATION_REPORT');
 		END IF;
	END$$
DELIMITER ;

call ADD_RES_REPORT();
DROP PROCEDURE ADD_RES_REPORT;

UPDATE REPORT_INFO SET RESOURCE_ID = 'USER_REPORT_101' WHERE REPORT_INFO_ID = '101';
UPDATE REPORT_INFO SET RESOURCE_ID = 'AUDIT_REPORT_102' WHERE REPORT_INFO_ID = '102';
UPDATE REPORT_INFO SET RESOURCE_ID = 'RECONCILIATION_REPORT_103' WHERE REPORT_INFO_ID = '103';
UPDATE REPORT_INFO SET RESOURCE_ID = 'SYNCHRONIZATION_REPORT_104' WHERE REPORT_INFO_ID = '104';

