use openiam;

DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='CHANGE_PASS_MANAGED_SYS';

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC','1','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Change Password Extended');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC10','10','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','更改密碼擴展');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC2','2','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Passwort ändern Erweiterte');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC4','4','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Cambiar contraseña Extended');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC8','8','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Расширенная смена пароля');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC9','9','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','パスワードの変更は、拡張');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC11','11','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Alterar senha Extensão');
