use openiam;
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='OrganizationEntity.displayNameMap' and REFERENCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_INFO_BTN', 'ORGANIZATIONS_PROV_BTN', 'ORGANIZATIONS_DEPROV_BTN');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ENT_USR_ORG_BTN_ROOT', 'MENU_ITEM', 'Root menu for UserOrg Membership', 'ENT_USR_ORG_BTN_ROOT', 'ENT_USR_ORG_BTN_ROOT', null, 50, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_ORG_BTN_ROOT_PUB', 'ENT_USR_ORG_BTN_ROOT', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ENT_USR_ORG_BTN_ROOT_DESC', 'ENT_USR_ORG_BTN_ROOT', 'MENU_DISPLAY_NAME', 'Root menu for UserOrg Membership');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ORGANIZATIONS_ADD_BTN', 'MENU_ITEM', 'Add User To Organization', 'ORGANIZATIONS_ADD_BTN', 'ORGANIZATIONS_ADD_BTN', '/webconsole/addUserToOrganization.html', 51, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_ADD_BTN_PUB', 'ORGANIZATIONS_ADD_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_ADD_BTN_DESC', 'ORGANIZATIONS_ADD_BTN', 'MENU_DISPLAY_NAME', 'Add User To Organization');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ORGANIZATIONS_EDT_BTN', 'MENU_ITEM', 'Edit Organization', 'ORGANIZATIONS_EDT_BTN', 'ORGANIZATIONS_EDT_BTN', null, 52, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_EDT_BTN_PUB', 'ORGANIZATIONS_EDT_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_EDT_BTN_DESC', 'ORGANIZATIONS_EDT_BTN', 'MENU_DISPLAY_NAME', 'Edit Organization');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('ORGANIZATIONS_DEL_BTN', 'MENU_ITEM', 'Delete User from Organization', 'ORGANIZATIONS_DEL_BTN', 'ORGANIZATIONS_DEL_BTN', '/webconsole/removeUserFromOrganization.html', 53, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_DEL_BTN_PUB', 'ORGANIZATIONS_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORGANIZATIONS_DEL_BTN_DESC', 'ORGANIZATIONS_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete User from Organization');


INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_ADD_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_EDT_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ENT_USR_ORG_BTN_ROOT', 'ORGANIZATIONS_DEL_BTN');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ENT_USR_ORG_BTN_ROOT', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORGANIZATIONS_ADD_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORGANIZATIONS_EDT_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORGANIZATIONS_DEL_BTN', '9');


INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ENT_USR_ORG_BTN_ROOT','1','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ENT_USR_ORG_BTN_ROOT','2','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ENT_USR_ORG_BTN_ROOT','4','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ENT_USR_ORG_BTN_ROOT','8','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ENT_USR_ORG_BTN_ROOT','9','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ENT_USR_ORG_BTN_ROOT','10','ENT_USR_ORG_BTN_ROOT','ResourceEntity.displayNameMap','User Organization Membership Buttons');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ORGANIZATIONS_ADD_BTN','1','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ORGANIZATIONS_ADD_BTN','2','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ORGANIZATIONS_ADD_BTN','4','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ORGANIZATIONS_ADD_BTN','8','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ORGANIZATIONS_ADD_BTN','9','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ORGANIZATIONS_ADD_BTN','10','ORGANIZATIONS_ADD_BTN','ResourceEntity.displayNameMap','Add Organization to User');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ORGANIZATIONS_EDT_BTN','1','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ORGANIZATIONS_EDT_BTN','2','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ORGANIZATIONS_EDT_BTN','4','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ORGANIZATIONS_EDT_BTN','8','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ORGANIZATIONS_EDT_BTN','9','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ORGANIZATIONS_EDT_BTN','10','ORGANIZATIONS_EDT_BTN','ResourceEntity.displayNameMap','Edit Organization');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_ORGANIZATIONS_DEL_BTN','1','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_ORGANIZATIONS_DEL_BTN','2','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_ORGANIZATIONS_DEL_BTN','4','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_ORGANIZATIONS_DEL_BTN','8','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_ORGANIZATIONS_DEL_BTN','9','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_ORGANIZATIONS_DEL_BTN','10','ORGANIZATIONS_DEL_BTN','ResourceEntity.displayNameMap','Remove Organization from User');
