use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'ORG_LOCATION';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'ORG_LOCATION';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'ORG_LOCATION_PUB';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_PROP_ID = 'ORG_LOCATION_DESC';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID = 'ORG_LOCATION';
DELETE FROM RES WHERE RESOURCE_ID = 'ORG_LOCATION';
DELETE FROM LOCATION;

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, URL, DISPLAY_ORDER) VALUES('ORG_LOCATION', 'MENU_ITEM', 'ORG_LOCATION', 'Organization Location','/webconsole/organizationLocation.html',3);
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORG_LOCATION_PUB', 'ORG_LOCATION', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('ORG_LOCATION_DESC', 'ORG_LOCATION', 'MENU_DISPLAY_NAME', 'Organization Location');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('ORGANIZATION_EDIT_ID', 'ORG_LOCATION');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('ORG_LOCATION', '9');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESORG_LOCATION','1','ORG_LOCATION','ResourceEntity.displayNameMap','Organization Location');
INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUORG_LOCATION','8','ORG_LOCATION','ResourceEntity.displayNameMap','Месторасположение организации');

