use openiam;


DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM RES WHERE RESOURCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID IN ('WEBCONSOLE_CHALLENGE_QUEST');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('WEBCONSOLE_CHALLENGE_QUEST', 'MENU_ITEM', 'Challenge Response', 'WEBCONSOLE_CHALLENGE_QUEST', 'WEBCONSOLE_CHALLENGE_QUEST', '/webconsole/challengeQuestRes.html', 20, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('WEBCONSOLE_CHALLENGE_QUEST_PUB', 'WEBCONSOLE_CHALLENGE_QUEST', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('WEBCONSOLE_CHALLENGE_QUEST_DESC', 'WEBCONSOLE_CHALLENGE_QUEST', 'MENU_DISPLAY_NAME', 'Challenge Response');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('WEBCONSOLE_CHALLENGE_QUEST_VIS', 'WEBCONSOLE_CHALLENGE_QUEST', 'IS_VISIBLE', 'false');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('USER_EDIT_MENU', 'WEBCONSOLE_CHALLENGE_QUEST');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('EN_WEBCONSOLE_CHALLENGE_QUEST','1','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response'),
  ('DE_WEBCONSOLE_CHALLENGE_QUEST','2','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response'),
  ('ES_WEBCONSOLE_CHALLENGE_QUEST','4','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response'),
  ('RU_WEBCONSOLE_CHALLENGE_QUEST','8','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response'),
  ('JP_WEBCONSOLE_CHALLENGE_QUEST','9','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response'),
  ('ZH_WEBCONSOLE_CHALLENGE_QUEST','10','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response'),
  ('PT_WEBCONSOLE_CHALLENGE_QUEST','11','WEBCONSOLE_CHALLENGE_QUEST','ResourceEntity.displayNameMap','Challenge Response');
