use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN  ('SELFSERV_USER_MEMSHP');
DELETE FROM RES WHERE RESOURCE_ID IN ('SELFSERV_USER_MEMSHP');

