use openiam;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS	WHERE TABLE_NAME='SYNCH_CONFIG' AND column_name='ATTRIBUTE_NAMES_LOOKUP') 
BEGIN
	ALTER TABLE SYNCH_CONFIG ADD ATTRIBUTE_NAMES_LOOKUP NVARCHAR(120) NULL;
END;


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='SYNCH_CONFIG' AND column_name='SEARCH_SCOPE') 
	ALTER TABLE SYNCH_CONFIG ADD SEARCH_SCOPE INTEGER NOT NULL DEFAULT 2;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME='MANAGED_SYS' AND column_name='SEARCH_SCOPE') 
	ALTER TABLE MANAGED_SYS ADD SEARCH_SCOPE INTEGER NOT NULL DEFAULT 2;

