use openiam;

ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN MATCH_FIELD_NAME VARCHAR(40) NULL;
ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN CUSTOM_MATCH_ATTR VARCHAR(40) NULL;
ALTER TABLE RECONCILIATION_CONFIG ADD COLUMN CUSTOM_MATCH_SRC_ATTR VARCHAR(40) NULL;