use openiam;

IF OBJECT_ID('PROFILE_PIC', 'U') IS NOT NULL
  DROP TABLE PROFILE_PIC

CREATE TABLE PROFILE_PIC (
	PROFILE_PIC_ID NVARCHAR(32) NOT NULL,
	USER_ID NVARCHAR(32) UNIQUE NOT NULL,
	NAME NVARCHAR(256) NULL,
    PICTURE varbinary(MAX) NOT NULL,
	PRIMARY KEY (PROFILE_PIC_ID),
	CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE);

CREATE INDEX PROFILE_PIC_IDX ON PROFILE_PIC(PROFILE_PIC_ID);
CREATE INDEX USERS_IDX ON PROFILE_PIC(USER_ID);

DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM RES WHERE RESOURCE_ID = 'PROFILE_PIC';
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID='PROFILE_PIC';


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, NAME, DESCRIPTION, DISPLAY_ORDER, IS_PUBLIC, URL) 
	VALUES('PROFILE_PIC', 'MENU_ITEM', 'PROFILE_PIC', 'Edit Your Profile Picture', 10, 'Y', '/selfservice/editProfilePic.html');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('PROFILE_PIC_PUB', 'PROFILE_PIC', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('PROFILE_PIC_DESC', 'PROFILE_PIC', 'MENU_DISPLAY_NAME', 'Edit Your Profile Picture');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFCENTER', 'PROFILE_PIC');

DELETE FROM RESOURCE_ROLE WHERE ROLE_ID='9' and RESOURCE_ID='PROFILE_PIC';
INSERT INTO RESOURCE_ROLE (ROLE_ID, RESOURCE_ID) VALUES('9', 'PROFILE_PIC');

DELETE FROM LANGUAGE_MAPPING WHERE ID IN ('EN_PROFILE_PIC_DESC', 'DE_PROFILE_PIC_DESC',
  'ES_PROFILE_PIC_DESC', 'RU_PROFILE_PIC_DESC', 'JP_PROFILE_PIC_DESC');

INSERT INTO LANGUAGE_MAPPING(ID, LANGUAGE_ID, REFERENCE_TYPE, REFERENCE_ID, TEXT_VALUE) VALUES
  ('EN_PROFILE_PIC_DESC', '1', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture'),
  ('DE_PROFILE_PIC_DESC', '2', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture'),
  ('ES_PROFILE_PIC_DESC', '4', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture'),
  ('RU_PROFILE_PIC_DESC', '8', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture'),
  ('JP_PROFILE_PIC_DESC', '9', 'ResourceEntity.displayNameMap', 'PROFILE_PIC', 'Edit Your Profile Picture');

-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Edit Your Profile Picture' WHERE ID = 'EN_PROFILE_PIC_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Edit Your Profile Picture' WHERE ID = 'DE_PROFILE_PIC_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Edit Your Profile Picture' WHERE ID = 'ES_PROFILE_PIC_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Edit Your Profile Picture' WHERE ID = 'RU_PROFILE_PIC_DESC';
-- UPDATE LANGUAGE_MAPPING SET TEXT_VALUE = 'Edit Your Profile Picture' WHERE ID = 'JP_PROFILE_PIC_DESC';

ALTER TABLE GRP ALTER COLUMN CREATED_BY NVARCHAR(32) NULL;
ALTER TABLE GRP ADD DEFAULT NULL FOR CREATED_BY;

ALTER TABLE GRP ALTER COLUMN GRP_NAME NVARCHAR(255) NOT NULL ;
ALTER TABLE RES ALTER COLUMN NAME NVARCHAR(255) NOT NULL ;

UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED' WHERE ID='DEMetadataTypeEntity76';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED' WHERE ID='ESMetadataTypeEntity76';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED' WHERE ID='JPMetadataTypeEntity72';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED', TEXT_VALUE='TERMINATED' WHERE ID='MetadataTypeEntity72';
UPDATE LANGUAGE_MAPPING SET REFERENCE_ID='TERMINATED', TEXT_VALUE='Удален' WHERE ID='RUMetadataTypeEntity78';
UPDATE METADATA_TYPE SET TYPE_ID='TERMINATED', DESCRIPTION='TERMINATED'  WHERE TYPE_ID='TERMINATE';

UPDATE pa 
SET pa.REQUIRED='N'
FROM POLICY_ATTRIBUTE AS pa
JOIN POLICY_DEF_PARAM AS pd 
ON pa.DEF_PARAM_ID = pd.DEF_PARAM_ID
WHERE pa.POLICY_ID= '4000' AND (
  ((pd.OPERATION = 'RANGE' AND (pa.VALUE1 IS NULL OR pa.VALUE1 = '') AND (pa.VALUE2 IS NULL OR pa.VALUE2 = ''))
   OR (pd.OPERATION = 'String' AND (pa.VALUE1 IS NULL OR pa.VALUE1 = '') )
   OR (pd.OPERATION = 'select' AND (pa.VALUE1 IS NULL OR pa.VALUE1 = '') )
  ));
  
  
  DECLARE @u_id VARCHAR(32);
DECLARE @q_id VARCHAR(32);
DECLARE cur1 CURSOR FOR (SELECT IDENTITY_QUESTION_ID, USER_ID FROM USER_IDENTITY_ANS);
OPEN cur1;

FETCH NEXT FROM cur1 INTO @q_id, @u_id;
WHILE @@FETCH_STATUS = 0
BEGIN
	IF ((SELECT count(*) FROM USER_IDENTITY_ANS WHERE IDENTITY_QUESTION_ID=@q_id AND USER_ID=@u_id) > 1) 
	BEGIN
		DELETE FROM USER_IDENTITY_ANS WHERE IDENTITY_QUESTION_ID=@q_id AND USER_ID=@u_id;
	END;
END;
CLOSE cur1;


ALTER TABLE USER_IDENTITY_ANS ADD CONSTRAINT UNQ_ROW UNIQUE(IDENTITY_QUESTION_ID, USER_ID);
