USE activiti;

create table ACT_HI_PROCINST (
    ID_ NVARCHAR(64) not null,
    PROC_INST_ID_ NVARCHAR(64) not null,
    BUSINESS_KEY_ NVARCHAR(255),
    PROC_DEF_ID_ NVARCHAR(64) not null,
    START_TIME_ DATETIME DEFAULT GETDATE() not null,
    END_TIME_ DATETIME DEFAULT GETDATE(),
    DURATION_ NUMERIC(19,0),
    START_USER_ID_ NVARCHAR(255),
    START_ACT_ID_ NVARCHAR(255),
    END_ACT_ID_ NVARCHAR(255),
    SUPER_PROCESS_INSTANCE_ID_ NVARCHAR(64),
    DELETE_REASON_ NVARCHAR(2000),
    primary key (ID_),
    unique (PROC_INST_ID_)
);

create table ACT_HI_ACTINST (
    ID_ NVARCHAR(64) not null,
    PROC_DEF_ID_ NVARCHAR(64) not null,
    PROC_INST_ID_ NVARCHAR(64) not null,
    EXECUTION_ID_ NVARCHAR(64) not null,
    ACT_ID_ NVARCHAR(255) not null,
    ACT_NAME_ NVARCHAR(255),
    ACT_TYPE_ NVARCHAR(255) not null,
    ASSIGNEE_ NVARCHAR(64),
    START_TIME_ DATETIME DEFAULT GETDATE() not null,
    END_TIME_ DATETIME DEFAULT GETDATE(),
    DURATION_ NUMERIC(19,0),
    primary key (ID_)
);

create table ACT_HI_TASKINST (
    ID_ NVARCHAR(64) not null,
    PROC_DEF_ID_ NVARCHAR(64),
    TASK_DEF_KEY_ NVARCHAR(255),
    PROC_INST_ID_ NVARCHAR(64),
    EXECUTION_ID_ NVARCHAR(64),
    PARENT_TASK_ID_ NVARCHAR(64),
    NAME_ NVARCHAR(255),
    DESCRIPTION_ NVARCHAR(2000),
    OWNER_ NVARCHAR(64),
    ASSIGNEE_ NVARCHAR(64),
    START_TIME_ DATETIME DEFAULT GETDATE() not null,
    END_TIME_ DATETIME DEFAULT GETDATE(),
    DURATION_ NUMERIC(19,0),
    DELETE_REASON_ NVARCHAR(2000),
    PRIORITY_ INTEGER,
    DUE_DATE_ DATETIME DEFAULT GETDATE(),
    primary key (ID_)
);

create table ACT_HI_DETAIL (
    ID_ NVARCHAR(64) not null,
    TYPE_ NVARCHAR(255) not null,
    PROC_INST_ID_ NVARCHAR(64) not null,
    EXECUTION_ID_ NVARCHAR(64) not null,
    TASK_ID_ NVARCHAR(64),
    ACT_INST_ID_ NVARCHAR(64),
    NAME_ NVARCHAR(255) not null,
    VAR_TYPE_ NVARCHAR(64),
    REV_ INTEGER,
    TIME_ DATETIME DEFAULT GETDATE() not null,
    BYTEARRAY_ID_ NVARCHAR(64),
    DOUBLE_ SMALLMONEY,
    LONG_ NUMERIC(19,0),
    TEXT_ NVARCHAR(2000),
    TEXT2_ NVARCHAR(2000),
    primary key (ID_)
);

create table ACT_HI_COMMENT (
    ID_ NVARCHAR(64) not null,
    TYPE_ NVARCHAR(255),
    TIME_ DATETIME DEFAULT GETDATE() not null,
    USER_ID_ NVARCHAR(255),
    TASK_ID_ NVARCHAR(64),
    PROC_INST_ID_ NVARCHAR(64),
    ACTION_ NVARCHAR(255),
    MESSAGE_ NVARCHAR(2000),
    FULL_MSG_ VARBINARY(MAX),
    primary key (ID_)
);

create table ACT_HI_ATTACHMENT (
    ID_ NVARCHAR(64) not null,
    REV_ INTEGER,
    USER_ID_ NVARCHAR(255),
    NAME_ NVARCHAR(255),
    DESCRIPTION_ NVARCHAR(2000),
    TYPE_ NVARCHAR(255),
    TASK_ID_ NVARCHAR(64),
    PROC_INST_ID_ NVARCHAR(64),
    URL_ NVARCHAR(2000),
    CONTENT_ID_ NVARCHAR(64),
    primary key (ID_)
);

create index ACT_IDX_HI_PRO_INST_END on ACT_HI_PROCINST(END_TIME_);
create index ACT_IDX_HI_PRO_I_BUSKEY on ACT_HI_PROCINST(BUSINESS_KEY_);
create index ACT_IDX_HI_ACT_INST_START on ACT_HI_ACTINST(START_TIME_);
create index ACT_IDX_HI_ACT_INST_END on ACT_HI_ACTINST(END_TIME_);
create index ACT_IDX_HI_DETAIL_PROC_INST on ACT_HI_DETAIL(PROC_INST_ID_);
create index ACT_IDX_HI_DETAIL_ACT_INST on ACT_HI_DETAIL(ACT_INST_ID_);
create index ACT_IDX_HI_DETAIL_TIME on ACT_HI_DETAIL(TIME_);
create index ACT_IDX_HI_DETAIL_NAME on ACT_HI_DETAIL(NAME_);
create index ACT_IDX_HI_DETAIL_TASK_ID on ACT_HI_DETAIL(TASK_ID_);

-- see http://stackoverflow.com/questions/675398/how-can-i-constrain-multiple-columns-to-prevent-duplicates-but-ignore-null-value
create unique index ACT_UNIQ_HI_BUS_KEY on ACT_HI_PROCINST (PROC_DEF_ID_, BUSINESS_KEY_)
where PROC_DEF_ID_ is not null and BUSINESS_KEY_ is not null;
