use openiam;

UPDATE POLICY_ATTRIBUTE SET VALUE1='false' WHERE (VALUE1='0' AND NAME IN('REPEAT_SAME_WORD_PASSPHRASE', 'CHNG_PSWD_ON_RESET', 'RESET_BY_USER'));

UPDATE POLICY_ATTRIBUTE SET VALUE1='true' WHERE (VALUE1='1' AND NAME IN('REPEAT_SAME_WORD_PASSPHRASE', 'CHNG_PSWD_ON_RESET', 'RESET_BY_USER'));