use openiam;

IF NOT EXISTS (SELECT * FROM RES WHERE RESOURCE_ID = 'RESOURCE_CERT_REPORT_106') 
BEGIN
	INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, MIN_AUTH_LEVEL, IS_PUBLIC,
	  		ADMIN_RESOURCE_ID, RISK, TYPE_ID, COORELATED_NAME) VALUES
		('RESOURCE_CERT_REPORT_106', 'REPORT', NULL, 'RESOURCE_CERT_REPORT_106', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'RESOURCE_CERT_REPORT');
END;

IF NOT EXISTS (SELECT * FROM REPORT_INFO WHERE REPORT_INFO_ID = '106') 
BEGIN
	INSERT INTO REPORT_INFO (REPORT_INFO_ID, REPORT_NAME, DATASOURCE_FILE_PATH, REPORT_FILE_PATH, BUILT_IN, RESOURCE_ID) VALUES
		('106', 'RESOURCE_CERT_REPORT', 'ResourceCertReport.groovy', 'ResourceCertReport.rptdesign', 'Y', 'RESOURCE_CERT_REPORT_106');
END;

IF NOT EXISTS (SELECT * FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID IN ('1061','1062','1063','1064')) 
BEGIN
	INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
			IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
		('1061', '106', 'OWNER_ID', NULL, '1', 'USER', 'N', 'N', 'Owner', 1, NULL),
		('1062', '106', 'RES_ID', NULL, '1', 'RESOURCE', 'N', 'N', 'Admin Resource', 2, '{"resourceTypeId":"ADMIN_RESOURCE", "userId":"${OWNER_ID}"}'),
		('1063', '106', 'PERIOD_START', NULL, '2', NULL, 'N', 'Y', 'Period Start', 3, NULL),
		('1064', '106', 'PERIOD_END', NULL, '2', NULL, 'N', 'N', 'Period End', 4, NULL);
END;
