use openiam;

INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
		IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS)
VALUES ('1025', '102', 'ORG_ID', NULL, '1', 'ORGANIZATION', 'N', 'N', 'Organization', '5', NULL);
