use openiam;

IF NOT EXISTS (SELECT * FROM RES WHERE RESOURCE_ID = 'PASSWORD_CHANGES_REPORT_110') 
BEGIN
	INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, MIN_AUTH_LEVEL, IS_PUBLIC,
	  		ADMIN_RESOURCE_ID, RISK, TYPE_ID, COORELATED_NAME) VALUES
		('PASSWORD_CHANGES_REPORT_110', 'REPORT', NULL, 'PASSWORD_CHANGES_REPORT_110', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'PASSWORD_CHANGES_REPORT');
END;

IF NOT EXISTS (SELECT * FROM REPORT_INFO WHERE REPORT_INFO_ID = '110') 
BEGIN
	INSERT INTO REPORT_INFO (REPORT_INFO_ID, REPORT_NAME, DATASOURCE_FILE_PATH, REPORT_FILE_PATH, BUILT_IN, RESOURCE_ID) VALUES
		('110', 'PASSWORD_CHANGES_REPORT', 'PasswordChangesReport.groovy', 'PasswordChangesReport.rptdesign', 'Y', 'PASSWORD_CHANGES_REPORT_110');
END;

IF NOT EXISTS (SELECT * FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID IN ('1101','1102','1103')) 
BEGIN
	INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
			IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
		('1101', '110', 'ORG_ID', NULL, '1', 'ORGANIZATION', 'N', 'N', 'Organization', 1, NULL),
		('1102', '110', 'PERIOD_START', NULL, '2', NULL, 'N', 'Y', 'Period Start', 2, NULL),
		('1103', '110', 'PERIOD_END', NULL, '2', NULL, 'N', 'N', 'Period End', 3, NULL);
END;

