use openiam;

DELETE FROM POLICY_ATTRIBUTE  WHERE DEF_PARAM_ID IN ('183','184');
DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID  IN ('183','184');

INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID, POLICY_DEF_ID, NAME, DESCRIPTION, OPERATION, VALUE1, VALUE2, REPEATS, PARAM_GROUP, HANDLER_LANGUAGE, POLICY_PARAM_HANDLER) VALUES ('184', '100', 'INITIAL_PASSWORD', 'Initial Password configuration', 'select', 'STATIC', 'STATIC,RANDOM', 0, 'PSWD_COMPOSITION', null, null);
INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, VALUE1, VALUE2, RULE_TEXT, REQUIRED) VALUES ('4201', '184', '4000', 'STATIC', 'STATIC,RANDOM', null, 'Y');

