use openiam;


IF NOT EXISTS (SELECT * FROM REPORT_PARAMETER_METATYPE WHERE PARAM_METATYPE_ID = 'RISK') 
BEGIN
	INSERT INTO REPORT_PARAMETER_METATYPE (PARAM_METATYPE_ID, PARAM_METATYPE_NAME, IS_MULTIPLE) VALUES ('RISK', 'Risk', 'N');
END;

IF NOT EXISTS (SELECT * FROM RES WHERE RESOURCE_ID = 'USER_ACCESS_REPORT_109') 
BEGIN
	INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, MIN_AUTH_LEVEL, IS_PUBLIC,
	  		ADMIN_RESOURCE_ID, RISK, TYPE_ID, COORELATED_NAME) VALUES
		('USER_ACCESS_REPORT_109', 'REPORT', NULL, 'USER_ACCESS_REPORT_109', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, 'USER_ACCESS_REPORT');
END;

IF NOT EXISTS (SELECT * FROM REPORT_INFO WHERE REPORT_INFO_ID = '109') 
BEGIN
	INSERT INTO REPORT_INFO (REPORT_INFO_ID, REPORT_NAME, DATASOURCE_FILE_PATH, REPORT_FILE_PATH, BUILT_IN, RESOURCE_ID) VALUES
		('109', 'USER_ACCESS_REPORT', 'UserAccessReport.groovy', 'UserAccessReport.rptdesign', 'Y', 'USER_ACCESS_REPORT_109');
END;

IF NOT EXISTS (SELECT * FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID IN ('1091','1092','1093','1094','1095')) 
BEGIN
	INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
			IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) VALUES
		('1091', '109', 'ORG_ID', NULL, '1', 'ORGANIZATION', 'N', 'N', 'Organization', 1, NULL),
		('1092', '109', 'ROLE_ID', NULL, '1', 'ROLE', 'N', 'N', 'Role', 2, NULL),
		('1093', '109', 'RISK', NULL, '1', 'RISK', 'N', 'N', 'Risk', 3, NULL),
		('1094', '109', 'MANAGED_SYS_ID', NULL, '1', 'MANAGED_SYSTEM', 'N', 'N', 'Managed System', 4, NULL),
		('1095', '109', 'USER_ID', NULL, '1', 'USER', 'N', 'N', 'User', 5, NULL);
END;

