use openiam;

ALTER TABLE RESOURCE_TYPE ADD URL NVARCHAR(512) NULL DEFAULT NULL;
ALTER TABLE RESOURCE_TYPE DROP COLUMN METADATA_TYPE_ID;

ALTER TABLE RES DROP FK_RESOURCE_RESOURCE_TYPE;
DROP INDEX FK_RESOURCE_RESOURCE_TYPE ON RES;

DECLARE @table NVARCHAR(512), @sql NVARCHAR(MAX);
SELECT @table = 'RESOURCE_TYPE';
SELECT @sql = 'ALTER TABLE ' + @table 
	+ ' DROP CONSTRAINT ' + name + ';'
	FROM sys.key_constraints
	WHERE [type] = 'PK'
	AND [parent_object_id] = OBJECT_ID(@table);
EXEC sp_executeSQL @sql;

ALTER TABLE RES ALTER COLUMN RESOURCE_TYPE_ID NVARCHAR(32) NOT NULL;
	
ALTER TABLE RESOURCE_TYPE ALTER COLUMN RESOURCE_TYPE_ID NVARCHAR(32) NOT NULL;
ALTER TABLE RESOURCE_TYPE ADD PRIMARY KEY (RESOURCE_TYPE_ID);

ALTER TABLE RES ADD CONSTRAINT FK_RESOURCE_RESOURCE_TYPE FOREIGN KEY (RESOURCE_TYPE_ID) REFERENCES RESOURCE_TYPE (RESOURCE_TYPE_ID);
CREATE INDEX FK_RESOURCE_RESOURCE_TYPE ON RES(RESOURCE_TYPE_ID);

