use openiam;

ALTER TABLE RES DROP FK_RESOURCE_RESOURCE_TYPE;
DROP INDEX FK_RESOURCE_RESOURCE_TYPE ON RES;
ALTER TABLE RES ALTER COLUMN RESOURCE_TYPE_ID NVARCHAR(32) NOT NULL; 
ALTER TABLE RES ADD CONSTRAINT FK_RESOURCE_RESOURCE_TYPE FOREIGN KEY (RESOURCE_TYPE_ID ) REFERENCES RESOURCE_TYPE (RESOURCE_TYPE_ID);

