use openiam;


IF EXISTS (SELECT * FROM information_schema.columns WHERE table_catalog='openiam' AND table_name = 'UI_FIELD_TEMPLATE_XREF' AND column_name = 'XREF_ID')
BEGIN
	ALTER TABLE UI_FIELD_TEMPLATE_XREF DROP COLUMN XREF_ID;
END;


ALTER TABLE UI_FIELD_TEMPLATE_XREF ADD XREF_ID NVARCHAR(32) NULL;
GO

DECLARE @xrefId INT = 1;
DECLARE @fieldId NVARCHAR(32);
DECLARE @templateId NVARCHAR(32);
DECLARE cur1 CURSOR FOR (SELECT UI_FIELD_ID, TEMPLATE_ID FROM UI_FIELD_TEMPLATE_XREF);
OPEN cur1;

FETCH NEXT FROM cur1 INTO @fieldId, @templateId;
WHILE @@FETCH_STATUS = 0
BEGIN
	IF (@fieldId IS NOT NULL) 
	BEGIN
		IF (@templateId IS NOT NULL) 
		BEGIN
			IF ((SELECT count(*) FROM UI_FIELD_TEMPLATE_XREF WHERE UI_FIELD_ID=@fieldId AND TEMPLATE_ID=@templateId AND XREF_ID IS NULL)=1) 
			BEGIN
				UPDATE UI_FIELD_TEMPLATE_XREF SET XREF_ID=@xrefId WHERE UI_FIELD_ID=@fieldId AND TEMPLATE_ID=@templateId;
				SET @xrefId = @xrefId + 1;
			END;
		END;
	END;
END
CLOSE cur1;

ALTER TABLE UI_FIELD_TEMPLATE_XREF ALTER COLUMN XREF_ID NVARCHAR(32) NOT NULL;
GO
ALTER TABLE UI_FIELD_TEMPLATE_XREF ADD PRIMARY KEY(XREF_ID);