use openiam;

--  MODIFY USER ATTRIBUTES --

IF EXISTS (SELECT * FROM information_schema.columns WHERE table_catalog='openiam' AND table_name = 'USER_ATTRIBUTES' AND column_name = 'IS_MULTIVALUED') 
BEGIN
	ALTER TABLE USER_ATTRIBUTES DROP COLUMN IS_MULTIVALUED;
END;


ALTER TABLE USER_ATTRIBUTES ADD IS_MULTIVALUED char(1) NOT NULL DEFAULT 'N';

IF OBJECT_ID('USER_ATTRIBUTE_VALUES', 'U') IS NOT NULL 
	DROP TABLE USER_ATTRIBUTE_VALUES;

CREATE TABLE USER_ATTRIBUTE_VALUES (
  USER_ATTRIBUTE_ID nvarchar(32) NOT NULL,
  VALUE nvarchar(255),
  CONSTRAINT USER_ATTRIBUTE_VALUES_FK FOREIGN KEY (USER_ATTRIBUTE_ID) REFERENCES USER_ATTRIBUTES(ID)
);

--  MODIFY GROUP ATTRIBUTES --

IF EXISTS (SELECT * FROM information_schema.columns WHERE table_catalog='openiam' AND table_name = 'GRP_ATTRIBUTES' AND column_name = 'IS_MULTIVALUED') 
BEGIN
	ALTER TABLE GRP_ATTRIBUTES DROP COLUMN IS_MULTIVALUED;
END;


ALTER TABLE GRP_ATTRIBUTES ADD IS_MULTIVALUED char(1) NOT NULL DEFAULT 'N';

IF OBJECT_ID('GROUP_ATTRIBUTE_VALUES', 'U') IS NOT NULL
	DROP TABLE GROUP_ATTRIBUTE_VALUES;

CREATE TABLE GROUP_ATTRIBUTE_VALUES (
  GROUP_ATTRIBUTE_ID nvarchar(32) NOT NULL,
  VALUE nvarchar(255),
  CONSTRAINT GROUP_ATTRIBUTE_VALUES_FK FOREIGN KEY (GROUP_ATTRIBUTE_ID) REFERENCES GRP_ATTRIBUTES(ID)
);

--  MODIFY ROLE ATTRIBUTES --


IF EXISTS (SELECT * FROM information_schema.columns WHERE table_catalog='openiam' AND table_name = 'ROLE_ATTRIBUTE' AND column_name = 'IS_MULTIVALUED') 
BEGIN
	ALTER TABLE ROLE_ATTRIBUTE DROP COLUMN IS_MULTIVALUED;
END;


ALTER TABLE ROLE_ATTRIBUTE ADD IS_MULTIVALUED char(1) NOT NULL DEFAULT 'N';

IF OBJECT_ID('ROLE_ATTRIBUTE_VALUES', 'U') IS NOT NULL
	DROP TABLE ROLE_ATTRIBUTE_VALUES;

CREATE TABLE ROLE_ATTRIBUTE_VALUES (
  ROLE_ATTRIBUTE_ID nvarchar(32) NOT NULL,
  VALUE nvarchar(255),
  CONSTRAINT ROLE_ATTRIBUTE_VALUES_FK FOREIGN KEY (ROLE_ATTRIBUTE_ID) REFERENCES ROLE_ATTRIBUTE(ROLE_ATTR_ID)
);

--  MODIFY ORGANIZATION ATTRIBUTES --

IF EXISTS (SELECT * FROM information_schema.columns WHERE table_catalog='openiam' AND table_name = 'COMPANY_ATTRIBUTE' AND column_name = 'IS_MULTIVALUED') 
BEGIN
	ALTER TABLE COMPANY_ATTRIBUTE DROP COLUMN IS_MULTIVALUED;
END;


ALTER TABLE COMPANY_ATTRIBUTE ADD IS_MULTIVALUED char(1) NOT NULL DEFAULT 'N';

IF OBJECT_ID('COMPANY_ATTRIBUTE_VALUES', 'U') IS NOT NULL
	DROP TABLE COMPANY_ATTRIBUTE_VALUES;

CREATE TABLE COMPANY_ATTRIBUTE_VALUES (
  COMPANY_ATTRIBUTE_ID nvarchar(32) NOT NULL,
  VALUE nvarchar(255),
  CONSTRAINT COMPANY_ATTRIBUTE_VALUES_FK FOREIGN KEY (COMPANY_ATTRIBUTE_ID) REFERENCES COMPANY_ATTRIBUTE(COMPANY_ATTR_ID)
);
