use openiam;
-- CREATE IDENTITY TABLE 

CREATE TABLE "IDENTITY" (
    IDENTITY_ID NVARCHAR(32) NOT NULL,
    MANAGED_SYS_ID NVARCHAR(32) NOT NULL,
    "IDENTITY" NVARCHAR(320) NOT NULL,
    REFERRED_OBJECT_ID NVARCHAR(32) NOT NULL,
    IDENTITY_TYPE NVARCHAR(20) NULL, -- GROUP, ROLE, TYPE ...
    CREATE_DATE DATETIME NULL,
    CREATED_BY NVARCHAR(32) NULL,
    STATUS nvarchar(20) NULL
);