use openiam;

ALTER TABLE RES DROP COLUMN BRANCH_ID;
ALTER TABLE RES DROP FK_RESOURCE_CATEGORY;
DROP INDEX FK_RESOURCE_CATEGORY ON RES;
ALTER TABLE RES DROP COLUMN CATEGORY_ID;
ALTER TABLE RES DROP COLUMN RES_OWNER_USER_ID;
ALTER TABLE RES DROP COLUMN RES_OWNER_GROUP_ID;

ALTER TABLE RES ADD ADMIN_RESOURCE_ID NVARCHAR(32) NULL;
ALTER TABLE RES ADD CONSTRAINT RES_ADMIN_RES_FK FOREIGN KEY (ADMIN_RESOURCE_ID) REFERENCES RES(RESOURCE_ID);

ALTER TABLE ROLE ADD ADMIN_RESOURCE_ID NVARCHAR(32) NULL;
ALTER TABLE ROLE ADD CONSTRAINT ROLE_ADMIN_RES_FK FOREIGN KEY (ADMIN_RESOURCE_ID) REFERENCES RES(RESOURCE_ID);


ALTER TABLE GRP ADD ADMIN_RESOURCE_ID NVARCHAR(32) NULL;
ALTER TABLE GRP ADD CONSTRAINT GRP_ADMIN_RES_FK FOREIGN KEY (ADMIN_RESOURCE_ID) REFERENCES RES(RESOURCE_ID);

INSERT INTO METADATA_TYPE (TYPE_ID, DESCRIPTION, ACTIVE, SYNC_MANAGED_SYS) VALUES('ADMIN_RESOURCE', 'Admin Resource', 'Y', 'Y');
INSERT INTO RESOURCE_TYPE (RESOURCE_TYPE_ID, DESCRIPTION, METADATA_TYPE_ID) VALUES('ADMIN_RESOURCE', 'Admin Resource', 'ADMIN_RESOURCE');

ALTER TABLE RESOURCE_TYPE ADD SUPPORTS_HIERARCHY CHAR(1) NULL DEFAULT 'Y';
GO
UPDATE RESOURCE_TYPE SET SUPPORTS_HIERARCHY='Y';
UPDATE RESOURCE_TYPE SET SUPPORTS_HIERARCHY='N' WHERE RESOURCE_TYPE_ID='ADMIN_RESOURCE';

Declare @v_constraintname NVARCHAR(max)
set @v_constraintname ='ALTER TABLE RESOURCE_TYPE DROP CONSTRAINT '
set @v_constraintname = @v_constraintname + (select c_obj.name as CONSTRAINT_NAME
from sysobjects c_obj
join syscomments com on c_obj.id = com.id
join sysobjects t_obj on c_obj.parent_obj = t_obj.id 
join sysconstraints con on c_obj.id = con.constid
join syscolumns col on t_obj.id = col.id
and con.colid = col.colid
where
c_obj.uid = user_id()
and c_obj.xtype = 'D'
and t_obj.name='RESOURCE_TYPE' and col.name='SUPPORTS_HIERARCHY')
exec(@v_constraintname)

ALTER TABLE RESOURCE_TYPE ALTER COLUMN SUPPORTS_HIERARCHY CHAR(1) NOT NULL 
ALTER TABLE RESOURCE_TYPE ADD DEFAULT 'Y' FOR SUPPORTS_HIERARCHY;

