use openiam;

CREATE INDEX CREATED_DATETIME ON OPENIAM_LOG(CREATED_DATETIME);
CREATE INDEX LOG_ACTION ON OPENIAM_LOG(LOG_ACTION);
CREATE INDEX FK_LOG_ATTRIBUTE_LOG ON OPENIAM_LOG_ATTRIBUTE(OPENIAM_LOG_ID);
CREATE INDEX FK_LOG_TARGET_LOG ON OPENIAM_LOG_TARGET(OPENIAM_LOG_ID);
CREATE INDEX OPENIAM_LOG_ID ON OPENIAM_LOG_LOG_MEMBERSHIP(OPENIAM_LOG_ID);
CREATE INDEX OPENIAM_MEMBER_LOG_ID ON OPENIAM_LOG_LOG_MEMBERSHIP(OPENIAM_MEMBER_LOG_ID);


