use openiam;

EXEC sp_RENAME 'RESOURCE_PROP.PROP_VALUE', 'VALUE', 'COLUMN'

ALTER TABLE RESOURCE_PROP ALTER COLUMN VALUE VARCHAR(4096);

ALTER TABLE RESOURCE_PROP ALTER COLUMN NAME NVARCHAR(100);

ALTER TABLE RESOURCE_PROP ADD IS_MULTIVALUED char(1) NOT NULL DEFAULT 'N';