use openiam;

ALTER TABLE RESOURCE_PROP ALTER COLUMN METADATA_ID NVARCHAR(32);

ALTER TABLE ROLE_ATTRIBUTE ALTER COLUMN METADATA_ID NVARCHAR(32);

ALTER TABLE GRP_ATTRIBUTES ALTER COLUMN METADATA_ID NVARCHAR(32);