use openiam;

EXEC sp_RENAME 'RESOURCE_PROP.VALUE', '_VALUE', 'COLUMN'
ALTER TABLE RESOURCE_PROP ALTER COLUMN _VALUE VARCHAR(4096);
EXEC sp_RENAME 'GRP_ATTRIBUTES.VALUE', '_VALUE', 'COLUMN'
ALTER TABLE GRP_ATTRIBUTES ALTER COLUMN _VALUE VARCHAR(4096);
EXEC sp_RENAME 'ROLE_ATTRIBUTE.VALUE', '_VALUE', 'COLUMN'
ALTER TABLE ROLE_ATTRIBUTE ALTER COLUMN _VALUE VARCHAR(4096);
EXEC sp_RENAME 'COMPANY_ATTRIBUTE.VALUE', '_VALUE', 'COLUMN'
ALTER TABLE COMPANY_ATTRIBUTE ALTER COLUMN _VALUE VARCHAR(4096);