use openiam;

UPDATE USERS SET JOB_CODE=null WHERE JOB_CODE not in (SELECT TYPE_ID from METADATA_TYPE WHERE GROUPING='JOB_CODE');
UPDATE USERS SET EMPLOYEE_TYPE=null WHERE EMPLOYEE_TYPE not in (SELECT TYPE_ID from METADATA_TYPE WHERE GROUPING='USER_TYPE');

IF NOT EXISTS (SELECT 1 FROM information_schema.TABLE_CONSTRAINTS tc WHERE CONSTRAINT_TYPE = 'FOREIGN KEY' AND TABLE_CATALOG = 'openiam' AND TABLE_NAME = 'USERS' AND CONSTRAINT_NAME='FK_JOB_CODE_METADATA_TYPE')
BEGIN
	ALTER TABLE USERS ALTER COLUMN JOB_CODE NVARCHAR(32) NULL;
	ALTER TABLE USERS ADD DEFAULT 'NULL' FOR JOB_CODE;
	ALTER TABLE USERS ADD CONSTRAINT FK_JOB_CODE_METADATA_TYPE FOREIGN KEY (JOB_CODE) REFERENCES METADATA_TYPE (TYPE_ID);
END;

IF NOT EXISTS (SELECT 1 FROM information_schema.TABLE_CONSTRAINTS tc WHERE CONSTRAINT_TYPE = 'FOREIGN KEY' AND TABLE_CATALOG = 'openiam' AND TABLE_NAME = 'USERS' AND CONSTRAINT_NAME='FK_EMPLOYEE_TYPE_METADATA_TYPE')
BEGIN
	ALTER TABLE USERS ALTER COLUMN EMPLOYEE_TYPE NVARCHAR(32) NULL;
	ALTER TABLE USERS ADD DEFAULT 'NULL' FOR EMPLOYEE_TYPE;
	ALTER TABLE USERS ADD CONSTRAINT FK_EMPLOYEE_TYPE_METADATA_TYPE FOREIGN KEY (EMPLOYEE_TYPE) REFERENCES METADATA_TYPE (TYPE_ID);
END;


