use openiam;

ALTER TABLE REQUEST_ATTRIBUTE DROP COLUMN ATTR_GROUP;

ALTER TABLE ROLE_ATTRIBUTE DROP COLUMN ATTR_GROUP;

ALTER TABLE LOGIN_ATTRIBUTE DROP COLUMN ATTR_GROUP;

ALTER TABLE USER_ATTRIBUTES DROP COLUMN ATTR_GROUP;