use openiam;

ALTER TABLE GRP ALTER COLUMN GROUP_DESC VARCHAR(512);
--ALTER TABLE GRP ADD DEFAULT 'NULL' FOR GROUP_DESC;


ALTER TABLE EMAIL_ADDRESS DROP CONSTRAINT EMAIL_ADDRESS_TYPE_FK ;
ALTER TABLE EMAIL_ADDRESS ALTER COLUMN TYPE_ID NVARCHAR(32);
ALTER TABLE EMAIL_ADDRESS ADD DEFAULT 'NULL' FOR TYPE_ID;

ALTER TABLE EMAIL_ADDRESS ADD CONSTRAINT EMAIL_ADDRESS_TYPE_FK FOREIGN KEY (TYPE_ID) REFERENCES METADATA_TYPE (TYPE_ID);


ALTER TABLE ADDRESS DROP CONSTRAINT ADDRESS_TYPE_FK ;
ALTER TABLE ADDRESS ALTER COLUMN TYPE_ID NVARCHAR(32); 
ALTER TABLE ADDRESS ADD DEFAULT 'NULL' FOR TYPE_ID;
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_TYPE_FK FOREIGN KEY (TYPE_ID) REFERENCES METADATA_TYPE (TYPE_ID);


ALTER TABLE PHONE DROP CONSTRAINT PHONE_TYPE_FK ;
ALTER TABLE PHONE ALTER COLUMN TYPE_ID NVARCHAR(32); 
ALTER TABLE PHONE ADD DEFAULT 'NULL' FOR TYPE_ID;
ALTER TABLE PHONE ADD CONSTRAINT PHONE_TYPE_FK FOREIGN KEY (TYPE_ID) REFERENCES METADATA_TYPE (TYPE_ID);

