use openiam;

EXEC sp_RENAME 'RESOURCE_PROP._VALUE', 'ATTR_VALUE', 'COLUMN'
ALTER TABLE RESOURCE_PROP ALTER COLUMN ATTR_VALUE VARCHAR(4096);

EXEC sp_RENAME 'GRP_ATTRIBUTES._VALUE', 'ATTR_VALUE', 'COLUMN'
ALTER TABLE GRP_ATTRIBUTES ALTER COLUMN ATTR_VALUE VARCHAR(4096);

EXEC sp_RENAME 'ROLE_ATTRIBUTE._VALUE', 'ATTR_VALUE', 'COLUMN'
ALTER TABLE ROLE_ATTRIBUTE ALTER COLUMN ATTR_VALUE VARCHAR(4096);

EXEC sp_RENAME 'COMPANY_ATTRIBUTE._VALUE', 'ATTR_VALUE', 'COLUMN'
ALTER TABLE COMPANY_ATTRIBUTE ALTER COLUMN ATTR_VALUE VARCHAR(4096);
