use openiam;


IF NOT EXISTS (SELECT * FROM information_schema.columns WHERE table_catalog='openiam' AND table_name = 'LOGIN' AND column_name = 'PROV_STATUS') 
BEGIN
	ALTER TABLE LOGIN ADD PROV_STATUS NVARCHAR(20) NULL;
END;


UPDATE LOGIN SET STATUS = NULL WHERE STATUS NOT IN ('ACTIVE', 'INACTIVE');