use openiam;


IF EXISTS (select * from information_schema.KEY_COLUMN_USAGE where table_CATALOG = 'openiam' and table_name = 'SECURITY_DOMAIN') 
BEGIN
	delete from PWD_HISTORY where  LOGIN_ID in (select LOGIN_ID from LOGIN where SERVICE_ID<>'USR_SEC_DOMAIN');

	delete from LOGIN where SERVICE_ID<>'USR_SEC_DOMAIN';

	ALTER TABLE LOGIN DROP FK_LOGIN_SERVICE;
	DROP INDEX UNIQUE_LOGIN ON LOGIN;
	DROP INDEX FK_LOGIN_SERVICE ON LOGIN;

	ALTER TABLE LOGIN DROP COLUMN SERVICE_ID;
	CREATE UNIQUE INDEX UNIQUE_LOGIN ON LOGIN (LOGIN ASC, MANAGED_SYS_ID ASC);



	ALTER TABLE ROLE DROP FK_ROLE_SERVICE;
	DROP INDEX FK_ROLE_SERVICE ON ROLE;
	ALTER TABLE ROLE DROP COLUMN SERVICE_ID;


	ALTER TABLE MANAGED_SYS DROP COLUMN DOMAIN_ID;

	IF OBJECT_ID('SECURITY_DOMAIN', 'U') IS NOT NULL
		DROP TABLE SECURITY_DOMAIN;
END;


IF EXISTS(select * FROM sys.views where name = 'USER_PSWD_EXPIRED_YESTERDAY_VW')
	drop view USER_PSWD_EXPIRED_YESTERDAY_VW;

GO
CREATE VIEW USER_PSWD_EXPIRED_YESTERDAY_VW AS
  select
    l.LOGIN AS LOGIN,
    l.MANAGED_SYS_ID AS MANAGED_SYS_ID,
    l.USER_ID AS USER_ID,
    l.GRACE_PERIOD AS EXPIRATION_DATE,
    u.FIRST_NAME AS FIRST_NAME,
    u.LAST_NAME AS LAST_NAME,
    u.STATUS AS STATUS
  from LOGIN l
    JOIN USERS as u ON l.USER_ID = u.USER_ID
  where
    ((l.USER_ID = u.USER_ID)
     and (l.MANAGED_SYS_ID = 0)
     and (((l.GRACE_PERIOD is not null)
           and (cast(l.GRACE_PERIOD as date) = (GETDATE() - 1)))
          or ((l.PWD_EXP is not null)
              and (l.GRACE_PERIOD IS NULL)
              and (cast(l.PWD_EXP as date) = (GETDATE() - 1)))));