use openiam;


DELIMITER $$

DROP PROCEDURE IF EXISTS ADD_PRIMARY_LOCATION_LOCALIZATION$$

CREATE PROCEDURE ADD_PRIMARY_LOCATION_LOCALIZATION()
	BEGIN
		IF NOT EXISTS (SELECT * FROM LANGUAGE_MAPPING WHERE LANGUAGE_ID='1' AND REFERENCE_ID='PRIMARY_LOCATION' AND REFERENCE_TYPE='MetadataTypeEntity.displayNameMap') THEN
			INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('MetadataTypeEntity88','1','PRIMARY_LOCATION','MetadataTypeEntity.displayNameMap','Primary Location');
 		END IF;
		IF NOT EXISTS (SELECT * FROM LANGUAGE_MAPPING WHERE LANGUAGE_ID='2' AND REFERENCE_ID='PRIMARY_LOCATION' AND REFERENCE_TYPE='MetadataTypeEntity.displayNameMap') THEN
			INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('DEMetadataTypeEntity88','2','PRIMARY_LOCATION','MetadataTypeEntity.displayNameMap','Primary Location');
 		END IF;
		IF NOT EXISTS (SELECT * FROM LANGUAGE_MAPPING WHERE LANGUAGE_ID='4' AND REFERENCE_ID='PRIMARY_LOCATION' AND REFERENCE_TYPE='MetadataTypeEntity.displayNameMap') THEN
			 INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ESMetadataTypeEntity88','4','PRIMARY_LOCATION','MetadataTypeEntity.displayNameMap','Ubicación principal');
 		END IF;
		IF NOT EXISTS (SELECT * FROM LANGUAGE_MAPPING WHERE LANGUAGE_ID='8' AND REFERENCE_ID='PRIMARY_LOCATION' AND REFERENCE_TYPE='MetadataTypeEntity.displayNameMap') THEN
			INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('RUMetadataTypeEntity88','8','PRIMARY_LOCATION','MetadataTypeEntity.displayNameMap','Основное местоположение');
 		END IF;
		IF NOT EXISTS (SELECT * FROM LANGUAGE_MAPPING WHERE LANGUAGE_ID='9' AND REFERENCE_ID='PRIMARY_LOCATION' AND REFERENCE_TYPE='MetadataTypeEntity.displayNameMap') THEN
			INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('JPMetadataTypeEntity88','9','PRIMARY_LOCATION','MetadataTypeEntity.displayNameMap','プライマリロケーション');
 		END IF;
		IF NOT EXISTS (SELECT * FROM LANGUAGE_MAPPING WHERE LANGUAGE_ID='10' AND REFERENCE_ID='PRIMARY_LOCATION' AND REFERENCE_TYPE='MetadataTypeEntity.displayNameMap') THEN
			INSERT INTO LANGUAGE_MAPPING (ID,LANGUAGE_ID,REFERENCE_ID,REFERENCE_TYPE,TEXT_VALUE) VALUES ('ZHMetadataTypeEntity88','10','PRIMARY_LOCATION','MetadataTypeEntity.displayNameMap','主要位置');
 		END IF;
	END$$
DELIMITER ;

call ADD_PRIMARY_LOCATION_LOCALIZATION();
DROP PROCEDURE ADD_PRIMARY_LOCATION_LOCALIZATION;
