use openiam;

IF EXISTS (SELECT * FROM RES WHERE RESOURCE_ID = 'USER_ACCESS_REPORT_109') 
BEGIN
	IF NOT EXISTS (SELECT * FROM REPORT_CRITERIA_PARAMETER WHERE RCP_ID = '1097') 
	BEGIN
		INSERT INTO REPORT_CRITERIA_PARAMETER (RCP_ID, REPORT_INFO_ID, PARAM_NAME, PARAM_VALUE, RCPT_ID, PARAM_META_TYPE_ID, 
			IS_MULTIPLE, IS_REQUIRED, CAPTION, DISPLAY_ORDER, REQUEST_PARAMS) 
			VALUES ('1097', '109', 'RESOURCE_IDS', NULL, '1', 'RESOURCE', 'Y', 'N', 'Resource', 7, NULL);
	END;
END;

