use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN', 'AR_VIEW_ROLE_BTN');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_VIEW_ROOT', 'MENU_ITEM', 'Root menu for Access Review Tabs', 'AR_VIEW_ROOT', 'AR_VIEW_ROOT', null, 20, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_ROOT_PUB', 'AR_VIEW_ROOT', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_ROOT_DESC', 'AR_VIEW_ROOT', 'MENU_DISPLAY_NAME', 'Root menu for Access Review Tabs');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_VIEW_RES_BTN', 'MENU_ITEM', 'Resource View', 'AR_VIEW_RES_BTN', 'AR_VIEW_RES_BTN', '/selfservice/accessReview/getResourcesView.html', 21, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_RES_BTN_PUB', 'AR_VIEW_RES_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_RES_BTN_DESC', 'AR_VIEW_RES_BTN', 'MENU_DISPLAY_NAME', 'Resource View');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_VIEW_ROLE_BTN', 'MENU_ITEM', 'Role View', 'AR_VIEW_ROLE_BTN', 'AR_VIEW_ROLE_BTN', '/selfservice/accessReview/getRolesView.html', 22, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_ROLE_BTN_PUB', 'AR_VIEW_ROLE_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_VIEW_ROLE_BTN_DESC', 'AR_VIEW_ROLE_BTN', 'MENU_DISPLAY_NAME', 'Role View');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_VIEW_ROOT', 'AR_VIEW_RES_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_VIEW_ROOT', 'AR_VIEW_ROLE_BTN');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_VIEW_ROOT', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_VIEW_RES_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_VIEW_ROLE_BTN', '9');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_VIEW_ROOT','1','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_VIEW_ROOT','2','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_VIEW_ROOT','4','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_VIEW_ROOT','8','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_VIEW_ROOT','9','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_VIEW_ROOT','10','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_VIEW_ROOT','11','AR_VIEW_ROOT','ResourceEntity.displayNameMap','Root menu for Access Review Tabs');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_VIEW_RES_BTN','1','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_VIEW_RES_BTN','2','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_VIEW_RES_BTN','4','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_VIEW_RES_BTN','8','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_VIEW_RES_BTN','9','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_VIEW_RES_BTN','10','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_VIEW_RES_BTN','11','AR_VIEW_RES_BTN','ResourceEntity.displayNameMap','Resource');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_VIEW_ROLE_BTN','1','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_VIEW_ROLE_BTN','2','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_VIEW_ROLE_BTN','4','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_VIEW_ROLE_BTN','8','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_VIEW_ROLE_BTN','9','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_VIEW_ROLE_BTN','10','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_VIEW_ROLE_BTN','11','AR_VIEW_ROLE_BTN','ResourceEntity.displayNameMap','Role');


DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('AR_BTN_ROOT', 'AR_ADD_RES_BTN', 'AR_ADD_ROLE_BTN', 'AR_ADD_GRP_BTN','AR_RES_DEL_BTN');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_BTN_ROOT', 'MENU_ITEM', 'Root buttons for Access Review', 'AR_BTN_ROOT', 'AR_BTN_ROOT', null, 20, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_BTN_ROOT_PUB', 'AR_BTN_ROOT', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_BTN_ROOT_DESC', 'AR_BTN_ROOT', 'MENU_DISPLAY_NAME', 'Root buttons for Access Review');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_ADD_RES_BTN', 'MENU_ITEM', 'Resource View', 'AR_ADD_RES_BTN', 'AR_ADD_RES_BTN', '/selfservice/addUserToResource.html', 21, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_RES_BTN_PUB', 'AR_ADD_RES_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_RES_BTN_DESC', 'AR_ADD_RES_BTN', 'MENU_DISPLAY_NAME', 'Add Resource');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_ADD_ROLE_BTN', 'MENU_ITEM', 'Add Role', 'AR_ADD_ROLE_BTN', 'AR_ADD_ROLE_BTN', '/selfservice/addUserToRole.html', 22, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_ROLE_BTN_PUB', 'AR_ADD_ROLE_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_ROLE_BTN_DESC', 'AR_ADD_ROLE_BTN', 'MENU_DISPLAY_NAME', 'Add Role');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_ADD_GRP_BTN', 'MENU_ITEM', 'Add Group', 'AR_ADD_GRP_BTN', 'AR_ADD_GRP_BTN', '/selfservice/addUserToGroup.html', 23, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_GRP_BTN_PUB', 'AR_ADD_GRP_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ADD_GRP_BTN_DESC', 'AR_ADD_GRP_BTN', 'MENU_DISPLAY_NAME', 'Add Group');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_RES_DEL_BTN', 'MENU_ITEM', 'Delete Resource', 'AR_RES_DEL_BTN', 'AR_RES_DEL_BTN', '/selfservice/removeUserFromResource.html', 24, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_RES_DEL_BTN_PUB', 'AR_RES_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_RES_DEL_BTN_DESC', 'AR_RES_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete Resource');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_ROLE_DEL_BTN', 'MENU_ITEM', 'Delete Role', 'AR_ROLE_DEL_BTN', 'AR_ROLE_DEL_BTN', '/selfservice/removeUserFromRole.html', 25, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ROLE_DEL_BTN_PUB', 'AR_ROLE_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_ROLE_DEL_BTN_DESC', 'AR_ROLE_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete Role');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('AR_GRP_DEL_BTN', 'MENU_ITEM', 'Delete Group', 'AR_GRP_DEL_BTN', 'AR_GRP_DEL_BTN', '/selfservice/removeUserFromGroup.html', 26, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_GRP_DEL_BTN_PUB', 'AR_GRP_DEL_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('AR_GRP_DEL_BTN_DESC', 'AR_GRP_DEL_BTN', 'MENU_DISPLAY_NAME', 'Delete Group');


INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_ADD_RES_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_ADD_ROLE_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_ADD_GRP_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_RES_DEL_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_ROLE_DEL_BTN');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('AR_BTN_ROOT', 'AR_GRP_DEL_BTN');

INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_BTN_ROOT', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_ADD_RES_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_ADD_ROLE_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_ADD_GRP_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_RES_DEL_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_ROLE_DEL_BTN', '9');
INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('AR_GRP_DEL_BTN', '9');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_BTN_ROOT','1','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_BTN_ROOT','2','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_BTN_ROOT','4','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_BTN_ROOT','8','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_BTN_ROOT','9','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_BTN_ROOT','10','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_BTN_ROOT','11','AR_BTN_ROOT','ResourceEntity.displayNameMap','Root buttons for Access Review');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_ADD_RES_BTN','1','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_ADD_RES_BTN','2','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_ADD_RES_BTN','4','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_ADD_RES_BTN','8','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_ADD_RES_BTN','9','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_ADD_RES_BTN','10','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_ADD_RES_BTN','11','AR_ADD_RES_BTN','ResourceEntity.displayNameMap','Add Resource');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_ADD_ROLE_BTN','1','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_ADD_ROLE_BTN','2','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_ADD_ROLE_BTN','4','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_ADD_ROLE_BTN','8','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_ADD_ROLE_BTN','9','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_ADD_ROLE_BTN','10','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_ADD_ROLE_BTN','11','AR_ADD_ROLE_BTN','ResourceEntity.displayNameMap','Add Role');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_ADD_GRP_BTN','1','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_ADD_GRP_BTN','2','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_ADD_GRP_BTN','4','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_ADD_GRP_BTN','8','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_ADD_GRP_BTN','9','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_ADD_GRP_BTN','10','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_ADD_GRP_BTN','11','AR_ADD_GRP_BTN','ResourceEntity.displayNameMap','Add Group');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_RES_DEL_BTN','1','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_RES_DEL_BTN','2','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_RES_DEL_BTN','4','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_RES_DEL_BTN','8','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_RES_DEL_BTN','9','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_RES_DEL_BTN','10','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_RES_DEL_BTN','11','AR_RES_DEL_BTN','ResourceEntity.displayNameMap','Delete Resource');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_ROLE_DEL_BTN','1','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_ROLE_DEL_BTN','2','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_ROLE_DEL_BTN','4','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_ROLE_DEL_BTN','8','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_ROLE_DEL_BTN','9','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_ROLE_DEL_BTN','10','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_ROLE_DEL_BTN','11','AR_ROLE_DEL_BTN','ResourceEntity.displayNameMap','Delete Role');


INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_AR_GRP_DEL_BTN','1','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_AR_GRP_DEL_BTN','2','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_AR_GRP_DEL_BTN','4','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_AR_GRP_DEL_BTN','8','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_AR_GRP_DEL_BTN','9','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_AR_GRP_DEL_BTN','10','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_AR_GRP_DEL_BTN','11','AR_GRP_DEL_BTN','ResourceEntity.displayNameMap','Delete Group');


