use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_TYPE='ResourceEntity.displayNameMap' and REFERENCE_ID IN ('SS_SAVE_USER_BTN');
DELETE FROM RES WHERE RESOURCE_ID IN ('SS_SAVE_USER_BTN');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, COORELATED_NAME, URL, DISPLAY_ORDER, IS_PUBLIC) VALUES ('SS_SAVE_USER_BTN', 'MENU_ITEM', 'Save User Button', 'SS_SAVE_USER_BTN', 'SS_SAVE_USER_BTN', null, 20, 'N');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_SAVE_USER_BTN_PUB', 'SS_SAVE_USER_BTN', 'MENU_IS_PUBLIC', 'false');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, ATTR_VALUE) VALUES ('SS_SAVE_USER_BTN_DESC', 'SS_SAVE_USER_BTN', 'MENU_DISPLAY_NAME', 'Save User Button');



INSERT INTO RESOURCE_ROLE (RESOURCE_ID, ROLE_ID) VALUES ('SS_SAVE_USER_BTN', '9');

INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('EN_SS_SAVE_USER_BTN','1','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('DE_SS_SAVE_USER_BTN','2','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ES_SS_SAVE_USER_BTN','4','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('RU_SS_SAVE_USER_BTN','8','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('JP_SS_SAVE_USER_BTN','9','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('ZH_SS_SAVE_USER_BTN','10','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES ('PT_SS_SAVE_USER_BTN','11','SS_SAVE_USER_BTN','ResourceEntity.displayNameMap','Save User Button');
