use openiam;

DELETE FROM LANGUAGE_MAPPING WHERE REFERENCE_ID = 'CHANGE_PASS_MANAGED_SYS';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'CHANGE_PASS_MANAGED_SYS';
DELETE FROM RES WHERE RESOURCE_ID = 'CHANGE_PASS_MANAGED_SYS';

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL, IS_PUBLIC) 
VALUES ('CHANGE_PASS_MANAGED_SYS','MENU_ITEM','Extended Change password','CHANGE_PASS_MANAGED_SYS',1,'/idp/changePasswordManagedSystem.html','Y');
INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFCENTER','CHANGE_PASS_MANAGED_SYS');


INSERT INTO LANGUAGE_MAPPING (ID, LANGUAGE_ID, REFERENCE_ID, REFERENCE_TYPE, TEXT_VALUE) VALUES
  ('CHANGE_PASS_MANAGED_SYS_DESC','1','CHANGE_PASS_MANAGED_SYS','ResourceEntity.displayNameMap','Change Password Extended');
