use openiam;

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');
DELETE FROM RES WHERE RESOURCE_ID IN ('RES_ATTR_PAGE', 'RESAPPROVER', 'RESENTITLEMENT', 'ROLE_ATTRIBUTES', 'GROUP_ATTRIBUTES', 'ORG_ATTRIBUTES', 'MNGSYS_ATTR_PAGE', '255');

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('ACCESSCENTER');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('ACCESSCENTER_MENU_DISPLAY', 'ACCESSCENTER', 'MENU_DISPLAY_NAME', 'Access Management');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('ACCESSCENTER_MENU_ICON', 'ACCESSCENTER', 'MENU_ICON', '/openiam-ui-static/images/common/icons/access_control.png');