use openiam;


DELETE FROM POLICY_ATTRIBUTE WHERE DEF_PARAM_ID IN(131,141, 180, 181, 182, 183);
DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID IN(131,141, 182,183);


INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, VALUE1, REQUIRED) VALUES ('4052', '180', '4000', 'MIN_WORDS_PASSPHRASE', '', 'Y');

INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, VALUE1, REQUIRED) VALUES ('4053', '181', '4000', 'REPEAT_SAME_WORD_PASSPHRASE', '', 'Y');

INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID, POLICY_DEF_ID, NAME, DESCRIPTION, PARAM_GROUP, POLICY_PARAM_HANDLER) VALUES ('182', '100', 'LIMIT_NUM_REPEAT_CHAR', 'Limit the repetition of same character', 'PSWD_COMPOSITION', 'org.openiam.idm.srvc.pswd.rule.LimitNumberRepeatCharRule');


INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, REQUIRED) VALUES ('4054', '182', '4000', 'LIMIT_NUM_REPEAT_CHAR', 'Y');

INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID, POLICY_DEF_ID, NAME, DESCRIPTION, PARAM_GROUP, POLICY_PARAM_HANDLER) VALUES ('183', '100', 'PWD_PASSWORD', 'Cannot repeat same Password', 'PSWD_COMPOSITION','org.openiam.idm.srvc.pswd.rule.PasswordNotPasswordRule');

INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, REQUIRED) VALUES ('4200', '183', '4000', 'PWD_PASSWORD', 'Y');



