use openiam;

DELETE FROM POLICY_ATTRIBUTE WHERE POLICY_ATTR_ID IN('NUM_DAYS_FRGT_PWD_TOKEN_VALID');
DELETE FROM POLICY_DEF_PARAM WHERE DEF_PARAM_ID IN('NUM_DAYS_FRGT_PWD_TOKEN_VALID');

INSERT INTO POLICY_DEF_PARAM (DEF_PARAM_ID, POLICY_DEF_ID, NAME, DESCRIPTION, PARAM_GROUP) VALUES ('NUM_DAYS_FRGT_PWD_TOKEN_VALID', '100', 'NUM_DAYS_FORGET_PWD_TOKEN_VALID', 'Number of days the forgot password token is valid', 'FORGET_PSWD');
INSERT INTO POLICY_ATTRIBUTE (POLICY_ATTR_ID, DEF_PARAM_ID, POLICY_ID, NAME, REQUIRED) VALUES ('NUM_DAYS_FRGT_PWD_TOKEN_VALID', 'NUM_DAYS_FRGT_PWD_TOKEN_VALID', '4000', 'NUM_DAYS_FORGET_PWD_TOKEN_VALID', 'Y');