use openiam;

DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN('WEB_REPORT', 'SELFSERVICE_REPORT');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('WEB_REPORT_DESC', 'WEB_REPORT', 'MENU_DISPLAY_NAME', 'Report');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('WEB_REPORT_PUB', 'WEB_REPORT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('WEB_REPORT_DISPLAY', 'WEB_REPORT', 'MENU_ICON', '/openiam-ui-static/images/common/icons/reports.png');

INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('SELFSERVICE_REPORT_DESC', 'SELFSERVICE_REPORT', 'MENU_DISPLAY_NAME', 'Report');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('SELFSERVICE_REPORT_PUB', 'SELFSERVICE_REPORT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES('SELFSERVICE_REPORT_DISPLAY', 'SELFSERVICE_REPORT', 'MENU_ICON', '/openiam-ui-static/images/common/icons/reports.png');