USE openiam;

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT_ORG';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT_ORG';
DELETE FROM RES WHERE RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT_ORG';

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT';
DELETE FROM RES WHERE RESOURCE_ID = 'SELFSRVS_ACCESS_MNGMNT';

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELF_SUB_ORGS_NEW';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELF_SUB_ORGS_NEW';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_NEW';

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELF_SUB_ORGS_SEARCH';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELF_SUB_ORGS_SEARCH';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_SEARCH';

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELF_SUB_ORGS_EDIT';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELF_SUB_ORGS_EDIT';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_EDIT';

DELETE FROM RESOURCE_PROP WHERE  RESOURCE_ID = 'SELF_SUB_ORGS_MEMEBERSHIP';
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID = 'SELF_SUB_ORGS_MEMEBERSHIP';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_MEMEBERSHIP';

DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_ROOT';
DELETE FROM RES WHERE RESOURCE_ID = 'SELF_SUB_ORGS_EDIT_ROOT';


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELFSRVS_ACCESS_MNGMNT', 'MENU_ITEM', 'Access Managment', 'SELFSRVS_ACCESS_MNGMNT', 6, '');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSRVS_ACCESS_MNGMNT_DESC', 'SELFSRVS_ACCESS_MNGMNT', 'MENU_DISPLAY_NAME', 'Access managment');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSRVS_ACCESS_MNGMNT_MENU_ICON', 'SELFSRVS_ACCESS_MNGMNT', 'MENU_ICON', '/openiam-ui-static/images/common/icons/access_control.png');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSRVS_ACCESS_MNGMNT_MENU_PUB', 'SELFSRVS_ACCESS_MNGMNT', 'MENU_IS_PUBLIC', 'true');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELFSRVS_ACCESS_MNGMNT', 'SELFSERVICE');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELFSRVS_ACCESS_MNGMNT_ORG', 'MENU_ITEM', 'Selfservice organization', 'SELFSRVS_ACCESS_MNGMNT_ORG', 1, '/selfservice/organizations.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSRVS_ACCESS_MNGMNT_ORG_DESC', 'SELFSRVS_ACCESS_MNGMNT_ORG', 'MENU_DISPLAY_NAME', 'Organizations');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELFSRVS_ACCESS_MNGMNT_ORG', 'SELFSRVS_ACCESS_MNGMNT');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_ROOT', 'MENU_ITEM', 'organizations menu', 'SELF_SUB_ORGS_ROOT', 2, '');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_NEW', 'MENU_ITEM', 'add organization', 'SELF_SUB_ORGS_NEW', 1, '/selfservice/editOrganization.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELF_SUB_ORGS_NEW_DESC', 'SELF_SUB_ORGS_NEW', 'MENU_DISPLAY_NAME', 'New Organization');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELF_SUB_ORGS_NEW', 'SELF_SUB_ORGS_ROOT');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_SEARCH', 'MENU_ITEM', 'add organization', 'SELF_SUB_ORGS_SEARCH', 1, '/selfservice/organizations.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELF_SUB_ORGS_SEARCH_DESC', 'SELF_SUB_ORGS_SEARCH', 'MENU_DISPLAY_NAME', 'Search Organization');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELF_SUB_ORGS_SEARCH', 'SELF_SUB_ORGS_ROOT');


INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_EDIT_ROOT', 'MENU_ITEM', 'organizations menu', 'SELF_SUB_ORGS_EDIT_ROOT', 2, '');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_EDIT', 'MENU_ITEM', 'add organization', 'SELF_SUB_ORGS_EDIT', 1, '/selfservice/editOrganization.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELF_SUB_ORGS_EDIT_DESC', 'SELF_SUB_ORGS_EDIT', 'MENU_DISPLAY_NAME', 'Edit Organization');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELF_SUB_ORGS_EDIT', 'SELF_SUB_ORGS_EDIT_ROOT');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, DISPLAY_ORDER, URL) VALUES ('SELF_SUB_ORGS_MEMEBERSHIP', 'MENU_ITEM', 'add organization', 'SELF_SUB_ORGS_MEMEBERSHIP', 1, '/selfservice/membership-organizations.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELF_SUB_ORGS_MEMEBERSHIP_DESC', 'SELF_SUB_ORGS_MEMEBERSHIP', 'MENU_DISPLAY_NAME', 'Organization Membership');
INSERT INTO res_to_res_membership (MEMBER_RESOURCE_ID, RESOURCE_ID) VALUES ('SELF_SUB_ORGS_MEMEBERSHIP', 'SELF_SUB_ORGS_EDIT_ROOT');
