use openiam;

DELETE FROM MNG_SYS_OBJECT_MATCH WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM MANAGED_SYS_ATTRIBUTE WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM MNG_SYS_GROUP WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM REQ_APPROVER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM MNG_SYS_LIST WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM ATTRIBUTE_MAP WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM SYNCH_CONFIG WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM SYNCH_CONFIG WHERE MATCH_MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM AUTH_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM MANAGED_SYS_RULE WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM CONTENT_PROVIDER_SERVER WHERE CONTENT_PROVIDER_ID IN(
	SELECT CONTENT_PROVIDER_ID FROM CONTENT_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202')
);
DELETE FROM URI_PATTERN_META_VALUE WHERE URI_PATTERN_META_ID IN(
	SELECT URI_PATTERN_META_ID FROM URI_PATTERN_META WHERE URI_PATTERN_ID IN(
		SELECT URI_PATTERN_ID FROM URI_PATTERN WHERE CONTENT_PROVIDER_ID IN(	
			SELECT CONTENT_PROVIDER_ID FROM CONTENT_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202')
		)
	)
);
DELETE FROM URI_PATTERN_META WHERE URI_PATTERN_ID IN(
	SELECT URI_PATTERN_ID FROM URI_PATTERN WHERE CONTENT_PROVIDER_ID IN(	
		SELECT CONTENT_PROVIDER_ID FROM CONTENT_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202')
	)
);
DELETE FROM URI_PATTERN WHERE CONTENT_PROVIDER_ID IN(
	SELECT CONTENT_PROVIDER_ID FROM CONTENT_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202')
);
DELETE FROM CONTENT_PROVIDER WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM GRP WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM LOGIN WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM RES WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN (SELECT RESOURCE_ID FROM RES WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202'));
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN (SELECT RESOURCE_ID FROM RES WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202'));
DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN (SELECT RESOURCE_ID FROM RES WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202'));
DELETE FROM MANAGED_SYS WHERE MANAGED_SYS_ID IN('SELFSERVICE_NEWHIRE', 'SELFSERVICE_CREATEREQUEST', 'SELFSERVICE_PROFILE', '200', '201', '202');