use openiam;

UPDATE ATTRIBUTE_MAP SET DATA_TYPE='STRING' WHERE DATA_TYPE='string';
UPDATE ATTRIBUTE_MAP SET DATA_TYPE='MEMBER_OF' WHERE DATA_TYPE='memberOf';
DELETE FROM MNG_SYS_OBJECT_MATCH WHERE MANAGED_SYS_ID = '101' AND OBJECT_SEARCH_ID='100';

DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('254');
DELETE FROM res_to_res_membership WHERE RESOURCE_ID IN ('254');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('254');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('254');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('254');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('254');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('254');
DELETE FROM RES WHERE RESOURCE_ID IN ('254');