use openiam;

DELETE FROM UI_TEMPLATE_FIELDS WHERE UI_FIELD_ID IN('USER_EMAIL_CREATABLE', 'USER_EMAILS_REQUIRED');

INSERT INTO UI_TEMPLATE_FIELDS (UI_FIELD_ID, NAME, TEMPLATE_TYPE_ID, IS_REQUIRED) VALUES('USER_EMAIL_CREATABLE', 'User can create email addresses', 'USER_TEMPLATE', 'N');
INSERT INTO UI_TEMPLATE_FIELDS (UI_FIELD_ID, NAME, TEMPLATE_TYPE_ID, IS_REQUIRED) VALUES('USER_EMAILS_REQUIRED', 'User is required to input at least one email address', 'USER_TEMPLATE', 'N');