use openiam; 

ALTER TABLE LOGIN CHANGE COLUMN LOGIN LOGIN VARCHAR(220) CHARACTER SET 'utf8' NOT NULL;
ALTER TABLE LOGIN CHANGE COLUMN LOWERCASE_LOGIN LOWERCASE_LOGIN VARCHAR(220) CHARACTER SET 'utf8' NOT NULL ;


