use openiam;

ALTER TABLE USER_ROLE DROP COLUMN CREATED_BY, DROP COLUMN END_DATE, DROP COLUMN START_DATE, DROP COLUMN CREATE_DATE, DROP COLUMN STATUS, DROP COLUMN USER_ROLE_ID;
ALTER TABLE USER_GRP DROP COLUMN CREATED_BY, DROP COLUMN END_DATE, DROP COLUMN START_DATE, DROP COLUMN CREATE_DATE, DROP COLUMN STATUS, DROP COLUMN USER_GRP_ID;
ALTER TABLE RESOURCE_USER DROP COLUMN END_DATE, DROP COLUMN STATUS, DROP COLUMN OP_AGAINST_ROLE, DROP COLUMN PRIVILEGE_LIST, DROP COLUMN RESOURCE_USER_ID, CHANGE COLUMN START_DATE START_DATE DATETIME NULL DEFAULT NULL , DROP PRIMARY KEY , ADD PRIMARY KEY (RESOURCE_ID, USER_ID);
ALTER TABLE USER_AFFILIATION DROP COLUMN CREATED_BY, DROP COLUMN END_DATE, DROP COLUMN START_DATE, DROP COLUMN STATUS, DROP COLUMN USER_AFFILIATION_ID, CHANGE COLUMN CREATE_DATE CREATE_DATE DATETIME NULL DEFAULT NULL , DROP PRIMARY KEY , ADD PRIMARY KEY (COMPANY_ID, USER_ID);
ALTER TABLE RESOURCE_GROUP DROP COLUMN END_DATE, DROP COLUMN RES_GROUP_ID, DROP PRIMARY KEY , ADD PRIMARY KEY (RESOURCE_ID, GRP_ID);
ALTER TABLE RESOURCE_ROLE DROP COLUMN END_DATE;

