use openiam;

ALTER TABLE MANAGED_SYS DROP FOREIGN KEY FK_MNG_SYS_PROV_CON ;

ALTER TABLE MANAGED_SYS ADD CONSTRAINT FK_MNG_SYS_PROV_CON FOREIGN KEY (CONNECTOR_ID ) REFERENCES PROVISION_CONNECTOR (CONNECTOR_ID );

ALTER TABLE AUTH_PROVIDER DROP FOREIGN KEY FK_MNG_AUTH_PROVIDER ;

ALTER TABLE AUTH_PROVIDER ADD CONSTRAINT FK_MNG_AUTH_PROVIDER FOREIGN KEY (MANAGED_SYS_ID ) REFERENCES MANAGED_SYS (MANAGED_SYS_ID );

ALTER TABLE MNG_SYS_OBJECT_MATCH DROP FOREIGN KEY FK_MNG_SYS_OBJ_MATC ;

ALTER TABLE MNG_SYS_OBJECT_MATCH ADD CONSTRAINT FK_MNG_SYS_OBJ_MATC FOREIGN KEY (MANAGED_SYS_ID ) REFERENCES MANAGED_SYS (MANAGED_SYS_ID );

ALTER TABLE AUTH_PROVIDER_ATTRIBUTE DROP FOREIGN KEY FK_PROVIDER_PROVIDER_ATTRIBUTE ;

ALTER TABLE AUTH_PROVIDER_ATTRIBUTE ADD CONSTRAINT FK_PROVIDER_PROVIDER_ATTRIBUTE FOREIGN KEY (PROVIDER_ID ) REFERENCES AUTH_PROVIDER (PROVIDER_ID );


