use openiam;

ALTER TABLE GRP DROP COLUMN OWNER_ID;

ALTER TABLE GRP DROP COLUMN PROVISION_METHOD;

ALTER TABLE GRP DROP COLUMN PROVISION_OBJ_NAME;

ALTER TABLE GRP DROP FOREIGN KEY FK_GRP_METADATA_TYPE;

ALTER TABLE GRP DROP COLUMN TYPE_ID;

ALTER TABLE GRP DROP COLUMN INTERNAL_GROUP_ID;

ALTER TABLE GRP DROP COLUMN EXTERNAL_GRP_NAME;

ALTER TABLE GRP ADD COLUMN (MANAGED_SYS_ID VARCHAR(32) NULL);

ALTER TABLE GRP ADD CONSTRAINT GRP_MNG_SYS_FK FOREIGN KEY (MANAGED_SYS_ID ) REFERENCES MANAGED_SYS (MANAGED_SYS_ID );