use openiam;

DROP TABLE IF EXISTS IDM_AUDIT_LOG_CUSTOM;
DROP TABLE IF EXISTS IDM_AUDIT_LOG;

DROP TABLE IF EXISTS OPENIAM_LOG_LOG_MEMBERSHIP;
DROP TABLE IF EXISTS OPENIAM_LOG_ATTRIBUTE;
DROP TABLE IF EXISTS OPENIAM_LOG_TARGET;
DROP TABLE IF EXISTS OPENIAM_LOG;

CREATE TABLE OPENIAM_LOG (
	OPENIAM_LOG_ID VARCHAR(32) NOT NULL,
	USER_ID VARCHAR(32) NULL,
	PRINCIPAL VARCHAR(320) NULL,
	MANAGED_SYS_ID VARCHAR(32) NULL,
	CREATED_DATETIME DATETIME NULL,
	SOURCE VARCHAR(50) NULL,
	CLIENT_IP VARCHAR(50) NULL,
	NODE_ID VARCHAR(50) NULL,
	LOG_ACTION VARCHAR(50) NULL,
	RESULT VARCHAR(50) NULL,
	SESSION_ID VARCHAR(100) NULL,
	HASH VARCHAR(100) NOT NULL,
	CORRELATION_ID VARCHAR(32) NULL,
	PRIMARY KEY(OPENIAM_LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE OPENIAM_LOG_TARGET (
	OPENIAM_LOG_TARGET_ID VARCHAR(32) NOT NULL,
	OPENIAM_LOG_ID VARCHAR(32) NOT NULL,
	TARGET_ID VARCHAR(32) NULL,
	TARGET_TYPE VARCHAR(70) NULL,
	PRIMARY KEY(OPENIAM_LOG_TARGET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE OPENIAM_LOG_ATTRIBUTE (
	OPENIAM_LOG_ATTRIBUTE_ID VARCHAR(32) NOT NULL,
	OPENIAM_LOG_ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(100) NULL,
	VALUE TEXT NULL,
	PRIMARY KEY(OPENIAM_LOG_ATTRIBUTE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE OPENIAM_LOG_LOG_MEMBERSHIP (
	OPENIAM_LOG_ID VARCHAR(32) NOT NULL,
	OPENIAM_MEMBER_LOG_ID VARCHAR(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

/*
AUDIT_USER_ROLE:
ROLE_ID
USER_ID
DATE
ACTION
 
AUDIT_USER_GRP
GRP_ID
USER_ID
DATE
ACTION 

AUDIT_USER_AFFILIATION
COMPANY_ID
USER_ID
DATE
ACTION
 
AUDIT_RESOURCE_USER
RESOURCE_ID
USER_ID
DATE
ACTION
*/