use openiam;


DELETE FROM res_to_res_membership WHERE MEMBER_RESOURCE_ID IN ('SELFSERVE_SUP_SUB');
DELETE FROM RESOURCE_USER WHERE RESOURCE_ID IN ('SELFSERVE_SUP_SUB');
DELETE FROM RESOURCE_ROLE WHERE RESOURCE_ID IN ('SELFSERVE_SUP_SUB');
DELETE FROM RESOURCE_PROP WHERE RESOURCE_ID IN ('SELFSERVE_SUP_SUB');
DELETE FROM RESOURCE_GROUP WHERE RESOURCE_ID IN ('SELFSERVE_SUP_SUB');
DELETE FROM RES WHERE RESOURCE_ID IN ('SELFSERVE_SUP_SUB');

INSERT INTO RES (RESOURCE_ID, RESOURCE_TYPE_ID, DESCRIPTION, NAME, URL) VALUES ('SELFSERVE_SUP_SUB', 'MENU_ITEM', 'Superiors & Subordinates', 'SELFSERVE_SUP_SUB', '/selfservice/supSub.html');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERVE_SUP_SUB_PUB', 'SELFSERVE_SUP_SUB', 'MENU_IS_PUBLIC', 'true');
INSERT INTO RESOURCE_PROP (RESOURCE_PROP_ID, RESOURCE_ID, NAME, PROP_VALUE) VALUES ('SELFSERVE_SUP_SUB_DESC', 'SELFSERVE_SUP_SUB', 'MENU_DISPLAY_NAME', 'Superiors & Subordinates');

INSERT INTO res_to_res_membership (RESOURCE_ID, MEMBER_RESOURCE_ID) VALUES('SELFSERV_USER_EDIT_ROOT', 'SELFSERVE_SUP_SUB');
